### ISSUE TITLE
Suggestion - Welcome mail to new members upon successfully verified registration. 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#103]
A very "nice to have" feature would be to have a "Welcome to the xxxxxx forum" mail automatically sent to users who have just registered successfully to the forum. 

Then you can inform new users about the forum, mention some rules, some useful starter links and such. Would be great thing, as I see it...  :-)

**Comment by Zero2Cool** [comment]
When does the new user receive the private message and from whom? I created new user and it is enabled and no private message.

**Comment by w8tcha** [comment]
If email verification is disabled the welcome email/pm is send after the registration is completed, otherwise the welcome message is send after the account is approved. The PM notification is coming from the host admin

**Comment by Zero2Cool** [comment]
Hmm, something I'll have to look further into and see why it's not working.

**Comment by w8tcha** [comment]
Well there is a bug at the moment it tries to send the pm from user id 2, i guess that could be the problem. this will be fixed soon

**Comment by Zero2Cool** [comment]
I have more than one Host Admin. I will remove one (UserID 2 specifically) and when someone registers new, I'll report back.
