### ISSUE TITLE
Unable to create forums "Invalid Value Passed to the Forum"

### ISSUE THREAD

**Issue by orawalters** [YAFNET/YAFNET#1030]
**Describe the bug**
Copied from: https://yetanotherforum.net/forum/Posts/t22103-Unable-to-create-forums

I've decided this is likely a bug since I can't find any workaround or cause

**To Reproduce**

1.     Delete default categories/forums
2.     Add a new category
3.     Attempt to add a new forum

**Expected behavior**

**Screenshots**
![96ZOZbh](https://github.com/YAFNET/YAFNET/assets/5394990/94f5ddcb-d686-4d22-ba04-03e661ffe849)

**System (please complete the following information):**
 - YAF Version: YAG v4.0.0-beta
 - .NET Version 8 Core
 - SQL Server Postgres 14

**Comment by w8tcha** [comment]
Fixed with https://github.com/YAFNET/YAFNET/commit/9535bd4a053518e4b3f660bd773f1407aa7468bc

**Comment by orawalters** [comment]
Now the saving of a forum results in an uncaught exception:

> **NullReferenceException: Object reference not set to an instance of an object.**
>
>     YAF.Pages.Shared.Pages_Shared__CategoryList.ExecuteAsync() in _CategoryList.cshtml, line 16

![image](https://github.com/YAFNET/YAFNET/assets/5394990/6d58f591-4ed7-4f52-ba7f-1232e542f825)
