### ISSUE TITLE
Saving of a V4 forum results in an uncaught exception

### ISSUE THREAD

**Issue by orawalters** [YAFNET/YAFNET#1031]
Now the saving of a forum results in an uncaught exception:

> **NullReferenceException: Object reference not set to an instance of an object.**
>
>     YAF.Pages.Shared.Pages_Shared__CategoryList.ExecuteAsync() in _CategoryList.cshtml, line 16

![image](https://github.com/YAFNET/YAFNET/assets/5394990/6d58f591-4ed7-4f52-ba7f-1232e542f825)

_Originally posted by @orawalters in https://github.com/YAFNET/YAFNET/issues/1030#issuecomment-1858688082_

**Comment by orawalters** [comment]
@w8tcha, this commit unfortunately didn't fix the issue.

![image](https://github.com/YAFNET/YAFNET/assets/5394990/6edc3c28-f757-401e-96e7-661a332b6386)

**Comment by w8tcha** [comment]
And this error appears after you try to save the forum?

**Comment by orawalters** [comment]
@w8tcha Correct.

**Comment by w8tcha** [comment]
Can you go to Admin > Maintenance > Event log and post the original error

**Comment by orawalters** [comment]
I updated to the latest version of master. Perhaps I missed the commit that fixed it. It's working now.
