### ISSUE TITLE
[V4] Admins cannot access moderation tools

### ISSUE THREAD

**Issue by orawalters** [YAFNET/YAFNET#1032]
**Describe the bug**
Clicking the "Moderate" tab while logged in as an admin sends you to the 403 Access Denied page.

**To Reproduce**
1. Login as Admin
2. Click on 'Moderate'

**Expected behavior**
Admins (and any role with the 'can moderate' flag) should be able to access these tools

**Screenshots**
![image](https://github.com/YAFNET/YAFNET/assets/5394990/fc100ab6-6710-47f8-a24e-1e684db2a52d)

**System (please complete the following information):**
 - YAF Version: 4.0 beta
 - .NET Version 8.1 Core
 - SQL Server PostgreSQL 14

**Comment by orawalters** [comment]
This issue has not been fixed for me.

**Comment by w8tcha** [comment]
> This issue has not been fixed for me.

Then i need more info on the user account which has this problem is this an host user? Or part of user group with admin or mod rights?

**Comment by orawalters** [comment]
Yes this is the host user that came with the install. I have checked that it has the admin role and that the admin role can moderate.

**Comment by w8tcha** [comment]
Okay can you try now with the latest changes.

**Comment by orawalters** [comment]
@w8tcha That worked!
