### ISSUE TITLE
[V4] Enabling 2FA breaks login

### ISSUE THREAD

**Issue by orawalters** [YAFNET/YAFNET#1034]
**Describe the bug**
When logging in with 2FA enabled, one gets a 500 error at `/api/LoginBox/SignIn`

**To Reproduce**
1. Enable 2FA
2. Log out
3. Attempt to log back in

**Expected behavior**
One should be prompted to enter their 2FA key.

**System (please complete the following information):**
 - YAF Version: 4.0 Beta 1
 - .NET Version: 8.100.1 Core
 - SQL Server: Postgres 16
 
**Affected browser**
* [X] Chrome
* [X] Firefox
* [X] Edge
* ~~Safari~~ Unable to test due to not having access to an Apple device.

**Comment by w8tcha** [comment]
i cannot reproduce this with the latest code, but i guess there is an exception thrown. Does the issue also appear on the login page?

**Comment by orawalters** [comment]
This is fixed in latest release, my bad.
