### ISSUE TITLE
[V4] Topic BBCode no longer working

### ISSUE THREAD

**Issue by orawalters** [YAFNET/YAFNET#1039]
**Describe the bug**
Using the Topic BBCode shows the raw BBCode and not the rendered output

**To Reproduce**
1. Create a new post
2. Type `[topic=123]Go to Topic[/topic]`
3. Post

**Expected behavior**
A link to a topic is output

**System (please complete the following information):**
 - YAF Version: v4 Beta 2
 - .NET Version 8.100 Core
 - SQL Server Postgres 14

**Comment by w8tcha** [comment]
the bbcode doesnt exist, i removed it from the help pages
