### ISSUE TITLE
New Standard Editor

### ISSUE THREAD

**Issue by w8tcha** [YAFNET/YAFNET#106]
Changing the original idea.

this current bbcode editor is so bad. you have to write and then click preview.

I Propose the following changes.

1. Use only one Editor (CKEditor) and remove all other (TinyMCE, Radeditor & FTB are already removed in YAF 2.31.0)
2. attachments can be directly uploaded via the editor

**Comment by Zero2Cool** [comment]
If it would enhance the speed of YAF, maybe get rid of all editors and go with one? It might make support more efficient and a better user experience in the long run.

**Comment by w8tcha** [comment]
> If it would enhance the speed of YAF, maybe get rid of all editors and go with one? It might make support more efficient and a better user experience in the long run.

Totally agree. It will take some time but this will be done for the next major release. I updated the first post. Any Concerns?

**Comment by john2014** [comment]
`2. Instead of using bbcodes only use html`

How would you be sanitizing html code added by user?

**Comment by jzabroski** [comment]
So... I am/(was?) the maintainer of cleditor which is part of the ckeditor lineage.  Not that that gives me any special authority. You should use Prose Mirror. :-)

Just 2 cents! 🥈

**Comment by Zero2Cool** [comment]
> So... I am/(was?) the maintainer of cleditor which is part of the ckeditor lineage. Not that that gives me any special authority. You should use Prose Mirror. :-)
> 
> Just 2 cents! 🥈

Why should Prose Mirror be used? What does it offer that others don't and what does it do better than others?

**Comment by jzabroski** [comment]
A proper Model. Very well thought out rich copy paste from things like web pages, emails, etc.

Honestly everyone is moving to it.

**Comment by w8tcha** [comment]
> A proper Model. Very well thought out rich copy paste from things like web pages, emails, etc.
> 
> Honestly everyone is moving to it.

Sorry but who is everyone? That editor doesn't even have the featured needed for yaf.

**Comment by w8tcha** [comment]
> `2. Instead of using bbcodes only use html`
> 
> How would you be sanitizing html code added by user?

Via the content filter of the editor. It allows only certain html

**Comment by w8tcha** [comment]
So some progress here. Html isnt really working. So again ProseMirror is not an option since it doesnt support BBCode!

- CKEditor is now the only editor
- Editor is not optimized for BBCodes

- not done yet -> move toolbar for full and basic to the host settings

**Comment by jzabroski** [comment]
> > A proper Model. Very well thought out rich copy paste from things like web pages, emails, etc.
> > Honestly everyone is moving to it.
> 
> Sorry but who is everyone? That editor doesn't even have the featured needed for yaf.

It would probably be helpful if you enumeratored the features you need for yaf, as I can't assess what you see as missing from a general purpose, pluggable editor like ProseMirror.  It's frustrating because BBCodes are simple top-down parsers as compared to Markdown example here: https://prosemirror.net/examples/markdown/

**Comment by jzabroski** [comment]
Here is a [BBCodeParser](https://github.com/svenslaggare/BBCodeParser) written in TypeScript - all you need to do is follow the MarkdownView typescript class in ProseMirror as an example for how to integrate BBCode.

**Comment by w8tcha** [comment]
Sorry but i don't see this as an option to start with a new editor from scratch. Why re-invent the wheel?! CKEditor already provides all the necessary features. And i dont have any experience with that posemirror. It would be really difficult and a waste of time

**Comment by w8tcha** [comment]
Also I see that the editor is a markdown editor. There isn't even an option to switch to source view or to html

**Comment by jzabroski** [comment]
ok, sorry.

**Comment by Zero2Cool** [comment]
> ok, sorry.

I appreciate the alternative. I couldn't find a way to insert and image. I'm all for a new editor if it makes sense. And we recently got the ability to paste images and losing that would be a big blow to the user base.

**Comment by w8tcha** [comment]
> I appreciate the alternative. I couldn't find a way to insert and image. I'm all for a new editor if it makes sense. And we recently got the ability to paste images and losing that would be a big blow to the user base.

pasting and adding images is of course already included in the CKEditor (its actually possible to paste regular attachments too)

**Comment by jzabroski** [comment]
> I appreciate the alternative. I couldn't find a way to insert and image. I'm all for a new editor if it makes sense. And we recently got the ability to paste images and losing that would be a big blow to the user base.

Copy-paste image works for me.

1. Open http://google.com and right-click the Google Logo and select Copy Image
2. In a separate tab, go to: https://prosemirror.net/examples/markdown/
3. Right below the editor, click the WYSIWYM radio button.
4. In the editor, Control+V *or* right-click Paste to paste the logo.

In addition, there is the upload example where you can upload whatever you want, and can support uploading multiple things at once: https://prosemirror.net/examples/upload/ - *This sample only does images, but you can modify it to do arbitrary files and put a paperclip icon similar to what MS Outlook does or how Gmail attachments work.*

You can also experiment with dragging the image up and down the text box and see why people love ProseMirror vs [sc|ck|cl]Editor abstraction we're all familiar with due to its BBCode popularity.

**Comment by jzabroski** [comment]
BTW, the other reason I personally love ProseMirror is its rules around copy-paste are well thought out.  Marijn wrote several blog posts about it, including his analysis of what MS Word and Google Docs do, as blindly jamming HTML from the Internet into a WYSIWYG editor can cause lots of problems.

**Comment by w8tcha** [comment]
Well ckeditor als has an convertor ms word am Google docs.

But again yaf needs a html editor not a markdown editor. 

Conversion will be closed because it's completely off topic
