### ISSUE TITLE
Search not working. Missing config?

### ISSUE THREAD

**Issue by ewaldventer** [YAFNET/YAFNET#1087]
Installed v3.2.2

Created a board, categories and forums. Posted a couple of topics.
Trying out the search function but it returns nothing. No errors.

Am I missing configuration somewhere?

Regards

**Comment by w8tcha** [comment]
Does the yaf event log contains any errors?

Are there any files created in the app_data/search_index directory?

It's possible that there is no write access on the appdata directory.

**Comment by ewaldventer** [comment]
Thank you. app_data didn't exist. 
Gave service account write access to root folder, reindexed and it's working now.
