### ISSUE TITLE
The command 'grunt' exited with code 6

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#1088]
I've download the source https://github.com/YAFNET/YAFNET/commit/6312cb0abf0394f0ca0aeef6047cf81398044b75 but when I try to build, I get this issue. I tried doing a few things to fix it, but can't seem to figure out this easy problem.

![image](https://github.com/YAFNET/YAFNET/assets/5612416/c3a3bd4d-722b-4e3e-9219-502d41cdcb46)

I tried this as some others suggested for the SQLServer project, but still no luck.
![image](https://github.com/YAFNET/YAFNET/assets/5612416/37372892-0afc-4a35-8236-a9387d63ea85)

Any ideas what I did wrong?

**Comment by w8tcha** [comment]
Did you install grunt?

There is a guide on how to build the source via the command line or visual studio 

https://github.com/YAFNET/YAFNET/wiki#building-the-source

**Comment by KevinDuganJr** [comment]
> Did you install grunt?
> 
> There is a guide on how to build the source via the command line or visual studio
> 
> https://github.com/YAFNET/YAFNET/wiki#building-the-source

That is what I tried following to set things up. I believe I have grunt installed.
![image](https://github.com/YAFNET/YAFNET/assets/5612416/3e39e59b-ef38-448e-bc4f-f8d66db823d9)

**Comment by w8tcha** [comment]
And what errors are you getting when you run grund directly from the command line or from the task runner?

**Comment by KevinDuganJr** [comment]
I had to install a few more modules to make some progress. And by progress I was getting "unable to load" under Grunt on Task Runner. Now I'm getting a list, but when I run 'default' this just popped up. Working through it now as I got notification of a response.

![image](https://github.com/YAFNET/YAFNET/assets/5612416/ca9ccbeb-aeef-4fba-b794-3b011ea5cb10)


\YetAnotherForum.NET" --gruntfile "C:/Users/Kevin/source/repos/KevinDuganJr/YAFNET/yafsrc/YetAnotherForum.NET/Gruntfile.js" default --color --force --verbose
Initializing
Command-line options: Reading "Gruntfile.js" Gruntfile...Registering Gruntfile tasks.
--base=C:\Users\Kevin\source\repos\KevinDuganJr\YAFNET\yafsrc\YetAnotherForum.NET, --gruntfile=C:\Users\Kevin\source\repos\KevinDuganJr\YAFNET\yafsrc\YetAnotherForum.NET\Gruntfile.js, --color, --force, --verbose
OK
OK
Reading package.json...Parsing package.json...OK
OK
Initializing config...Registering "grunt-contrib-sass" local Npm module tasks.
Registering "@lodder/grunt-postcss" local Npm module tasks.
Registering "grunt-contrib-copy" local Npm module tasks.
Registering "grunt-contrib-uglify" local Npm module tasks.
Registering "grunt-contrib-cssmin" local Npm module tasks.
Registering "@w8tcha/grunt-dev-update" local Npm module tasks.
Registering "grunt-shell" local Npm module tasks.
Registering "grunt-replace" local Npm module tasks.
Registering "grunt-zip" local Npm module tasks.
Registering "grunt-file-append" local Npm module tasks.
Registering "grunt-webpack" local Npm module tasks.
Loading "Gruntfile.js" tasks...+ Running tasks: Running "default" task
>> Local Npm module "grunt-contrib-sass" not found. Is it installed?
>> Local Npm module "@lodder/grunt-postcss" not found. Is it installed?
>> Local Npm module "grunt-contrib-copy" not found. Is it installed?
>> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
>> Local Npm module "grunt-contrib-cssmin" not found. Is it installed?
>> Local Npm module "@w8tcha/grunt-dev-update" not found. Is it installed?
>> Local Npm module "grunt-shell" not found. Is it installed?
>> Local Npm module "grunt-replace" not found. Is it installed?
>> Local Npm module "grunt-zip" not found. Is it installed?
>> Local Npm module "grunt-file-append" not found. Is it installed?
>> Local Npm module "grunt-webpack" not found. Is it installed?
OK
css, default, deploy, deploy-MySql, deploy-PostgreSQL, deploy-SqlServer, deploy-Sqlite, emailTemplates, js, updateBootstrap, updateBootswatchThemes, updateFlagIcons, updateFontAwesome, updatePackages
default
Warning: Task "webpack:lightBox" not found. Used --force, continuing.
Done, but with warnings.
Process terminated with code 0.

**Comment by w8tcha** [comment]
You need to run npm install first. Then all needed packages getting installed automatically.

**Comment by KevinDuganJr** [comment]
I have npm installed already though.
![image](https://github.com/YAFNET/YAFNET/assets/5612416/5bf699b6-c082-49a1-b8f2-d3ebb4015d81)

**Comment by w8tcha** [comment]
You need to install it separate for every project otherwise it won't work.

You need to run npm install from within the Yetanotherforum.net folder. That's how npm works.

**Comment by KevinDuganJr** [comment]
> You need to install it separate for every project otherwise it won't work.
> 
> You need to run npm install from within the Yetanotherforum.net folder. That's how npm works.

Ohh. I did not know that. Okay, I will do that and report back.

**Comment by w8tcha** [comment]
That is of course wrong!

You only need to install on the YetAnotherForum.NET folder or via the task runner

And run npm install and not npm install -g

It is all documented in the wiki.

**Comment by KevinDuganJr** [comment]
Bah. I'll read it again and try again.

**Comment by w8tcha** [comment]
If you use task runner then you only execute two commands

https://github.com/YAFNET/YAFNET/wiki/Build-with-Visual-Studio

**Comment by w8tcha** [comment]
Looks like the package.json is missing from the Yetanotherforum.net folder?!

**Comment by KevinDuganJr** [comment]
> Looks like the package.json is missing from the Yetanotherforum.net folder?!

It seems to be where it should be. 🤷

![image](https://github.com/YAFNET/YAFNET/assets/5612416/8d9668dd-2aee-486b-a744-59d413c431b2)

**Comment by KevinDuganJr** [comment]
I downloaded the latest source. Opened it up and this is what I see under Task Runner.
![image](https://github.com/YAFNET/YAFNET/assets/5612416/72497413-6068-4d22-9160-8d5a8e2983f4)

I then right click on project YAF-SqlServer, Open Terminal and install npm. 
![image](https://github.com/YAFNET/YAFNET/assets/5612416/04560031-c1ba-4f9e-93f0-00008c6e9589)

I still don't see the 'package.json' in my Task Runner Explorer. I'm not sure what step in the Wiki I'm missing. I've tried a few different times and same issue.
![image](https://github.com/YAFNET/YAFNET/assets/5612416/94589733-02ac-493f-a7c3-0e9109b4ce5b)

**Comment by w8tcha** [comment]
I cannot check this at the moment. But in the case you manually run npm via the command line after that you should be able to run the grunt command

**Comment by KevinDuganJr** [comment]
I was able to run Grunt through the command terminal after I changed my executionpolicy for scripts. Now the solution builds with no errors.

I can't login though because of this, but I'll read up on what the changes were and figure that out tomorrow or some other day, haha. Thanks for your help, Ingo!
![image](https://github.com/YAFNET/YAFNET/assets/5612416/83a6bfd8-f330-4103-9069-324aee694279)
