### ISSUE TITLE
Wiki - Task Runner

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#1089]
![image](https://github.com/YAFNET/YAFNET/assets/5612416/0645e9b8-cd9a-48b4-bc81-de928b0b241b)

The Visual Studio extension for Task Runner is for versions prior to the required Visual Studio 2022.

<img width="821" alt="image" src="https://github.com/YAFNET/YAFNET/assets/5612416/132ad77d-38e5-410b-8a1e-616396ccf30b">

But it seems we get Task Runner with Visual Studio 2022 by clicking View > Other Windows > Task Runner Explorer
![image](https://github.com/YAFNET/YAFNET/assets/5612416/e8537451-e7bb-44fd-8a59-c6827114e9cb)

This is probably already known and nothing, but it stumbled me up so thought I'd share.

**Comment by w8tcha** [comment]
By default this is not included in vs 2022, i had to install this via the extension manager

![extensions](https://github.com/YAFNET/YAFNET/assets/722575/a5ef0cac-0fea-4d14-a461-8596f74093c6)

**Comment by KevinDuganJr** [comment]
> By default this is not included in vs 2022, i had to install this via the extension manager
> 
> ![extensions](https://private-user-images.githubusercontent.com/722575/309638443-a5ef0cac-0fea-4d14-a461-8596f74093c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NTg5ODEsIm5iZiI6MTcwOTU1ODY4MSwicGF0aCI6Ii83MjI1NzUvMzA5NjM4NDQzLWE1ZWYwY2FjLTBmZWEtNGQxNC1hNDYxLTg1OTZmNzQwOTNjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQxMzI0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGE5NmNkYWE0YWZiMWVhOGQ3MGI5MjY3MjBhZTNlNWEyYzI1YzVjOTgyZDYxNzU3YWEzMDJiZjc2MjE0MzYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8WtvhvRxjt-KfplHsDJPHd2HqaN3A91VeN-AAgIJwBQ)

Fascinating. I just installed Visual Studio 2022 on that laptop and do not recall adding any extensions of any sort other than ReSharper. I might have checked a box on the install that pulled it in. 🤷‍♂️

**Comment by w8tcha** [comment]
Its possible that it was directly added to Vs in one of the updates. I also noticed that you can easily restore the npm packages now via the solution explorer

![RestoreNpmPackages](https://github.com/YAFNET/YAFNET/assets/722575/356f6944-d245-48bb-b0a1-5f847af5094b)

**Comment by KevinDuganJr** [comment]
That's how I restored packages in one of my attempts but was still getting an error. And I didn't see the same two tasks as shown in Wiki.

**Comment by w8tcha** [comment]
I updated the wiki, But its odd that your getting an error if you click on Restore Packages it executes the same npm install command. 

I tried to find a solution on google, it seems like it is a path problem

> In Visual Studio, go to Tools, Options.
> Expand the Projects and Solutions, Web Package Management, then External Web Tools.
> Confirm $(PATH) is at the top of your "location of external tools"
