### ISSUE TITLE
Authenticator Prompt

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#1096]
I'm running the Sample Application with YAF v3.1.16. I made a backup of the database and pointed YAF Standalone v4 against and when I try to log in, I'm getting prompted for Authenticator.  I poked around a little bit last night trying to figure out how to disable that, or figure out why it's even happening with no luck. 

I guess my question is why is this being displayed when I haven't set it up? And how can I get around it?

![image](https://github.com/YAFNET/YAFNET/assets/5612416/ee5df9ed-744c-41e7-b5e7-820f6b95f2ee)

**Comment by w8tcha** [comment]
By default this setting is disabled. You can disable it in the aspnetusers table column **TwoFactorEnabled**. Can you check if it is enabled for all users?

**Comment by KevinDuganJr** [comment]
In [yaf_AspNetUsers], yes, all users have it enabled.
![image](https://github.com/YAFNET/YAFNET/assets/5612416/3ba61dd8-1547-4639-a429-b4118d12ac47)

**Comment by w8tcha** [comment]
Found the issue, this setting was set on upgrade from YAF pre 3x. For now manually update those values. this will be fixed in 4.0.0/3.2.3 final
