### ISSUE TITLE
[V4] NullReferenceException when up

### ISSUE THREAD

**Issue by orawalters** [YAFNET/YAFNET#1100]
**Describe the bug**
I'm unable to upload an avatar to my website

**To Reproduce**
1. Enable user avatar uploading
2. Go to Modify Avatar
3. Attempt to upload an avatar

**Expected behavior**

**Screenshots**
![image](https://github.com/YAFNET/YAFNET/assets/5394990/0aadca9a-b405-4a39-8a2b-ab7ac12aeed5)

**System (please complete the following information):**
 - YAF Version: v4 BETA 5
 - .NET Version 8.100 Core
 - SQL Server Postgres 16

**Comment by orawalters** [comment]
Upon further testing, the actual bug is that the Uploads folder is not created by the installer or included in the source so it was never created. The exception occurs whenever the wwwroot/Uploads folder doesn't exist.

**Comment by w8tcha** [comment]
> Upon further testing, the actual bug is that the Uploads folder is not created by the installer or included in the source so it was never created. The exception occurs whenever the wwwroot/Uploads folder doesn't exist.

Thats odd the uploads folder exists in the source 

https://github.com/YAFNET/YAFNET/tree/master/yafsrc/YetAnotherForum.NET/wwwroot/uploads

**Comment by orawalters** [comment]
That's odd. I wonder why it isn't in my publish folder.

**Comment by w8tcha** [comment]
Because it was excluded. I updated the project files. now it should appear on publish
