### ISSUE TITLE
Recover password not working

### ISSUE THREAD

**Issue by savian-net** [YAFNET/YAFNET#1101]
**Describe the bug**
My userid continues to receive email but I can't recover the password.

**To Reproduce**

1. Try to recover password. Clicking has no impact.

**Expected behavior**
An email would be received to recover password

**Affected browser**

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [X ] Edge

**Additional context**

**Comment by w8tcha** [comment]
What yaf version are you using?

**Comment by savian-net** [comment]
I am not. I am trying to unsubscribe my email since I haven’t used the software in forever (5 yrs?). The forum keeps sending me emails and there is no way to stop it.

I from just removed my email from the system, that would be great.

The place where it isn’t working is the actual YAF.NET site.

Alan

**Comment by w8tcha** [comment]
Sorry but if it's not a yaf issue than you posting it in the wrong place. You should contact the site admin.

**Comment by savian-net** [comment]
Isn’t this the site:

https://yetanotherforum.net/

I am contacting the YAF.NET site. That is the issue. It’s that site that has the problem.

**Comment by w8tcha** [comment]
Well that was not clear, you should have written this directly.

Did you remember your user name? So I can remove your account

Or your email address associated with the account?

**Comment by savian-net** [comment]
***@***.******@***.***>

BTW, I really liked the software. My idea for my plans post career (I have been a dev for 40+ years) changed which is why I stopped using it.

I ran into the problem of not being able to recover my password and also not being able to unsubscribe. There is no contact us on the site which is why I was in a pickle.

Good luck with the software and thanks for making it available.

Thanks,
Alan

Alan Churchill
Savian, LLC
C:   719-310-4870
H:   719-687-5952

**Comment by w8tcha** [comment]
I tried to reproduce the issue and for me the forget password function works, its sending out the reset password link. Did you enter the correct user name or email address?

Again to remove your account i need the user name or email address

**Comment by savian-net** [comment]
The email is this one ***@***.******@***.***>). I am using Edge browser (so Chromium).

Thanks,
Alan

Alan Churchill
Savian, LLC
C:   719-310-4870
H:   719-687-5952

**Comment by w8tcha** [comment]
the email is censored. Can you post only the part before the '@' sign?

**Comment by savian-net** [comment]
alan.churchill

Thanks,
Alan

Alan Churchill
Savian, LLC
C:   719-310-4870
H:   719-687-5952

**Comment by w8tcha** [comment]
Found and deleted!

**Comment by savian-net** [comment]
Awesome, thank you.

When I press recover password, nothing happens. It is as if the event is not triggered or thrown away (caught and discarded). I don’t develop on this machine so I am not displaying errors.

Hope that helps.

Again, thanks for great software.

Thanks,
Alan

Alan Churchill
Savian, LLC
C:   719-310-4870
H:   719-687-5952
