### ISSUE TITLE
Using non-SqlServer project doesn't build

### ISSUE THREAD

**Issue by danFbach** [YAFNET/YAFNET#1108]
Source is pulled directly from github. When opening a solution that is not YAF.NET-SqlServer.sln, the 'tests' project still references YAF.NET-SqlServer.csproj instead of the relative csproj opened, in my case, MySql.

Changing YAFNET.Tests.Utils.csproj file from...
`<ProjectReference Include="..\..\YetAnotherForum.NET\YAF-SqlServer.csproj" />`
to
`<ProjectReference Include="..\..\YetAnotherForum.NET\YAF-MySql.csproj" />`
seems to resolve the build error. 
Not sure if this can be changed dynamically based upon which solution is loaded?

Also, heads up - I'll be your new guinea pig testing YAFv4 on AlmaLinux 8 and 9, with MySql (mariadb) and nginx rev proxy, so this should be fun!

**Comment by w8tcha** [comment]
Welcome on board! 

I excluded the playwright tests from those solutions.
