### ISSUE TITLE
Typo for english 'ADMINEMAIL' localization

### ISSUE THREAD

**Issue by danFbach** [YAFNET/YAFNET#1109]
While setting up, i noticed that the `Email Adress` is spelled with one 'd', and in english should be 2, `Address`. `english.json` only contains the misspelling once, for `ADMINEMAIL`

Perhaps some translations correctly only have one D - idk, i'm only multilingual when it comes to programming 😂.

**Comment by w8tcha** [comment]
> Perhaps some translations correctly only have one D - idk, i'm only multilingual when it comes to programming 😂.

Yes in my language its 'Adresse', thats why i always mix it up with english
