### ISSUE TITLE
Issue - Belarus is back... 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#111]
This is an old issue that has appeared earlier, however in 1.9.6.1+ it was fixed... 
Since 2.0 it has resurfaced. 

The problem is simply that the word "by" (which happens to be the official "shortening" for Belarus) is sometimes translated to "Belarus" in the forum display...  

Not a big issue really, but annoying to some...
I also have "Views Moderator List" sometimes in the top menu instead  of "Moderate"...  

Low priority of course, since it's an intermittent issue.... 

![image](https://f.cloud.github.com/assets/5246746/2302708/b09ee998-a189-11e3-8d16-e26c8263c622.png)

**Comment by JP58** [comment]
Happens sporadically, wontfix is ok.

**Comment by w8tcha** [comment]
Yes i can reproduce it once a month, but another page refresh and the problem is gone. From what i can see in the code everything is correct.

**Comment by JP58** [comment]
We might as well close it, right - With Bootstrap coming...  :-)
