### ISSUE TITLE
Linux path case sensitivity issues

### ISSUE THREAD

**Issue by danFbach** [YAFNET/YAFNET#1110]
YAF v4
This is really only relative to linux based installations, as windows is not case sensitive.
After a clean installation, YAF is looking for logo (displayed at the top of the page) at `domain.com/Images/Logos/` and then the dropdown img element in board settings is looking at `/images/logos/`, while the actual file location is `/images/Logos/`, so technically both are wrong when compared to the actual path. 

To run an experiment, i added a symbolic link, images => Images. Now the options in board settings will load, but when you open the logo selector in board settings the images do not load, because the img tag is looking at `images/logos`, all lowercase. 

so, these paths just need case consistency across the application.

On a sidenote, it looks like you're the soul maintainer on this project - would you accept pull requests for some linux related fixes as i come accross them? I would really like to get this into a production stable release for linux as fast as possible. I've already added code for enabling a reverse proxy and defining a listening port for the rev proxy using the `appsettings.json` file.
I generally like to contribute to FOSS when maintainers are open to it. I've got several years of dotnet core and dotnet framework experience, i'd be happy to help with at least the things i complain about.

**Comment by w8tcha** [comment]
i fixed the path issues for the logos and uploads folder

> On a sidenote, it looks like you're the soul maintainer on this project - would you accept pull requests for some linux related fixes as i come accross them?

Yes i do. the goal is that the the application would be cross platform

**Comment by danFbach** [comment]
in BoardSettings `/Admin/Settings`, the logo dropdown (both selected item and options) is still making the whole path lowercase.

`YAFNET.Web/TagHelpers/OptionTagHelper.cs` line 91, `this.Item.Value.ToLower()` remove tolower()?

No sure why one would have that there to begin with.

**Comment by w8tcha** [comment]
It was added for the Flags which have lower case file names, but it should not be there for other images.
