### ISSUE TITLE
Edit user corrupts user profile

### ISSUE THREAD

**Issue by danFbach** [YAFNET/YAFNET#1115]
As an admin, if you save changes to a user from the "User Info" tab, it messes up a user profile.

First, the "IsApproved" input is disabled, so it isn't included in the form submission, so the model assumes it is false, default value for a bool.
There is also a hidden input for "IsApproved", with a false value (which i assume is generated as part of the default implementation of a checkbox.)
When this form is submitted, it messes up the UserFlags bit value and the user account becomes essentially inaccessible.
After the user has been 'corrupted', even if you navigate directly to `/Admin/EditUser/4`, you cannot re-approve the user account.
Error thrown when trying to approve account from edit user user info tab:
```
NullReferenceException: Object reference not set to an instance of an object.
YAF.Pages.Admin.EditUser.Pages_Admin_EditUser_UsersInfo.<ExecuteAsync>b__52_0() in 
C:\VSProjects\YAF_v4\yafsrc\YetAnotherForum.NET\Pages\Admin\EditUser\UsersInfo.cshtml, line 92
```
The only way i've found to bring the user account back online is to go into the database and manually adjust the IsApproved and UserFlags values.

Secondly, after saving the value, the user is redirected to `/Admin/EditUser?userId=4`
This loads a "Guest" EditUser page, because `EditUser.cshtml` is looking for routing like `/Admin/EditUser/Id/Tab`,

**Comment by danFbach** [comment]
I submit a pr for problem one, IsApproved.

Problem two appears to be unrelated so i'm going to make a seperate issue.

**Comment by w8tcha** [comment]
> First, the "IsApproved" input is disabled, so it isn't included in the form submission, so the model assumes it is false, default value for a bool.

I wasnt aware of that. The approved checkbox is always disabled so i removed the code for updating the isapproved field/flag.
