### ISSUE TITLE
v4 updating User routing broken

### ISSUE THREAD

**Issue by danFbach** [YAFNET/YAFNET#1124]
when updating a user account (except from the `User Details` page because it does name have a tab defined on first load), the after post routing is broken.

If you load `/Admin/EditUser/{u}` all of the lazy loaded views (tabs) request `/Admin/EditUser/{tabName}?userId=4`.

If you load `/Admin/EditUser/{u}/{view#}` (which is what you get after you save any page other than the first), then the lazy requests turn into `/Admin/EditUser/{u}/{tabName}?userId=4`, which routes it to EditUser instead of the specified tab.

Path of `/Admin/EditUser/{u}` turns into `/Admin/EditUser/{fetchRelative}?userId={userId}` ✅
Path of `/Admin/EditUser/{u}/{viewNumber}` turns into `/Admin/EditUser/{u}/{fetchRelative}?userId={userId}` ❌

in `JavascriptBlock.cs`, function `EditUserTabsLoadJs` ~ line 229, all of the fetch requests are relative to path, and need to be relative to origin.

Changing the fetch requests to `/Admin/EditUser/{tabName}?userId={userId}` fixes this.

Will send pr shortly.

**Comment by w8tcha** [comment]
Your fix throws 404 errors for all tabs, because its missing the area if there is any. I added the area and now it should work in all cases.
