### ISSUE TITLE
Allow setting theme mode default

### ISSUE THREAD

**Issue by danFbach** [YAFNET/YAFNET#1127]
Low priority, but on the board settings, could we add a Default theme mode (Dark/Light.)
And then when a user account is created, the board default is loaded into the user DarkMode bool?

Or, perhaps a better option:

It was kind of brought up long ago in #119 (but wasn't available or widely used in 2014), use the browser default as the initial theme, and then it can be overridden by the user if they want to set a default. So, perhaps change the User DarkMode bool to be nullable. If null, use browser default, if set, then follow their override? And then add a toggle could be added up by the user name between 🌙 and ☀️ or something?

**Comment by orawalters** [comment]
As a workaround, this javascript code from StackOverflow will set dark/light mode depending on browser/system settings. Obviously, it doesn't allow the user to override it for the site.

```js
; (function () {
    const bodyElement = document.querySelector("body")
    if (bodyElement.getAttribute("data-bs-theme") === 'auto') {
        function updateTheme() {
            bodyElement.setAttribute("data-bs-theme",
                window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light")
        }
        window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', updateTheme)
        updateTheme()
    }
})()
```

**Comment by w8tcha** [comment]
> So, perhaps change the User DarkMode bool to be nullable. If null, use browser default, if set, then follow their override? And then add a toggle could be added up by the user name between 🌙 and ☀️ or something?

I like the idea but i have some thoughts. Since most of us use multiple devices, Do people really have dark mode enabled on all devices? Storing the setting in the db i think is the wrong approach.  Instead i would save it in the browser via cookie or localstorage. In that case it can be different for devices and it also can be applied to guests.

**Comment by danFbach** [comment]
yes, I use localstorage for this in another app and it works well. it assumes the browser default on load and then if the theme is toggled, it is saved to localstorage

**Comment by danFbach** [comment]
@w8tcha this is clean and simple, good work and thanks 👍
