### ISSUE TITLE
v4 Websockets issue on linux w/ nginx

### ISSUE THREAD

**Issue by danFbach** [YAFNET/YAFNET#1132]
The websocket connection fails to establish when deployed on linux with nginx.

Browser logs look like this: (fails on chromium based browsers too, so it isn't browser related)
`Firefox can’t establish a connection to the server at wss://forum.leeprecision.com/chatHub?id=TUpCtkAhtcMdHqSF1xZ6_w.`
`[2024-04-01T13:30:19.385Z] Information: (WebSockets transport) There was an error with the transport.`
`[2024-04-01T13:30:19.385Z] Error: Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.`

I know you don't have a linux server to work with so it'll be tough for you to troubleshoot this, so I'll try to gather what logs i can and troubleshoot. 
From what I gather, there is some amount of configuration needed in both dotnet and nginx to get this to work, but my experience here is limited. I'll be working on this as i can.

**Comment by w8tcha** [comment]
From what i understand from the ms documentation you have to define the set a new path for SignalR Hub on nginx configuration file..

Like described here....
https://learn.microsoft.com/en-us/aspnet/core/signalr/scale?view=aspnetcore-8.0#linux-with-nginx

Did you setup this path?

**Comment by danFbach** [comment]
Yes, i was working with something similar to this, but I'm confused.
did you replace `/hubroute` with `/chatHub`?

**Comment by danFbach** [comment]
Okay, i got it. I'm configuring on a cpanel server, so you have to get a bit creative building nginx config files, so many of them are generated and automatically overwritten.
Anyway, it is possible and actually relatively easy to get this working on linux + nginx + cpanel.
