### ISSUE TITLE
weird interaction when loading additional categories

### ISSUE THREAD

**Issue by danFbach** [YAFNET/YAFNET#1134]
**Describe the bug**
When there are more than 20 forums and the homepage collapses them, the showing of additional categories feels clunky.
There is an element that says `20 of 28 Forums shown`, but one must scroll all the way to the bottom of the page before additional categories are loaded. The element does nothing and seems deceiving, it feels odd and is not intuitive.

In consideration of lazily loading categories beyond 20:
was this chosen to lessen the initial page load time, or just brevity so that the first page isn't excessively long on first load?

If we want to stick with lazy loading, the button looking element that says `20 of 28 Forums shown` could perhaps actually be a button with different wording like 'Show additional ## categories` or perhaps the additional categories are loaded once that element comes into view?

Another option would be to eliminate the scroll reliant lazy loading with pagination. I believe a paged interface would be more intuitive.

**System (please complete the following information):**
 - YAF Version: 4 b7

**Comment by w8tcha** [comment]
I added lazy loading to increase the page load. 

From my point of view in that case i think lazy loading is the better option then pagination.

>  or perhaps the additional categories are loaded once that element comes into view?

That should be the case, or at least that was the idea

**Comment by w8tcha** [comment]
i updated the scroll script, its starts  now loading more early (before the stats appear). In my test with over 1000 forums its loads now as it should be.

**Comment by danFbach** [comment]
okay, i pulled through the update and when reviewing on mobile it loads once the stats element reaches the top of the page...
> its starts now loading more early (before the stats appear)

is not what I'm experiencing here.

was going to suggest a different solution, but have localized the error.

In `Index.cshtml`:
```cs
@if (!this.Model.PageBoardContext.BoardSettings.TwoColumnBoardLayout)
{
    @Html.Raw("</div><div class=\"\"row row-discussions\"\">")
}
```
There are duplicate `\"`'s.
```cs
@if (!this.Model.PageBoardContext.BoardSettings.TwoColumnBoardLayout)
{
    @Html.Raw("</div><div class=\"row row-discussions\">")
}
```
removing the extra `\"`'s fixes the loading bug
