### ISSUE TITLE
Scroll to top button on dark theme has transparent background

### ISSUE THREAD

**Issue by danFbach** [YAFNET/YAFNET#1135]
**Describe the bug**
Scroll to top button on dark theme has transparent background, background should be solid. also the icon should be vertically and horizontally centered within the button's borders.

![image](https://github.com/YAFNET/YAFNET/assets/17554977/4147db84-f2b8-4d58-a7c8-81a46417e641)

**Comment by danFbach** [comment]
There is a right margin which makes the icon uncentered in the button. The class `me-1` is responsible for this and should probably be removed from text-less buttons.

**Comment by w8tcha** [comment]
The transparent background is correct, it is also in the light theme. Issue with margin is fixed.
