### ISSUE TITLE
Poor UI of subforums list

### ISSUE THREAD

**Issue by danFbach** [YAFNET/YAFNET#1136]
when looking at a forum with subforums:
![image](https://github.com/YAFNET/YAFNET/assets/17554977/6220f6f3-6353-48b2-b649-bb470b4e4ebb)

The ellipsis (`...`) is on a second line, which looks bad and wastes space. 
However, the ellipsis serves no functional purpose. 
My suggestion would be either turning the ellipsis into a link/button that would toggle visibility of or load the remaining subforums, or eliminate the sub-forums all together and replace it with some kind of toggle to view all sub-forums.

**Comment by w8tcha** [comment]
> However, the ellipsis serves no functional purpose.

Yes it does it indicates that there are more sub forums then at the moment shown

**Comment by danFbach** [comment]
well, yes, I understand that. this was brought to my attention by a user that expected it to do something, like show the additional forums.

**Comment by w8tcha** [comment]
So making it a link which goes to the forum showing all sub forums would solve this i guess?

**Comment by danFbach** [comment]
I think that would be acceptable. I can see how it would be redundant, but also I see the perspective where a user might expect it to do something too, so I think making it a link is a fair compromise.
