### ISSUE TITLE
Style of "Jump to newest post" button does not match in dark theme

### ISSUE THREAD

**Issue by danFbach** [YAFNET/YAFNET#1138]
Button styling does not match the rest of the theme.

As with the top of page button, there is a right margin which makes the icon uncentered in the button. The class me-1 is responsible for this and should probably be removed from text-less buttons.

![image](https://github.com/YAFNET/YAFNET/assets/17554977/2e45e4fd-d378-4601-a730-96d39ad7d769)

**Comment by w8tcha** [comment]
Why does it not match the rest of the theme?

**Comment by danFbach** [comment]
a majority of the other buttons are gray with white text/background, this one is just a border and light gray content. I guess it's okay, it just feels inconsistent.

**Comment by w8tcha** [comment]
Thats because that link button is redundant in that case, its serves the same link as if you would click on the topic link.
