### ISSUE TITLE
Preventing Forum Spams

### ISSUE THREAD

**Issue by john2014** [YAFNET/YAFNET#116]
Most forums receive a lot of spam. One common thing among majority of these spam posts is that they contain between 5 to 20 URLs embedded in them,

What I was thinking is can we mark these post as unapproved if urls in one post is more than some numbers.

Example: In Admin setting, we can have a check box which says "Mark forum post as unapproved it it contains more than 5 URLS".

Note:
1. This checkbox is unchecked by default. This way older forums will work as usual.
2. In admin settings above, we can have a drop down with number from 1 to 20. Default value can be 5.

The advantage of this enhancement is that (1) it should capture majority of spammed forum posts (2) we do not have to send each forum post to stopforumspam and thus it would speed up adding posts. (3) confuse spammers as all their posts are getting unapproved.

This was the only solution I found which will not block current forum members but will immediately block forum spammers who are posting spams posts manually. The stop forum spam is catching less than 5% of all forum spams, so this would be very helpful in blocking most of the forum spams. With the checkbox setting, admins can also disable this functionality.

**Comment by Zero2Cool** [comment]
The spam word filter is working very well.  If there could be a way to ignore users with more than say 50 posts, that would make it even gooder. 

The word "cheap" is used by all spammers regardless of them selling shoes, kitchens, jerseys or whatever and has eliminated spam on my site at least. Although, it is also catching users saying "sign Player X on the cheap" or "what a cheap shot" and things of that ilk.

If we could apply the spam word filter for users under X amount of posts, I think it would make the spam blocking that much more solid of a feature.

**Comment by w8tcha** [comment]
> If we could apply the spam word filter for users under X amount of posts, I think it would make the spam blocking that much more solid of a feature.

Good idea there is now a setting for that.

**Comment by JP58** [comment]
I really like the way this is going.  :-) 

In fact all spam filters could have a common setting for the "under X amount of posts", could maybe even speed up loading time a little for the "good guys"?

**Comment by w8tcha** [comment]
> In fact all spam filters could have a common setting for the "under X amount of posts", could maybe even speed up loading time a little for the "good guys"?

Agree, all spam checking after registration is now disabled if user reaches x amount of posts

**Comment by JP58** [comment]
And the "X" as configurable in the settings?  

Would be great to have some option for "control". ;-)

**Comment by w8tcha** [comment]
Yes of course it can be defined in the host settings.

**Comment by JP58** [comment]
This is implemented now, right?
Maybe time to close?

**Comment by Zero2Cool** [comment]
If you're asking about applying the spam word catcher on users with less than X posts, yes sir, it is.

**Comment by w8tcha** [comment]
No it's not completed, URL checking is not implemented yet

**Comment by JP58** [comment]
Ok, was just wondering...  :-)
