### ISSUE TITLE
Quick Reply Expand rather than Modal

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#1164]
Several years ago the Quick Reply would just expand below the posts. We could scroll up to see other posts we're referencing rather than multi-quoting the whole thing. The Modal is pretty fancy, but I find myself missing the old style where it just expanded.  Maybe we could go back to the expanded Quick Reply instead of popup/modal style?

**Comment by w8tcha** [comment]
Hmh, the idea of the quick reply to make a quick reply and not quoting multiple posts.

> We could scroll up to see other posts we're referencing rather than multi-quoting the whole thing.

Why use the quick reply function for that? If you use the regular post reply page you can scroll through the posts without scrolling the whole page, and keep the editor in focus. That seems the better solution.

Also you could also just close dialog and scroll and the open the dialog again and continue writing.

**Comment by KevinDuganJr** [comment]
> > We could scroll up to see other posts we're referencing rather than multi-quoting the whole thing.
> 
> Why use the quick reply function for that? If you use the regular post reply page you can scroll through the posts without scrolling the whole page, and keep the editor in focus. That seems the better solution.

Why? Because it was a more efficient user experience than clicking a button, navigating to another page and then typing up the post. 

> Also you could also just close dialog and scroll and the open the dialog again and continue writing.
Of course that can be done, however, that is extra user interaction that wasn't necessary prior to the introduction of the modal for Quick Reply. Plus, most people think closing a popup (or modal) will cause them a loss of their inputted data. 

I dunno, it was just an idea. I kind of like how GitHub has ability to reply just at the end of the posts.

**Comment by w8tcha** [comment]
Sorry i'm not against your idea. But your first sales pitch regarding referencing multiple quotes, was not convincing for me.

But i agree i like it how github handles it directly under the post. One solution could be to make it configurable so you can switch between modal and expand.

**Comment by w8tcha** [comment]
I might have found the best solution, to use both. At the moment the quick reply button, which opens the dialog is at the bottom and top of the posts page. 

So first solution to move it to each post  
![quickreply](https://github.com/YAFNET/YAFNET/assets/722575/91fc743c-625f-4ee9-936d-71a9bafe0c21)

which would open the quick reply dialog. And at the end of the posts is the quick reply card..

![quickreply2](https://github.com/YAFNET/YAFNET/assets/722575/e8a29760-8455-4de6-9d33-846d3ce62b85)

**Comment by KevinDuganJr** [comment]
I think that could be good too. I have just never been a fan of popups/modal boxes for things other than notifications. However, I know you have a lot on your plate with this so I am not trying to cause problems. I was just bouncing it around here because I was feeling nostalgic about how you used to have Quick Reply and how it felt smoother and more convenient. And since no one else has said anything about it, that tells me it's likely just a "me" issue, lol.
