### ISSUE TITLE
Migration92 does not work with mySql

### ISSUE THREAD

**Issue by danFbach** [YAFNET/YAFNET#1175]
I just pulled down the most recent version 4 and MySql/MariaDb cannot run migration 92.

When I start up the app, i get the error:
`InfoException: Migration 'Migration92' is still in progress, timeout in 373.509s.` (I only have 6 users, so I'm confident it isn't a patience issue, lol)

I also attempted to run Migration92 from the terminal.

``` mysql
SELECT name FROM sys.default_constraints WHERE parent_object_id = OBJECT_ID('yaf_User') and name like '%DarkMo%';
ERROR 1305 (42000): FUNCTION OBJECT_ID does not exist
```

**Comment by danFbach** [comment]
Okay, I see that it does also try the following for mysql.
``` mysql
SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @tableName AND COLUMN_NAME = @columnName AND TABLE_SCHEMA = @schema
PARAMS: tableName=yaf_User, columnName=DarkMode, schema=leecom_yaf
```

I just forcibly dropped the DarkMode column and then faked out the Migration as complete... luckily this was a relatively simple migration.

It appears that yaf's mysql user did not have privileges to access sys.information_schema table? Some additional testing will need to be done to confirm that

**Comment by w8tcha** [comment]
> Okay, I see that it does also try the following for mysql.
> 
> ``` mysql
> 
> SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @tableName AND COLUMN_NAME = @columnName AND TABLE_SCHEMA = @schema
> 
> PARAMS: tableName=yaf_User, columnName=DarkMode, schema=leecom_yaf
> 
> ```
> 
> 
> 
> I just forcibly dropped the DarkMode column and then faked out the Migration as complete... luckily this was a relatively simple migration.
> 
> 
> 
> It appears that yaf's mysql user did not have privileges to access sys.information_schema table? Some additional testing will need to be done to confirm that

This code should only be executed on a ms sql server. I need to test if dropping the constraint is needed for other sql.
