### ISSUE TITLE
Dark more imperfect on first load from dark mode browser

### ISSUE THREAD

**Issue by danFbach** [YAFNET/YAFNET#1179]
Open the forum in an private/incognito tab (so that everything is loaded default), from a browser in dark mode.
You'll notice a few elements are showing in their light mode version.

Home:
![image](https://github.com/YAFNET/YAFNET/assets/17554977/ee748d9b-901e-4c16-b4b4-61c32248e954)

Topic:
![image](https://github.com/YAFNET/YAFNET/assets/17554977/69711236-8f79-4626-8daf-ed789065e3f9)

As a side issue, a "page flicker" occurs when loading from a dark browser. For a brief moment it shows as light, then quickly changes to dark. 
I _fixed_ this by extracting the js theme code (found at the tail of both forumExtensions files) and creating a new theme.js file. Then executing theme.js in the head, rather than the footer. I don't see any advantage to having it execute in the footer other than allowing it reside within the consolidated js files. You may want to solve this some other way, so I won't make a PR but this solution does work.

**Comment by danFbach** [comment]
coincidentally, executing the theme code in the head also fixes the miscolored elements that prompted me to open the issue.

**Comment by w8tcha** [comment]
This would still require a page reload after the loading on every page, because of the server side class names. I switched the class names to use the newer variable class names. Now there is no more reload

**Comment by danFbach** [comment]
There is still page flicker on loading with an unset theme with a dark default browser.
Calling the autoexecuting theme code in the head resolves it.
