### ISSUE TITLE
[v4 BETA 9] Unhandled exception on poll vote

### ISSUE THREAD

**Issue by kheiserw** [YAFNET/YAFNET#1190]
**Describe the bug**
Voting on a poll causes an uncaught exception in PollController.cs.  The vote is never counted.

**To Reproduce**
Go to a forum topic that has an open poll and click on any of the vote selections

**Expected behavior**
Vote should be counted with no exception thrown

**Screenshots**
![image](https://github.com/YAFNET/YAFNET/assets/168655711/eff3f4ba-ea54-4ba9-9b3e-a2b94d3c5070)

**System (please complete the following information):**
 - YAF Version: [YAF v4 BETA 9].
 - .NET Version [8.0]

**Comment by w8tcha** [comment]
I tried it with a regular and admin user with singe vote and multi vote and it works without errors. I added an is null check, possible this fixes the issue .

**Comment by kheiserw** [comment]
Dug into this a bit more.  The call to get the forumAccess on line 81 is returning null.  The form action for the button is setting the forumId to be the same as the topicId instead of the correct forumId for some reason.  Not sure why this is happening with my install.

![image](https://github.com/YAFNET/YAFNET/assets/168655711/d25e62b7-5b46-46cd-9593-a1f5a6c6d291)

**Comment by kheiserw** [comment]
Looks on line 282 of Pages/Shared/_PollList.cshtml, it should be 

asp-route-forudId="@Current.PageForumID" 

instead of TopicID.  Not sure why it works on your server.  Maybe a coincidence that the topic id happens to be a valid ForumID?

**Comment by w8tcha** [comment]
> Looks on line 282 of Pages/Shared/_PollList.cshtml, it should be
> 
> asp-route-forudId="@Current.PageForumID"
> 
> instead of TopicID. Not sure why it works on your server. Maybe a coincidence that the topic id happens to be a valid ForumID?


Yes that looks like the case on my test installation.

Issue is fixed now
