### ISSUE TITLE
Combined Program.cs and Startup.cs - using forum 4.0 and Blazor

### ISSUE THREAD

**Issue by mrmacdmacd** [YAFNET/YAFNET#1201]
Is it possible to get a new style Program.cs? ie not using startup.cs

or perhaps a little bit of guidance towards running blazor pages along side the forum.

used the example forum as a base and upgraded the project to use blazor manually. 

I can get blazor components to work if i use the original program.cs, but not the one referring to the startup.cs.

that is still working, with the initial load but i cannot get the event's to fire.

probably an ID10T error, but have been trying options to get the blazor into the startup or the dependancy injection (narrowed it down to that) into the program.cs, and haven't gotten anything yet.

appreciate this is probably a support forum question, but upgrading to the single program.cs could only help? :) and the support forum is a bit new and still with some growing pains.

thanks a million!

**Comment by w8tcha** [comment]
The startup.cs is needed to run YAF. So no its not possible to remove it. 

I followed the ms documentation on how to include blazor componennts in to a razor pages app, which you can find here..

https://learn.microsoft.com/en-us/aspnet/core/blazor/components/prerendering-and-integration?view=aspnetcore-7.0&viewFallbackFrom=aspnetcore-8.0&pivots=server#configuration

I updated the yaf sample application to include the counter (blazor component) from the documentation on a razor page or as blazor page.

**Comment by mrmacdmacd** [comment]
Thanks w8tcha, I think that solves my current problem certainly indirectly. 

it was likely related to trying to run the components from the componenets directory separate from the pages. probably my newness to .net blazor.

much appreciated.

You know i'm probably going to ask you about WASM in the near future! for now though i will on with serverside.

**Comment by w8tcha** [comment]
No problem, for me blazor is new too. I never used it before.
