### ISSUE TITLE
YAF Official Website - password reset throws 404

### ISSUE THREAD

**Issue by danFbach** [YAFNET/YAFNET#1213]
Tried to log into the YAF official site, it said my password was not valid - okay, guessing it may have to do with the transition to v4.
So I request password reset. I get the email, click the link and get 404.

![image](https://github.com/YAFNET/YAFNET/assets/17554977/d126633a-b85f-4aa9-9fb1-73e032f3ae69)

**Comment by danFbach** [comment]
The reset link contains `%252f` multiple times and `%253d` twice at the end which is which `/` and `-` double encoded. However, replacing them with `%2f` and `%2d` or `/` and `-` did not resolve the issue. I can PM you the original link if it helps.

**Comment by w8tcha** [comment]
> Tried to log into the YAF official site, it said my password was not valid - okay, guessing it may have to do with the transition to v4.

The old passwords should still work, no changes after v4.

The Code doesnt work as route value because of the `/`  I changed it back to a querystring.

**Comment by danFbach** [comment]
>The old passwords should still work, no changes after v4.

All that i can say about the password situation is that I use firefox's password manager that generates and stores secure passwords and never knew my own password, so it isn't that i am misremembering or mistyping it.

>The Code doesnt work as route value because of the / I changed it back to a querystring.

should the reset links be working now? i sent another this morning and still got 404.

**Comment by w8tcha** [comment]
> should the reset links be working now? i sent another this morning and still got 404.

No i have to update the nuget packages first in order to update the site. Will do this on the weekend.

**Comment by w8tcha** [comment]
updated site is online
