### ISSUE TITLE
Build with Visual Studio Requires Ruby + Sass

### ISSUE THREAD

**Issue by jeffsdata** [YAFNET/YAFNET#1214]
**Describe the bug**
Build with Visual Studio may be missing info about extra dependencies. 
https://github.com/YAFNET/YAFNET/wiki/Build-with-Visual-Studio

In order to run the solution, it requires Ruby and Sass to be on the PATH. 

**To Reproduce**
1. Follow steps in the link above. 
2. Build Fails
3. Message: "You need to have Ruby and Sass installed and in your PATH for this task to work. More info: https://github.com/gruntjs/grunt-contrib-sass"

**Expected behavior**
Link above should include some info about Ruby + Sass - either instructions how to turn off this step or mention that you need to install them and have them available on the PATH. 

**Screenshots**
![image](https://github.com/YAFNET/YAFNET/assets/4433118/752d89a1-0d30-46cc-a443-2f8d569506e1)

**System (please complete the following information):**
 - YAF Version: [e.g. YAF vX.XX.XX]
 - .NET Version 8.0
 - SQL Server N/A

**Comment by jeffsdata** [comment]
I ended up having to:
- install Ruby (on Windows) - using [rubyinstaller.org](https://rubyinstaller.org/downloads/)
- install the "Sass" gem into Ruby - `gem install sass`

That allowed me to get past that error, but then I got another one:
```
1>Running "sass:forum" (sass) task
1>EXEC : error : File to import not found or unreadable: prism.
1>        on line 1 of wwwroot/lib/forum.scss
```

**Comment by danFbach** [comment]
I had similar issues. You may also have to install the prism gem if i remember? 
The environment setup is confusing to set up.

**Comment by w8tcha** [comment]
You no longer need to install ruby. It now uses the compiled dart sass

**Comment by danFbach** [comment]
Okay, Since i took the same path as @jeffsdata initially, i explain what i did to set up the environment correctly this time.

In visual studio, open the developer console (Menu -> View -> Terminal, or (CTRL + \`))
`cd ./YetAnotherForum.NET/` (you should now be in the project root directory where node_modules is located)
`npm install grunt-sass`
 then, optionally, `npm upgrade`
