### ISSUE TITLE
I can't access to the URL to generate machine key

### ISSUE THREAD

**Issue by matteorsso1** [YAFNET/YAFNET#1218]
Good evening,

I urgently need to install this forum, but I'm unable to access your website to generate the machine key. The URL (https://www.yetanotherforum.net/key) seems to keep loading indefinitely.

Thank you in advance,
Matteo

**Comment by matteorsso1** [comment]
Also I need to generate it for the 2.2.4 version of YAF

**Comment by w8tcha** [comment]
I currently testing limiting access to the site because of the aggressive bots. If the site doesn't load then just wait 10-30 minutes then it should work again.

**Comment by matteorsso1** [comment]
ok thank you! One question, I can still use the generated machine key with older version of YAF?

**Comment by w8tcha** [comment]
Yes it should work with older versions.
