### ISSUE TITLE
Suggestion - User message edit policy & quick admin restore option. 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#122]
User post edit issue: 

Would be nice if we could have a "default policy" for editing posts with exemptions.
The "default policy" is there, but only admins/mods are exempted from that rule... 

Ie, I have to have a 365 day edit post limit since some members are actively updating reference information in a very useful post - but I do also occasionally have members who get "grumpy" sometimes and start to edit/emptying their posts in protest in the heat of the moment, which breaks the "forum flow" and renders a topic very confusing... 
So, the default setting + the ability to exempt a few members from that default rule. 

Some kind of "Always edit my own posts" role or such that could be assigned to the members who maintain a reference post of facts. Includes locked topics.

I would like to be able to set a short "edit timeout" like eg 3 days for the forum, but be able to make some members to be able to edit posts more or less eternally without making them moderators/admins and still seen as "regular members" without mod/adm rights...   

Quick admin restore:

Wasn't there a "restore message" button in some older version of YAF in the Message History (when you click "Edited by" and get a list of the edits) so you could do a one-click restore for a selected version in the message edit history? 
Would be very happy if this feature could be reinstated so moderators don't have to manually edit posts and do a copy/paste from the edit history message text.  

I don't know if anyone else has problems with this, but I do certainly have it... 
So it's just another suggestion from a live forum situation...

**Comment by w8tcha** [comment]
> Wasn't there a "restore message" button in some older version of YAF in the Message History (when you click "Edited by" and get a list of the edits) so you could do a one-click restore for a selected version in the message edit history?

Its still there!
