### ISSUE TITLE
Clicking post multiple times creates multiple message

### ISSUE THREAD

**Issue by kheiserw** [YAFNET/YAFNET#1253]
**Describe the bug**
If you click post multiple times before the page is loaded, the message will be repeated the number of times clicked.  This occurs with both reply and quick reply.  

**To Reproduce**
1. Go to Forums
2. Select any topic
3. Scroll down the post box
4. Type something in the body of the message and click the post button multiple times

**Expected behavior**
Only one message should be posted

**Screenshots**
![image](https://github.com/user-attachments/assets/b65dbcba-50b9-48ea-bbeb-7384af20255a)

**System (please complete the following information):**
 - YAF Version: [YAF v4.0 RC3]
 - .NET Version [8.0]

**Comment by kheiserw** [comment]
This seems to be still occurring.

**Comment by w8tcha** [comment]
With the latest beta i can not reproduce it. The button should be disabled after you click it.

**Comment by kheiserw** [comment]
Hmmm okay.  I can double check to see if I missed getting some code.  FWIW, I can still reproduce this on the YAF forum, although it looks like it's been a few weeks since that has been updated.

**Comment by w8tcha** [comment]
Odd how can you still reproduce it on the support forum? Quick Reply is disabled

**Comment by kheiserw** [comment]
It also happens with the regular reply.

**Comment by w8tcha** [comment]
> It also happens with the regular reply.

Ah okay that's an important info. The issue should be also resolved  with the latest commits
