### ISSUE TITLE
Error during Attachment upload: Parameter is not valid.

### ISSUE THREAD

**Issue by lb4029** [YAFNET/YAFNET#1263]
**Describe the bug**
When attempting to upload a attachment that is not a image type (jpg, png, etc) it fails and give the following error on the event logs.

**To Reproduce**
1. Create a new post
2. Fill out required forums
3. Attempt to add an attachment by clicking the attachment button above the Message field
4. Drag and drop a .txt file. (have to drag and drop because the add button does not seem to work even on the live version of the forums)
5. Window closes and displays an error saying Parameter is not valid.

**Expected behavior**
When i upload a file is should be saved to the IIS server

**Screenshots**
![yafnet Error](https://github.com/user-attachments/assets/efefeb26-6bef-4c4a-9df7-17b5c6045781)

**System (please complete the following information):**
 - YAF Version: 3.2.6 & 3.2.7
 - .NET Version: 4.8
 - SQL Server: SQL Server 2022
 
**Affected browser**

* [x] Chrome
* [X] Edge

**Additional context**

**Comment by lb4029** [comment]
Ok so I was able to modify the source and found that in YAF.Core.FileUploader.cs there was an error.

I found that the variable resized would only ever be null if it was not and image file, in this current version there are no checks if resized is null or not like their is in the .net core version. This is my quick and dirty fix to make it work that basically copied what was already there in version 4.

I hope this helps!

```
                    if(resized == null) // Is not an image
                    {
                        newAttachmentId = this.GetRepository<Attachment>().Save(
                                            yafUserId,
                                            fileName,
                                            file.ContentLength,
                                            file.ContentType);
                        using var fs = new FileStream($"{previousDirectory}/u{yafUserId}-{newAttachmentId}.{fileName}.yafupload", FileMode.Create, FileAccess.ReadWrite);
                        byte[] fileData = null;
                        using (var binaryReader = new BinaryReader(file.InputStream))
                        {
                            fileData = binaryReader.ReadBytes(file.ContentLength);
                        }
                        fs.Write(fileData, 0, fileData.Length);
                    } 
                    else
                    {
                        newAttachmentId = this.GetRepository<Attachment>().Save(
                                            yafUserId,
                                            fileName,
                                            file.ContentLength,
                                            file.ContentType);
                        var newFile = Image.FromStream(resized ?? file.InputStream);

                        using var memory = new MemoryStream();
                        using var fs = new FileStream($"{previousDirectory}/u{yafUserId}-{newAttachmentId}.{fileName}.yafupload", FileMode.Create, FileAccess.ReadWrite);
                        newFile.Save(memory, newFile.RawFormat);
                        var bytes = memory.ToArray();
                        fs.Write(bytes, 0, bytes.Length);

                        newFile.Dispose();
                    }
```

**Comment by w8tcha** [comment]
Thanks. I only fixed the issue in YAF 4 not 3.  Issue should be fixed now.
