### ISSUE TITLE
Suggestion - Category Security

### ISSUE THREAD

**Issue by Gofer01** [YAFNET/YAFNET#128]
Abled to place roles and security's levels to a newly create category. Use same values when setting up forum roles,

Reason. We can hide for example Admin, Moderator, or Super Users Categories from everyone else except the users assigned to that role.  All the forums in the category will take on it's category security. If the category is hidden from certain roles.

**Comment by w8tcha** [comment]
>> Reason. We can hide for example Admin, Moderator, or Super Users Categories from everyone else except the users assigned to that role.

If a user does not has access to a forum the category would not be shown. There is no need to add Category Security
