### ISSUE TITLE
Dark mode selection is not persistent through browser closing

### ISSUE THREAD

**Issue by kheiserw** [YAFNET/YAFNET#1281]
**Describe the bug**
If a user selects dark mode, the mode reverts back to light mode after the browser window is closed.  Theme selection is persistent. 

**To Reproduce**
1. Select dark mode while browsing the forum
2. Close all browser windows
3. Open a new browser window and navigate back to the forum
4. See that forum has reverted to light mode

**Expected behavior**
Selection of dark mode should persist after browser is closed.

**System (please complete the following information):**
 - YAF Version: [e.g. YAF v4.0 RC3]
 - .NET Version [8.0]

**Comment by w8tcha** [comment]
I can not reproduce it with edge nor chrome. The cookies are set Correctly. Does this happen in private mode?

**Comment by kheiserw** [comment]
From what I've seen, it only happens when you close all browser windows (even ones that aren't viewing the forums).  I've seen it with both Chrome and Firefox.  I was able to reproduce it both on our site and on the YAF support forum.  Private mode is not enabled.

**Comment by w8tcha** [comment]
Okay i found the issue. If the expire date is not set for the cookie its only valid for the session
