### ISSUE TITLE
Easy Extraction of Number of User Posts

### ISSUE THREAD

**Issue by mrmacdmacd** [YAFNET/YAFNET#1353]
Using v4.03beta with MS SQL for the forum and as my membership management.

going well so far, but now looking to implement something that will require user to have made a minumum number of posts,
it's the NumPosts from yaf_User, which i could call separately, but feel that would be an extra db call as there should be something through public BoardContext Current1 => BoardContext.Current;
Current1.UserNumposts 

I've looked in the forum and it seems that this isn't implemented.

oh and ofcourse this seems like a support forum request, but it doesn't seem to be sending me emails to auth my account.

thanks for the time, support and great product, looking forwards to showing what I am building.

**Comment by w8tcha** [comment]
Yes the number of posts is in the boardcontext

` this.PageBoardContext.PageUser.NumPosts`

or

` BoardContext.Current.PageUser.NumPosts`

**Comment by mrmacdmacd** [comment]
Seems obvious now!
Thanks a million, appreciate the fast response.

    On Tuesday 19 November 2024 at 11:45:43 GMT+2, Ingo ***@***.***> wrote:  
 
 


Yes the number of posts is in the boardcontext

 this.PageBoardContext.PageUser.NumPosts

or

 BoardContext.Current.PageUser.NumPosts

**Comment by w8tcha** [comment]
Regarding you registration in the support forum. It looks like Yahoo has blocked my mail server, and I can't do anything about it. 

The only solution is to register again with a different email address.
