### ISSUE TITLE
Idea: CSS style applied to Topic author

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#137]
If you've seen blogs you have noticed when a blogger authors a topic/article, and makes a comment, their comment has a different CSS to it than the others.  

Would this be something interesting for YAF to have?  You start a topic, then your post body has a .8 transparency or something to give it a little distinguished look from the others?

**Comment by w8tcha** [comment]
Implemented as "topic starter" badge next to the user name in YAF 2.3.0
