### ISSUE TITLE
Paste Image from clipboard = Upload Attachment

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#1371]
I'm playing around with YAF 4.0 RC4 an the new Editor and pasting an image from clipboard doesn't upload it as attachment. I'm labeling this Feature Request with the assumption it is feature just not yet implemented.  If it is implemented and I'm doing something wrong, please let me know. 

The new editor is pretty slick! 😁

**Comment by w8tcha** [comment]
It should actually work. Does the attachment upload work via the attachment button?

**Comment by KevinDuganJr** [comment]
Yes, attaching via clicking the button does work. I also tried this on the YAF Support Forum, too. I do not see any console errors or anything to indicate an issue.

**Comment by w8tcha** [comment]
Sorry i didnt read correctly. The issue was about copy from clipboard not drag and drop. 

Bot both dont seem to work. Working on a fix

**Comment by KevinDuganJr** [comment]
We're going to be able to drag and drop images into a post??? Whoa, that will be awesome!

**Comment by w8tcha** [comment]
drag and drop was not enabled, any copy to clipboard needs to be implemented

**Comment by KevinDuganJr** [comment]
BTW, confirmed this is fixed.
