### ISSUE TITLE
Interests field size increase to 4000 chars.

### ISSUE THREAD

**Issue by lasercreationsnz** [YAFNET/YAFNET#1372]
Any chance we can get the limit on the User Profile->Interests field increased to 4000 chars.  I see the database is an nvarchar(4000), but it's restricted in the EditProfile.cshtml.cs to 400, and in UsersProfileInputModel.cs and EditProfileInputModel.cs.

**Comment by w8tcha** [comment]
Actually the field was not set correctly in the db. It should be set to 400. Or do you want the field to be increased?

**Comment by lasercreationsnz** [comment]
I was hoping for it to be increased

**Comment by w8tcha** [comment]
Yes if this is needed i change this for 3.2.8/4.0.0 final
