### ISSUE TITLE
Feature - Embed Facebook Status

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#144]
Apparently this can be done, but even looking at the Twitter embed I haven't been able to figure it out. 

https://developers.facebook.com/docs/plugins/embedded-posts

**Comment by Zero2Cool** [comment]
The Twitter and Facebook embed stuff is awesome! Below you can see an example of the Facebook embed.

http://www.packershome.com/forum/posts/m301788-GameDay--2014-Playoffs--Green-Bay-Packers-vs-Dallas-Cowboys

**Comment by RawbertVegan** [comment]
Aw.. that's so cool! I want it too!
Will it work in DNN? If yes, how do I do it?

**Comment by Zero2Cool** [comment]
Yeah, just do as Ingo suggests lol
