### ISSUE TITLE
Allow Users to Deactivate their Own Accounts

### ISSUE THREAD

**Issue by Jaben** [YAFNET/YAFNET#16]
It would not delete their existing posts -- just delete their user account and set their posts to owned by Guest.

Would require re-entering password.

**Comment by w8tcha** [comment]
Needs to implement as soon as possible! GDPR requires that the user can delete the account!

**Comment by w8tcha** [comment]
Will be implemented as user can delete their account.

Will set the user to unapproved, and delete all posts (flagged as deleted)
