### ISSUE TITLE
FYI - Yaf Standard BBCode Editor shortcuts

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#166]
My live site is still on I think 2.1 and CTRL Q brings up the quote tags. I noticed in my beta site which is using the latest changeset/build, the shortcut is not longer working.

This is not a request for it to be added back or anything of the sort. Just passing it along in case it was not intended to be discarded.

**Comment by Zero2Cool** [comment]
What editor must be used to see these? I'm using Standard and this is what I see.
![image](https://user-images.githubusercontent.com/5612416/70558915-62110080-1b4b-11ea-8b28-0cf8d8c11c33.png)

On YAF's support forum I see the good stuff.
![image](https://user-images.githubusercontent.com/5612416/70558852-4ad21300-1b4b-11ea-9119-4c8021a5de48.png)
