### ISSUE TITLE
Incorrect "my topics" fuctionality in multiprocessor server

### ISSUE THREAD

**Issue by maxdm** [YAFNET/YAFNET#176]
If I specify for YAF app pool more than one working processes, I get randomly changed last access times in combo and different set of latest topics, when click F5 or click my topics (active, from last visit combobox)

**Comment by w8tcha** [comment]
Sorry for the late answer. But the Problem is that each worker process has its own session state. For YAF its not recommended to use multiple processes because yaf needs to maintain the state.
