### ISSUE TITLE
Suggestion for active users list(s)... 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#18]
When looking at the forum stats at the bottom:

![image](https://f.cloud.github.com/assets/5246746/1125585/0a52a9fe-1b14-11e3-9c27-d47779e8c69e.png)

Then I press the 172 guests... 

![image](https://f.cloud.github.com/assets/5246746/1125629/f7423a04-1b14-11e3-8d59-1fdf77337fec.png)

As an admin, I would be happy if this list could be sortable on eg the IP address to determine if a rouge Romanian magpie bot has spawned like 100 of threads from the same IP that slows the forum down...  Grid column sortability would be a very nice option to have from an admin point of view... Also in the admin section "Who is online" pane... 

![image](https://f.cloud.github.com/assets/5246746/1125685/e10a177e-1b15-11e3-8b24-c8a39c07656e.png)

Just a suggestion for future releases, can be done client-side so it it doesn't load the db so much...

**Comment by w8tcha** [comment]
Added in 2.2.0 final

**Comment by JP58** [comment]
Thanks, must upgrade to 2.2 soon so I can try to help more... Has been a "lost year" for me YAF-wise... :-(
