### ISSUE TITLE
New Installation - Azure Database error

### ISSUE THREAD

**Issue by john2014** [YAFNET/YAFNET#191]
When installing the YAF forum for first time on azure, it gives the following error:

Server Error in '/' Application.

FILE:
mssql/tables.sql

ERROR:
Tables without a clustered index are not supported in this version of SQL Server. Please create a clustered index and try again.
The statement has been terminated.

STATEMENT:
if exists (select top 1 1 from sys.columns where object_id = object_id(N'[dbo].[yaf_Active]') and name='IP' and precision < 39)
alter table [dbo].[yaf_Active] alter column [IP] varchar(39) not null

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Exception: FILE:
mssql/tables.sql

ERROR:
Tables without a clustered index are not supported in this version of SQL Server. Please create a clustered index and try again.
The statement has been terminated.

STATEMENT:
if exists (select top 1 1 from sys.columns where object_id = object_id(N'[dbo].[yaf_Active]') and name='IP' and precision < 39)
alter table [dbo].[yaf_Active] alter column [IP] varchar(39) not null

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[Exception: FILE:
mssql/tables.sql

ERROR:
Tables without a clustered index are not supported in this version of SQL Server. Please create a clustered index and try again.
The statement has been terminated.

STATEMENT:
if exists (select top 1 1 from sys.columns where object_id = object_id(N'[dbo].[yaf_Active]') and name='IP' and precision < 39)
    alter table [dbo].[yaf_Active] alter column [IP] varchar(39) not null]
   YAF.Classes.Data.LegacyDb.system_initialize_executescripts(String script, String scriptFile, Boolean useTransactions) in d:\YAFNET-c88c6e1172ef60b6bdd1c3d6b81a7012a51af557-1\YAFNET-c88c6e1172ef60b6bdd1c3d6b81a7012a51af557\yafsrc\YAF.Classes\YAF.Classes.Data\mssql\LegacyDb.cs:6059
   YAF.Core.Services.InstallUpgradeService.ExecuteScript(String scriptFile, Boolean useTransactions) in d:\YAFNET-c88c6e1172ef60b6bdd1c3d6b81a7012a51af557-1\YAFNET-c88c6e1172ef60b6bdd1c3d6b81a7012a51af557\yafsrc\YAF.Core\Services\InstallUpgradeService.cs:349
   YAF.Core.Services.InstallUpgradeService.UpgradeDatabase(Boolean fullText, Boolean upgradeExtensions) in d:\YAFNET-c88c6e1172ef60b6bdd1c3d6b81a7012a51af557-1\YAFNET-c88c6e1172ef60b6bdd1c3d6b81a7012a51af557\yafsrc\YAF.Core\Services\InstallUpgradeService.cs:253
   YAF.Install._default.Wizard_NextButtonClick(Object sender, WizardNavigationEventArgs e) +1617
   System.Web.UI.WebControls.Wizard.OnNextButtonClick(WizardNavigationEventArgs e) +111
   System.Web.UI.WebControls.Wizard.OnBubbleEvent(Object source, EventArgs e) +401
   System.Web.UI.Control.RaiseBubbleEvent(Object source, EventArgs args) +37
   System.Web.UI.WebControls.Button.OnCommand(CommandEventArgs e) +114
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +159
   System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument) +10
   System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument) +13
   System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData) +35
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1724

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.36213

**Comment by Pistle** [comment]
There is IP restriction for accessing Azure Database.
You need to add your Public IP to the allowed Ip address on the Azure ManageMent Portal.
