### ISSUE TITLE
Suggestion : Selected Quote

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#217]
You ever want to quote just a snippet of what someone said, but have to quote the entire thing and delete a lot of it and inadvertently break the BBCodes? 

How about adding a feature for when a user highlights a portion of a post, an option is display for them to quote/reply?

**Comment by JP58** [comment]
Would be a great feature, but how? 
Select a text, press Reply and automagically get the selected text as a quote into your reply (with original poster) sounds like a huge challenge to me - but it would be a stunning feature indeed...  ;-)

**Comment by Zero2Cool** [comment]
When the user highlights the text, a button/text is displayed saying "Quote". You click "Quote", it gets quoted and located into the Quick Reply box. I've seen this on other forum software so it can be done, but I'm Javascript illiterate so I haven't a clue lol

**Comment by JP58** [comment]
Means that there are 2 of us...  :-D

**Comment by RawbertVegan** [comment]
That would be a really nice feature!!
