### ISSUE TITLE
dbo.yaf_forum_moderators stored proc is taking 5 minutes to run

### ISSUE THREAD

**Issue by ontariosingh** [YAFNET/YAFNET#223]
I migrated yaf database from 1.9.1.8 to 2.1.2 BETA 20140406. Installer had successfully completed. 

I notice that database access is very slow. 
dbo.yaf_forum_moderators stored proc is taking 5 minutes to run.
Other calls to many other stored procs are slow too.

number of records in db:
yaf_vaccessfull: 45913518 (took 2.44 minutes to do count(*))
yaf_vaccess_group: 110061006 (0 second to do count(*))
yaf_vaccess: 45913478 (took 3.03 minutes to do count(*))

**Comment by Zero2Cool** [comment]
Was this fixed or just closed?

**Comment by w8tcha** [comment]
This was a duplicate from the forum which was already answered (if i remember correctly) without any feedback
