### ISSUE TITLE
Suggestion - Top 500 topics when moving

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#229]
The moving posts is quite painful and when you have to wait for every topic to load, it is even more painful. Can we have a dropdownlist with various quantities to speed it up? 

Show Most Recent : 150, 500, All

Something like that where it defaults to the zero index first so it loads faster.

**Comment by w8tcha** [comment]
![selectmenu](https://cloud.githubusercontent.com/assets/722575/5888641/cf7bc666-a407-11e4-9b14-e56b003e6282.png)

I just build a new drop down, as shown in the screenshot you can directly search for a topic. Or by default with no search input the List has paging. Its calles infinite scrolling which means it loads by default 15 topics and when you scroll down 15 more and so on.

Its a nice little control which should be in more then this place.

**Comment by JP58** [comment]
Could it maybe be an idea to use for the whole forum too? A "quick search"? 
I mean an Ajax search box to search topic titles within the forum with a quick jump to the selected topic? 

I think that kind of search would help many users to quickly search for something they are interested in and at least get some quick hits on topics similar to what they are interested in. 

Of course there are 2 things to complicate it - forum role based security (topics viewable for only registered users, admins, moderators and other roles should not show for a "guest" and so on... )... 
And of course that users give "good" topic subjects, but that is a matter of user maturity... 

Just an idea, might make the forum easier to use and avoid duplicate topics in the long run... 

When you get into the 10 000's of topics, it gets a bit "scattered" to put it mildly....  ;-)

**Comment by w8tcha** [comment]
Yes a real time results search for the current quick search is on my to do list
