### ISSUE TITLE
Integration YAF in NopCommerce

### ISSUE THREAD

**Issue by hundhaus** [YAFNET/YAFNET#234]
How to make a single authorization?

**Comment by hundhaus** [comment]
How to make one authorization?

**Comment by w8tcha** [comment]
Depends on which membership system NopCommerce uses?

**Comment by hundhaus** [comment]
No. NopCommerce not use membership.

**Comment by w8tcha** [comment]
Ok in that case you would create a solution to manually register and login the user on the page where the forum control is included.

So basically check during page_load if the user is logged-in via nopcommerce check if the user exists in Yaf, if yes then set the login cooke and if not register the user in yaf
