### ISSUE TITLE
Use tags with topics

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#240]
A few ideas pertaining to the use of tags with topics before I burp and forget them!

Ability for admin/moderator to silently set tag words. Silently as in don't display the "edited by moderator" dialogue. 

Or  maybe use each word of the topic as individual tags?

**Comment by BonzoFestoon** [comment]
Has any one implemented a topic tags or labels feature?  If not, can you give an idea of how you think it would be best to implement this feature?  It seems like it would be a huge undertaking.

**Comment by w8tcha** [comment]
Tagging should be visible for all users like on stackoverflow. this would make it possible to search the forum for tags

**Comment by Zero2Cool** [comment]
This is gonna be awesome.
