### ISSUE TITLE
MySQL Support

### ISSUE THREAD

**Issue by mistressofjellyfish** [YAFNET/YAFNET#241]
So, as you're already using a ORM with a few custom things, there are chances to finally port YAF to MySQL.

I personally like to give it a shot, Are there any caveats to watch out for? A quick look over the code does not show anything too bad.

**Comment by masterofjellyfish** [comment]
I've started an implementation here - https://github.com/masterofjellyfish/YAFNET/tree/mysql

Once this is reasonably done (aka core functions are working) I'd send you a pull request.

**Comment by Jaben** [comment]
FYI: https://github.com/vzrus/VZF

**Comment by w8tcha** [comment]
I guess this can be closed

**Comment by w8tcha** [comment]
Support will be added in 3.0
