### ISSUE TITLE
Issues with attachments in version 2.2

### ISSUE THREAD

**Issue by avousv** [YAFNET/YAFNET#244]
Hi, 
I have noticed some issues with attachment in recent stable version 2.2.0.

1. I miss a lot the Attach button that was for years next to Edit and before Thanks button. 
2. The new popup window appears for 1 second and then it disappears (both Chrome and Firefox).
3. I can't figure out how to delete (remove) an attachment from a post anymore.

My database was upgraded from a 2.2 beta version and perhaps has some schema flows (it seems that a field was removed).

Any ideas?

Thanks

**Comment by w8tcha** [comment]
1. That button is now inside the Editor the little paper clip icon
2. I assume you mean the pop up window for Attachments Upload? Are you getting any JS errors in the browser console?
3. this will be possible again in 2.2.1 where you can remove the old attachments

**Comment by avousv** [comment]
Thanks for the fix. Now it works fine.

For some reason I can't see the little paper clip icon. Is it a matter of selected theme (Clean Slate)? Which is the working theme?

**Comment by w8tcha** [comment]
> For some reason I can't see the little paper clip icon. Is it a matter of selected theme (Clean Slate)? 

No its not a matter of the theme but of the editor you are using it is only used in the Standard BB Code Editor, in all other Editor's the Attachments Feature is bellow the Editor.

The only thing else which matters is that it is only shown for user roles with Attachment Access.
