### ISSUE TITLE
Password reset emails are being filtered as SPAM

### ISSUE THREAD

**Issue by gavinharriss** [YAFNET/YAFNET#246]
The hosting company where I have http://www.paydirt.co.nz/forums installed have a SPAM filter that will intercept SMTP mails it considers SPAM.

I'd see these errors in the events log:

SendMailThread Failed for the 2nd time (the email will now deleted) with an SmtpException (Email to: [EMAIL ADDRESS], Subject: Password Retrieval for PayDirt Forums Forum): System.Net.Mail.SmtpException: Transaction failed. The server response was: 5.7.1 Mail (m-42532-06140) appears to be unsolicited - blackRe: 'big5 (20)' - contact postmaster@[MYDOMAIN] for resolution at System.Net.Mail.DataStopCommand.CheckResponse(SmtpStatusCode statusCode, String serverResponse) at System.Net.Mail.DataStopCommand.Send(SmtpConnection conn) at System.Net.Mail.SmtpConnection.OnClose(Object sender, EventArgs args) at System.Net.ClosableStream.Close() at System.Net.Mail.MailWriter.Close() at System.Net.Mail.SmtpClient.Send(MailMessage message) at YAF.Core.MailMessageExtensions.Send(MailMessage message) in c:\!Projects\Pay Dirt\YAFNET\YAF-Nightly-SRC-163e0c016087d4c2b8b625d807ce0b1eaa417195\YAF.Core\Extensions\MailMessageExtensions.cs:line 133 at YAF.Core.Services.YafSendMail.SendAllIsolated(IEnumerable`1 messages, Action`2 handleExceptionAction) in c:\!Projects\Pay Dirt\YAFNET\YAF-Nightly-SRC-163e0c016087d4c2b8b625d807ce0b1eaa417195\YAF.Core\Services\YafSendMail.cs:line 73

The hosting company setup a rule to allow these emails through but made this suggestion:

To avoid this issue reoccurring in the future I would recommend that you set the character set of the password reset emails to something other than the following (they are currently encoded as 'big5'):

charset=.?BIG5
charset=.?CHINESEBIG
charset=.?GB2312
charset=.?KS_C_5601
charset=.?KOI8
charset=.?EUC-KR
charset=.?ISO-2022
charset=.?CP1251

**Comment by w8tcha** [comment]
Which YAF Version?

**Comment by w8tcha** [comment]
This issue is already fixed in 2.2.0
