### ISSUE TITLE
Unable to attach files if BB Codes not loaded in board

### ISSUE THREAD

**Issue by crf370** [YAFNET/YAFNET#251]
This may be by design, but you are no longer able to add and view file attachments to a post if you do not have the BB Code [attach] installed. We upgraded to 2.2.0 and run about 150 boards in one instance. We did not use BB Codes in the past and now all of the boards have lost the capability to view attached files. 

The file attachment part does work, and correctly displays [attach]xxx[/attach], but without the BB code, it will never display as an file, but rather just as the tags.

Is there a work around, or can we remove the dependency?

Thanks

**Comment by w8tcha** [comment]
If the bb code doesn't work then you have unchecked the check box during on the upgrade wizard to upgrade the bb codes.

You can resolve this by simply re-run the upgrade wizard and make sure that the checkbox is checked (which it is by default).

**Comment by crf370** [comment]
Thanks, but we did do this, and for those boards with bb codes it's not a problem. I have 150 boards without any bb codes installed and frankly don't need them. Is it a requirement that bb codes are loaded for file attachment display to work? I would rather leave them off if possible.

**Comment by w8tcha** [comment]
Yes in that case it is required. What's the reason to not install them?

**Comment by crf370** [comment]
These forums are all private and behind a login and are used by a very unsophisticated user base. Much of these codes would not be used and just confuse our users. The extra challenge I now have is that I have 150 boards that do not have these codes installed that have just lost the functionality of viewing attachments. I'm going to look at rather removing the dependency attachments have and see what I can code up.

**Comment by w8tcha** [comment]
Well you dont have two install all of them simply install just the attachment bbcode

**Comment by crf370** [comment]
That might be the way I go for now. Certainly the quickest if I can find a way to do 150 at once? Any suggestions? Script it directly to the database?  I see they are stored in yaf_BBCode. I can probably come up with some sql to loop and insert.

**Comment by w8tcha** [comment]
Yes all you have to call via sql would be yaf_bbcode_save

**Comment by crf370** [comment]
I'll try that, thanks.
