### ISSUE TITLE
Topics Visible to OP Only

### ISSUE THREAD

**Issue by voicis** [YAFNET/YAFNET#252]
All the topics in the forum are visible only to their OP and users who have permission to see visible to OP only topics. ([phpBB equivalent](https://www.phpbb.com/community/viewtopic.php?t=543859))

**Comment by w8tcha** [comment]
What does OP means?

**Comment by Zero2Cool** [comment]
Original Poster? 

I hit the phpBB link and I am not sure I understand why anyone would only want to see only topics they have started.  It might cause duplicate threads and silo conversations because if you can only see topics you started, who are you going to converse with?

**Comment by w8tcha** [comment]
Well limiting view access to certain users or roles can already be done via the access masks for a forum. And also there are the hide bbcodes which makes it possible to limit the topic visibility to a specific user group or user

**Comment by voicis** [comment]
Probably should have started with the usecase.

We have an application form which on submit creates a topic in forum where the applicants can only see and reply to their own applications, but members can see and reply to all applications. We are migrating away from phpBB and would like to keep this feature. 

I've tried several combinations of access masks, but couldn't achieve the wanted result. If I understad correctly bbcodes only hides the content of post not the whole topic, which is not what we are looking for.

**Comment by w8tcha** [comment]
> We have an application form which on submit creates a topic in forum where the applicants can only see and reply to their own applications, but members can see and reply to all applications. We are migrating away from phpBB and would like to keep this feature.

I understand now, but this would require lots of work, in order to override the access masks. At this point i don't think such feature will be implemented anytime soon.

**Comment by JP58** [comment]
I must be stupid, but I don't see the point of this at all unless you want to create "secret buddies group posts"... Or have I misunderstood completely?
