### ISSUE TITLE
Adding a way to manage your subscriptions from the notification email

### ISSUE THREAD

**Issue by crf370** [YAFNET/YAFNET#253]
We needed a way to easily remind our users how to unsubscribe from a topic or forum they are watching. Especially since we do automatically subscribe them to a few when they sign up. What we did was add the following into the language.xml (english.xml in our case) file for the resources TOPICPOST_HTML and TOPICPOST_TEXT.

"Unsubscribe and manage your subscriptions here {subscriptionlink}".

Then in YAF.Core/Services/YafSendNotification.cs in the ToWatchingUsers method at line 380 when adding the Template Parameters:

watchEmail.TemplateParams["{subscriptionlink}"] = YafBuildLink.GetLinkNotEscaped(ForumPages.cp_subscriptions, true);

Would it be possible to permanently add this feature to YAF? Saves us from having to add it back each time we upgrade. If people don't want to use it, they can just leave it off their language file. Or you could just leave it off by default.

Thanks
Clyde

**Comment by w8tcha** [comment]
Good idea

> Would it be possible to permanently add this feature to YAF?

Do you know how to make a pull request? (Clone the source code -> commit your changes -> create a pull request) Otherwise i add it manually.

**Comment by crf370** [comment]
Might be a good idea for me to figure out how. We have some other enhancements we've added that may be of use to the community and we are happy to share. Let me give it a try.

**Comment by Zero2Cool** [comment]
crf370 that would be greatly appreciated.

**Comment by crf370** [comment]
Thanks for the reminder. I'll get this code up this coming week.
