### ISSUE TITLE
Last posted by forum statistics 

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#260]
It looks like the last person posted is showing regardless of the viewers security. 
![screenshot_2015-04-04-08-36-17](https://cloud.githubusercontent.com/assets/5612416/6992853/476948cc-daa6-11e4-92f9-fb30c308ab74.png)

**Comment by w8tcha** [comment]
But thats not really a problem because no content is revealed, this wont be changed

**Comment by Zero2Cool** [comment]
I wasn't saying it was a problem, simply pointing it out in case it was simple to modify to present accurate information, that was all. :)

**Comment by w8tcha** [comment]
Because of that i removed again the link to the last topic. The would be a performance decrease to make the last topic link depended on the current user.

**Comment by Zero2Cool** [comment]
I did notice that it was not there. :-) I was quite happy to not have to modify that lol 

Also, great point, it would certainly decrease performance if another check had to be done. My bad, I was just pointing it out.  You're doing awesome with YAF, thank you again!

**Comment by vzrus** [comment]
YAF has cache.
