### ISSUE TITLE
Pagination on Search

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#262]
If you have more than 15 results and you're trying to go page by page, after the second or third click, you're tossed back to page one.  Using YAF.NET 2.2.1 BETA 20150329

**Comment by w8tcha** [comment]
I tried to reproduce it with the support forum but it works as expected.

But i thing that could happen depending on the theme you are using when you are not clicking on the number but on button around the number

**Comment by Zero2Cool** [comment]
If you right click open link in new tab and click another number in the pagination, it'll go back to page one. Does this on support forum and my forum. I really do not know if this is an issue or not so feel free to close. I'm thinking when the new page is opened, it might reset a session variable or something?

**Comment by w8tcha** [comment]
Thanks for the info. now i was able to reproduce it and fix it. Indeed as soon as you visit a page that was not search page the search session was cleared. This is fixed now.
