### ISSUE TITLE
The variable name '@LastMessageID' has already been declared.

### ISSUE THREAD

**Issue by ZeroBugBounce** [YAFNET/YAFNET#264]
Hi folks, I was trying to build/run the latest commit, completely new installation, and during the database setup I got this SQL exception:

FILE:
mssql/install/procedures.sql

ERROR:
The variable name '@LastMessageID' has already been declared. Variable names must be unique within a query batch or stored procedure.

Seems pretty straightforward, but let me know if I can provide any more info.

**Comment by Zero2Cool** [comment]
Ha, cool username!  

Did you try running the install twice by chance? Additionally, once you received this error, did you try deleting that database, creating a new one and attempting again?

**Comment by ZeroBugBounce** [comment]
Thanks @Zero2Cool!, I just hopped in an deleted and retried, still got the error, so I just took a quick look:
````
create procedure [{databaseOwner}].[{objectQualifier}message_delete](@MessageID int, @EraseMessage bit = 0) as
begin
    
    declare @TopicID		int
    declare @ForumID		int
    declare @MessageCount	int
    declare @LastMessageID	int
    declare @UserID			int
	declare @LastMessageID	int
	declare @ReplyToID      int
````

Sorry, I should've looked before.

Once I removed the 2nd Declare, it did work.... I can make a pull request for this tiny change but it won't be until tonight.
