### ISSUE TITLE
Arabic RTL Theme Support.

### ISSUE THREAD

**Issue by mesutcakir** [YAFNET/YAFNET#268]

**Comment by w8tcha** [comment]
Can you be more specific? RTL is supported via the language files.

**Comment by mesutcakir** [comment]
Situation like this,

I chose my arabic language file.

But from right to left writing is required, IsRTL = true / false. I can not find the setting.

**Comment by w8tcha** [comment]
Sorry yes this was not implemented yet, yaf now detects if the current culture is rtl and then changes to page output to rtl. But this is still not 100% perfect yet
