### ISSUE TITLE
IP White list

### ISSUE THREAD

**Issue by w8tcha** [YAFNET/YAFNET#273]
In order to avoid certain users or ip addresses getting automatically banned by ip, we would need an Ip White list as counterpart for the banned ip

**Comment by Zero2Cool** [comment]
Why would an IP get banned if not for good reason?

**Comment by w8tcha** [comment]
Because Sometimes the reasons are not good, or at least the intentions are good but turn out to be bad. I got several of reports of mods banning the wrong users, causing the forum to go completely go down.

And on the support forum there where a few users who got banded because they selected the wrong user name which was in the stopforumspam database

**Comment by Zero2Cool** [comment]
Oh yeah, it bans by username.  Would it be worthwhile to notify the user at the time of registering that the username is a known spam account?  Or would that just let the spammers know to change the name?

**Comment by JP58** [comment]
Well, it's a way to keep your own IP from being banned as I see it...  ;-)

**Comment by Zero2Cool** [comment]
I'm pretty much a certified angel so I have no worries bout being banned incidentally from my site. :)

**Comment by w8tcha** [comment]
Not needed any more.
