### ISSUE TITLE
Image attachments to posts in editor preview issue.

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#274]
I am in the process of upgrading to 2.2.1 final and have noticed a small annoyance with attached images in the editor. I use the standard YAF editor. 

The whole process of uploading works fine, with selecting an existing one, multiple drag'n'drop upload and so on. 

However, while in edit mode.... 

When doing a preview in the editor, the images are not using ceebox as in a final post... 

The scenario is like this: 

1 - I make new long post, or edit an existing one, and write something super clever (as usual)...  :-) 
2 - I attach some images to the new/edited post.
3 - I want to preview the post and press the Preview button.
4 - In the preview pane, I wish to see the sequence of attached images so I click on one image. 
5 - The image opens up in the current tab fully (it's just a link), and that was not was I expected so I close it. 
6 - I have now closed the forum page and with it - all my edits and all the insightful clever work I have done is lost.... 
7 - I get annoyed since I can't remember all the great wordings I used while editing the new/existing post. 
8 - I am sure many of my users will do like this too and feel the same thing and be less happy with the forum software. 

So I wonder, is it much work to add the ceebox rendering also to the editor preview? 
It would be a much better "user experience" if the preview worked the same way as a posted post.

**Comment by w8tcha** [comment]
the ceebox part is now included, but i think to resolve the issue...

> 6 - I have now closed the forum page and with it - all my edits and all the insightful clever work I have done is lost.... 

This is related to Issue #256. I think i need to port my autosave plugin to the default YAF Editor.
