### ISSUE TITLE
Suggestion for the admin Banned Email/IP/Username dialogs.

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#276]
It is great that we have this history feature now in these pages. 
This is a great tool to monitor moderator actions compared to the forum spam rule based actions towards the spammers. 

It would be very nice if it could be column sortable, or at least have the default sort on date descending so the latest actions are listed first. 

Just an idea...

**Comment by w8tcha** [comment]
I think it is enough to sort it by newest first + the option to search

**Comment by JP58** [comment]
That is great. :-)
