### ISSUE TITLE
Changing email in user profile

### ISSUE THREAD

**Issue by maxdm** [YAFNET/YAFNET#279]
Editbox with email enabled but nothing changes when I trying to save new emai address.

**Comment by w8tcha** [comment]
It can take a few seconds until the page is saved, otherwise check the browser console if there are any errors occuring during saving

**Comment by w8tcha** [comment]
Otherwise this could also be related to the caching issue posted here

http://yetanotherforum.net/forum/posts/t17664-Pages-stay-the-same-until-I-refresh
