### ISSUE TITLE
Cannot move message to another topic (2.2.2 Beta).

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#280]
Seems like something is not right here... 

![image](https://cloud.githubusercontent.com/assets/5246746/8011878/fdfcc23e-0bbc-11e5-93e2-e582888201d1.png)

The "Select forum to move to" is ok with a list of existing forums, but there is no list presented under "Select topic to move to"... 

![image](https://cloud.githubusercontent.com/assets/5246746/8011940/8f10610e-0bbd-11e5-87a3-d5ccc364ad65.png)

My moderators are scared to death if this is not working.  
Moving a whole topic seems to work fine, though.

**Comment by JP58** [comment]
I think this is something that is wrong in my Live forum, in my test forum it works.

**Comment by JP58** [comment]
After downloading the entire live site & db to my local machine, I believe this is an Ajax vs multiprocessor thingy, similar to some other issue reported earlier as I remember it...   

On my home computer with a single 4-core i5 it works perfectly fine, but on the live site with dual Xeon E5-2620 with in total 24 logical cores it fails... 

So I think it might be some kind of timing, thread safety issue or such.

Thus a reopen is motivated. I think this could be a tricky one... :-/

**Comment by w8tcha** [comment]
This issue is not caused by yaf, i'm getting the following exeception...

>> mu-jquery.js:115 Uncaught TypeError: $(...).jqte is not a function

on 

```javascript
// Textarea editor selectors
$("#MU_Helptexts textarea").jqte();
```

**Comment by JP58** [comment]
Sorry, but that JS error has been there for ages... It's just a textarea editor used in other places of the site and has not affected YAF operation earlier. And it works on a single processor 4-core i5 machine but does not work on a dual processor E5-2620... 

Removed the references to it from the live site, but I still get the same phenomenon so the missing script function is not the reason for not listing the options in the dialog, but some kind of multi CPU threading issue as I see it... 

Live site (multiprocessor): 
[image](https://cloud.githubusercontent.com/assets/5246746/8021206/c9d7d59a-0c96-11e5-8a63-5c3264f4a6f8.png)


Copy of live site at home (single processor) : 
Works well even with the jqte function failing... 
![image](https://cloud.githubusercontent.com/assets/5246746/8021241/5e720e18-0c98-11e5-94d6-a106ad9a95a8.png)

Earlier versions have worked fine, even with the missing homebrewn JS function on the forum page.

**Comment by JP58** [comment]
Same DB after upgrade, same forum settings, same app.config etc... 
Win 2012 R2 (Win 8.1 at home), SQL Server 2014, latest .Net libraries, service packs and so on... 
So I am a bit confused too... The only thing that differs is the hardware and base OS, and that smells like timing/threading/async issues to me since the "Select topic to move to" is not populated as expected... 

I beg to differ regarding the issue as "invalid", if you don't mind, since it exists and I would be happy for a little bit deeper look into it if possible when time allows...     

Will of course keep an eye out for the "nightlies" and update also the live site...

**Comment by w8tcha** [comment]
I see an 302 redirect error when while calling the ajax function, the odd thing is that a similiar ajax function to get the attachments list in the editor works fine.

I see only one difference between those ajax calls which was the content type was not set. I uploaded a new nightly, but i guess this will not fix the issue.

**Comment by JP58** [comment]
Installed the latest nightly on my fresh home copy of the site, and now that selection box does not work anymore at all "at home" - neither on the live site copy nor on the standalone forum copy I also have to separate my own mistakes from forum issues...  

Have had a similar issue myself once, but that was doing "AsParallell" LINQ queries towards the EF. 

To me it seems like the content for the dropdown box is not served in time for the script to pick it up, or there is some quirk in the query leading to a null or a non-list result return of the values...  I am just speculating wildly as usual... Please bear with me...  :-)

**Comment by w8tcha** [comment]
Check your web.config do you have the

```xml
<webServices>
      <protocols>
        <add name="HttpGet" />
        <add name="HttpPost" />
      </protocols>
    </webServices>
```
entries under system.web?

**Comment by JP58** [comment]
I did not, and after adding them to the site web.config it works perfectly... 

A thousand Thanks for solving this, it is obviously a config change that I had not noticed. 

Nothing wrong with the code, I have obviously been to lazy to check for any web.config changes lately..  :-)

**Comment by JP58** [comment]
And obviously there could be something more to it, since it has returned...  Really strange...  

![image](https://cloud.githubusercontent.com/assets/5246746/8894750/3dc8cbce-33c2-11e5-86b7-087ad37af505.png)

**Comment by w8tcha** [comment]
What version are you currently using?

**Comment by JP58** [comment]
Oohhh, I think it's nightly 90...
