### ISSUE TITLE
YAF publish from VS has errors: missing files

### ISSUE THREAD

**Issue by maxdm** [YAFNET/YAFNET#281]
1>------ Publish started: Project: YAF, Configuration: Release Any CPU ------
1>Connecting to C:\Users\maxdm\Desktop\yaf...
1>Copying all files to temporary location below for package/publish:
1>obj\Release\Package\PackageTmp.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Web\Microsoft.Web.Publishing.targets(2988,5): Error : Copying file Content\images\progressbar.gif to obj\Release\Package\PackageTmp\Content\images\progressbar.gif failed. Could not find file 'Content\images\progressbar.gif'.
2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Web\Microsoft.Web.Publishing.targets(2988,5): Error : Copying file Content\fonts\glyphicons-halflings-regular.woff2 to obj\Release\Package\PackageTmp\Content\fonts\glyphicons-halflings-regular.woff2 failed. Could not find file 'Content\fonts\glyphicons-halflings-regular.woff2'.
2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Web\Microsoft.Web.Publishing.targets(2988,5): Error : Copying file Scripts\jquery-2.1.4.min.map to obj\Release\Package\PackageTmp\Scripts\jquery-2.1.4.min.map failed. Could not find file 'Scripts\jquery-2.1.4.min.map'.

**Comment by Zero2Cool** [comment]
What kind of errors?

**Comment by maxdm** [comment]
Sorry, i've posted empty issue.
