### ISSUE TITLE
Question/bug? - The new attach image preview size and its configuration? 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#282]
With the old attachment method, the image preview size followed the setting in the host settings.  

![attachsettings](https://cloud.githubusercontent.com/assets/5246746/8137308/af76d59c-1142-11e5-98ec-ccbb5bcb06ad.jpg)

But with the new attach method, they show as 200px wide thumbnails instead of what is set in the host settings. Where does this come from? 

![imgsmall](https://cloud.githubusercontent.com/assets/5246746/8137344/fe8e308a-1142-11e5-9598-34ab34f78dea.jpg)

I think that it would be nice if the image attachment size rules would apply also to the new attach method. Actually I think it is a kind of "bug"....

**Comment by JP58** [comment]
I can also add that if I uncheck the "Enable Image Attachment Resize" checkbox, the images show in the configured size once, but the ceebox is inactivated so there's no prev-next and such in any images. 

What is worse - if the topic contains images attached with the new routine, and the "Enable Image Attachment Resize"  is unchecked - entering the topic itself will generate a forum error. 

If anyone else has encountered this phenomenon, I think we have small bug. 
I think it should be reproducable. 

Still on beta 2.2.2.0 70 in the live environment.

**Comment by JP58** [comment]
Great, will try it tomorrow night!   :-)

**Comment by JP58** [comment]
Will there be a "nigthly" on this?

**Comment by w8tcha** [comment]
https://ci.appveyor.com/project/YAFNET/yafnet/build/artifacts

**Comment by JP58** [comment]
Works fine, now respects the Host settings as it seems.
