### ISSUE TITLE
Global Board Announcement

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#283]
From support forum by: MAs_MAa

all forums should have a global announcement feature .. meaning it should appear on all sections ... 
How do we do that? for now under the 'priority' tab we have  sticky and Announcement and both are serving the same function... by being the pinned up post in a particular section
pls make announcement as a global feature rather than a section feature

**Comment by Zero2Cool** [comment]
Being able to have a public announcement to the entire board would be a nice addition. A little blurb about "we're going to be down from X to Y doing an upgrade" will inform all users nicely. That's just one use case of it.

**Comment by JP58** [comment]
Announcements can be topic-specific, so some additional admin controlled public announcement area at the top of each forum page would be great indeed. With some show/hide option of course...  :-)

**Comment by ITVF** [comment]
We need help with making global announcement feature which is viewed in all sections... can we have that as a feature please???

**Comment by w8tcha** [comment]
added in 2.31.0
