### ISSUE TITLE
CK Editor - CTRL + ENTER

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#284]
yafStandardEditor has this cool feature for submitting a post by hitting ctrl and enter at the same time. CKEditor seems to lack this shortcut. Actually, just noticed it appears to be missing all shortcuts.... also spell check doesn't work while typing either.

**Comment by Zero2Cool** [comment]
Skip this... my posts with ckeditor aren't even showing up so I must have messed up something while upgrading.

**Comment by w8tcha** [comment]
CKEditor now has all short cuts as the standard editor.

**Comment by Zero2Cool** [comment]
If I didn't have a 40 mile bike ride to do, I'd be upgrading lol ...

**Comment by Zero2Cool** [comment]
CKEditor is not posting the message after CTRL + Enter. It just reloads the page.
