### ISSUE TITLE
Onsite Notification for YAFNET

### ISSUE THREAD

**Issue by alishachris** [YAFNET/YAFNET#287]
Hello, 

Can you also develop a feature that would allow users to be notified in the forum If a user quoted them or replied in a post that they are involved in?

Instead of the notification going to the email address of the individual, he gets the notification while on the forum website, just like Facebook. 

Thanks

**Comment by JP58** [comment]
This is a good idea indeed IMHO, we live in an online device world where we expect instant notifications about things we are involved in on our devices or when we are online on a site. Often you don't have the email you registered to the forum with at your home computer directly accessible on your phone, pad or work computer - at least I don't...  ;-)

**Comment by w8tcha** [comment]
Onsite Notification for Quoted Posts, Mentions and received Thanks has been added to YAF 2.3.0
