### ISSUE TITLE
Add post rating icons

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#291]
Adding status ratings to a post would be great  addition.

Default options: Thumbs up, Thumbs down, Agree, Disagree, Funny, Informational, Appreciation, Useful, Old News, etc ... this would give users a lot of options and could even allow an admin page to add new ones with linking it to an image, kind of like how the smileys page works.

**Comment by w8tcha** [comment]
I guess this wold make the thanks feature obsolete

**Comment by Zero2Cool** [comment]
Yeah, probably not a great idea. Especially now that I see other places doing it.
