### ISSUE TITLE
Old image attachment CSS does not apply to the new attach method. 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#292]
I just nagging on about the new attach method compared to the old one. 

It was very nice to be able to customize the "old" attachment container with CSS, but those CSS settings do not apply to the new attach method. 

Are there some new CSS settings that can be defined/applied, or could maybe the existing settings be made to be applied to the new [attach] tag within code?

**Comment by w8tcha** [comment]
Be aware that image attachment now treated more like images (img tags) inside the post. 

This means that if attachment resize is disabled the css classes for the image would be "UserPostedImage" which is the same as for the image tag from the img bbcode. And additionally it contains the "attachedImage" css class if you want to style it differently

When attachment resize is enabled the the link has the css class "attachedImage"

**Comment by JP58** [comment]
Thanks, I saw the "attachedImage" class when I tried to use it to make the new attachments the same size as the old "attach" prior to reporting the bug regarding the attachment settings. 
I'll play more with the "attachedImage" class....  :-)
