### ISSUE TITLE
500 (Internal Server Error) when moving a message

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#295]
Trying to move a message into another topic and I'm getting 500 (Internal Server Error). I'm not sure what could be changed, but it's not working on any of the three YAF sites I have.  Anyone else having issues? 

Version: Powered by YAF.NET 2.2.2 BETA 20150525 

Ingo, if you want to see the error, you're Host Admin on www.packerpeople.com

btw, I do have the ... 

    <webServices> 
    <protocols>
      <add name="HttpGet" />
      <add name="HttpPost" />
    </protocols>
  </webServices> 

in my web.config

**Comment by Zero2Cool** [comment]
{"Message":"Invalid JSON primitive: forumID.","StackTrace":"   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()\r\n   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)\r\n   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)\r\n   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)\r\n   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize[T](String input)\r\n   at System.Web.Script.Services.RestHandler.GetRawParamsFromPostRequest(HttpContext context, JavaScriptSerializer serializer)\r\n   at System.Web.Script.Services.RestHandler.GetRawParams(WebServiceMethodData methodData, HttpContext context)\r\n   at System.Web.Script.Services.RestHandler.ExecuteWebServiceCall(HttpContext context, WebServiceMethodData methodData)","ExceptionType":"System.ArgumentException"}

**Comment by w8tcha** [comment]
is that still an issue on your sites? because i can not reproduce it there. or does it happen in a specifc sub forum?

**Comment by Zero2Cool** [comment]
Yes, it is still happening on both of the sites. I cannot move any message from a topic into another topic.

**Comment by Zero2Cool** [comment]
Also, each keystroke entered into the topic dropdownlist produces another console error like the one pasted below.

    POST http://www.packerpeople.com/forum/YafAjax.asmx/GetTopics 500 (Internal Server Error)
