### ISSUE TITLE
Attachment Upload Dialog was not working in master

### ISSUE THREAD

**Issue by maxdm** [YAFNET/YAFNET#296]
When I select file or drag file to area - nothing happends

**Comment by w8tcha** [comment]
Was it working before?

Which browser?

Are there any java script errors in the browser console?

**Comment by maxdm** [comment]
Yes, error is in screenshot.
![untitled](https://cloud.githubusercontent.com/assets/6984595/8401165/642b51fa-1e33-11e5-9f82-5f3dbde8775d.png)

I use local jquery version.

**Comment by w8tcha** [comment]
Fixed with latest commit
