### ISSUE TITLE
Suggestion - Google & other resource images to show with the img-tags... 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#297]
Many are using image URL:s nowadays that look like this (Google's new shared photos example):

https://lh3.googleusercontent.com/_vaNDfD8o_I9Ro8FfFuuEvea8URjHaxDdnctKPNE1Ky1=w1047-h785-no

Means no file extension to rely on for presentation, between the img bbcode tags. 

With this particular case, there is a workaround for the forum - if you append ?.jpg to the URL, it shows. But this is in this special case of URL I think, since it is not a parameter but a "route"...  Adding the extra ?.jpg does not work if there are other URL parameters added via ? and &. 

So I have a small 2-step suggestion... 

1 - The simple fix - add ?.jpg to the URL between the img tags at runtime if there is no file extension nor parameters in the URL given within the img bbcode tags for "external" links before the forum presentation of the URL is made. Should cater for at least for the new Google type of links to .jpg images.  

2 - The real fix is of course to evaluate the file type in the file header at runtime, but that is a bit more complicated work as I understand... 

The example URL above works directly in a browser.

![image](https://cloud.githubusercontent.com/assets/5246746/8337213/0034a0c0-1aaa-11e5-8231-c7c8f1e50aa6.png)

**Comment by w8tcha** [comment]
Hmh are there only image served via that domains or is that also used for other files? If only for images i see no problem adding detection for that domain.
