### ISSUE TITLE
Opps - this was in an earlier 2.2.1 beta, has it returned in 2.2.2 beta? 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#298]
![image](https://cloud.githubusercontent.com/assets/5246746/8363132/639bdad8-1b7d-11e5-8161-40e31fd2070b.png)

Would explain why I only get FB signups the last week(s)...

**Comment by Zero2Cool** [comment]
What was the issue? Looks like my site seems to be okay and it's on 2.2.2 Beta.

http://www.packershome.com/forum/register

**Comment by JP58** [comment]
Which nightly build are you running?

**Comment by Zero2Cool** [comment]
This link here is running latest build from source.
http://www.packerpeople.com/forum/register

Has the domain error. Is that something we need to set because that's a copy of packershome.com and i know the emailing doesn't work because of the domain.

**Comment by w8tcha** [comment]
That error has nothing to do with yaf, Invalid domain would mean that the key does not match the domain

**Comment by JP58** [comment]
Strange, it has matched for a couple of years...

**Comment by JP58** [comment]
Ok, deleted & created a new rC key pair.  Works now.

**Comment by w8tcha** [comment]
I think the new recaptcha system needed a new key, which was added in 2.2.0
