### ISSUE TITLE
Soft Delete and Hard Delete

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#299]
I would like Moderators to have the ability to Soft Delete (flagged as deleted) something, but not Hard Delete (database removal).  Would this be something worth while? I am probably in the minority when it comes to never wanting things deleted so this might not be distinguishable.

**Comment by JP58** [comment]
Well, why don't you tell them not to check the "Delete from Database" checkbox? 
My guys are well behaved and do not do permanent deletes since they are instructed not to...  :-) 
We actually mostly move rouge messages from members to a moderator area for "bad messages"...

Of course, killing spammers & deleting the Nike et als messages with the "Kill User" button is another story, don't want these in the db at all...

**Comment by Zero2Cool** [comment]
If people were robots, then simply telling them not to do something would suffice. Unfortunately, people are human and humans make mistakes. I think there should be a distinction between the two, especially with the " Delete All Posts?" is automatically checked.  I would like Permanent Delete to be more deliberate and intentional.  In my infinite brilliance, I have a few times tabbed through, hit space and that checked the box and I didn't see it before I hit tab and space again and it was permanently deleted.  And of course if there were any posts linked to it, they were deleted as well. D'oh!

That was on me and I am fine with that blame. I am not fine if this happens to one of the moderators whom I do not want permanently deleting things. 

Spam is easier because they simply move the topic into the Spam section we have. Then I look for keywords to add to the awesome spam word block-magic feature. Then I delete it. 

Essentially, I want full responsibility over my site data while still allowing others to help out with moderator privileges. Maybe I can manipulate this concept via some Access Mask / Role magic?

I'll have to poke around and see what I can break, err, find.    :)

**Comment by JP58** [comment]
Well, I've had my trusted moderator team for some years now and they know the "rules"... 
What we move into our "restricted area" are more like bad behaviour posts, and spammers are just killed. Earlier we moved spam too, but no need to do that nowadays so we just kill it. Several bots/day are blocked with the Spam features, and the few "manual" spammers are dealt with by the mods.   

Must give immense credit and admiration to Ingo for making this killer "Internal Spam words" feature, it is indeed something that works extremely well and is unique to this forum software as I understand.

I just love how Ingo is bringing this project forwards...  :-)

**Comment by w8tcha** [comment]
Well we already have the option to soft and hard delete messages.

The solution for that would be to hide the "Delete from Database" checkbox from Moderators if you don't trust your mods. 

I don't know should this box shown only for admins by default or should this be an access mask option?

**Comment by Zero2Cool** [comment]
The trust factor comes from trusting it won't happen, not that the moderators are rogue. Essentially, I want to sleep well knowing nothing will be accidentally deleted. 

Yes, there is the option to soft delete and hard delete, however, I can't find a way to limit hard delete to Admin's and only have moderators (or some other role/mask) soft delete. It seems if you can do one, you get both. I could be wrong and apologize if I am.
