### ISSUE TITLE
How to login by URL string?

### ISSUE THREAD

**Issue by tanobi92** [YAFNET/YAFNET#301]
Hi all! 
I use login of YAF.
I want to login by url. Format url:http://localhost:42648/yaf_login.aspx?returnurl=%2fdefault.aspx&i="string". 
string: encrypted password, username.
when I enter url if username,pass true then go to forum. 
I try set Authenticated = true if check string return true. but not go to forum, it stay login.
this.Login1.RememberMeSet = false;

      AuthenticateEventArgs auth = new AuthenticateEventArgs();
      auth.Authenticated = true;
      Login1_Authenticate(this, auth);
      LoginCancelEventArgs log = new LoginCancelEventArgs();
      Login1_LoggedIn(this, log);

I think I'm still missing something.
Help me, please! Thank!

**Comment by w8tcha** [comment]
Question has been answered in the support forum
http://yetanotherforum.net/forum/posts/t17760-How-to-login-by-URL-string

**Comment by tanobi92** [comment]
Thank you very much!
