### ISSUE TITLE
Attachment with tinymce

### ISSUE THREAD

**Issue by avousv** [YAFNET/YAFNET#302]
Hi,
I have a forum which uses tinymce editor (HTML). I've downloaded YAFNET-2.2.2 (code and examples)  and added tinymce scripts from an older (working) version (2.2.0). I updated database to the new schema.

I (still) have issues using the new attachment system.

I can select existing attachments (although they are marked as [attach]102[/attach][attach]106[/attach], which is not convenient for me) but I cannot select new attachments either by Add files or Drop files. 

I can pick files but as soon as I select them, nothing happens so there is no Start upload.

Also there is no delete attachment functionality.

Then I changed databases and I created a new database from scratch. What I noticed is that although I selected Tinymce (html) as editor, the editor does not appear (probably a script error somewhere). Also in this scenario New Attachments don't work. Reverting back to my database eliminated the problem of editor.

I must confess that the 2.0.x way of attachments was working as expected for me and I wish it could be back. 

Maybe I'm missing something (I don't use bbcodes etc). 

Alex
 

I

**Comment by w8tcha** [comment]
> I can pick files but as soon as I select them, nothing happens so there is no Start upload.

Did you get any error messages in the browser console?

YAF 2.2.3 BETA contains a few fixes regarding. Please let me know if that issue also occurs with that version
