### ISSUE TITLE
Email Admins on topic post.

### ISSUE THREAD

**Issue by valdearg** [YAFNET/YAFNET#303]
Hello,

Previously I had the forum setup to email Administrator users whenever there was a post on the forum.

This option does not appear to be working since I upgraded to version 2.2 from an earlier version of 1.9.5. 

Currently running version 2.2.2 BETA 20150525.

**Comment by w8tcha** [comment]
Well there was never such option, only if the post is in a forum that needs to be approved. If you want admins to automatically get a email on a new post then there have to manually opt in. First of all you need to enable the Host Setting ->  "Allow Notification of All Posts on All topics" 

Then a user can opt in via the Email Notification Preferences page, and change the "Select email notification preference" to "Notification for all posts on all topics"

**Comment by valdearg** [comment]
I've checked this option but it doesn't appear to be working.

Under Host Administration > Host Settings > Permissions, Allow Notification of All Posts on All Topics is set. Under my profile the "Notification for all posts on all topics" is set.

Any other options I should check?

**Comment by w8tcha** [comment]
Ok this is indeed a bug, fixed in 2.2.3
