### ISSUE TITLE
Reported post count is off

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#305]
To reproduce the glitch.

Report a post
Do not resolve the post
Move the post to a new topic

You'll still have one reported post in the balance but when you click on it, nothing worthwhile happens.

**Comment by w8tcha** [comment]
i try to reproduce this. with 2.2.3 beta but no luck. is this still an issue?

I tried exactly what you did. I moved the second posts in one topic to a new topic and i was still able to click on the report count button to see the post.

**Comment by Zero2Cool** [comment]
I would think if you could not reproduce it, then it is probably no longer an issue.

**Comment by w8tcha** [comment]
Okay i close it for now. Feel free to re-open it again if the problem occurs again
