### ISSUE TITLE
YAF and <asp:Content 

### ISSUE THREAD

**Issue by vzrus** [YAFNET/YAFNET#308]
It seems YAF doesn't work inside Content control. At least in the end of the last year it still worked.
The page simply freezing and links are not available.
This means YAF cannot be used inside sites with MasterPages.

**Comment by Zero2Cool** [comment]
I'm not sure I understand what you're saying, but I'm pretty sure I'm using YAF within Content control. Below is my Default.aspx  if that helps.

     <%@ Page Title="Green Bay Packers" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="PackersHome.Default" %>

<%@ Register TagPrefix="YAF" Assembly="YAF" Namespace="YAF" %>

<asp:Content ID="BodyContent" runat="server" ContentPlaceHolderID="MainContent">
    <div class="blockWrapper">
        <div class="largeHeader styleHeader">Green Bay Packers Forum</div>
        <div class="blockBody">
            <YAF:Forum runat="server" ID="forum1" BoardID="1"></YAF:Forum>
        </div>
    </div>

    <br />
</asp:Content>

**Comment by w8tcha** [comment]
If the pages are freezing then this could be a java script issue. Are you getting any errors in the browser console ?

**Comment by vzrus** [comment]
No. It's simply freezing. Surely, I suspect JS conflict. 
Thanx, Zero2Cool. At least I know where to dig it now. I didn't know you are using the horrors. :) 
P.S. This is another issue.
I didn't look why but when this setting is enabled
<add key="YAF.JQueryUIOverrideFile" value="jquery-ui-1.11.4.min.js" />
it gives an error in the Firebug console, but if it's disabled YAF still loads the script from /Scripts

**Comment by vzrus** [comment]
The problem is that normalize.css from main application loads first and 
blocks something intrection
Somehow it turns all page links unclickable, not YAF's only. The are looking 'half-transparent" In Firebug.
Thanx for help. At least it can be fixed in a way.
