### ISSUE TITLE
Individual Block Option For PM/Email/Friend Request

### ISSUE THREAD

**Issue by john2014** [YAFNET/YAFNET#31]
From: http://forum.yetanotherforum.net/yaf_postsm61337_User-Option-In-CP-for-PM-Email-Friend-Request.aspx

Can we add an option in user control panel to allow user to have an option to block receiving PM/Email/Friend request from other users?

Currently the only way to block PM is to have admin create a role with PM=0 and manually move user to that role. Also currently there is no option to block email/friend request from others.

Is it possible to add this as a feature request. It would be very simple to implement:

In user control panel, add three check box:
1. Block other users from sending me PM
2. Block other users from sending me Email.
3. Block other users from sending me friend request.

In backend DB, just add one more column in users table called "BlockContact"

It can have values "pm,email,friend" for each user.

If it has all three values, it means users does not want to receive pm, email and friend request.

If it has values "pm, email", it means user does not want to receive pm and email only. He is fine with others sending him friend request.

If it is NULL, then they are no blocks.

All this assumes that pm, email and friend request are enabled in Admin settings.

**Comment by Zero2Cool** [comment]
Every time I read about PM's I think back to Ingo's idea of having PM's more conversation-like and would really like to see it go that direction.

**Comment by w8tcha** [comment]
Sorry this took a bit longer then expected. I like the idea however the only exception should be to exclude users that are in the friends list. Meaning if you add a friend then the user would be able to send you a private message
