### ISSUE TITLE
Render Error in yaf.modules.bbcode.attach

### ISSUE THREAD

**Issue by sslfto** [YAFNET/YAFNET#310]
If the user leave an uncorrect formatted message example: [attach]1[attach]18[/attach][attach]19[/attach]7[/attach]
the complete site will fail.

In source code change from

var attachment =
                this.GetRepository<Attachment>()
                    .ListTyped(attachmentID: this.Parameters["inner"].ToType<int>())
                    .FirstOrDefault();

to

try{
var attachment =
                this.GetRepository<Attachment>()
                    .ListTyped(attachmentID: this.Parameters["inner"].ToType<int>())
                    .FirstOrDefault();
}catch{ return; }

**Comment by Zero2Cool** [comment]
Tested this error and can confirm, it does indeed blow the site up.
