### ISSUE TITLE
Security: Not validated return url on the login page

### ISSUE THREAD

**Issue by hawksign** [YAFNET/YAFNET#316]
It is possible to enter any url inside the 'returnurl' parameter of the login page. You can also inject javascript code with it. An attacker, for example, could abuse this to steel usernames and passwords.

Example code:
/login?returnurl=javascript:alert('XSS')

**Comment by w8tcha** [comment]
I can not reproduce the issue. The javascript gets never executed, at least not in chrome.

**Comment by hawksign** [comment]
I have tested it on firefox (43.0.1) and chrome (47.0.2526) and they both executes the javascript code. It is only executed after a user has signed in successfully.
