### ISSUE TITLE
Enable attachment in posts

### ISSUE THREAD

**Issue by romulodp** [YAFNET/YAFNET#318]
Hi,

How can I set new topics to enable attachments?

Thank you,
Romulo Portillo

**Comment by w8tcha** [comment]
If you want to enable Attachments you can do that via the Access Masks, for example if you want to allow  all users to allow Attachments then you need to Assign the Member Access Mask to the Member Role. You have to do that for each forum. So what you need to do is go to Admin > Settings > Forums > Click on edit of the forum you want to edit. On the next Page you can assign an Access Mask for each Role (Group)
