### ISSUE TITLE
Use Windows authentication and register user automatically as guest

### ISSUE THREAD

**Issue by romulodp** [YAFNET/YAFNET#319]
Hi,

I'm trying to change how YAF Forum authenticates users. Just a brief overview of how forum is set up. Currently, when a user is added in third party system, we are adding the same user in the forum's database and Windows authentication is enabled in IIS. 

Business wants to remove this dependency and allow any user to access the forum itself. We are looking for still uses the Windows authentication but handle it just after user type the credentials. So, if user has access continue loding forum controls and page. Else, we want to add the user to the forum DB automatically. 

What's is the best option to achieve this?

Thank you,
Romulo

**Comment by JP58** [comment]
Not YAF forum related, but I actually implemented something similar some month ago for our new customer document portal...  I used this as the blueprint - http://tech.trailmax.info/2016/03/using-owin-and-active-directory-to-authenticate-users-in-asp-net-mvc-5-application/
