### ISSUE TITLE
New Chat Link

### ISSUE THREAD

**Issue by john2014** [YAFNET/YAFNET#32]
New enhancement/feature request:

Can we add a link called "chat" in the forum header. It will be located besides My profile, my album, my topic.

When a user clicks on this link, they are taken to a separate page where the chat is in "full screen" or larger mode than iframe.

We can keep it simple by just loading the chat popup iframe with a bigger height and width than the current setting.

**Comment by w8tcha** [comment]
The Shoutbox has been removed in 2.3.0. The new YAF Sample Application includes a new SignalR Chat. At the moment it will not be part of YAF directly. But i will be available as Extension
