### ISSUE TITLE
Notify users when post is soft deleted/edited

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#320]
When soft deleting a post it is basically hidden. Would there be any benefit to notifiying the user one of their posts has been hidden with the reason why? I think this would give them the opportunity to say "screw you!" or maybe cooler heads prevail and say "eh, my bad, can you restore it so I can edit it?"

**Comment by w8tcha** [comment]
Well sending the user an email with the delete reason would not be difficult to implement. But what happens next. Should the user contact the person who deletes the post?! and the person mod or admin next restores the message. I think that would be the easiest solution

**Comment by Zero2Cool** [comment]
Sending a user an email is probably obnoxious. Maybe an alert that they have soft deleted messages and urge them to rectify the reason why they were soft deleted? More emails that are sent out, the more they become ignored noise is how I feel about it.  I think my intentions for soft deleting is different than YAF intends. I could see it being used more as a tool for moderation in the sense that we all lose our cool from time to time or act out of character and instead of a swift hand of justice, maybe give them an opportunity to "let cooler heads prevail".

**Comment by JP58** [comment]
How about a PM?

**Comment by w8tcha** [comment]
I still dont like this. especially this would need to also notify user of linked posts which are also automatically deleted.

I'm closing this for now.
