### ISSUE TITLE
Suggestion - Admin function to consolidate accounts... 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#321]
Some of us run forums over a long time (15 years in my case) so there are always members who registered "100 years ago" with one user name and register with a new name later since they don't remember their old credentials or have moved forward with a new web identity due to social media accounts and such. They (and a serious forum admin) of course want to move their older posts  to their new name/id to have some continuity...  

Today I edit the db tables manually and it can be a bit tedious at times...  

So my idea is to have a simple admin routine to move posts, topics, albums & PM's from one user id to another one. Like a simple dialog with 2 select/search fields with from/to user and a move button that updates the db. Attachment uploads are a bit more tricky, but those will still be viewable as long as you don't delete the user. 

As usual, I like to suggest admin improvements... ;-)

**Comment by Zero2Cool** [comment]
I just move the topics/messages to the old ID via sql stored proc, resetting their password and send email with new password. Once they sign back in, blow away new account. Happens about once a year.  I would imagine this wouldn't be difficult to incorporate though.  And if it's happening a lot, certainly would be beneficial.

**Comment by JP58** [comment]
I think it would help a lot, having it an "official" way as a forum admin feature... 
Brought this up as a suggestion since I've had 3 requests this month, usually just max 1/month but it would be helpful to have a routine so co-mods/co-admins can do it via the admin interface without having accounts on the SQL Server... Would help on a site with distributed 24/7 moderation with several trusted moderators/admins.

**Comment by w8tcha** [comment]
You know that user can change their names via the display name feature?

**Comment by JP58** [comment]
I haven't enabled that feature. And users are old ones registering with a new Internet "identity", wishing to change to the new instead of their ancient id...

**Comment by w8tcha** [comment]
After some time and a review. I still dont understand the problem. Whey do they want a new account when they want to keep there messages?

Thats why the display name feature exist! The user can change the name and the rest of the user profile and keep all the content (messages, private messages, attachments, albums, etc).

**Comment by w8tcha** [comment]
Closing this for now!
