### ISSUE TITLE
Suggestion - Image/file attachments also in PM's 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#323]
I have had the question a couple of times now why you can't attach images in PM's, ie there is no "paperclip button" so you can select existing or upload new attachments also in the PM editor. 

It would be very nice if it was possible to enable attachments also in PM's, like when someone in a forum wants to sell some item and the potential buyer wants more details & pics before deciding.  It would make life within the forum easier for users so they don't have to send emails or bloat a forum topic with pics nobody else is interested in. Another area is where you wish to send documents from your computer to another member without disclosing you mail address... Would keep members in the forum within the forum scope regarding information exchange.   

Tried to insert the attach code in a PM... 
Edit: 
![image](https://cloud.githubusercontent.com/assets/5246746/14027426/d95488a0-f1f7-11e5-8fa5-737b31b5d434.png) 

Preview: 
![image](https://cloud.githubusercontent.com/assets/5246746/14027466/0e7091f0-f1f8-11e5-99ec-3601e1d54a1d.png)

Received PM:
![image](https://cloud.githubusercontent.com/assets/5246746/14027527/5912d4fc-f1f8-11e5-83ad-f8c008209ca7.png)

My observations:
Attachments would be possible since the preview resolves the attachment ID, but the PM "viewer" does not resolve the attachment the same way as the preview does. I think attachments with "download only" possibility would be good enough to start with. No real need to implement the image viewer logic fully. However, if it's "just" bbcode interpretation - why not the same for posts & PM's?

**Comment by w8tcha** [comment]
The problem that the access mask would not work here. To allow or disallow the attachment uploads for user groups or user.

The question is if we need this on a group base. Or only one host setting to enable or disable attachments uploads for private messages?

**Comment by JP58** [comment]
In my case, it's a host scope setting since I only run one forum actively - and I think it's ok for any authenticated member to attach pics in PM's to another member since they already can attach pics in public posts... It's a kind of behind the scenes scenario - member-to-member - and if you are a member you should be able to send attachments too in PM's. Would even help admins if screen dumps with error codes could be posted in error reports notified via PM's from members. 

That's my thought of it, of course there might be other issues with multiboard installations and such...

**Comment by FrancoZ** [comment]
I would also like this function. There is not a real risk for abuse from users' part of this function in my opinion. It is much worse not to allow them to attach simple files since doing so will bring them to use email or other media moving away from the forum.

**Comment by JP58** [comment]
Oooh, would have needed this feature today...  ;-) 
Well, will have to email back and forth with the forum member instead... :-)
