### ISSUE TITLE
CeeBox not handling img-tags in 2.2.3... 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#325]
I found that the great feature for click-to-view images published with the img bbcodes using CeeBox is not working anymore with 2.2.3. A click on an image just opens up the url in the same browser window. 

Attached images work as they should.

**Comment by Zero2Cool** [comment]
I've been Powered by YAF.NET 2.2.3 BETA 20150822 and with attachments it just opens in the browser. I thought it was a feature newly added.

**Comment by JP58** [comment]
The attachments have "always" popped up on the same screen with the introduction of the CeeBox "Lightboxy" functionality.  In the last versions, this has also been the standard for links to images within the img tags. Guess who suggested that so images in posts would be treated "the same"... ;-) 

So that's why I noticed it immediately, one of my implemented improvement suggestions does not work anymore...

**Comment by Zero2Cool** [comment]
Not suggesting a switch, but was looking into it just in case I need something like that for other projects. Can't find a working version of it, but did find this alternative. http://fancybox.net/

**Comment by w8tcha** [comment]
We switch to a bootstrap solution in the future. The ceebox is outdated and has some problems.

The issue with the posted Images is fixed now

**Comment by Zero2Cool** [comment]
This looks like a decent Bootstrap solution. What says you?

https://blueimp.github.io/Bootstrap-Image-Gallery/

**Comment by JP58** [comment]
Thanks w8tcha!
Just waiting for the bootstrap 3.0 milestone version! :-)

Blueimp does look very decent to me... :-)
