### ISSUE TITLE
Upgrade to .NET 4.5.2

### ISSUE THREAD

**Issue by w8tcha** [YAFNET/YAFNET#327]
I think most people already running the latest .NET version. So i think we can use this as Minimum version for the next Major version 2.3.x

**Comment by Zero2Cool** [comment]
What features a part of 4.5.1 will be used by YAF?

**Comment by w8tcha** [comment]
Well 4.5 should be more fast and better performance. Other then that there is nothing you really can see

**Comment by Zero2Cool** [comment]
Right now YAF is at 4.0 requirement, right?

**Comment by Cambridgeport90** [comment]
4.6 is the latest, hence we should probably require it. It’s always better to be running the latest than anything less, because that way all security updates are taken care of.

**Comment by w8tcha** [comment]
Yes at the moment it is 4.0. 4.6 is not an option. Of course normally the newest is the best solution. But it takes some time until all web hosts have upgraded. And the most common version at the moment is 4.5.x

**Comment by Cambridgeport90** [comment]
Well, that’s unfortunate. People need to hurry up. What if self-hosters like myself want to use the latest though? Wil it work, at least?

**Comment by JP58** [comment]
Just remember, 4.5.1 is not supported any more. 4.5.2 is the lowest supported 4.x version.
https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

**Comment by w8tcha** [comment]
> Well, that’s unfortunate. People need to hurry up. What if self-hosters like myself want to use the latest though? Wil it work, at least?

Of course you can install the latest version of .net and have the latest security updates. This has nothing to do with the Application.

**Comment by Cambridgeport90** [comment]
Oh … dang. But I guess if the features implemented in the latest versions aren’t actually needed, then, doesn’t realy make a whole lot of sense.

**Comment by marietteknap** [comment]
The performance benefit of > 4.5 is huge IMHO and if possible we should go asap to 4.5.2

**Comment by Zero2Cool** [comment]
Where are you seeing a performance benefit from 4.0 to 4.5? I haven't noticed nor read anything conclusive that supports that. I'm hoping you have a source for that because it'll help me push my boss into moving our servers to 4.5 ;-)

**Comment by marietteknap** [comment]
Tell him I told you... First support ends https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/ and performance https://blogs.msdn.microsoft.com/dotnet/2014/08/07/moving-to-the-net-framework-4-5-2/.

**Comment by marietteknap** [comment]
Ingo, there is one reason in particular I prefer to have YAF for DNN 2.2.3 compiled against .Net 4.5 or higher and that is Websockets in > .Net 4.5. Stuff like SignalR (chat modules) communicate over websockets instead of http and make it much faster and more reliable.

**Comment by w8tcha** [comment]
I will release YAF 2.2.3 with two packages one compiled against 4.0 and the other against 4.5.2. And this will be the last release for .NET 4.0

**Comment by marietteknap** [comment]
Thank you very much!

**Comment by Zero2Cool** [comment]
You know you could do the compile against whichever framework you want, right? Ingo has a great setup for that. Easy as pie, even I can (usually) do it! :D

**Comment by vzrus** [comment]
4.6.1 is the latest. There is a thing for webforms in 4.6. A magic 'async' for pages. Nothing else is of much interest. But even in the case a hosting dba can fall into dispair if it will be massively used in YAF. If someone really can harness some new thingies he can easily compile  source code.
4.0 obviously stops further enhancements.

**Comment by john2014** [comment]
Could you also update all web.config to use the 4.5.2 version (and remove all reference to 4.0). Examples:

1. requestValidationMode=2.0
2. All assemblies version 4.0.0
3. Change HAshAlgorithm from SHA1 to SHA256 (including machine key code). SHA1 is no longer considered secure.
4. You have enabled dynamiccompression by default - this would increase CPU usage a lot on active sites

https://github.com/YAFNET/YAFNET/blob/master/yafsrc/YetAnotherForum.NET/recommended.web.config

**Comment by w8tcha** [comment]
Thanks i applied the changes you suggested

**Comment by john2014** [comment]
Few more suggestions:

1. Could you also update the key from SHA1 to SHA256 in this link: http://yetanotherforum.net/key
2. Since the future is HTML5, can we remove this line: <xhtmlConformance mode="Strict" />
3. In line 144, you can set both "doDynamicCompression" and "dynamicCompressionBeforeCache" as either true or both as false. Currently one is set as true and another as false.
4. Also consider removing the explicit declaration of mime-type from line 146 to 155. Is there a reason that IIS server would not serve those extension with the correct file type? Just curious 😄
