### ISSUE TITLE
Custom UrlRewriter for integration problem

### ISSUE THREAD

**Issue by vzrus** [YAFNET/YAFNET#328]
Source: Config.cs in YAF.Classes.Config 
Entries like these don't work should be like
 return obj != null &&  obj.ToString().ToLower().IndexOf("mojoportal", StringComparison.Ordinal) >= 0;
  everywhere. The same problem is in several properties checks.
IsRainbow, Mojoportal and DNN

**Comment by w8tcha** [comment]
Youz mean the GetType(). is not needed?

**Comment by vzrus** [comment]
Yes, it's obvious. If you are planning to fix it, don't forget to check in Config properties for the entries that Http.Current.Session object is not null. And after it you can check a cookie itself in the object.

**Comment by vzrus** [comment]
Ingo, I fixed it a bit. Now it should be OK.
