### ISSUE TITLE
Web.config is missing

### ISSUE THREAD

**Issue by aliziani** [YAFNET/YAFNET#332]
Hello,

I just pulled the project on master branch, i successfully build the solution whiout error but when i try to run it, it prompts this:
![image](https://cloud.githubusercontent.com/assets/5922212/15151331/f628fe0e-16d0-11e6-99ac-a155518f0dff.png)

![image](https://cloud.githubusercontent.com/assets/5922212/15151417/4d51dac0-16d1-11e6-919d-d5908c06843c.png)

Could you add those files to the project please ? :

Thank you

**Comment by w8tcha** [comment]
You need to rename the recommended.web.config to web.config
