### ISSUE TITLE
2.2.3 - "Quote selected message"

### ISSUE THREAD

**Issue by mrdance** [YAFNET/YAFNET#335]
Since 2.2.3. I see several "Quote selected message" text at bottom of page. You can see this here:

http://www.visualcron.com/forum.aspx?g=posts&m=25698#post25698

Test both in firefox and chrome.

**Comment by w8tcha** [comment]
Did you compile yaf yourself? i see that your forum.min.css is missing the css for the selectionshare plugin. What happens when you use the css file from the download package?

**Comment by mrdance** [comment]
No, I didn't compile myself. Where should the css file exactly be stored?

**Comment by Zero2Cool** [comment]
--- //Content/forum.min.css

**Comment by mrdance** [comment]
Thanks, that fixed it. For some reason I both have to put files in /Content instead of installation folder /forum/Content
