### ISSUE TITLE
Would it be possible to set a role/give a medal to a user based on their tenure?

### ISSUE THREAD

**Issue by BlackHawk8100** [YAFNET/YAFNET#346]

**Comment by BlackHawk8100** [comment]
Bump

**Comment by w8tcha** [comment]
Sorry for the very late response, what exactly do you mean with tenure? do you mean roles or medals depending on how long the registered to the forum?

**Comment by Zero2Cool** [comment]
Yes, rather than post count level you level up on role or medal, based on time registered. Maybe the reason is to say congratulations user X on five years.
Just my interpretation of the request

**Comment by w8tcha** [comment]
Yes thats what i understand, but does it really makes sense? For example users registers but never posts and would get medals for do nothing. It would only makes sense if it would based on time on the forum, last visit and posts. but that makes it really complicated

**Comment by Zero2Cool** [comment]
Yeah, I think it would be better to give them out ad hoc as noticed.   As you said, what if the plan is to have members of 1 year have access to a "secret" or whatever category.  They registered, dont' come back for 11 months, their account gets hacked and now someone else has that "secret" access. Sure, it's a far fetched scenario, but I just am not sure the value.

**Comment by w8tcha** [comment]
I close this for now, maybe it can be added in the future. From my point of view it makes more sense to manually award such users with medals.
