### ISSUE TITLE
were can i see the unapproved post ? (moderator role)

### ISSUE THREAD

**Issue by prasadraja07** [YAFNET/YAFNET#349]
Hi,

Thanks for providing such a form system.. really easy to implement..
I got stuck with the **form moderator**

**Scenario:**
I created 2 forum

1) Forum 1 (no need of moderator approval)

**2) Forum 2 (Moderator approval need to publish the post to live)**
i defined the settings, while creating "Forum 2, moderator need to approve".. When user is trying to post a topic under "Forum 2".
**Shown this message.**
![image](https://cloud.githubusercontent.com/assets/2306153/19560872/d28377ca-96de-11e6-9050-2ec245f71342.png)

**When i logged in as moderator i can't see the post to apporve. where can i find the unapproved forum and approve it**

Your reply will be highly appreciated

![image](https://cloud.githubusercontent.com/assets/2306153/19560702/1d14a940-96de-11e6-9ac1-b8047eb41377.png)

**Comment by prasadraja07** [comment]
i can see moderate button, when i logged in as "moderator/admin.".  after selecting, its not showing anything...

is the i am doing any thing wrong ?

**Comment by JP58** [comment]
Strange, users with admin/moderator access should see if there are posts that need approval, reported posts and such in the "Moderate" menu...  ???

**Comment by prasadraja07** [comment]
"Moderate" menu was available in the menu,

When i was trying to visit the moderate page, it showing empty, can't see the post for approval... **I logged in as admin**

**Comment by JP58** [comment]
When I turned on "moderated forum", all posts to to that forume were moderated and showed in the list. 
However, this was with an earlier version of the YAF forum. Maybe the functionality has changed, or it's a bug... What happens if you check the "Moderate all posts" and set the value to 1?
