### ISSUE TITLE
Location by IP

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#351]
Instead of the Location field, maybe we could have a location by IP that way no one is lying. Unless they spoof it of course.  Location of user per each post.

**Comment by JP58** [comment]
But...  I thought the location was determined by IP at registration already.
Unfortunately you can edit it in your profile and remove the info. 
Should be "read only" in my opinion, but others may have another opinion.

See my issue #293 regarding IP lookup also for registration via FB accounts and such ...

What would be really cool would be to have IP location lookup & update whenever you log on, and thus updated in the profile & "userbox" too...  But then we are getting into the area of paid services regarding the number of requests, maybe...

**Comment by w8tcha** [comment]
> Instead of the Location field, maybe we could have a location by IP that way no one is lying. Unless they spoof it of course. Location of user per each post.

No sorry thats not a good idea, there is a reason why the ip address for each post is only shown to admins.  This is similiar to emails and real addresses. The is personal information and should not be displayed to all users.

**Comment by Zero2Cool** [comment]
You're absolutely right. This would have been shown only to admins, or a link to a who is on the IP. I agree though, not a good idea.

**Comment by w8tcha** [comment]
Yes but the ip address is already shown on each message
