### ISSUE TITLE
Posted with what device

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#356]
Any value in displaying the device the post was posted with? I was thinking it'd be cool if you see `he'll` when you think it should be `hell`, but auto correct happened. You could see it was posted by a phone and know it was probably an auto correct thing.

**Comment by JP58** [comment]
Like this idea a lot!
In today's mobile world it makes a lot of sense.

**Comment by w8tcha** [comment]
Is this still a requested feature? i don't really see the value of this!

**Comment by Zero2Cool** [comment]
Agreed, little to no value. Other fish to fry.
