### ISSUE TITLE
Redirect to an external URL opens up in current window, should be new window/tab

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#358]
As you may know, there is a feature where you can redirect a forum to an external site. 
Unfortunately,  it opens up in the same window which means you are thrown out from the forum site and may forget to go back. Since some of the clubs who visit my little forum now have their own FB groups I would like to provide an entry point to those FB groups from the forum too without losing them from the forum pages. 

My suggestion is that the URL should open in a new window instead of the current forum window so the visitor is "kept" at the forum site too. URL:s in posts open in a new window and that is the preferred behavior.   

![image](https://cloud.githubusercontent.com/assets/5246746/22562170/bb6f0d84-e97b-11e6-923b-0a2f01e9980a.png)

Is there a way to configure this already?  If so, tell me about it.

**Comment by w8tcha** [comment]
I agree added in 2.2.4
