### ISSUE TITLE
why not change to MVC

### ISSUE THREAD

**Issue by thefristloser** [YAFNET/YAFNET#360]
up

**Comment by Zero2Cool** [comment]
From the Lead Developer. "The problem is we not have the resources. I'm the only developer and i only have little time. Converting YAF to MVC would require a complete rewrite of the fronted. At this point it is impossible,"

**Comment by JP58** [comment]
This is a mammoth task to do, even if YAF is quite "service orientated" in the backend design.
The front end & web service call architecture (Views & Controllers) are quite different compared to web forms.
