### ISSUE TITLE
Facebook/Google account login for existing users... 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#362]
I have recently got the question why you cannot login to the forum with your FB account even if we have the option.  I know that if you do it while registering you can, but users who have registered the traditional can't even if they have their FB account in the profile... 

Using Owin during login, it should be possible to do claims authentication towards FB, Google and other online services. The requirement is of course that you are registered in the forum already as an existing user and have and have eg your FB account registered in your profile. As I understand, the basic mechanism is already there since you can register to the forum using FB & such. 

Just a suggestion to make the forum login process a little bit more "contemporary", so to speak.   :-)

**Comment by w8tcha** [comment]
That is already possible you can connect an existing forum account with google / facebook.
Of course it will only work if the email address for the forum account is the same as the one in facebok /google
