### ISSUE TITLE
Suggestion - I think this is a cool feature to have

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#367]
Would it be possible to have a "thread starter" indication in the "Userbox" as in the attached pic in topics? 

Since it is available while hovering in the Active Topics (after my nagging about it for some time earlier :-D ) it could maybe be used in the topic itself too? 

Not a necessary feature, but rather cool and adds a kind of clarity in a topic discussions...  

![image](https://user-images.githubusercontent.com/5246746/29429333-a0ff36e0-8390-11e7-80ab-68d5fd77e69a.png)

**Comment by Zero2Cool** [comment]
#137

:-)

**Comment by JP58** [comment]
I personally think it would help to keep topics in line with the subject, when the original starter is marked, since topics (at least in my forum) where discussions can digress a bit from the original issue/question on page 2 or so since noone remembers who started the topic and why...  ;-)

**Comment by w8tcha** [comment]
Implemented as "topic starter" badge next to the user name in YAF 2.3.0
