### ISSUE TITLE
Advanced URL Formatting in DNN

### ISSUE THREAD

**Issue by esmasina** [YAFNET/YAFNET#368]
We have recently upgraded our DNN environment from 8.4 to 9.1.1, and have changed our DNNFriendlyUrl setting from humanfriendly to advanced URL format. We have noticed that the Intelligencia URLRewriter (from our YAF 1.9.6.1 installation) is conflicting with this new advanced URL format, and a number of DNN functionality is not working. In an effort to resolve these errors, we removed Intelligencia from our site, but this breaks some of YAF's functionality and we can no longer post replies or new topics. Is there a fix for advanced URL formatting in a newer version of YAF?

**Comment by w8tcha** [comment]
The latest version uses the friendly url provider to generate the urls, and there are no problems

**Comment by esmasina** [comment]
One of the issues we noticed is a conflict between Intelligencia and the DNN advanced URL Rewriting process. When we turned on DNN's advanced URL Rewriting, we noticed that when we go to sites in our environment, we get an 'Object moved to here.' message. DNN indicated this was caused by the out-of-box 301 redirects not occurring for extensionless URL's. We have confirmed that removing Intelligencia fixes this issue, but of course breaks YAF. Can you confirm that you have seen this 'Object moved' issue before and that it's a specific issue that you've addressed with support for advanced DNN Url Formatting? This is an important question for us because we need to upgrade our YAF installation to address this issue, which will take a bit of time for us. We just need to verify that it will definitively fix the error that we are encountering.

**Comment by w8tcha** [comment]
Well the Intelligencia url rewriter is not used anymore in yaf dnn module. That was one of the reasons we use the friendly url provider api. And also to make all urls in the dnn installation look the same.
