### ISSUE TITLE
Login form does not work in IE when YAF.EnableURLRewriting config parameter is set to false

### ISSUE THREAD

**Issue by MadBender** [YAFNET/YAFNET#371]
Bug appears in all versions of IE, but not in Edge.
Steps to reproduce:
1. Set `YAF.EnableURLRewriting` to `false` in `app.config` (IIRC it is `false` by default)
1. Go to login form
1. Input name and password
1. Click login button
1. Login does not happen, login form appears again with empty fields

The reason is that HTML form (`form1`) that contains page content is rendered with empty action attribute. IE treats the empty action incorrectly and posts the form to root URL (/), while other browsers post to `/default.aspx?g=login&ReturnUrl=%2f `

Also, this may cause problems on other pages, but I didn't verify this.

**Comment by w8tcha** [comment]
Atleast with IE 11 i no can reproduce this issue

**Comment by MadBender** [comment]
Login page, reproduced on all 3 client machines and 2 installations of forum - 2.2.4.3 in production and and latest from Github on localhost 
![image](https://user-images.githubusercontent.com/4372982/31004742-56b1e698-a4fe-11e7-9e46-92a1640ebc0a.png)

If I change form's action in dev tools to default.aspx?g=login, then it works

**Comment by willhowells** [comment]
We have experienced this problem too and also on Firefox (I'm going to turn URL rewriting on as a workaround.)

**Comment by w8tcha** [comment]
Ah sorry. if the urlrewriter is enabled then in that case you need to change the form tag in the default.aspx...

change from
`<url:Form id="form1" runat="server" enctype="multipart/form-data">`

to 
`<form id="form1" runat="server" enctype="multipart/form-data">`

and

from..
`</url:Form>`
to...
`</form>`

**Comment by w8tcha** [comment]
by the way why did you guys disable the url rewriting, are there any problems?

**Comment by MadBender** [comment]
>by the way why did you guys disable the url rewriting, are there any problems?

Don't remember exactly, it is old installation made in 2014 that I'm updating now. May be it was disabled by default.

>Ah sorry. if the urlrewriter is enabled then in that case you need to change the form tag in the default.aspx...

I did not change anythig and it works

**Comment by willhowells** [comment]
Ditto - I think it was an old default that's carried through.
