### ISSUE TITLE
Forum URL malformed at v2.2.4.3-5805

### ISSUE THREAD

**Issue by marietteknap** [YAFNET/YAFNET#372]
In https://github.com/YAFNET/YAFNET-DNN/releases/tag/v2.2.4.3-5805 the header links to the default URL for the forum ads 'Forum' to the URL causing a 404.

![30-09-2017-15 44 47 00](https://user-images.githubusercontent.com/5551768/31046292-6269fbee-a5f6-11e7-96af-f4d054a728cb.png)

**Comment by w8tcha** [comment]
which dnn version?

**Comment by marietteknap** [comment]
DNN version is 8.0.4 and tab name is 'forum'. Name of the board is 'Windows Server Essentials'

**Comment by w8tcha** [comment]
https://github.com/YAFNET/YAFNET-DNN/releases/tag/v2.2.4.3-5806 is online this should address the issue and possible also the avatar problem

**Comment by marietteknap** [comment]
The URL issue is fixed with this release but the Avatar issue not.
