### ISSUE TITLE
Line breaks in messages give an extra empty line... 2.2.4.3 latest build

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#374]
I think this speaks for itself...

Editing message:
![image](https://user-images.githubusercontent.com/5246746/31145796-0e34155a-a885-11e7-8a14-b11b03532ea6.png)

Message preview:
![image](https://user-images.githubusercontent.com/5246746/31189631-19f2aa8c-a939-11e7-83a5-28df02ed82c1.png)

Message as seen posted in the forum:
![image](https://user-images.githubusercontent.com/5246746/31145958-723096be-a885-11e7-9cae-cb4ff2cd3489.png)

It could maybe have something to do with the bbcode/HTML rendering stuff you have worked on lately...

**Comment by w8tcha** [comment]
issue is resolved in 2.2.4.4
