### ISSUE TITLE
Suggestion - make it visible when there is moderator action needed for posts, in the top menu 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#375]
As an admin/moderator, I have for a long time wished for some form of indication on the forum page "Moderate" menu item so you quickly can see if there are any pending post reports.
Like a "bubble" with the number of posts pending or just make the menu item blinking or such. 

This would really help moderators to quickly respond to reports/requests/items needing attention. 

![image](https://user-images.githubusercontent.com/5246746/31192036-51b76e6a-a940-11e7-931e-102822dc302e.png)

**Comment by w8tcha** [comment]
<img width="105" alt="moderate" src="https://user-images.githubusercontent.com/722575/32144121-2e239758-bcb4-11e7-86f2-c0b4884abad2.PNG">

i agree good idea will be added in YAF 2.3.0
