### ISSUE TITLE
Sitecore 8.2 integration of YAF

### ISSUE THREAD

**Issue by abhilashca** [YAFNET/YAFNET#376]
Hello,

I would like to know whether YAFNET can be integrated with Sitecore v8.2. I saw [YAF Integration](https://marketplace.sitecore.net/Modules/Y/YAF_integration.aspx?sc_lang=en) and [Sitecore YAF](https://marketplace.sitecore.net/en/Modules/Sitecore_YAF.aspx) in [Sitecore Marketplace](https://marketplace.sitecore.net/SearchResults#qr=YAF). YAF modules in Sitecore marketplace are last revised in 2015 and is 2 years old.

Is the project **compatible with Sitecore 8.2**?

Any help will be appreciated.
Thank you.

**Comment by w8tcha** [comment]
I don't have any experience with Sitecore. but in the support forums the users report that the module in the sitecore marketplace doesn't work with Sitecore 8

there is a project here...
https://github.com/brooksyd2/sitecoreyaf8

But i don't know if it works or not
