### ISSUE TITLE
Delete IP address in Spam Admin Banned IP fails  v 2.2.4.4

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#377]
The spam filter has been reworked to count URL:s in posts...  
Unfortunately this was set to 1, it seems...  So a new user got automaticallly banned by the system for posting 2 image links... 

When I try to delete the banned IP - it fails and throws:  

![image](https://user-images.githubusercontent.com/5246746/31576129-305c2082-b0f5-11e7-806a-c55e53274cfd.png)

**Comment by JP58** [comment]
I suppose there is a modification in the language.xml file that I have missed somehow, since I have a host admin field without description which I presume is the #of URL:s allowed to post before banned... 
It was set to 1, but I changed it to 50 so new users would not be banned immediately.... 

As you can see, I use a rather agressive spam check policy... 

![image](https://user-images.githubusercontent.com/5246746/31630474-fa192470-b2b6-11e7-8f69-8e4d48b24360.png)

**Comment by w8tcha** [comment]
> The spam filter has been reworked to count URL:s in posts...
Unfortunately this was set to 1, it seems... So a new user got automaticallly banned by the system for posting 2 image links...

I will increase the default allowed number to 10. The default setting 2 was used in the YAF Support forum by most of the spammers.

> I suppose there is a modification in the language.xml file that I have missed somehow, since I have a host admin field without description which I presume is the #of URL:s allowed to post before banned...
It was set to 1, but I changed it to 50 so new users would not be banned immediately....

Are you using a different language file then english.xml? the description is included in the language files

` <Resource tag="SPAMCHECK_ALLOWED_URLS">Allowed Number of URLs before flagged as SPAM:</Resource>
  <Resource tag="SPAMCHECK_ALLOWED_URLS_HELP">If the user posts in one Message more then the allowed URLs the message is flagged as spam. This Check also depends how many user the posts have.</Resource>`
