### ISSUE TITLE
Avatar upload issues - 2.2.4.4 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#378]
It seems like the yaf_User table "Avatar" field isn't updated with a link to an uploaded avatar that is uploaded with the "Choose file" option.  This gives the "noavatar.gif" of course, since the db value is NULL in that field.

These examples should clarify it a bit: 

My own record in the yaf_User table
![screenshot1](https://user-images.githubusercontent.com/5246746/31732881-45462e82-b43a-11e7-90eb-51c03d3464e2.jpg)

A user (10965) who just uploaded a new avatar
![screenshot2](https://user-images.githubusercontent.com/5246746/31732955-76801f26-b43a-11e7-93fa-781d876f47dd.JPG)

The file is uploaded, exists, and is well within restrictions
![fileisthere](https://user-images.githubusercontent.com/5246746/31733004-93c6afbe-b43a-11e7-9b06-851523ddca0e.JPG)

But since the yaf_user "Avatar" field is NULL in yaf_User, the noavatar.gif is shown
![before](https://user-images.githubusercontent.com/5246746/31733083-d7411018-b43a-11e7-9dd8-e482076096f5.JPG)

After I manually edit the database field for user 10965, it shows ok both in profile & forum
![after](https://user-images.githubusercontent.com/5246746/31733108-f60d51e6-b43a-11e7-890d-8326706b65b3.JPG)

Just for reference - my own avatar in the profile, uploaded exactly the same way quite a while ago... 
![myown](https://user-images.githubusercontent.com/5246746/31733172-2375ba88-b43b-11e7-8d94-e194cc3cc6be.JPG)

So I think there is a kind of new malfunction in this routine, since it does not seem to work as it did earlier. 

Hope this is enough info to find the "missing link"...  :-)

**Comment by w8tcha** [comment]
At this point i no can reproduce the issue, not even in your forum. I select an image for upload click on "Update" and the image is uploaded and selected as avatar url

**Comment by JP58** [comment]
Isn't the "Upload Avatar from Your Computer" supposed to fill the "AvatarImage" with an image "blob" and the "AvatarImageType" with the mime type? 

It used to work like that with this option...  

![image](https://user-images.githubusercontent.com/5246746/32066323-aaf84f62-ba7f-11e7-8914-f4408b8e6ec0.png)

**Comment by w8tcha** [comment]
> Isn't the "Upload Avatar from Your Computer" supposed to fill the "AvatarImage" with an image "blob" and the "AvatarImageType" with the mime type?

Only if the setting *Use File Table* is enabled in the host settings

**Comment by w8tcha** [comment]
> And, I can't upload a new avatar at all, image within sizes - get a "not a proper image file" or such in the message field at the top of the page...

can you attach the image file you try to upload so i can try to reproduce the issue?

**Comment by JP58** [comment]
What are the implications/scenarios of the "Use File Table"? 
Does it mean that also post attachments are stored in DB ?  (Don't want that...)  

Test image attached...

![testimg](https://user-images.githubusercontent.com/5246746/32120334-724714ee-bb58-11e7-9ba7-7ef9b12f6b3a.jpg)

**Comment by w8tcha** [comment]
> What are the implications/scenarios of the "Use File Table"?
Does it mean that also post attachments are stored in DB ? (Don't want that...)

Yes attachments, avatars and albums are saved as blob in the file table inside the db

**Comment by w8tcha** [comment]
> And, I can't upload a new avatar at all, image within sizes - get a "not a proper image file" or such in the message field at the top of the page...

That info message only occurs when there is an error during the saving of the avatar, strangely i was to upload the image as avatar on your forum. the only thing i can do is i added logging of the error message to the event log so we can see the real error

**Comment by w8tcha** [comment]
Is that issue still occurring?
