### ISSUE TITLE
DB User Read Tracking without Session tracking

### ISSUE THREAD

**Issue by w8tcha** [YAFNET/YAFNET#380]
The feature of User Read Tracking isn't working between different devices. For example if I look at a newly created post on my phone on my way to my work and read the newest message, I will still get the same message when I get back to work, my computer flagging it as new.

I've tried to press the mark everything as read button every time I've read all the messages and it has improved slightly but the problem still persists.

In our setup we've activated "User Read Tracking" but it doesn't seem to work as I would have thought. Is it something I'm missing or is this feature not working perfectly, what issues are known about this feature?

I can see that I have rows getting inserted/deleted into the database when I post/read threads but it still doesnt' sync between devices. I can have my computer aside my phone and they show different results. Is this working for you?

**Comment by JP58** [comment]
Interesting, works fine for me... 
Just signed in to my forum with my Android "Pokemon Go" phone for the first time ever, and read tracking seemed to work just fine...   ??? 

However, earlier there have been issues with multi-page topics that have been fixed...

**Comment by w8tcha** [comment]
It should work finally the way as i first implemented it.
