### ISSUE TITLE
Rather urgent suggestion - Please add confirmation dialog for "Delete Topic"  

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#383]
When we delete a message, we get a dialog where we can check "erase from database" or give a reason etc... 

When you press  "Delete Topic" - it's irreversible...  The topic and all its messages are deleted from the db on the spot... This is not so good when you have several mods/admins... 

Had a moderator/admin doing that a day ago in our moderator area while trying to delete a message...  All our references to user behaviour patterns were wiped out without mercy... 

He managed to press "Delete Topic" instead of delete message 1 on page 48 or such while trying to moderate on a mobile phone...    

In the yaf_topic table there is a field "IsDeleted", but obviously it is not used for anything...  So obviously it works quite differently from "Delete Message"...  You would expect "common" deletion behavior for forum content, wouldn't you? 

Please, at least try to implement a confirmation dialog that says "Are you sure you wish to delete this topic and all the messages in it!" with big red warning signs...

**Comment by Zero2Cool** [comment]
I clicked Delete Topic and I got an alert asking me if I wanted to "Delete this topic?".   When I confirmed it, the topic and messages were deleted from the database. 

Maybe change all deleting to soft delete and use an admin purge feature that shows the content you're going to delete with the option to restore?

**Comment by JP58** [comment]
Never got an alert - it just went on deleting...  :-/

**Comment by w8tcha** [comment]
There is definitely an confirm dialog before you delete a topic! i also checked in your forum
