### ISSUE TITLE
Attempt by security transparent method 'Intelligencia.UrlRewriter' failed.

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#384]
As we inch closer to Bootstrap 4, I thought I would try to give my website an update using the latest current commit. After I got everything ready to go, I am getting this error message and can't find where to fix it, even though it seems to be telling me exactly what the issue is. (yes, I feel stupid right now)

Any guidance would be appreciated. Thank you.

------
Attempt by security transparent method 'Intelligencia.UrlRewriter.RewriterHttpModule.System.Web.IHttpModule.Init(System.Web.HttpApplication)' to access security critical method 'YAF.Classes.Config.get_EnableURLRewriting()' failed.

Assembly 'Intelligencia.UrlRewriter, Version=2.1.0.2, Culture=neutral, PublicKeyToken=0573f3650687980d' is marked with the AllowPartiallyTrustedCallersAttribute, and uses the level 2 security transparency model.  Level 2 transparency causes all methods in AllowPartiallyTrustedCallers assemblies to become security transparent by default, which may be the cause of this exception.

![image](https://user-images.githubusercontent.com/5612416/34727695-55677a0e-f51d-11e7-9a19-c05052405f20.png)

**Comment by Zero2Cool** [comment]
Adding the line below into my AssemblyInfo.cs appears to have resolved this issue.



     [assembly: SecurityRules(SecurityRuleSet.Level2, SkipVerificationInFullTrust = true)]

**Comment by Zero2Cool** [comment]
I decided to try stand alone YAF on my test site, http://www.packerpeople.com/ and I'm getting the same error.

**Comment by w8tcha** [comment]
Should work now i didn't commit the updated assembly file before
