### ISSUE TITLE
Stored XSS via file upload

### ISSUE THREAD

**Issue by qweqweqweTRTRT** [YAFNET/YAFNET#387]
Hi. During one of our inside security testing I found stored XSS in our forum that is based on yaf.
If you upload allowed file format (.png, .jpg, .gif) to ur album and specify Content-Type of it as text/html and then place html page in body, it will return html page when asking for a uploaded resource directly - like this one http://www.yetanotherforum.net/forum/resource.ashx?image=185 - must be logged in to see. The request looks like attached pic (I cleared it from useless data like eventvalidation and cookies). I didnt find any tips for reporting security vulns, so placing it here on github. Also works with other MIME-types, image/svg+xml, text/xml and so on. 
![yafxss](https://user-images.githubusercontent.com/35286088/35900291-028030b4-0bf3-11e8-87c6-a9562ed2bd78.jpg)

**Comment by qweqweqweTRTRT** [comment]
could we issue a CVE?

**Comment by w8tcha** [comment]
What is a CVE? the Issue is fixed in the latest release!
