### ISSUE TITLE
Moving a message from one topic to another locks up the forum

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#388]
Had to split a topic into a new topic tonight,  topic was created and messages incl replies were moved quite swiftly.  Then I had to move messages from another topic into the newly created topic and I noticed that the message by message move is very slow and locks up the forum while doing it. 

I & my moderator team have actually noticed this earlier too, but since I had to move about 30 msgs this time it took about 1,5 hrs to complete them one by one... And forum was inaccessible while the moves executed... 

Could of course be an SQL Server issue too so you have to avoid an SQL query read lock on the whole message or topic table while the request is executed...  We actually have a similar issue with our help desk application at work and the company who makes it are just as puzzled about it as I am...  

Ideas are welcome and if it's in the forum software - a solution would be appreciated.

**Comment by Zero2Cool** [comment]
The stored proc that handles the splitting of posts -- do you know if it is done transactionally or if its just a NOLOCK stored proc?

**Comment by w8tcha** [comment]
The problem is that a moving a message or topic is a huge task, i'm not sure if a nolock would help. I guess the only option would be to set the forum off-line while the task is executed.

**Comment by JP58** [comment]
Could it be an indexing issue? - ie the move message routine does a lot of read table scans while performing the move, which needs table locks for consistency? 

There is a setting in SQL Server that circumvents the issue of locking a whole table during a read, using tempdb instead and leaving the table unlocked, but I'm not sure how it affects row consistency. On the other hand - an "old" message is most likely not to be in a middle of an active change transaction...

**Comment by JP58** [comment]
Actually, I can't also really see that moving a moving a message to another existing topic is a huge task...
As I see it it's just about changing the topic ID for the message, which I have done successfully via direct db edits sometimes when a bulk of sequential messages have had to be moved. I may have a very simplistic view about it though, since I haven't studied the code...  :-)
