### ISSUE TITLE
Can't access resource - installed in subdirectory

### ISSUE THREAD

**Issue by SpaghettiEnforcer** [YAFNET/YAFNET#389]
`[ArgumentException: Requested value 'admin_attachments' was not found.]
   System.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument) +3906279
   System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult) +12978625
   System.Enum.Parse(Type enumType, String value, Boolean ignoreCase) +78
   YAF.Types.Extensions.EnumExtensions.ToEnum(String value) +55
   YAF.Controls.AdminMenu.BuildUrlList(IEnumerable1 listItems) +317
   YAF.Controls.AdminMenu.RenderAccordian(HtmlTextWriter writer) +700
   YAF.Controls.AdminMenu.Render(HtmlTextWriter writer) +227
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +66
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter) +100
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer) +25
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +128
   System.Web.UI.Control.RenderChildren(HtmlTextWriter writer) +13
   YAF.Core.ForumPage.Render(HtmlTextWriter writer) +20
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +66
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter) +100
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer) +25
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +128
   System.Web.UI.Control.RenderChildren(HtmlTextWriter writer) +13
   YAF.Forum.Render(HtmlTextWriter writer) +236
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +66
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter) +100
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer) +25
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +128
   System.Web.UI.HtmlControls.HtmlForm.RenderChildren(HtmlTextWriter writer) +9857008
   System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) +32
   System.Web.UI.HtmlControls.HtmlForm.Render(HtmlTextWriter output) +53
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +66
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter) +100
   System.Web.UI.HtmlControls.HtmlForm.RenderControl(HtmlTextWriter writer) +40
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +128
   System.Web.UI.Control.RenderChildren(HtmlTextWriter writer) +13
   System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer) +32
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +66
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter) +100
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer) +25
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +128
   System.Web.UI.Control.RenderChildren(HtmlTextWriter writer) +13
   System.Web.UI.Page.Render(HtmlTextWriter writer) +29
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +66
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer, ControlAdapter adapter) +100
   System.Web.UI.Control.RenderControl(HtmlTextWriter writer) +25
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1303
`

I'm getting this error when accessing the admin index or host settings pages. Everything else works fine and I can access every other page without an issue. Any clues as to why this resource is inaccessible while I'm seemingly able to access all the others? Maybe it has something to do with the <page /> definition for 'admin_attachments' is only in the languages/admin/english.xml file? I can get the resources from inside the languages/help/english.xml so I don't see why that would be the case,

Thanks in advance for any help!

**Comment by w8tcha** [comment]
Which version did you use?

**Comment by SpaghettiEnforcer** [comment]
I'm using the latest version as of right now. v2.2.4.9

**Comment by w8tcha** [comment]
Okay i see the problem you are using the source package right? I forgot to update the that package. I re-uploaded the source zip file

**Comment by SpaghettiEnforcer** [comment]
Worked like a charm. You're the man, thanks for the help!
