### ISSUE TITLE
Install bug

### ISSUE THREAD

**Issue by EvgGen** [YAFNET/YAFNET#391]
Last source 2.2.4.9. Start error http://prntscr.com/j6s3ur
Commented a line... Then I started the installation 
http://prntscr.com/j6s4us
http://prntscr.com/j6s5d4
http://prntscr.com/j6s5pk
http://prntscr.com/j6s5xr
http://prntscr.com/j6s63e
http://prntscr.com/j6s6b5
Ignored all exceptions - continued installation http://prntscr.com/j6s749
Then I got another error http://prntscr.com/j6s7x0  http://prntscr.com/j6s8eu

**Comment by w8tcha** [comment]
Did you accidently compiled the master branch of the github repository? That is version 2.3.0 BETA not 2.2.4.9

For the 2.2.4.9 download the source package https://github.com/YAFNET/YAFNET/releases/download/v2.2.4.9/YAF-v2.2.4.9-Source.zip

**Comment by EvgGen** [comment]
Yes it works. When I tried to enter the admin, the center received an error:
**System.InvalidCastException: "Unable to cast object of type 'YAF.Classes.YafBoardSettings' to type 'YAF.Core.YafLoadBoardSettings'."

System.ArgumentException: "Requested value 'admin_attachments' was not found."**

After a little glance, he added:
russian.xml
