### ISSUE TITLE
Security Qestions

### ISSUE THREAD

**Issue by maxdm** [YAFNET/YAFNET#392]
Forum has a very strange option: a security question at the register user page.
It works very bad and I don't know any successful user password resets.
And there is no option to change the security question\answer in the user profile.
Can you make this questions optional?
Or completely disable it?

**Comment by w8tcha** [comment]
You can disable it in the web.config via the membership connection string requiresQuestionAndAnswer="false"

**Comment by maxdm** [comment]
That's great, thank you!

**Comment by w8tcha** [comment]
i can not test this right now but in that case you need to disable password resets enablePasswordReset="false"

**Comment by maxdm** [comment]
In this case I receive:

```
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.


[HttpException (0x80004005): Membership provider does not support password retrieval or reset.]
   System.Web.UI.WebControls.PasswordRecovery.AttemptSendPasswordUserNameView() +719
   System.Web.UI.WebControls.PasswordRecovery.OnBubbleEvent(Object source, EventArgs e) +96
   System.Web.UI.Control.RaiseBubbleEvent(Object source, EventArgs args) +84
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3804
```

**Comment by w8tcha** [comment]
Sorry for the late reply but this issue needed some investigation. Turns out the solution with the Security Question and Answer is the only way to reset the password. This is how the ASP.NET Membership system works.

For the Release 2.2.4.11 it is now possible to change the Security Question and Answer via the Change Password page.
