### ISSUE TITLE
Timezones breaks with update.

### ISSUE THREAD

**Issue by maxdm** [YAFNET/YAFNET#394]
I see in users table **180**
But in profile: - **UTC-12**
And so for all users!
And when I change timezone, it writes to db (**Russian Standard Time**), but in profile interface I see **UTC-12**

And My topics since last visit shows empty list.

**Comment by w8tcha** [comment]
Which version?

**Comment by maxdm** [comment]
Last release:
2.2.4.9 (: 29.03.2018).
https://www.cryptopro.ru/forum2/

**Comment by w8tcha** [comment]
Okay found the issue the data from the db was not populated in the dropdown. Fixed in 2.2.4.10
