### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by EvgGen** [YAFNET/YAFNET#396]
New PM message. Search current users... http://prntscr.com/jdw4nb

**Comment by w8tcha** [comment]
Which version?

**Comment by EvgGen** [comment]
Good evening. 2.2.4.9

**Comment by w8tcha** [comment]
Atleast with the latest version 2.2.4.10 i can not reproduce the issue. You compile the source version right? Did you recompile the YAF.Types project?

**Comment by EvgGen** [comment]
Hello. Yes, I recompiled YAF.Types. Just assembled 2.2.4.10 on a clean database. The problem persists ... Existing users can not be found. If the user is not in the database, the forum notifies us about this. MSSQL http://prntscr.com/jfo29y

**Comment by w8tcha** [comment]
okay i found the problem. that file was not updated in the zip package

FIxed now 

https://github.com/YAFNET/YAFNET/releases/download/v2.2.4.10/YAF-v2.2.4.10-Source.zip

**Comment by EvgGen** [comment]
Please specify the files. There is no way to transfer a large amount of code to a new version of the forum.

**Comment by w8tcha** [comment]
You only need to recompile and send the new dlls to S the Server.

**Comment by EvgGen** [comment]
S Server?

**Comment by w8tcha** [comment]
sorry that was just a typo. I mean copy the dlls to the server.

**Comment by EvgGen** [comment]
Hmm. So the problem is that I'm working locally? Thanks for the advice!

**Comment by w8tcha** [comment]
But it's the same process copy the files to the bin folder where you run the forum

**Comment by w8tcha** [comment]
You can see the changes here...

https://github.com/YAFNET/YAFNET/commit/da1a916213d5749df9fdb4f4292f6e66b79150d6

Current Release is now in the stable branch
