### ISSUE TITLE
Validation (question)

### ISSUE THREAD

**Issue by EvgGen** [YAFNET/YAFNET#397]
Hello. Why not make a validation system when registering for prohibited characters? Or Cyrillic. For example, to check for logins and passwords.

**Comment by w8tcha** [comment]
Why? for passwords there are no validation for characters need all chars are allowed. And for usernames exist validation

**Comment by EvgGen** [comment]
For usernames, or for logins, is there a validation? There was a need to ban characters and Cyrillic characters in logins and passwords. And the forum settings unfortunately do not have such options.

**Comment by w8tcha** [comment]
No for passwords not. But technicaly it's not needed you can use all chars for passwords. And also for usernames. The bad word replace for example can be applied for usernames

**Comment by EvgGen** [comment]
The fact is that with the help of the stored procedure yaf_prov_creatiser I am bringing a pair of login / password to an additional table (for other needs). And there I can not use symbols and Cyrillic. The most simple variant which I see is to prohibit in the validator ... Where is it by the way?

**Comment by w8tcha** [comment]
The validator for user names is on the register page...

https://github.com/YAFNET/YAFNET/blob/07e1377af7a9b4f391e546a16e9151a59331f7bf/yafsrc/YetAnotherForum.NET/pages/register.ascx.cs#L317
