### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by Miclebrick** [YAFNET/YAFNET#398]
It would be nice if this forum software supported .NET Core

**Comment by Zero2Cool** [comment]
How would that benefit the software? How would that be implemented?   I'm asking because I'm working with ASP.NET Core on a project in the near future.

**Comment by Miclebrick** [comment]
It's benefit it by being able to be used by ASP.NET Core sites, and I'm not entirely sure on the porting process, but there's an article about it here: https://docs.microsoft.com/en-us/dotnet/core/porting/

**Comment by w8tcha** [comment]
At this point a conversation to .NET core is not planned. Without more developers a complete rewrite of the complete forum is impossible. 

Windows Forms are not supported by .NET Core and this prevent a quick and easy porting.

**Comment by Mogikan** [comment]
Windows Forms is now supported. Does it change something?

**Comment by w8tcha** [comment]
> Windows Forms is now supported. Does it change something? Seems like a misprint. You must be talking about web forms.

Yes of course i was talking about web forms and not win forms. I edited my post above

**Comment by Zero2Cool** [comment]
Aside from using a framework that is not end of life, what benefits are there for porting to Core?

**Comment by Mogikan** [comment]
C# 8 is not supported in .net4.7. Do you have .net2 installed on your pc? In the long run noone will use obsolete platform.

**Comment by Mogikan** [comment]
@Zero2Cool .net core can run on linux

**Comment by Zero2Cool** [comment]
> @Zero2Cool C# 8 is not supported in .net4.7. Do you have .net2 installed on your pc? In the long run noone will use obsolete platform. Ide will stop support and you will have to install old ide to run obsolete technology. Silverlight is a good example of such technology.

I've developed applications with Core already, but not sure what benefits there are from porting a Web Forms solution from .NET Framework to .NET Core aside from what I mentioned (framework being end of life, obsolete) and you later re-told me.  More specifically, I should have asked, do we get any performance gains from a ported Web Forms into Core or would it be better to re-write it from ground up in Core and leverage the improvements?

**Comment by Mogikan** [comment]
There is also Blazor which should be as well considered as an alternative to MVC.

**Comment by Mogikan** [comment]
@Zero2Cool As for performance it is indeed much faster:
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/
https://twitter.com/ben_a_adams/status/1314401170652377088/photo/1

**Comment by Zero2Cool** [comment]
> @Zero2Cool As for performance it is indeed much faster:
> https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/
> https://twitter.com/ben_a_adams/status/1314401170652377088/photo/1

I'm aware that Core has better performance. My question was, is a ported Web Forms application to Core benefit from those performances? I would assume so, however, the conference I had watched awhile back regarding porting they weren't confident. And the suggestion was not to port, and to build the application from ground up in Core.  This conference was at least a year, maybe two years ago, so that is why I'm asking. Maybe porting is better now?

**Comment by w8tcha** [comment]
I think there are some wrong statements here. First of all .NET Framework is not obsolete soon, it will be support and will receive security Fixes until 2031. So it Will be obsolete in 10 Years. 

This would be a large time frame to port old projects. But generally as for large web forms projects at this point converting is not an option, and also not recommend by microsoft.

> C# 8 is not supported in .net4.7

That's not true, You can use c#9 in .net 4.8 it already works fine in YAF 3.0.

>As for performance it is indeed much faster:
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/
https://twitter.com/ben_a_adams/status/1314401170652377088/photo/1

That comparison is between .net core and .net 5 you can't compare the speed of webforms project with an .net core project.

That said, i build a prototype to see if YAF can run as a core project. It is indeed Possible. The biggest works would be converting each page

So i started building a new YAF NET 5 and with razor pages.  It will take some time, but the current situation that i have to migrate my websites away from a Windows Server and also away from the MS SQL Server, forcing me to do this.

So yes there will be an .NET (Core) Version. Maybe when .NET 6 is out by the end of the Year there will be a first alpha version.

**Comment by Zero2Cool** [comment]
> I think there are some wrong statements here. First of all .NET Framework is not obsolete soon, it will be support and will receive security Fixes until 2031. So it Will be obsolete in 10 Years.

Nah, it's already obsolete. 😁 There's something newer out and it won't be receiving any updates other than security patches. To me, that's obsolete. I think some feel obsolete means it won't work anymore and that's not accurate. Heck, you could still run Windows XP if you wanted!   The applications I work with for my employer are 4.5 🤨https://dotnet.microsoft.com/download/dotnet-framework 


> So i started building a new YAF NET 5 and with razor pages. It will take some time, but the current situation that i have to migrate my websites away from a Windows Server and also away from the MS SQL Server, forcing me to do this.
Why do you have to migrate your websites away from Windows Server and from MS SQL Server and what does that mean for YAF?

**Comment by w8tcha** [comment]
> Why do you have to migrate your websites away from Windows Server and from MS SQL Server and what does that mean for YAF?

The windows server is too expensive for me and to insecure. Linux is the better option.

Of course yaf would still work on an ms server.

**Comment by dotnba** [comment]
> I think there are some wrong statements here. First of all .NET Framework is not obsolete soon, it will be support and will receive security Fixes until 2031. So it Will be obsolete in 10 Years.
> 
> This would be a large time frame to port old projects. But generally as for large web forms projects at this point converting is not an option, and also not recommend by microsoft.
> 
> > C# 8 is not supported in .net4.7
> 
> That's not true, You can use c#9 in .net 4.8 it already works fine in YAF 3.0.
> 
> > As for performance it is indeed much faster:
> > https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-5/
> > https://twitter.com/ben_a_adams/status/1314401170652377088/photo/1
> 
> That comparison is between .net core and .net 5 you can't compare the speed of webforms project with an .net core project.
> 
> That said, i build a prototype to see if YAF can run as a core project. It is indeed Possible. The biggest works would be converting each page
> 
> So i started building a new YAF NET 5 and with razor pages. It will take some time, but the current situation that i have to migrate my websites away from a Windows Server and also away from the MS SQL Server, forcing me to do this.
> 
> So yes there will be an .NET (Core) Version. Maybe when .NET 6 is out by the end of the Year there will be a first alpha version.

It's so cool ! I am looking forward to it.Thank u a lot !

**Comment by stallone0109** [comment]
I recently read a help document, and the method in it is also very good.https://support.servbay.com/dotnet/how-to-develop-asp-net-framework-4-x-on-macos
