### ISSUE TITLE
BBCode [CODE]...[/CODE] is broking after upgrade from 2.2.4.4 to 2.2.4.12

### ISSUE THREAD

**Issue by Patagames** [YAFNET/YAFNET#400]
Hi,

on a version 2.2.4.12 the code shown like following
![image](https://user-images.githubusercontent.com/12828157/42406587-079ece68-81ee-11e8-9d42-9be4d0b0dae1.png)

**Comment by Patagames** [comment]
[code=cs]
using Patagames.Pdf;
using Patagames.Pdf.Enums;
using Patagames.Pdf.Net;
using Patagames.Pdf.Net.BasicTypes;

namespace RemoveLinks
{
    class Program
    {
        static void Main(string[] args)
        {
            //Initialize engine
            PdfCommon.Initialize();
                        
            //Load the document 
            using (var doc = PdfDocument.Load(@"d:\test.pdf"))
            {
                //Get a cross-reference table and a list of indirect objects in the document 
                var cross = PdfCrossReferenceTable.FromPdfDocument(doc); 
                var list = PdfIndirectList.FromPdfDocument(doc);
                //Receive a list of objects that have at least one reference in the document
                var refObjects = PdfRefObjectsCollection.FromPdfDocument(doc);
                //Enumerate objects in the list and check if there is an object with a given number in the list of objects referenced in the document
                foreach(var obj in cross)
                {
                    //Get indirect object
                    REFOBJ refObj= refObjects.GetBy(obj.ObjectNumber);
                    if (refObj == null)
                    {
                        //If there is no such an object then delete it
                        list.Remove(obj.ObjectNumber);
                        cross.Remove(obj.ObjectNumber);
                    }
                }
                //Save the document
                doc.Save(@"d:\test_modified.pdf", SaveFlags.NoIncremental);
            }
        }
    }
}
[/code]

**Comment by w8tcha** [comment]
That is the theme from the syntax highlighter. If you prefer a different theme download the theme from the prismjs website and put it in your forum theme.css

**Comment by Patagames** [comment]
Thank you very match for your answer.
Is there any instruction how to do that?
I just added the content of the downloaded prism.css to the end of forum.min.css and result looks ugly

![image](https://user-images.githubusercontent.com/12828157/42417119-1218f2f2-82c4-11e8-965c-21e80bb55ef6.png)

Looks like I should remove funky theme before adding new one. Ho can I do that?

**Comment by w8tcha** [comment]
> Looks like I should remove funky theme before adding new one. Ho can I do that?

In that case you would need to download the source package and recompile the forum.css with the updated prism.css in the Content folder
