### ISSUE TITLE
installing yaf

### ISSUE THREAD

**Issue by Kendarr** [YAFNET/YAFNET#401]
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--

full error: https://i.imgur.com/tuM3qsD.png

**Comment by w8tcha** [comment]
did you define a machinekey in the web.config?

**Comment by Kendarr** [comment]
Yes it is defined

Sent from my iPhone

On 10 Jul 2018, at 17:12, Ingo <notifications@github.com<mailto:notifications@github.com>> wrote:


did you define a machinekey in the web.config?

**Comment by w8tcha** [comment]
But then there is something wrong with that config section. If you are using the recommend.web.config did you uncomment that machinekey section?

and does it look something like this..

`<machineKey validationKey="5B169A4270DB7D6A285CF068B81047D1A73A5FDDE9B204254AB86147B061C3C13DB6E84311E98EDFDD7FF50309DB9632A1C573A716CF120535EC3401BF7706D7"
        decryptionKey="910403AE3DEB5DD0AF73911DBB180518144AC983C1C7E7BDEE1CC8B6C74CBEF3"
        validation="SHA256" decryption="AES"/>`

**Comment by Kendarr** [comment]
<machineKey validationKey="F0C2D823E4A003FF04FD80DFA10B6B645BB10371F63E48B3A082CD326C9DEA23742F4A45119FB9923B029D6D8D39626920181B49BDA9DD6DB81C1698595C8BD4" decryptionKey="4D5F56172FA2D22C6DED04198A5EE9C005D1EE71CC4E78F9" validation="SHA256" decryption="AES" /> 
[webconfig.zip](https://github.com/YAFNET/YAFNET/files/2184329/webconfig.zip)

**Comment by Kendarr** [comment]
I just made a fresh VM, install IIS downloaded the web installer and installed it from that and i am getting the same error. What am i doing wrong? i made a new key for that web.config on that server.

**Comment by w8tcha** [comment]
> What am i doing wrong?

The web.config is okay! Which app pool did you select in the IIS Manager for the application? So far  i run out of ideas what is wrong, and google is not really helping

**Comment by Kendarr** [comment]
https://i.imgur.com/iPKURHK.png

**Comment by vincentw56** [comment]
I am having this exact same issue. Brand new server. I tried the machine key provided in the web.config and I also generated a new one on the site. Both give me an error.

**Comment by Kendarr** [comment]
Remove the machine key out the web.config
