### ISSUE TITLE
Has local time zone offset stopped working?  (2.2.4.12)  

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#402]
Seems like the user profile time zone offset vs UTC does not work correctly in 2.2.4.12. 
Upgraded tonight and posted a message in the forum 19:55 local time, but was shown as posted at 17:55.  Was not like this before the upgrade from 2.2.4.4 tonight. 

Middle European Summer Time - 2 hr offset vs UTC. 

Just wondering... 

![image](https://user-images.githubusercontent.com/5246746/42838989-8acabb64-8a02-11e8-9659-9668916e6ee5.png)

![image](https://user-images.githubusercontent.com/5246746/42836966-df5ab766-89fc-11e8-9dad-1790bc3d9adc.png)

**Comment by w8tcha** [comment]
Check your user profile is the correct time zone selected?

**Comment by JP58** [comment]
It is...

**Comment by w8tcha** [comment]
Okay found the problem! the conversation couldnt work when the system did not know it is an utc value

I didn't see it because i have the timeago feature enabled. In your forum it is disabled.

Will be fixed in 2.2.4.13
