### ISSUE TITLE
Question about 2.3.0 regarding themes. 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#403]
As I understand, 2.3 will have a bootstrap based page layout. 

Will the old "themes" still work or will there be a new way of doing the themes? 
What I am anxious to know is if I will have to rework my forum theme completely, and if so - if there is a Bootstrap forum theme CSS example file somewhere in the works? 

Just want to be prepared when 2.3 goes official...  :-)

**Comment by Zero2Cool** [comment]
If YAF is going to go to bootstrap, it's best to adopt bootstrap themes.  I've found good themes to modify from https://bootswatch.com/

**Comment by JP58** [comment]
Saw you even updated the 2.3 to include the latest FA icons... ;-) 
Really looking forward to having one BS theme on the whole site and also with the YAF portion of it. 

So what you are really saying is that the "themes" folder will become obsolete some time in the future, and we can adapt custom BS themes also for the forum? 

BS + FA is a very good base standard indeed these days...

**Comment by Zero2Cool** [comment]
I can't speak for Ingo, but in my opinion, 100% Bootstrap is the way to go with a forum.css or site.css for over rides and certain custom elements Bootstrap doesn't account for, or little tweaks.  I would suspect a themes folder would still be valid.    /themes/bootstrap.litera.css  could be a theme that you select via XML selector like the current system works.   

Thinking more about it, it could actually make themeing YAF a lot more smooth than what is currently being done. Then again, I hate tables so I could be a little bias there. :D

**Comment by w8tcha** [comment]
> Will the old "themes" still work or will there be a new way of doing the themes?

No the old themes will not work anymore, you have to do everything from scratch. But there will be at least one standard theme/skin. 

But you still have a lot of time to be prepared, because i don't have as much time as i would like to continue work on the bootstrap transformation
