### ISSUE TITLE
ASP.NET Identity

### ISSUE THREAD

**Issue by w8tcha** [YAFNET/YAFNET#406]
I think it is time to replace the old Membership/Role/Profile Providers (outdated and obsolete) with the current [ASP.NET Identity](https://www.asp.net/identity) including oAuth

**Comment by Zero2Cool** [comment]
Heck yeah! Let's do it!

**Comment by john2014** [comment]
Few important things you should know:

1. ASP.Net Identity 2.0 will only work with .Net Framework. https://archive.codeplex.com/?p=aspnetidentity

2. ASP.Net Identity 3.0 will only with with .Net Core.

So YAF will only work with ASP.Net Identity 2.0. However version 2.0 will no longer be adding any features and this release is for bug fixes only. So it is important to know this. It is also possible that Asp.Net Identity 2.0 requires using Entity Framework. So this will add another dependency to the project.

**Comment by JP58** [comment]
Good idea - would make it easier with claims auth towards FB, Google and such...

**Comment by w8tcha** [comment]
First implementation for YAF 3.0 with Asp.Net identity is online. 

- New installs should work
- Upgrade from old yaf provider is working
- Upgrade from standard membership provider is working

TODO:
- external logins (via fb/twitter/google etc.)

**Comment by JP58** [comment]
Have you looked at this? 

At work we are planning to use IdentityServer in our main product since you can do auth towards most providers...  

https://identityserver4.readthedocs.io/en/latest/

**Comment by w8tcha** [comment]
> Have you looked at this? 
> 
> 
> 
> At work we are planning to use IdentityServer in our main product since you can do auth towards most providers...  
> 
> 
> 
> https://identityserver4.readthedocs.io/en/latest/ 
> 
>  

It’s AspNet Core only. Not  an option for yaf at the moment
