### ISSUE TITLE
compile error with this.Get<IList<Assembly>>("ExtensionAssemblies").Select(a => a.FullName).ToList();

### ISSUE THREAD

**Issue by senlinyan** [YAFNET/YAFNET#408]
I download the source code and compile it with Visual Studio 2017, get a compile error in the row 
this.Get<IList<Assembly>>("ExtensionAssemblies").Select(a => a.FullName).ToList();

**Comment by w8tcha** [comment]
Which source did you download? If you want to use the latest version please download the stable branch and not the master branch!

**Comment by senlinyan** [comment]
> Which source did you download? If you want to use the latest version please download the stable branch and not the master branch!
I have downloaded the master branch. Thanks for your suggestion.
