### ISSUE TITLE
Ignore user

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#41]
When a user is ignored, their post is still showing up, but the content is hidden. Can the post just not be shown at all?

Also, if an ignored users post is quoted, it is then displayed. Any possible way of having that hidden?

**Comment by w8tcha** [comment]
The complete post is now hidden. Quotes however will still show up!

**Comment by w8tcha** [comment]
> Why not just exclude it all together? Sure there's a reason behind it, I just don't get it. If I block someone, it's because I want to pretend they don't exist, not because I want to see that they said something, but not know what was said.

There is a difference between ignoring and blocking. Ignoring the content of a user would not mean that you don't want to receive private messages
