### ISSUE TITLE
Vimeo video's are not showing on post.

### ISSUE THREAD

**Issue by RabiNarayanPadhy** [YAFNET/YAFNET#410]
Hi TAF Team,

I am sending the forum link below: Please check it. **Both video are not showing on post.**

1. (https://wasp3d.com/Forum....aspx?g=posts&t=1568)

2. https://wasp3d.com/Forum...t.aspx?g=posts&t=282

> Your YAF.NET Version: 2.2.4.4 (Date: 08-10-2017).

Please help me on this.

#################################################

Description: [VIMEO]http://www.vimeo.com/xxxxxxxxx[/VIMEO]

Search RegEx: `\[vimeo\](?<inner>(?<prefix>.+?)vimeo.com/(?<vimeoId>[0-9]{9}))/[^[]*\[/vimeo\]|\[vimeo\](?<inner>(?<prefix>.+?)vimeo.com/(?<vimeoId>[0-9]{8}))[^[]*\[/vimeo\]`

Replace RegEx: `<div><iframe width="100%" height="550" src="http://player.vimeo.com/video/${vimeoId}?show_title=1&amp;show_byline=1&amp;show_portrait=1&amp;&amp;fullscreen=1" frameborder="0" allowfullscreen></iframe></div>`

Replace Variables: `prefix;vimeoId`

#################################################

Thanks,
Rabi

**Comment by w8tcha** [comment]
What happens when you change the replace regex with...

`<div><iframe width="560" height="350" src="//player.vimeo.com/video/${vimeoId}?show_title=1&amp;show_byline=1&amp;show_portrait=1&amp;&amp;fullscreen=1" frameborder="0"></iframe></div>`

**Comment by ravinpadhy** [comment]
https://vimeo.com/180003190   - Not working in YAF, Please help me on this.

Description: 
[VIMEO]https://www.vimeo.com/xxxxxxxxx[/VIMEO]

Search RegEx:
\[vimeo\](?<inner>(?<prefix>.+?)vimeo.com/(?<vimeoId>[0-9]{9}))/[^[]*\[/vimeo\]|\[vimeo\](?<inner>(?<prefix>.+?)vimeo.com/(?<vimeoId>[0-9]{8}))[^[]*\[/vimeo\]

Replace RegEx:
<div><iframe width="560" height="350" src="//player.vimeo.com/video/${vimeoId}?show_title=1&amp;show_byline=1&amp;show_portrait=1&amp;&amp;fullscreen=1" frameborder="0"></iframe></div>

Thanks,
Rabi
