### ISSUE TITLE
404 issue when integrating with ASP.NET VS 2017

### ISSUE THREAD

**Issue by KodaRayTominus** [YAFNET/YAFNET#411]
Server Error in '/' Application.
The resource cannot be found.
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

Requested URL: /Default.aspx

I have followed this https://github.com/YAFNET/YAFNET/wiki/YAF.NET-Integration-in-to-an-existing-ASP.NET-Application 6 times. can't seem to get anything to work. The sample does not follow the how-to, so comparing has been difficult. here are my application and branch I am working on it with. https://github.com/KodaRayTominus/MiniaturesForSale/tree/Forum

this is an ongoing project for school, that I hope to eventually launch. Any and all help would be appreciated

**Comment by KodaRayTominus** [comment]
Manually added Details.aspx and Site.Master as well as added references. Looks like some of the sample code may be depreciated YafForumInfo.GetURLToResource(Config.JQueryFile); these calls are no longer available.

**Comment by w8tcha** [comment]
The wiki was pointing to an old release of the sample application! I updated the wiki page...

https://github.com/YAFNET/YAF.SampleWebApplication/releases

**Comment by KodaRayTominus** [comment]
Awesome thank you!

**Comment by KodaRayTominus** [comment]
So I'm getting an error where all paths are trying to skip the "forum" portion of the URLs. I have my most recent code uploaded on that previous github link/ branch. 
I'm sure I'm missing something trivial, and it would be very appreciated!
Could not find a part of the path 'D:\School Work\FifthQuarter\CPW215\MiniaturesForSale\MiniaturesRUs\languages'.

**Comment by w8tcha** [comment]
I see you are not using the urlrewriter.config that is included in the yaf sample application

**Comment by KodaRayTominus** [comment]
So, I have the file, and the  <rewriter configSource="URLRewriter.config" >
Is the one in the sample that different?

**Comment by KodaRayTominus** [comment]
Thank you! That fixed it! I can't believe I overlooked that! Thank you so much!

**Comment by KodaRayTominus** [comment]
So that allowed it to go the homepage, but when navigating to /forum to get the install going its still trying to route too http://localhost:49989/install/default.aspx, instead of http://localhost:49989/forum/install/default.aspx

**Comment by KodaRayTominus** [comment]
I tried launching it from the IIS server as well and get Requested URL: /TheMiniatureMan/error.aspx, which again is calling it without the /forum/ portion.

**Comment by KodaRayTominus** [comment]
Sorry to keep asking. I'm about 20 hours into this and dedicated on getting it working lol.

**Comment by w8tcha** [comment]
Are you using the app.config from the sample application?

**Comment by KodaRayTominus** [comment]
I wasn't even with the exact app.config I still get the 404 Requested URL: /TheMiniatureMan/error.aspx

**Comment by KodaRayTominus** [comment]
Got it working, I guess I didn't link the app.config. Opps. THANK YOU!

**Comment by KodaRayTominus** [comment]
So did I need to create the Default.aspx file and master in the root to get this running?

**Comment by KodaRayTominus** [comment]
Have you heard of anyone running into an issue with getting forwarded from /accounts/login to /accounts/forum.aspx?

**Comment by KodaRayTominus** [comment]
Not sure if its a conflict between Identity and what you're using, but I can't log in on the forums either.

**Comment by KodaRayTominus** [comment]
removing this allows log in with Identity

 ` <rewrite url="^~/(.+?)?login?(\?(.+))?$" to="~/$1forum.aspx?g=login&amp;$3" processing="stop" />`

**Comment by KodaRayTominus** [comment]
still can't log on the forum, also noticed the captcha isn't loading.

**Comment by w8tcha** [comment]
Are you trying to login with the forum account or with your site account? Be aware that Asp.net identity and the yaf asp.net membership is not compatible!

**Comment by KodaRayTominus** [comment]
The admin account created on install. It just  reloads the login or home page with no login action completed.

**Comment by KodaRayTominus** [comment]
I was going to have the main site account and forum accounts separate.

**Comment by KodaRayTominus** [comment]
How incompatible are they? Do they conflict, or do you mean they just can't be integrated to use the same tables/data

**Comment by KodaRayTominus** [comment]
To clarify, I am only logging in on the main portion with my identity accounts, which now loads the login page without that line. But still cannot log into the forum portion, with the forum admin credentials made on the install of the forum, it simply forwards too the home page without install or loads the same login page with no errors, though it is hitting the database, as when using the wrong credentials, it's says they are wrong or not in use

**Comment by KodaRayTominus** [comment]
Thank again for helping out.

**Comment by KodaRayTominus** [comment]
this was the overall issue 
`      <remove name="FormsAuthentication" />`
don't know where it came from, guessing my original web.config.
