### ISSUE TITLE
Replace Smileys with jQuery plugin Emojis

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#412]
What do you think about removing the current smiley system and replacing it with a jQuery plugin that adds the smiley to the actual message? Similar to how mobile devices work? I was thinking something like this would be pretty slick!

https://www.jqueryscript.net/text/WYSIWYG-Emoji-Converter-Picker-Plugin-For-jQuery-EmojiOne-Area.html

**Comment by w8tcha** [comment]
https://github.com/YAFNET/YAFNET/issues/67

It's already done. Smilies will be replaced by native emoji

**Comment by Zero2Cool** [comment]
What the heck? I upgraded last night and ... ugh. I will be back! :D
