### ISSUE TITLE
UserName showing up on old messages from deleted user

### ISSUE THREAD

**Issue by willhowells** [YAFNET/YAFNET#413]
When a user account is deleted but messages remain on the forum, it looks like the username goes into the UserName field in the yaf_Message table and is then displayed alongside the posted messages.

This should probably be the display name instead so that, for example, email addresses aren't shown?

**Comment by w8tcha** [comment]
It is correct the username is saved in the username field. and the display name in the UserDisplayName field. Only the logic that shows the name was wrong. Will be fixed in YAF 2.24.15

**Comment by willhowells** [comment]
Thanks!
