### ISSUE TITLE
YAF integration with Sitecore 9

### ISSUE THREAD

**Issue by NagendraK89** [YAFNET/YAFNET#414]
Hello,

I would like to know whether YAFNET can be integrated with Sitecore v9. I have modified the latest version of YAFNET as per below project.

https://github.com/brooksyd2/sitecoreyaf8

but it's not working.

Any help will be appreciated.

Thank you.

**Comment by Zero2Cool** [comment]
What's the error you're receiving that it's not working?

**Comment by NagendraK89** [comment]
Initially, I got this error

Could not load file or assembly 'Sitecore.Kernel, Version=11.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)

That I resolved after removing below code from AssemblyInfo.cs files of each YAF project.

#if !NCRUNCH
[assembly: AssemblyDelaySign(false)]
[assembly: AssemblyKeyFile("..\\YetAnotherForum.NET.snk")]
#endif

after this, I getting below error that I unable to resolve 

![image](https://user-images.githubusercontent.com/22005598/53960854-4df82880-410d-11e9-952c-61b624b383dd.png)

**Comment by Zero2Cool** [comment]
I was hoping the error would add some context where I could help, unfortunately it did not. Sorry.

**Comment by w8tcha** [comment]
I think thats nothing we can help you with. There is no free version of this product, so there is no chance that i can test this, or build a solution
