### ISSUE TITLE
Right margin/padding

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#418]
When the forum is full width, there is a margin/padding on the right.  I fixed that by removing `width:99%;` from the content/forum.min.css

You can see it here. http://kevinduganjr.com/

**Comment by w8tcha** [comment]
Yes this is correct! otherwise the vertical scrollbar occurs

**Comment by Zero2Cool** [comment]
You mean the horizontal scrollbar on the bottom? `overflow-x: hidden;` should take care of that without the `width:99%`

**Comment by w8tcha** [comment]
> You mean the horizontal scrollbar on the bottom?
Yes

>  To stop that from happening enter the following in default.aspx page.

That is needed to make it responsive

What problems is causing the 99% value i dont see any issues?

**Comment by Zero2Cool** [comment]
I've added it to my site linked above and it's responsive. I also did something similar with my main packers site because I didn't like the horizontal scrollbar on the bottom.   The problem with the spacing is it was not even. I had a large space on the right side that was not matched on the left. I'm kind of picky I guess haha.

**Comment by w8tcha** [comment]
Sorry i dont get it. if i add the 99% value the space left is equal to the right. and if remove the value there is less space right.

You can change the css from within your site if you dont like that!

**Comment by Zero2Cool** [comment]
If you're not seeing it, then it is not an issue.  I have seen it before with bootstrap projects and it bothers me so I fixed it. This is what I am seeing when `width:99%;` included.  
![image](https://user-images.githubusercontent.com/5612416/56499163-c99a1300-64ca-11e9-9d38-dc452b020d0f.png)

**Comment by w8tcha** [comment]
the problem is that the rows are not wrapped in a container. so i applied the padding and margin to the body instead of the container. Now the issue is fixed with

```
#YafBody {
    padding-right: 15px;
    padding-left: 15px;
    margin-right: auto;
    margin-left: auto;
}
```
