### ISSUE TITLE
Thanks not working

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#427]
When debugging the latest master commit, I noticed Thanks are not added or removed, nothing in the console, nor error logged in the event viewer. However, when trying to remove a Thanks in YetAnotherForum.net there is an error in the console. 

/forum/YafAjax.asmx/RemoveThanks:1 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

``System.InvalidOperationException: RemoveThanks Web Service method name is not valid.
   at System.Web.Services.Protocols.HttpServerProtocol.Initialize()
   at System.Web.Services.Protocols.ServerProtocolFactory.Create(Type type, HttpContext context, HttpRequest request, HttpResponse response, Boolean& abortProcessing)``

**Comment by w8tcha** [comment]
I dont think you are using the latest master "YafAjax.asmx" is no longer in the code. this has been removed.

**Comment by Zero2Cool** [comment]
When doing this on the latest source, nothing happens.  The error message posted is what happens on YetAnotherForum.net website, the YAF Support website. Not my site. On my site, no error, no console, nothing, nothing at all happens for YAF.

**Comment by w8tcha** [comment]
Issue should be fixed now in the code. not the support forum!
