### ISSUE TITLE
Emoji Menu

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#430]
Something I stumbled onto a few times consistently is the emoji smiley menu requires a second click to keep the menu open. It appears to happen with YAF Sample Application and YAF stand alone.

**Comment by w8tcha** [comment]
The button is disabled on mobile devices because it's not needed

**Comment by Zero2Cool** [comment]
Why would it not be needed? One of the benefits of using a responsible design framework is to give both mobile and desktop users a similar user experience.  Either way, are you experiencing the same thing with the opening of the smiley menu?>

**Comment by w8tcha** [comment]
Should be fixed now!

**Comment by Zero2Cool** [comment]
> The button is disabled on mobile devices because it's not needed

I'll have to enable it because consistency is good. :P (I fully understand why you believe it is not needed though and normally I would agree) 

And I think it is fixed. I believe there is a small 250ms delay for the emoji menu to open. Absolutely not a big deal at all.

**Comment by w8tcha** [comment]
> And I think it is fixed. I believe there is a small 250ms delay for the emoji menu to open. Absolutely not a big deal at all.

yes it is, it takes some time to load parse all emojis
