### ISSUE TITLE
Move Sub-Forums section to bottom of topics

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#438]
I noticed with having just three sub-forums that on mobile you kind of had to do a lot of scrolling. So, I moved the Sub-Forums to the bottom, the way bottom of topics control page.  Do you see value in this for YAF itself?

https://github.com/Zero2Cool/YAFNET/commit/b250201bb8ce8b540d4d0d37f2c2853f6cf4bc25

**Comment by w8tcha** [comment]
I would prefer adding a collapse button to it and make the card collapse. Just like on the Categories

**Comment by Zero2Cool** [comment]
Probably easier solution than what I did lol

**Comment by w8tcha** [comment]
i committed the changes
