### ISSUE TITLE
Update for ModeratePosts hangs 

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#440]
When trying to update to latest commit (second latest now) the database update hangs. No error, no timeout, just hangs. This database update is required because of the ModeratePosts value that's needed.

**Comment by w8tcha** [comment]
Can you try now?!

**Comment by Zero2Cool** [comment]
This appears to have improved the speed and it completed. However, I have a ``<url:Form runat="server" ID="form1">`` related error. I can fix that when I get home.

**Comment by w8tcha** [comment]
I updated the sample application. With the updated Form control

**Comment by Zero2Cool** [comment]
Awesome!
