### ISSUE TITLE
search on old database

### ISSUE THREAD

**Issue by AlbertoP57** [YAFNET/YAFNET#444]
With an old database (v. 1.9X) there is a problem with the search functionality (2.3.0 beta). This is caused by some not used (null) fields.

To fix it, in my environment, I have updated the **message_list_search** stored procedure this way (excerpt):
>select
        m.MessageID,
		m.[Message],
		m.Flags,
		m.Posted,
		**ISNULL(m.UserDisplayName, u.DisplayName) as UserDisplayName**,
		**ISNULL(m.UserName, u.Name) as UserName**,
		u.UserStyle,
		m.UserID,
                t.TopicID,
		t.Topic,
                f.ForumID,
		f.Name,
		t.[Description]

but maybe it could be better to convert the database?

**Comment by w8tcha** [comment]
Thanks, i think changing the sp is the best option to directly fetch the name from the user table
