### ISSUE TITLE
Issues - Moderate section of site - 2.3.0 BETA 20190707 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#445]
**First of all - fantastic work to get here with 2.3.0 !**  
I use the "yaf" skin, and I love the look, feel & user interaction functions with it like the notifications and PM's in the menu bar, OP badge on posts and much more - even the "Moderate" area is not looking like the "lost grandmother" any more, but clear and distinct by category/forum. Ok, some things are not perfect but it's a very good start and also a reason for upgrading.  

Issues detected so far in the moderate area... 

- Replies via PM to the reporter of a post do not include a quote of the original report post as it does in 2.2 
- Attached images, nor album images show in the reported post but linked remote images do. Would be nice if it was consistent so all types of images in the post show. 
- Radio buttons in compare message versions are not exclusive but behave like checkboxes, see attachment.
- Made a restore of original message, but edited date/time shows same date/time instead of original when compared to recent edit (also in attached image).
 
Just my thoughts about small things that would make this function more consistent. Moderators spend daily time here, so it should be more or less "perfect" for the daily work...  

![MessageCompare](https://user-images.githubusercontent.com/5246746/61554495-54a09000-aa5d-11e9-956d-7952dfbbeffb.JPG)

**Comment by w8tcha** [comment]
> Made a restore of original message, but edited date/time shows same date/time instead of original when compared to recent edit (also in attached image).

That is correct if you restore a message it would show this as edited as the time of when you restore the message!

All issues are fixed now!
