### ISSUE TITLE
Suggestion - Message layouts in 2.3 beta

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#446]
Have spent some time browsing the new forum software with a mobile (Huawei P20 pro) and noted some things that can be regarded as "cosmetic", but still a bit annoying regarding overall user experience...  

**The placement of "Post Reply" & the other buttons in a topic message list.** 

**On mobile**
![Screenshot_20190721_190614_com android chrome](https://user-images.githubusercontent.com/5246746/61594664-c9570400-abee-11e9-80df-8439b64d2e58.jpg)
![Screenshot_20190721_190637_com android chrome](https://user-images.githubusercontent.com/5246746/61594671-d07e1200-abee-11e9-8059-84de1ea893ce.jpg)
![Screenshot_20190721_190651_com android chrome](https://user-images.githubusercontent.com/5246746/61594673-d4119900-abee-11e9-9c31-1a22244fb91d.jpg)
![Screenshot_20190721_190709_com android chrome](https://user-images.githubusercontent.com/5246746/61594678-daa01080-abee-11e9-9025-0e2de462aa1f.jpg)

**On Computer**
![View on PC](https://user-images.githubusercontent.com/5246746/61594694-fdcac000-abee-11e9-9fb7-7c2931ccd52a.JPG)

I think it would be better if the button block was placed before the active users/similar topics list (and the feed button), would be easier on mobile (and computer too)... I presume it is a "simple" change of control order on the page in the code...  

**The font size in "Thanks list" could be smaller....** 
Kind of distracts attention from the action links too much... 
![Screenshot_20190721_185652_com android chrome](https://user-images.githubusercontent.com/5246746/61594840-88f88580-abf0-11e9-898a-a55f5bf99110.jpg)

**When replying/quoting messages, the Persistent Topic option is showing.** 
Is this for admins only or does it show to regular members too? Can see the purpose if only visible for admins. 
![Screenshot_20190721_190347_com android chrome](https://user-images.githubusercontent.com/5246746/61594974-b8f45880-abf1-11e9-86ec-510f28f5c766.jpg)

My "petty" thoughts for today, that was... :-) 

Just wait until I get into the image presentation issues in messages that I have noted...  :-D

**Comment by w8tcha** [comment]
makes all sense, 

> When replying/quoting messages, the Persistent Topic option is showing.

It is now only visible for mods and admins!
