### ISSUE TITLE
Compiling 2.3 Source code - YAF.Web.Controls namespace missing.

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#447]
Downloaded the latest source code this afternoon to get the fixes for my initial report, but it would not compile due to references to YAF.Web.Controls namespace (1515 errors)... 

I presume this is a code reorganization & cleanup in progress, and the Controls source haven't been pushed to the YAF.Web project in the master repo yet...

**Comment by w8tcha** [comment]
Rename the recommended.web.config to web.config then it should compile.

**Comment by JP58** [comment]
Downloaded the project zip again, and this time the YAF.Web contained a Controls folder...  The one I had earlier did not have that, but all the controls were in the YAF.Web folder.

Compiled ok, only some JQuery/JS issues with this batch of source - Images do not open in a JS popup, but directly in the same window. 

![image](https://user-images.githubusercontent.com/5246746/61732872-e3bfe780-ad7e-11e9-9a55-cc1b225d27af.png)
 
![image](https://user-images.githubusercontent.com/5246746/61732977-21bd0b80-ad7f-11e9-98d2-7813682425e4.png)

**Comment by w8tcha** [comment]
Can you open a new issue for each problem? this makes it easier to track and fix each issue!

**Comment by w8tcha** [comment]
> Compiled ok, only some JQuery/JS issues with this batch of source - Images do not open in a JS popup, but directly in the same window. 

Make Sure that you clear the browser cache! If it still does not work check the browser JS Error Console

**Comment by JP58** [comment]
Regarding JQuery issues - local JQuery URL showed site.net/~forum/Scripts/jquery.min.etcetera even if the forum root was set to "/" in app.config.  Changing to CDN script loading remedied the JQuery issue and now it works as expected - imgs pop up in the same page...

**Comment by w8tcha** [comment]
It takes the URL from YAF.ClientFileRoot and not approot
