### ISSUE TITLE
Collapsible Userbox

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#448]
One post can consume quite a bit of vertical space, regardless of the contained message. Anyway to have this (maybe) be collapsed on default? Or maybe only accessed via hover card?  Just a thought to bring focus to the comments in a post rather than the static (e.g. Userbox information) stuff.

![image](https://user-images.githubusercontent.com/5612416/62839323-40ac1080-bc4e-11e9-950d-97fd28785bfd.png)

**Comment by w8tcha** [comment]
I think its better to drop the userbox completely! and replace it with rows

<img width="910" alt="userinfo" src="https://user-images.githubusercontent.com/722575/63220023-6326b800-c17f-11e9-9ad4-4f6764fa4c42.PNG">

**Comment by Zero2Cool** [comment]
Great idea!

**Comment by w8tcha** [comment]
Sure it still take some space. But you also want to know what person is writing in the discussion an avatar picture is easy to remember. And in my opinion better then just a name with a hover card.

**Comment by Zero2Cool** [comment]
The more I see it, the more I'm liking how Github implements a "userbox".  It's to the point and if you wanna know more about the person who made the comment, click on the profile. Focus is on the comments, not the who.  I'll have to tinker with it at some point :D

**Comment by w8tcha** [comment]
I Made some changes it looks much better now!

http://yetanotherforum.net/forum/posts/t21675-Block-User-and-Email-issue

**Comment by Zero2Cool** [comment]
Agreed, much gooder!

**Comment by w8tcha** [comment]
I committed the updated user info
