### ISSUE TITLE
Tweak to Login layout

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#449]
After entering a Username and Password, I think it's common to have the immediate button be the action of getting authenticated.   The login page currently has the "Lost Password" button first. I find myself clicking that instead of Forum Login, lol.

Maybe put `Lost Password` next to `Register as new user` and put `Login` and remember me on the same line below password field?

Current.
![image](https://user-images.githubusercontent.com/5612416/62839425-34748300-bc4f-11e9-9ac0-9492eef48917.png)

Alternative?
![image](https://user-images.githubusercontent.com/5612416/62839754-95528a00-bc54-11e9-9d90-48992ed9c531.png)

**Comment by JP58** [comment]
I think this is a good suggestion, this is the way it should look indeed.
There are some "layout order" things that should be looked at too, so I hope this version is not being rushed into release too soon.
