### ISSUE TITLE
2.3.0 Beta 1 - Adding pictures to Albums does not seem to work ok 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#450]
Seems like the image selection routine is broken. I can choose a file, but the file name is not recognized/copied to the YAF dialog text field by the routine and gives me a null exception when I press Upload. 

![image](https://user-images.githubusercontent.com/5246746/62963759-e2c02a00-be01-11e9-9fb7-21a731a03e91.png)

**Comment by Zero2Cool** [comment]
Anyway to mimic how Github adds pictures by copy/paste them into the body
of the message?

>

**Comment by JP58** [comment]
That would be the best "user experience", of course - just like on FB and other places too... 

But then there is a bit of work to do to save them...  Easy to embed them as base64 code images in a html post with many JS editors, but what you really want is to extract that base64 image and save it as a separate file or db blob so you can reference it from other places too. Have tried that with an email form using the Summernote JS editor, but that was just a "simple" test - not a solution...
