### ISSUE TITLE
2.3.0.0 BETA 1 configuration error

### ISSUE THREAD

**Issue by perniklas** [YAFNET/YAFNET#451]
Hello!

I've successfully deployed the 2.3 beta to an Azure web app, but some scenarios (opening topics, creating topics) will throw a configuration error

-  **Parser Error Message: Attribute not recognized 'passwordFormat'** 

regarding the AspNetSqlProfileProvider profile in web.config (line 92 or so in recommended-azure.web.config) and I cannot for the life of me figure out what causes it and how to circumvent the issue.

**Comment by w8tcha** [comment]
Just remove the attribute "passwordformat" then it should work. It should not be there!

**Comment by Pistle** [comment]
I suggest you firstly try to add the maxInvalidPasswordAttempts property and see if it helps. here is an example:

 <add name="AspNetSqlMembershipProvider" type="System.Web.Security.SqlMembershipProvider, System.Web, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" connectionStringName="LocalSqlServer" enablePasswordRetrieval="false" enablePasswordReset="true" requiresQuestionAndAnswer="true" applicationName="/" requiresUniqueEmail="false" passwordFormat="Hashed" maxInvalidPasswordAttempts="100" minRequiredPasswordLength="7" minRequiredNonalphanumericCharacters="1" passwordAttemptWindow="10" passwordStrengthRegularExpression=""/>
