### ISSUE TITLE
2.3.0 Suggestion - Make UserBox placement an admin option. 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#453]
In the earlier versions, the UserBox is to the left. In 2.3.0 it's to the right. 

It would be very nice to have the placement of the UserBox as an administered option either to the left or right. Users of YAF are used to the current layout and when you have an established audience, radical changes to general forum layout are maybe not always welcome by the forum members/visitors.

**Comment by w8tcha** [comment]
I agree. But keep in mind YAF 2.3.0 has a completely new layout! However the userbox will be removed and replaced with a user info row. You can see it live in the support forum

**Comment by JP58** [comment]
Oooohhh...  That user info row really wastes some valuable screen space, doesn't it?
Also attracts attention away from the message, as I perceive it. 

Maybe smaller size on avatars and more of the data on one line. 

To be honest, I think it looks a bit silly when the post header consumes more space than the actual post...  Or maybe I'm just too old...  :-D 

![image](https://user-images.githubusercontent.com/5246746/63227041-7c148500-c1e2-11e9-8a44-bd9df0058e43.png)

**Comment by w8tcha** [comment]
I made some changes. i think now it is okay!

http://yetanotherforum.net/forum/posts/t21675-Block-User-and-Email-issue
