### ISSUE TITLE
2.3.0 Beta 1 - Images part 2 & 2.1 - Images posts do not expand when clicked

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#455]
Part 2...
Before 2.3.0 images in posts where expanded to a certain percentage of the screen size or their real size if the were smaller using a JavaScript popup feature.  

In 2.3.0 the popup is of a constant small size, not giving the expected experience you normally want to see when clicking the image so you can notice more details. 

![image](https://user-images.githubusercontent.com/5246746/63215008-79515b80-c120-11e9-998d-96b381d966c7.png)

Part 2.1
Images in a post that are inserted as URL links do not pop up at all, nothing happens when you click them.

**Comment by w8tcha** [comment]
> In 2.3.0 the popup is of a constant small size, not giving the expected experience you normally want to see when clicking the image so you can notice more details.

You need to increase the resize max width & height. Right now its set to 500x500 i will  increase it to 2000x2000

> Images in a post that are inserted as URL links do not pop up at all, nothing happens when you click them.

Should be fixed now
