### ISSUE TITLE
2.3.0 Beta - Maybe some visual tidying up among the on/off switches in the admin interface

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#458]
Would be a lot easier to see in "table form", so to speak...  A couple of the pages look kinda confusing...  

![image](https://user-images.githubusercontent.com/5246746/63227962-af5c1180-c1ec-11e9-980a-eab9a9a0bab6.png)

![image](https://user-images.githubusercontent.com/5246746/63227993-327d6780-c1ed-11e9-9c8e-1aefef0d1632.png)

**Comment by Zero2Cool** [comment]
I've always liked the form styling. 
https://getbootstrap.com/docs/4.0/components/forms/#readonly-plain-text

**Comment by w8tcha** [comment]
![8E0CC409-34B8-4B89-8ECF-B94E16FBA5A5](https://user-images.githubusercontent.com/722575/63231369-f9f48280-c21a-11e9-90f3-7354aee9d7b7.png)

I'm open for suggestions. For me I mostly use a mobile device so for me it will always look like this

**Comment by w8tcha** [comment]
> There's a space between the '-' button and input field 

Thats only an issue with the bootstrap theme of the yaf website.

The info buttons are much smaller now
