### ISSUE TITLE
2.3.0 - Images in posts part 4 - not quite there yet.

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#459]
Ok, now some images from different sources show the same size in posts, but more or less a thumbnails. 

The admin settings are not honored as expected, seems like only album images are doing the right thing. 

![image](https://user-images.githubusercontent.com/5246746/63228498-18935300-c1f4-11e9-8293-02caef0563f3.png)

![image](https://user-images.githubusercontent.com/5246746/63228464-9a36b100-c1f3-11e9-8bf6-e42aecd1369f.png)

**Comment by w8tcha** [comment]
the images are Cached. You need to clear the all the caches. then the album image will show also in the same size. right now the thumbnail size can not be changed.

**Comment by JP58** [comment]
Since the classes added to the different img elements are different or not there, cache clearing did not work. 
![image](https://user-images.githubusercontent.com/5246746/63284624-3fb15980-c2b4-11e9-91ea-7bd6ce9a6e05.png)

**Comment by w8tcha** [comment]
Sorry I was not clear, I was meaning the application cache. You need to recycle the app pool or restart iis

**Comment by JP58** [comment]
Did all that, several times - YAF cache, browser cache & app pool & restart IIS & Restart the machine... :-) 

Interesting to see is that it seems that album image attached honors the admin setting (700px wide), and since it has the img-resp... sorry, img-fluid class in BS4 - it's the only one that behaves "as expected" from a users point of view...  
![image](https://user-images.githubusercontent.com/5246746/63285974-38d81600-c2b7-11e9-893f-e02e7dfdaed3.png)

**Comment by w8tcha** [comment]
According to your last Screenshot all 3 images are now correct. The thumails are all max 200x200

**Comment by JP58** [comment]
No, the album attachment is "img-fluid" so it follows the window size, it's smaller than the other two. :-)

**Comment by JP58** [comment]
Are you sure all the changed files for Beta2 are in the YAFNET-master.zip file? 
I have downloaded & compiled it twice today and still get the old layout and image css markup...

**Comment by w8tcha** [comment]
okay i commited the changes the .img-fluid is not needed when .img-posted is used

**Comment by JP58** [comment]
Finally I get the same img tag classes  as the code changes imply...  :-) 
Now, how can we get the img presentation in posts to honor the settings in the admin panel? 

![image](https://user-images.githubusercontent.com/5246746/63536203-66210000-c513-11e9-915d-ba08351e6d95.png)

**Comment by w8tcha** [comment]
That setting does not yet exist! Image thumbnail size will be added in beta 2

**Comment by w8tcha** [comment]
The thumbnail max width &height can now be set via the host settings
