### ISSUE TITLE
2.3.0 - Default avatar (.svg) is huge, does not adhere to avatar size restrictions. 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#460]
![image](https://user-images.githubusercontent.com/5246746/63535162-19d4c080-c511-11e9-9666-94c4b1ff3b4a.png)

![image](https://user-images.githubusercontent.com/5246746/63535331-7afc9400-c511-11e9-925f-eb175ad3293d.png)

**Comment by w8tcha** [comment]
I changed the size to 50x50. until i find a solution to apply the host settings directly to the image
