### ISSUE TITLE
2.3.0 Beta 2 - Images in posts part 5, security issue in "last 10 posts". 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#461]
Seems like there is some security/access flaw in the code regarding attached images when looking at "last 10 posts" by a member... Album images & linked images show ok... This has worked fine earlier, and is not an upload folder read access issue.  

Message in topic: 
![image](https://user-images.githubusercontent.com/5246746/63538126-86eb5480-c517-11e9-899b-a6bb73ead3d3.png)

Message in "Last 10 message":
![image](https://user-images.githubusercontent.com/5246746/63538425-2b6d9680-c518-11e9-88f5-957700e22d45.png)

**Comment by w8tcha** [comment]
Its one of the limits of the attachments. This also happens on the search results. Attachments will now only show as info. Because there is no way to retrieve the user permission for that posting

**Comment by JP58** [comment]
The attachments reside in the upload folder as well as the album images... Shows ok in posts, but not in "Show last 10" and you also say in search... I thought restrictions were on forums/topics/posts only, and not post content...  Has not been a problem earlier in pre-2.3.0...

**Comment by w8tcha** [comment]
It was never correctly implemented before. It is a security issue. Attachments should be only shown when the user has download access. inside posts this is not a problem But inside the the profile page it wont work. The preview shows now simply the icon with the attachment name!
