### ISSUE TITLE
2.3.0 Beta 2 - image resizing settings in host admin section. 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#462]
There has an image size setting since long in pre-2.3.0.

With the latest changes, it seems like those settings are not read, but it seems like a new setting pair has been introduced...  In the host settings dialog, you can now see 2 pairs of settings, and that's a bit confusing. 

In the attached image, you can see an "unlabeled" image settings pair, and the old dialog settings as well. The forum responds to the "unlabeled" settings, but not to the "old" settings  

![image](https://user-images.githubusercontent.com/5246746/63708895-e73f0680-c835-11e9-86ca-260e03ac58c6.png)

**Comment by JP58** [comment]
Settings seem to be like the master branch english.xml dictates...  Have restarted server, restarted app, cleared caches in server & browser.  

![image](https://user-images.githubusercontent.com/5246746/63710916-9251bf00-c83a-11e9-9e76-712c6d153f5d.png)

**Comment by w8tcha** [comment]
I Renner you are using a custom language file. Did you updated that file ?

**Comment by JP58** [comment]
No I use a clean 2.3.0 with no modifications for testing... Could be a cache issue regarding the labels after all since it looks like this now. 

But the "old" resize setting, what does it affect? - if anything? 

![image](https://user-images.githubusercontent.com/5246746/63712887-e1015800-c83e-11e9-81e7-4080bd54a747.png)

**Comment by w8tcha** [comment]
What you mean? The new setting allows to set the dimensions of the thumbnails. Before it was not changeable.

**Comment by JP58** [comment]
In CSS it was possible with some tweaking, but I mean the image resize settings - not this new feature.

**Comment by w8tcha** [comment]
The other image resize setting resizes the images on upload. The would prevent huge image files fill up the server.
