### ISSUE TITLE
2.3 RC - Bootstrap navbar search box not resizing well on medium size screens

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#469]
This is purely cosmetics of course, but if you if you have a medium size screen - lets say 1180 - 1330 px wide as on older laptops - the search box looks a bit messy and expands menu height. On smaller screens you get the "hamburger menu" as you should, but there is a "grey area" between the full/large window screen and < 1024 px screens where the Search box looks awful if you eg have a rather long "navbar-brand" item...   Just an observation, and only "cosmetic" - but could be annoying to some forum visitors...    

Not a critical issue, just an observation. 

Larger - all ok
![image](https://user-images.githubusercontent.com/5246746/65710762-eba84a80-e093-11e9-9da3-3f2a8ef6a9c1.png)

Around 1300 px
![image](https://user-images.githubusercontent.com/5246746/65710841-0ed2fa00-e094-11e9-8583-201494b05751.png)

Around 1150 px
![image](https://user-images.githubusercontent.com/5246746/65710894-24e0ba80-e094-11e9-99cf-415fb24efa8a.png)

Around 1024 px, just above
![image](https://user-images.githubusercontent.com/5246746/65711154-99b3f480-e094-11e9-8c81-6d3e06c658fc.png)

Less than 1024 - all ok
![image](https://user-images.githubusercontent.com/5246746/65711326-f1526000-e094-11e9-9f0e-84ea1dee7adc.png)

**Comment by w8tcha** [comment]
Well technically this would only happen for admins and host users. not for regular member

**Comment by JP58** [comment]
Yeah, well since the 3 extra menu items are only visible to admins who can take some "discomfort" - it's really a non-issue for the general users as you say...  :-) 

Sorry about it, thanks for pointing it out -  closing it... :-)
