### ISSUE TITLE
2.3 RC - Runtime error on admin page

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#470]
Admin -> Settings -> Board Settings throws a runtime I/O exception, so it's a bit hard to work with it...  

![image](https://user-images.githubusercontent.com/5246746/65793993-773edb80-e167-11e9-97d3-2f2bdc98cc4a.png)

**Comment by w8tcha** [comment]
As quick fix simply add the empty folder logos to the images folder
