### ISSUE TITLE
2.3 RC - Admin message edit history is a bit unfinished... 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#472]
Some issues with the Admin message edit history page... 

1 -  "Edited by" not updated with editor's IP, seems to keep OP IP... 

2 - Message edit comparison table does not fit into the width of card space. 

3 - Checked radio buttons on the same row not exclusive in selection, both can be checked...  

![image](https://user-images.githubusercontent.com/5246746/65900711-e4947b80-e3b6-11e9-8182-1b0751b66644.png)

**Comment by w8tcha** [comment]
I made some changes to the layout, and also resolved the issue with the IP Address
