### ISSUE TITLE
2.3 RC - Latest source changes do not build ok. 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#473]
Downloaded the latest zip today but it does not want to build well... 

It's trying to downgrade NuGet packages and also some code errors where Yaf.Web.Controls is not referenced in the source code even if it's a referenced namespace in the config (something with BBcode routines missing a reference).  Checked web.config against recommended web.config but could not spot any immediate alarming differences... 

Gave up after trying to fix it with using statements, and restored the source from about a week ago, so I can continue with some issue hunting...

**Comment by AlbertoP57** [comment]
> 
> Downloaded the latest zip today but it does not want to build well...
> 
Yes me too. I restarted to work on YAF again but its not working anymore (: 
I restarted with a clean fork.

> It's trying to downgrade NuGet packages 

Tools -> NuGet Package Manager -> Manage NuGet Package for solution
Select Updates
Above the list click on the checkbox "Select all packages"
Click Update
A modal window appears click OK

> and also some code errors where Yaf.Web.Controls is not referenced in the source code even if it's a referenced namespace in the config (something with BBcode routines missing a reference). Checked web.config against recommended web.config but could not spot any immediate alarming differences...
> 

`Error	CS0535	'YafBBCode' does not implement interface member 'IBBCode.FormatMessageWithCustomBBCode(string, MessageFlags, int?, int?)'	\yafsrc\YAF.Core\BBCode\YafBBCode.cs	49
Error	CS0535	'YafSearch' does not implement interface member 'ISearch.AddSearchIndex(IEnumerable<SearchMessage>)'	\yafsrc\YAF.Core\Services\YafSearch.cs	59	Active
Error	CS0535	'YafSearch' does not implement interface member 'ISearch.AddSearchIndexItem(SearchMessage)'		\yafsrc\YAF.Core\Services\YafSearch.cs	59	Active
Error	CS0535	'YafSearch' does not implement interface member 'ISearch.UpdateSearchIndexItem(SearchMessage)'	\yafsrc\YAF.Core\Services\YafSearch.cs	59	Active`

I will try to discover what happened.

**Comment by AlbertoP57** [comment]
Maybe the repository's sync is not update.

I made these edits:

\yafsrc\YAF.Configuration\YAF.Configuration.csproj
`<PackageReference Include="Microsoft.CSharp" Version="4.6.0" />`

\yafsrc\YAF.Configuration\YAF.Core.csproj
```
<PackageReference Include="Microsoft.CSharp" Version="4.6.0" />
<PackageReference Include="System.ComponentModel.Composition" Version="4.6.0" /> 
```

\yafsrc\YAF.Core\BBCode\YAFBBCode.cs
added this simple placeholder function in #region Methods
```
        public string FormatMessageWithCustomBBCode([NotNull] string message, [NotNull] Types.Flags.MessageFlags flags, int? displayUserId, int? messageId)
        { return message;}
```

\yafsrc\YAF.Types\Interfaces\ISearch.cs
add & rem 
```
        /// <summary>
        /// Adds or updates the search index
        /// </summary>
        /// <param name="messageList">The message list.</param>
        void AddUpdateSearchIndex(IEnumerable<SearchMessage> messageList);

        /// <summary>
        /// Adds or updates the search index
        /// </summary>
        /// <param name="message">The message.</param>
        void AddUpdateSearchIndex(SearchMessage message);

        /// <summary>
        /// Adds the search index
        /// </summary>
        /// <param name="messageList">The message list.</param>
        //void AddSearchIndex(IEnumerable<SearchMessage> messageList);

        //void AddSearchIndexItem(SearchMessage message);

        //void UpdateSearchIndexItem(SearchMessage message);
```
To the using section of these modules: 
\yafsrc\YAF.Web\Modules\BBCode\AlbumImage.cs
\yafsrc\YAF.Web\Modules\BBCode\Attach.cs
\yafsrc\YAF.Web\Modules\BBCode\ExampleBBCodeModule.cs
\yafsrc\YAF.Web\Modules\BBCode\GroupHide.cs
\yafsrc\YAF.Web\Modules\BBCode\HideBBCodeModule.cs
\yafsrc\YAF.Web\Modules\BBCode\HideReplyModule.cs
\yafsrc\YAF.Web\Modules\BBCode\HideReplyThanksModule.cs
\yafsrc\YAF.Web\Modules\BBCode\SpoilerBBCodeModule.cs

added:
`using YAF.Web.Controls; `

even better it could be delete:
`using YAF.Core.BBCode;`

Then I updated to latest version Newtonsoft.Json in Yaf.core

Now it compiles but when I try to run it, it raises this error:
Could not load file or assembly 'YAF.Controls' or one of its dependencies.

YAF.Controls seems not to exists anymore? 
Better to wait for a cleaner repository?

**Comment by Zero2Cool** [comment]
Yeah, the little X means the last commit didn't build.  
![image](https://user-images.githubusercontent.com/5612416/65965843-e137d900-e424-11e9-8400-87b8035ae79a.png)

**Comment by w8tcha** [comment]
Sorry i merged the wrong Branch. Issue will be fixed on the weekend!
