### ISSUE TITLE
2.3 RC - Just a question regarding announced feature... 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#474]
I just wonder...

One of the features announced is the "mark as answer" for a good and helpful post. 

I must be blind, but I haven't seen any simple admin option to do that for a post - at least not so far...

**Comment by w8tcha** [comment]
Sorry but at the moment you can't disable that feature.

**Comment by JP58** [comment]
What I mean is - I cant see any "mark as answer" on posts...  So I wonder how to mark a post as answer...   :-)

**Comment by w8tcha** [comment]
<img width="843" alt="markasanswer" src="https://user-images.githubusercontent.com/722575/65965897-a4d59e80-e45f-11e9-8627-51c792b63ea2.PNG">

The topic starter find that option in the footer of all the post replies to his initial post in a topic

**Comment by JP58** [comment]
Ahaaa...   :-) 

Ok, maybe admins should be able to see that option too and be able to mark it? 
I mean, sometimes there are "heated discussions" about what is a correct answer and the admin has to lock topics (in pre-2.3) when the correct answer has been given and others still argue about the right answer to a question...    :-/

**Comment by w8tcha** [comment]
No I disagree. Only the person who ask the question can decide what is the answer or not. Not any mod or admin

**Comment by Zero2Cool** [comment]
> No I disagree. Only the person who ask the question can decide what is the answer or not. Not any mod or admin

Agreed, good point.

**Comment by JP58** [comment]
Good point, so I agree to disagree for now...  :-D

Will see if I can do a kind of "Q&A admin page" outside the forum so answers in older topics (ever since 2001) also can be marked if there is a correct answer... :-)
