### ISSUE TITLE
2.3 RC2 - GoTo last post in topic seems to be broken.

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#475]
Go to last post in topic & go to last unread (if last post) seems to be broken. 

If you go to "last unread" in a topic where you haven't read them all, it works. 
Last post page seems to fail if attachments or album images are present. 

![image](https://user-images.githubusercontent.com/5246746/66226214-921ace00-e6da-11e9-8bf1-8a533d4a62de.png)

**Comment by JP58** [comment]
Seems like page jumps (not to last page) also suffer from this... 
![image](https://user-images.githubusercontent.com/5246746/66230686-f9d61680-e6e4-11e9-96c7-31795b5e460a.png)

Must have something to do with the removed BBcode module - all references not updated in code, maybe...

**Comment by w8tcha** [comment]
Can you reproduce the issue in the Support Forum? I cannot reproduce this issue. Did you compile the latest commit?

**Comment by JP58** [comment]
Yes, compiled the latest commit-  but source copied without cleaning up removed files...  
I will try a full clean install of the latest commit. Getting 500-errors from start when trying the test site today.

**Comment by JP58** [comment]
Still having problems with 500 errors at startup with the new code & 404:s when I reverted back to the code from 2 weeks ago. Obviously = have some local problem not related to YAF at the moment, will come back later regarding YAF issues.

**Comment by w8tcha** [comment]
You need to make sure that the moved or deleted cs files are really deleted. All Projects have been converted to the Vs 2017 format. All cs files inside the project folder are automatically compiled.

**Comment by JP58** [comment]
I've solved my local problems, thanks for your help.  In short - always compile the zip with release option, make sure your database (yaf_registry settings table) points to existing things and the best of it all - you always learn new details about YAF code and "how it works"... :-) 

Closing this, since todays source code does not produce those exceptions.
