### ISSUE TITLE
2.3 RC2 - Comment & suggestion - The Blueimpgallery needs some love & care

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#476]
The great things with the pre-2.3 click on image in post presentation were: 

1 - Image scaled up proportionally to the screen size or its own size if smaller. 
2 - Images carousels were just doing the images in one post. 

With the Blueimpgallery: 

1 - A small  white popup with a small image, no screen size adjustment at all... 
2 - If more than one pic in a post, prev/next takes you through all images in all posts in a topic... 

Design suggestion, get rid of the space-wasting header & footer and white background... It's just awful as it is right now and not very useful... And why the next/prev buttons in a footer and not the usual left/right arrow  at the sides of  slide? ???  Sorry if I sound like a grumpy old man who thinks "it used to be better in the good old times", but I don't think it's good enough for a release version... :-)

**Comment by w8tcha** [comment]
Well atleast the issue with the carousel should only show the images for the post is already fixed.

**Comment by w8tcha** [comment]
I made some changes to the gallery. Bootstrap Modal is gone.

**Comment by JP58** [comment]
Good start, already looks a little bit better. :-)

**Comment by JP58** [comment]
Downloaded RC3 2019-10-15 and the gallery layout look great!
