### ISSUE TITLE
Post approval by moderators as member based moderation. 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#477]
Since I today learnt about a nice FB feature - To turn on "Moderator Post Approval" for a limited time (fixed 30 days on FB) for a member that misbehaves, uses foul language, is aggressive towards others and so on... Could something similar be done in YAF - ie member-based posting moderation? 

I think it would be a great feature to have also in the forum. Today we can set topics/forums as moderated but that hits everyone who wishes to post in that particular topic/forum... We can also suspend members so they cannot post at all for a certain time and not read the forum more than anonymous users can do (if they delete their cookie). 

These are fine ways of doing it traditionally, but something in between these rather blunt methods could maybe be interesting - to set a member in "moderated status" for a time period just like we have the suspension period... Then the member is not locked out completely and can visit & read "member only topics" freely but not post garbage answers at will...

At least in my forum a few members from time to time need a kind of reminder to "shape up", and a member post moderation would be a great tool to remind them about it without suspending/banning...  

Just an idea that I think would be worth realizing to improve admin/moderator flexibility and also a forum feature that would be appreciated...

Anyone else who thinks it's a good idea?

**Comment by JP58** [comment]
And of course also have them pop up in the wonderfully refurbished moderation page as a box/member as well as indicated in the "Moderate" menu badge that moderation is needed ...   

![image](https://user-images.githubusercontent.com/5246746/66506756-37181b00-eace-11e9-93fc-317ea5d81075.png)

**Comment by w8tcha** [comment]
Good idea, could be easily added. But too late for 2.30. maybe for 3.00 or 2.31

**Comment by JP58** [comment]
2.3.1 has my vote...  :-D
