### ISSUE TITLE
2.3 RC3 - Visual impressions of forum start page...  Cosmetics... 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#478]
Just 2 remarks regarding start page layout.... 

1 - Same font size in forum list of topics and Active Discussions list (and maybe smaller italics inside the parenthesis as the description is in the forum list) would be good. The best would be if the topic subject and description had a similar layout in the "ADL" as the forum list of topics - would make the looks more consistent and appealing to the eye for the visitor.

2 - "GoTo" buttons would look better if they were aligned at the same "col-" alignment as the forum list buttons in the Active Discussion list rows...  In short, same "col-" layout for both lists if possible. OP & last post user as in the forum list would be the best....         

I think it would look more "professional" out of the box, but that's me...  :-) 

![image](https://user-images.githubusercontent.com/5246746/66948398-e74ccd00-f054-11e9-9e51-17727c3f8aed.png)

**Comment by w8tcha** [comment]
1. The font sizes are all the same

**Comment by w8tcha** [comment]
<img width="1405" alt="goto" src="https://user-images.githubusercontent.com/722575/67156506-9a504b80-f31f-11e9-906b-e44bf66f9963.PNG">

the buttons on the right looks to ugly on the right. and also on mobile devices. Its better to leave the buttons right next to the topic name

**Comment by Zero2Cool** [comment]
I like the buttons on the right because it offers a consistent expected UX. That said, I do not think ti is the solution to the "problem". Perhaps removing the text and using an icon only? The buttons attract the eyes too much for its purpose, I feel. Thoughts?

**Comment by JP58** [comment]
I beg to disagree regarding font sizes in the lists - they do not look the same (2.3 RC4). :-) 
![image](https://user-images.githubusercontent.com/5246746/67638702-f7cc3580-f8e7-11e9-9bc1-1f5ee1224867.png)

**Comment by Zero2Cool** [comment]
For good UX, things that are static should be aligned. So if the big buttons for to go last post and go to first unread, those should be prefixing the title (which can be short or long).

**Comment by JP58** [comment]
If so, maybe no big buttons - just the icons as in earlier versions (with hover explanation) but at the left edge...  Maybe even vertical alignment of the "goto icons" at the beginning since we have 2 lines and move the "new posts" towards the end of the title...  
Just a crazy thought...

**Comment by w8tcha** [comment]
![active](https://user-images.githubusercontent.com/722575/67661460-934dbc80-f961-11e9-97ee-04442d020613.png)

maybe it would be better to use the space better and use colums here

**Comment by Zero2Cool** [comment]
That is a good idea. How would it look without Active Discussions?  Would the  Users' Cards go horizontal?

**Comment by w8tcha** [comment]
Yes

**Comment by w8tcha** [comment]
I committed the changes

**Comment by Zero2Cool** [comment]
> Yes

If you disable Active Discussions, the Cards do not go horizontal. 
![image](https://user-images.githubusercontent.com/5612416/69498395-48b25800-0ead-11ea-9c89-0161fe876ef3.png)

**Comment by w8tcha** [comment]
Fixed!
