### ISSUE TITLE
Error in YAF.Core.Services.YafSendNotification

### ISSUE THREAD

**Issue by ChristianWellnitz** [YAFNET/YAFNET#479]
There are several errors like this in the file YafSendNotification.cs

`var subject = this.Get<ILocalization>().GetTextFormatted(
                "NOTIFICATION_ROLE_ASSIGNMENT_SUBJECT",
                this.BoardSettings.Name);` has error should be 

 ` var subject = this.Get<ILocalization>().GetTextFormatted(
                "NOTIFICATION_ROLE_ASSIGNMENT_SUBJECT",
                this.BoardSettings.Language);`

**Comment by w8tcha** [comment]
What error are you getting and with which version?

**Comment by ChristianWellnitz** [comment]
Hi 
I'm on Rc5
I'm getting an unhandled exception language file not found.
I have described obow how i fixed it . What else do you need to know ?

**Comment by w8tcha** [comment]
Then upgrade to the final version and post the full error message. The solution you posted is wrong!

**Comment by w8tcha** [comment]
`var subject = this.Get<ILocalization>().GetTextFormatted( "NOTIFICATION_ROLE_ASSIGNMENT_SUBJECT", this.BoardSettings.Language);`

this would result in the string = "english.xml Forum Account Update"

**Comment by ChristianWellnitz** [comment]
That is corect but right now in your cod it is set to 
`var subject = this.Get<ILocalization>().GetTextFormatted(
                "NOTIFICATION_ON_NEW_FACEBOOK_USER_SUBJECT",
                this.BoardSettings.Name);`

**Comment by w8tcha** [comment]
Sorry but this wouldnt make any sense. Please upgrade to the final version and post the full error message.

**Comment by ChristianWellnitz** [comment]
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--


[ApplicationException: Invalid language file C:\Sites\Radioarkivet\languages\Radioarkivet]
   YAF.Core.Services.Localization.Localizer.LoadFile() +490
   YAF.Core.Services.Localization.Localizer..ctor(String fileName) +76
   YAF.Core.Services.Localization.YafLocalization.LoadTranslation(String fileName) +518
   YAF.Core.Services.Localization.YafLocalization.GetText(String page, String tag, String languageFile) +69
   YAF.Core.Services.YafSendNotification.SendRegistrationNotificationEmail(MembershipUser user, Int32 userId) +271
   YAF.Pages.register.CreateUserWizard1_CreatedUser(Object sender, EventArgs e) +950
   System.Web.UI.WebControls.CreateUserWizard.OnCreatedUser(EventArgs e) +137
   System.Web.UI.WebControls.CreateUserWizard.AttemptCreateUser() +469
   System.Web.UI.WebControls.CreateUserWizard.OnNextButtonClick(WizardNavigationEventArgs e) +128
   System.Web.UI.WebControls.Wizard.OnBubbleEvent(Object source, EventArgs e) +491
   System.Web.UI.Control.RaiseBubbleEvent(Object source, EventArgs args) +50
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +5028

**Comment by ChristianWellnitz** [comment]
Error is stil the same i your code ...

**Comment by ChristianWellnitz** [comment]
Pleas look in the file
YAFNET/yafsrc/YAF.Core/Services/YafSendNotification.cs
Line 454
Line 532
Line 560
Line 646
Line 685

**Comment by w8tcha** [comment]
As expected this is a different error. will be fixed in 2.30.01!
