### ISSUE TITLE
PMList.ascx unmattched div

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#483]
Why is this needed? I removed it and then it broke the alignment of the columns. Is there a opening div in the code behind? 

![image](https://user-images.githubusercontent.com/5612416/69483581-b6e41580-0dee-11ea-9d9e-fea4bc108534.png)

**Comment by Zero2Cool** [comment]
Same thing with ViewThanks.ascx

**Comment by w8tcha** [comment]
Please don't remove it. the div is closed in the parent Control (page) cp_pm.ascx
