### ISSUE TITLE
Topic Status removed?

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#485]
I'm on the latest version and can't see where to set a Topic Status. Did that get removed?

Here's a screen shot of the v2.2.3
![image](https://user-images.githubusercontent.com/5612416/69503755-c6448b00-0ee2-11ea-8dd4-ac352cd0a788.png)

v2.3.0
![image](https://user-images.githubusercontent.com/5612416/69503782-0572dc00-0ee3-11ea-8b67-4320ed082441.png)

**Comment by w8tcha** [comment]
Yes that feature was removed. I build it first to create and question and answer option. But the new mark as answer feature is more logic.

Also the next version will have a tags which is more flexible then topic statuses. But it was to complex to a add it in version 2.30

**Comment by Zero2Cool** [comment]
That makes sense.  I was using that to populate the "blog" portion of my site.  When tags come, I can just use that. Tags are better anyway!
