### ISSUE TITLE
Replace noavatar.svg

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#486]
I'm struggling to find where we can change the noavatar.svg.    It seems we are forced to have a file named 'noavatar.svg'. When this was a GIF, not a big deal because creating a GIF is pretty standard with image editors. SVG as I've found in the last hour are not.

**Comment by w8tcha** [comment]
The problem is that the old gif format is not really compatible for responsive layouts l. That's why I have replaced all with svg files.

If needed I could make a setting for this.

Did you try converters like...
https://convertio.co/gif-svg/

**Comment by Zero2Cool** [comment]
Yep, I tried that website. I also tried Photoshop and Paint.NET. Spent a lot of time on it.  

GIF definitely is not a solution.  SVG I feel for avatar (the default avatar) which is not going from tiny to large could be a compressed PNG. 

No need for a setting as there are more important things. Now that I know it has to be a SVG, I will figure out how to create an SVG. Thanks!
