### ISSUE TITLE
Quote messages

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#487]
I think some tweaking to distinguish a Quoted message from the Author would be beneficial.

v2.3.0 Quote
![image](https://user-images.githubusercontent.com/5612416/69565250-2fc3a880-0f7a-11ea-972f-36af81c97c3c.png)

v2.2.3 Quote (well, I styled it a little bit, but that was a perk with 2.2.3 is we could style it without affecting everything else)
![image](https://user-images.githubusercontent.com/5612416/69565296-4cf87700-0f7a-11ea-87a3-3faf00d7ef25.png)

**Comment by w8tcha** [comment]
maybe using blockquotes and doing it more fancy

![quote](https://user-images.githubusercontent.com/722575/69908781-607b6600-13f0-11ea-9ea2-7bff9b70b66f.png)

**Comment by Zero2Cool** [comment]
Nice! That looks much better.
