### ISSUE TITLE
Multi-Quote : Column 'UserDisplayName' does not belong to table Table.

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#488]
How to reproduce. On the http://yetanotherforum.net/ website, check "Multi-Quote" and then click "Quote" on any other message. 

![image](https://user-images.githubusercontent.com/5612416/69565521-c001ed80-0f7a-11ea-8376-bdb8add33856.png)

**Comment by w8tcha** [comment]
fixed in 2.30.02!
