### ISSUE TITLE
Suggestion: DisplayPost Footer Design

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#489]
The footer of displaypost currently takes up a lot of space. 
![image](https://user-images.githubusercontent.com/5612416/69566230-423ee180-0f7c-11ea-8ba9-1b47b0efa6f9.png)

Maybe use buttons with icons and tool tips to free up horizontal space? I'm not sure what can be done. I just know it wastes space currently. It seems like a difficult problem to solve. 

**Ingo**, I think you did some really kick ass work here getting the HTML tables replaced with responsive design elements. Really impressive.

**Comment by Zero2Cool** [comment]
The modification to Thanks definitely will help.  Would the Report and Management Message and Quote/s be all on one line?

**Comment by w8tcha** [comment]
yes correct!
