### ISSUE TITLE
Duplicate ModuleId causing error 

### ISSUE THREAD

**Issue by grant007** [YAFNET/YAFNET#490]
I go to Host Settings - Editors and switch to CKEditor (HTML). Save. Create new Topic and get following error...

`[InvalidOperationException: Sequence contains more than one matching element]    System.Linq.Enumerable.SingleOrDefault(IEnumerable`1 source, Func`2 predicate) +341    YAF.Core.Helpers.ForumEditorHelper.GetCurrentForumEditor() +459    YAF.Pages.postmessage.OnInit(EventArgs e) +121    System.Web.UI.Control.InitRecursive(Control namingContainer) +166    System.Web.UI.Control.AddedControl(Control control, Int32 index) +214    YAF.Web.Controls.Forum.OnLoad(EventArgs e) +974    System.Web.UI.Control.LoadRecursive() +68    System.Web.UI.Control.LoadRecursive() +162    System.Web.UI.Control.LoadRecursive() +162    System.Web.UI.Control.LoadRecursive() +162    System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3785`

It appears that error is because two modules have same ModuleID = 5.

**Comment by w8tcha** [comment]
Thanks for the report! Issue will be fixed in 2.30.02
