### ISSUE TITLE
Suggestion: Thanks to Header?

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#491]
I've been trying to figure out how to reduce the space the footer consumes.  What do you think about having an indicator for how many users have thanked a post? Then when it's clicked it displays the users who have thanked for that useful post?

And then this could be displayed in the Header with a number and the thanks icon? 

What do you think? Good idea or "Kevin go back to the drawing board" lol

**Comment by w8tcha** [comment]
i'm implementing popovers

![quote](https://user-images.githubusercontent.com/722575/69909276-e8fe0480-13f8-11ea-9c68-d59648b672d1.png)

**Comment by Zero2Cool** [comment]
Sweet! Maybe a line break after each one to put them in a list of sorts?

**Comment by w8tcha** [comment]
sure

![thanks2](https://user-images.githubusercontent.com/722575/69909556-c4a42700-13fc-11ea-9435-c4b8c61eed70.png)

i thinks this will also resolve issue #489

**Comment by Zero2Cool** [comment]
That is awesome!  What happens when you get like 20 users thanked on a post?

**Comment by w8tcha** [comment]
then there will be scrolling!
