### ISSUE TITLE
send emails templates in html format

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#495]
Private Message email is nicely formatted. Sending an email Administration > Mail does not have any formatting. Maybe this is expected?

**Comment by w8tcha** [comment]
I guess it was never implemented. There are lots of emails that are send in text format.

Its already on my list for 2.31 to send all Mails with html format

**Comment by Zero2Cool** [comment]
I didn't know if it was intended or not. It's not a big deal or nothing. I was sending out an email to all the users that we've upgraded (folks like the new YAF!) and noticed it was plain text.
