### ISSUE TITLE
Error when saving YafBBCode Extension

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#496]
When navigating to Administration > YafBBCode Extensions > Edit YafBBCode Extensions and trying to save a BBCode  A potentially dangerous Request.Form value was detected from the client error gets thrown.

![image](https://user-images.githubusercontent.com/5612416/70560402-20358980-1b4e-11ea-917c-8d69b5ab4e47.png)

**Comment by w8tcha** [comment]
I can't reproduce the issue. Make sure that page validation is disabled for the application and master page. This should be already fixed in the sample application

**Comment by Zero2Cool** [comment]
Sorry, yes, I just verified this only happens in Sample Application.  I am not seeing the page validation being disabled on the master page in that repository, but I can figure this out.
