### ISSUE TITLE
Notification for Thanks does not go away if you click "No"

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#498]
After you've received a Thanks, you get a notification asking to visit the newest Thanked post. If you click "No", the Modal notification closes, however, it comes back every 15 or so seconds.   I experienced this while trying to type a post after clicking "No".  My thinking was when I click "No" that the indicator that I have X unread Thanks posts would be set to 0. 

Random thought here. Would it be good to have a list of posts in the Modal so the user can go the post they were thanked and view it? And also add a function to reset the unread counter to when the Modal closes? That way regardless if the user clicks Yes, No or one of the links the count is reset and they are not notified again?

**Comment by w8tcha** [comment]
Fixed in 2.30.03
