### ISSUE TITLE
Error On Add/Edit Role

### ISSUE THREAD

**Issue by jyehahaha** [YAFNET/YAFNET#499]
Please see below attachment. 

Thank You
![Error YAF](https://user-images.githubusercontent.com/18694454/70692007-6bd66780-1cf5-11ea-8473-60142edcab19.PNG)

**Comment by Zero2Cool** [comment]
I can confirm this as well.   If you go to Administration > Roles > Add/Edit Role and just click Save, the error gets thrown. 

Appears to be similar to the Forum saving error just fixed.
![image](https://user-images.githubusercontent.com/5612416/70716689-6a378000-1cb2-11ea-824b-5cb1f9b07e6c.png)

**Comment by w8tcha** [comment]
Fixed in 2.30.03
