### ISSUE TITLE
Error after edit the post in moderator mode

### ISSUE THREAD

**Issue by jyehahaha** [YAFNET/YAFNET#501]
Hi,

I found that there is an error after i edit the post that I posting previoulsy. 
The post is in moderator mode.
The error come out after I click on continue.

![Edit post error](https://user-images.githubusercontent.com/18694454/70959217-90945b80-20b6-11ea-9d2b-53dfc2a6fc50.PNG)

Thanks

**Comment by w8tcha** [comment]
Can you describe the steps to reproduce the issue?

**Comment by jyehahaha** [comment]
My post are in pre-moderator mode. When I ammend/edit my post and I click
on continue the error comes up but the edit post is edited successfully. I
can see on moderator tab that i need to approve the post.

**Comment by w8tcha** [comment]
Thanks issue will be fixed in 2.30.04

**Comment by jyehahaha** [comment]
Thanks Ingo.

I try to login/register to your forum, unfortunately, i am not able to
access it. Could I know why?

And I want to know how to create new page in yaf?

**Comment by w8tcha** [comment]
What error are you getting?

**Comment by jyehahaha** [comment]
You tried to enter an area where you didn't have access. Then i tried to
login but login failed and does not show any error message.

**Comment by w8tcha** [comment]
Sorry issue should be fixed now!
