### ISSUE TITLE
Question: How does the Thanks popover work?

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#502]
I'm experiencing some issue with the who thanked a user. The popover isn't working and I'm only getting the bland yellow tooltip message stating that someone has thanked the user for that post. I'm assuming I have something wrong in my SampleApplication, but thought I'd ask how it works before I start digging around too much.

**Comment by w8tcha** [comment]
Did you modify the displaypost.ascx?

**Comment by Zero2Cool** [comment]
No, I do not think so. I'll copy the one from your 'master' branch to be sure and check again.
https://github.com/Zero2Cool/YAFNET/blob/custom/20191130-PackersHome/yafsrc/YetAnotherForum.NET/controls/DisplayPost.ascx

**Comment by w8tcha** [comment]
Did you clear the browser cache? The popover is initialized in the js files

**Comment by Zero2Cool** [comment]
> Did you clear the browser cache? The popover is initialized in the js files

Yes. I've done this on my phone and web browser and in the application and browser. 

Maybe a separate issue, but I noticed on the YAF support site the popovers do not popup on mobile device (Galaxy S10)

**Comment by w8tcha** [comment]
Strange Atleast on mz iphone it works.

**Comment by Zero2Cool** [comment]
This is what I see after touching the info button on topic list. 

![Screenshot_20191217-193450_Chrome Beta](https://user-images.githubusercontent.com/5612416/71048269-69647b00-2104-11ea-8a1f-806e06b66b4d.jpg)

**Comment by w8tcha** [comment]
Ah sorry I thought this was about the thanks popover. The topics are not updated correctly you can ignore that.

**Comment by w8tcha** [comment]
Is that still an issue? on the support site it should work now!

**Comment by Zero2Cool** [comment]
What was the fix? I can't get the Thanks popover to work outside of YAF stand alone.  Meaning, YAF alone it works, but inside my sample application it just displays a toolitp

**Comment by w8tcha** [comment]
is that site online? check the source if the javascript is loaded

**Comment by Zero2Cool** [comment]
Yes. www.packershome.com ... I have to update YAF though.  I have your latest changes, but have to re-make my layout changes.

**Comment by w8tcha** [comment]
![6544A432-C295-48E4-87F4-C3028B3A19B9](https://user-images.githubusercontent.com/722575/71325580-1832fd80-24ef-11ea-9d14-da655be19a19.jpeg)

At least the old code seems to be working

**Comment by Zero2Cool** [comment]
Yep, that works fine. The Thanks popover does not.  Thanks popover works when I run just YAF, but when I run YAF (same exact code) in my Sample App, it does nothing but show the stock .NET tooltip.

**Comment by w8tcha** [comment]
Well you should update all files! the code, that initializes the popover is missing from the jquery.ForumExtensions.js?v=2

**Comment by w8tcha** [comment]
I see you upgraded the forum, but not the java script file

**Comment by Zero2Cool** [comment]
When I merged the latest YAF changes into my branch, I uploaded every single file. You said I didn't update the javascript file so I downloaded the source from GitHub, and copied the /Scripts folder to my /forum/scripts/ folder and now the Thanks list works as expected.
