### ISSUE TITLE
2.30.3 Edit forum error - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by JamalAPI** [YAFNET/YAFNET#503]
URL ..../admin/editforum

Object reference not set to an instance of an object.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 

[NullReferenceException: Object reference not set to an instance of an object.]
   YAF.Pages.Admin.<>c__DisplayClass59_0.<SaveClick>b__0(RepeaterItem item) +33
   System.Collections.Generic.List`1.ForEach(Action`1 action) +85
   YAF.Types.Extensions.EnumerableExtensions.ForEach(IEnumerable`1 list, Action`1 action) +133
   YAF.Pages.Admin.editforum.SaveClick(Object sender, EventArgs e) +3215
   YAF.Web.Controls.ThemeButton.OnClick(EventArgs e) +95
   YAF.Web.Controls.ThemeButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument) +77
   System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument) +15
   System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData) +9883878
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1639

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3429.0

**Comment by w8tcha** [comment]
Thanks issue is corrtly fixed in 2.30.4
