### ISSUE TITLE
2.30.3 admin/deleteforum error - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by JamalAPI** [YAFNET/YAFNET#504]
[NullReferenceException: Object reference not set to an instance of an object.]
   YAF.Pages.Admin.deleteforum.Page_Load(Object sender, EventArgs e) +173
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +51
   System.EventHandler.Invoke(Object sender, EventArgs e) +0
   System.Web.UI.Control.OnLoad(EventArgs e) +95
   System.Web.UI.Control.LoadRecursive() +59
   System.Web.UI.Control.LoadRecursive() +131
   System.Web.UI.Control.LoadRecursive() +131
   System.Web.UI.Control.LoadRecursive() +131
   System.Web.UI.Control.LoadRecursive() +131
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +678

**Comment by w8tcha** [comment]
I can't reproduce the issue. Did you click on delete on the admin/forums page?

**Comment by JamalAPI** [comment]
Yes, but I just tried it now and works fine.  I suspect a timing issue and the forum was deleted already and a null value was encountered. Will keep an eye on it if happens again.

**Comment by w8tcha** [comment]
No problem i added a few checks (2.30.04) to prevent this from happening.
