### ISSUE TITLE
2.30.3 - UserName is always displaying instead of Display Name

### ISSUE THREAD

**Issue by JamalAPI** [YAFNET/YAFNET#505]
In Host Settings, Features I enabled Enable User Name and Allow Display Name Modification. I also updated the Display Name in my profile, however, the UserName is still on the forum messages; I updated "What name do want displayed to others?" and I verified it, but the UserName is still  displayed.

**Comment by w8tcha** [comment]
Did you also enable display name feature? There are two settings in the host settings

**Comment by JamalAPI** [comment]
Yes, I did. Please see screenshot
![2019-12-23_14-14-59](https://user-images.githubusercontent.com/35046731/71376467-9941d180-258f-11ea-8542-33c21e00b54f.jpg)

**Comment by w8tcha** [comment]
And in which places it shows the user name instead of the display name ?

**Comment by JamalAPI** [comment]
The issue seems to be affecting the administrator account only which was created when the forum was created. This forum is new and the 2 checkboxes were enabled as shown in the previous screenshot after the forum was created. I add a new user and the display name is showing correctly, however, the administrator account is still showing the UserID even though there is a display name.  The User Name is showing when viewing the main forums and when going into Topics. 

I changed the new user to administrator and it is showing correctly, but the old administrator is still stuck on the User Name.

**Comment by w8tcha** [comment]
But the display name was actually saved? Technically there is no difference between accounts. But the names are a cached. You could try to restart the app and/ or clear the caches via the host settings

**Comment by JamalAPI** [comment]
Unfortunately, clearing the cache and restarting the app, and also stopping the app and restarting azure, did not solve the issue. 
The display name is saved already.  Please screenshot below.
![2019-12-24_10-58-53](https://user-images.githubusercontent.com/35046731/71419276-a4067000-263c-11ea-8636-101445c5d17d.jpg)

Also, see below a screenshot of the **yaf_Topic** table, as you can see the UserName is NULL in some cases **which indicates a failure on the Save operation when a topic is posted**. Same goes for the LastUserName.

![2019-12-24_11-12-47](https://user-images.githubusercontent.com/35046731/71419685-aec20480-263e-11ea-8587-9e3def400a55.jpg)

**Comment by w8tcha** [comment]
Yes you are probably right. I committed the changes. 

Please try the latest pre-release
https://github.com/YAFNET/YAFNET/releases/tag/v2.3.0.4-beta.1

**Comment by JamalAPI** [comment]
Thanks for the update. It seems to have fixed the issue. However, looking at the yaf_Topics again, the UserName and LastUserNames columns are still saved as NULL except for Guest.

**Comment by w8tcha** [comment]
Correct. the columns are no longer used
