### ISSUE TITLE
Previously clicked last post by shows invalid date.

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#506]
Previously clicked last post by shows invalid date.

![image](https://user-images.githubusercontent.com/5612416/71367854-da27ef00-256b-11ea-8ba0-850cf1e2dc65.png)

![image](https://user-images.githubusercontent.com/5612416/71367868-e449ed80-256b-11ea-84fe-0dd0908568e9.png)

**Comment by w8tcha** [comment]
I can't reproduce it. Can you describe the steps to reproduce the issue. also on which page`?

**Comment by Zero2Cool** [comment]
I'm on Windows 10 Surface Book and using Chrome. 
![image](https://user-images.githubusercontent.com/5612416/71369255-c7afb480-256f-11ea-81fb-d4e7d5c40bc3.png)


On page http://yetanotherforum.net/forum/forum 
I click the Info icon, then click another info icon.
![image](https://user-images.githubusercontent.com/5612416/71369189-99ca7000-256f-11ea-9479-f0415278f790.png)


On page http://yetanotherforum.net/forum/topics/11-YAF-Announcements#!
I click the Info icon, then click another info icon.
![image](https://user-images.githubusercontent.com/5612416/71369219-ae0e6d00-256f-11ea-80a6-7b945fb45d83.png)

**Comment by w8tcha** [comment]
okay found it!
