### ISSUE TITLE
Design Suggestion:  Last Post By area

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#507]
Line 1: [new post icon] [title of topic link]
Line 2: [go to last post icon] [go to first unread icon] [relative time ago] by [username] 

Something like this?  
![image](https://user-images.githubusercontent.com/5612416/71369056-36d8d900-256f-11ea-9693-1f4a0f8faa4e.png)

Purpose of suggestion is the last post by area seems to put items the user would want to read and/or click in inconsistent locations. Sometimes it can be the end in one nice line, but other times it gets jumbled.
![image](https://user-images.githubusercontent.com/5612416/71369130-71427600-256f-11ea-937b-3aa7e514a755.png)

**Comment by w8tcha** [comment]
makes sense
