### ISSUE TITLE
Question: Disable Quote/Thank notification?

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#508]
I looked around and couldn't find a setting to turn off the notification that pops up a modal informing users a message was Thanked or Quoted.  It's a nice feature, but it's really aggressive. Even after you click No, or X, the modal pops up again when you click elsewhere on the forum.  I'm assuming I have some JavaScript screwing things up and instead of trying to chase that down, I'd rather just disable the feature.

**Comment by w8tcha** [comment]
As requested i added a setting to disable the Activity Stream Feature.

But i also fixed the issue where the notification was shown multiple times.

**Comment by Zero2Cool** [comment]
> As requested i added a setting to disable the Activity Stream Feature.
> 
> But i also fixed the issue where the notification was shown multiple times.

Does clicking No stop the Modal from coming up again and again? I'd click No and click on another area in forum and it woid come back.

**Comment by w8tcha** [comment]
Yes if you click no or yes it wont come back. It only shows the notification one time
