### ISSUE TITLE
Suggestion: Activity Stream to Notification icon

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#509]
Getting a lot of complaints about the activity stream modal and it not working as users expected. If you have multiple, it just brings you to the last one and therefore miss the others. 

The Activity Stream concept is really awesome, but maybe it could be altered to serve users better?  

Removed my idea layout because the Github concept is better. 

Edit: I tried to find an example and well, the notification system from GitHub is basically what I outlined. https://github.com/notifications
![image](https://user-images.githubusercontent.com/5612416/71551495-a1927600-29ae-11ea-9fc3-066d8159be85.png)

**Comment by w8tcha** [comment]
Yes i agree. i made some changes, Unead activity is now highlighted in the activity stream
