### ISSUE TITLE
The correlation name 'lastUser' is specified multiple times in a FROM clause.

### ISSUE THREAD

**Issue by JamalAPI** [YAFNET/YAFNET#511]
On new installation, same **inner join** is specified Twice! See line 4651 in 
FILE:
mssql/install/procedures.sql

inner join 
        [{databaseOwner}].[{objectQualifier}User] lastUser on lastUser.UserID = t.LastUserID
inner join 
        [{databaseOwner}].[{objectQualifier}User] lastUser on lastUser.UserID = t.LastUserID

[Exception: FILE:
mssql/install/procedures.sql

ERROR:
The correlation name 'lastUser' is specified multiple times in a FROM clause.

STATEMENT:
CREATE PROCEDURE [dbo].[yaf_topic_latest]
(
    @BoardID int,
    @NumPosts int,
    @PageUserID int,
    @StyledNicks bit = 0,
    @ShowNoCountPosts  bit = 0,
    @FindLastRead bit = 0
)
AS
BEGIN

    SELECT TOP(@NumPosts)
        t.LastPosted,
        t.ForumID,
        f.Name as Forum,
        t.Topic,
        t.Status,
        t.Styles,
        t.TopicID,
        t.TopicMovedID,
        t.UserID,
        UserName = IsNull(t.UserName,(select x.[Name] from [dbo].[yaf_User] x where x.UserID = t.UserID)),
        UserDisplayName = IsNull(t.UserDisplayName,(select x.[DisplayName] from [dbo].[yaf_User] x where x.UserID = t.UserID)),
        t.LastMessageID,
        t.LastMessageFlags,
        t.LastUserID,
        t.NumPosts,
		t.Views,
        t.Posted,
		LastMessage = (select m.Message from [dbo].[yaf_Message] m where m.MessageID = t.LastMessageID),
        LastUserName = lastUser.Name,
        LastUserDisplayName = lastUser.DisplayName,
        LastUserStyle = case(@StyledNicks)
            when 1 then  (select top 1 usr.[UserStyle] from [dbo].[yaf_User] usr  where usr.UserID = t.LastUserID)
            else ''	 end,
        LastForumAccess = case(@FindLastRead)
             when 1 then
               (SELECT top 1 LastAccessDate FROM [dbo].[yaf_ForumReadTracking] x WHERE x.ForumID=f.ForumID AND x.UserID = @PageUserID)
             else ''	 end,
        LastTopicAccess = case(@FindLastRead)
             when 1 then
               (SELECT top 1 LastAccessDate FROM [dbo].[yaf_TopicReadTracking] y WHERE y.TopicID=t.TopicID AND y.UserID = @PageUserID)
             else ''	 end

    FROM
        [dbo].[yaf_Topic] t
    INNER JOIN
        [dbo].[yaf_Forum] f ON t.ForumID = f.ForumID
    inner join 
        [dbo].[yaf_User] lastUser on lastUser.UserID = t.LastUserID
    inner join 
        [dbo].[yaf_User] lastUser on lastUser.UserID = t.LastUserID
    INNER JOIN
        [dbo].[yaf_Category] c ON c.CategoryID = f.CategoryID
    JOIN
        [dbo].[yaf_ActiveAccess] v   ON v.ForumID=f.ForumID
    WHERE
        c.BoardID = @BoardID
        AND t.TopicMovedID is NULL
        AND v.UserID=@PageUserID
        AND (CONVERT(int,v.ReadAccess) <> 0)
        AND t.IsDeleted != 1
        AND t.LastPosted IS NOT NULL
        AND
        f.Flags & 4 <> (CASE WHEN @ShowNoCountPosts > 0 THEN -1 ELSE 4 END)
    ORDER BY
        t.LastPosted DESC;
END]

**Comment by w8tcha** [comment]
Thanks, i updated the scripts and the download packages. Issue should be fixed!
