### ISSUE TITLE
YAF 2.30.04: SqlException - Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.

### ISSUE THREAD

**Issue by JamalAPI** [YAFNET/YAFNET#512]
Fresh new Forum installed. Upon completion, the following is reported.

[SqlException (0x80131904): Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.]    System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +2555926    System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +5959200    System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +285    System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) +4169    System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows) +240    System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more) +268    System.Data.SqlClient.SqlDataReader.Read() +34    System.Data.Common.DataAdapter.FillLoadDataRow(SchemaMapping mapping) +211    System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue) +197    System.Data.Common.DataAdapter.Fill(DataSet dataSet, String srcTable, IDataReader dataReader, Int32 startRecord, Int32 maxRecords) +410    System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior) +218    System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior) +136    System.Data.Common.DbDataAdapter.Fill(DataSet dataSet) +88    YAF.Types.Interfaces.Data.<>c__DisplayClass7_0.<GetDataset>b__0(IDbCommand c) +72    YAF.Core.Data.DbAccessBase.Execute(Func`2 execFunc, IDbCommand cmd, IDbTransaction dbTransaction) +185    YAF.Types.Interfaces.Data.IDbAccessExtensions.GetDataset(IDbAccess dbAccess, IDbCommand cmd, IDbTransaction dbTransaction) +139    YAF.Types.Interfaces.Data.IDbAccessExtensions.GetData(IDbAccess dbAccess, IDbCommand cmd, IDbTransaction dbTransaction) +57    YAF.Core.Data.DynamicDbFunction.<InvokeGetData>b__28_0(IDbCommand cmd) +30    YAF.Core.Data.DynamicDbFunction.DbFunctionExecute(DbFunctionType functionType, InvokeMemberBinder binder, IList`1 parameters, Func`2 executeDb, Object& result) +224    YAF.Core.Data.DynamicDbFunction.InvokeGetData(InvokeMemberBinder binder, Object[] args, Object& result) +85    YAF.Core.Data.TryInvokeMemberProxy.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result) +18    CallSite.Target(Closure , CallSite , Object , Nullable`1 ) +183    YAF.Core.Model.BoardRepositoryExtensions.UserStats(IRepository`1 repository, Nullable`1 boardID) +333    YAF.Controls.ForumStatistics.<ForumStatistics_Load>b__25_2() +63    YAF.Core.Services.Cache.HttpRuntimeCache.GetOrSetInternal(String key, Func`1 getValue, Action`1 addToCacheFunction) +341    YAF.Core.Services.Cache.HttpRuntimeCache.GetOrSet(String key, Func`1 getValue, TimeSpan timeout) +236    YAF.Controls.ForumStatistics.ForumStatistics_Load(Object sender, EventArgs e) +1242    System.Web.UI.Control.OnLoad(EventArgs e) +95    System.Web.UI.Control.LoadRecursive() +59    System.Web.UI.Control.LoadRecursive() +131    System.Web.UI.Control.LoadRecursive() +131    System.Web.UI.Control.LoadRecursive() +131    System.Web.UI.Control.LoadRecursive() +131    System.Web.UI.Control.LoadRecursive() +131    System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +678
--

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3429.0

**Comment by w8tcha** [comment]
Which sql server version?

**Comment by JamalAPI** [comment]
The sql database is hosted on Microsoft SQL Azure (RTM) - 12.0.2000.8   

I had no issues with YAF.NET v2.3.0.03.

Discussion on same issue:
https://stackoverflow.com/questions/2653188/sql-server-subquery-returned-more-than-1-value-this-is-not-permitted-when-the-s

**Comment by w8tcha** [comment]
Okay I look in to it. But why switch back from yaf version 2.30.03 to 2.30.00 and not to the latest version 2.30.04?

**Comment by JamalAPI** [comment]
Sorry, that was a typo. It is 2.30.04

**Comment by w8tcha** [comment]
I uploaded 2.30.05 with a possible fix.

https://github.com/YAFNET/YAFNET/releases/tag/v2.3.0.5-beta.1

**Comment by JamalAPI** [comment]
Created a fresh forum with a new SQL database and so far it looks good.
**Thanks & Happy New Year!**
