### ISSUE TITLE
YAF.NET v2.3.0.05 - no categories or forums are showing

### ISSUE THREAD

**Issue by JamalAPI** [YAFNET/YAFNET#515]
![2019-12-31_14-10-13](https://user-images.githubusercontent.com/35046731/71631572-58713a80-2bd7-11ea-88d2-9d1944d59ade.jpg)

New forum, fresh SQL DB. Create forums with proper access as shown in image. However, no categories or forums are showing. I think this issues started with 2.3.0.04.

**Comment by w8tcha** [comment]
ups sorry i thought i already fixed this in beta 1. its fixed in beta 2. You need to run the upgrade wizard manually. then the new forums will show up

**Comment by JamalAPI** [comment]
Did the beta 2 upgrade and forums are showing up now. Thanks!
