### ISSUE TITLE
YAF.NET v2.3.0.05 - Invalid date in Active Discussion box after clicking Mark all forums as read

### ISSUE THREAD

**Issue by JamalAPI** [YAFNET/YAFNET#516]
Clicking "**Mark all forums as read**" causes **Invalid date** to be displayed in Active Discussion box. 

See: GIF
![yaf_invalid_date](https://user-images.githubusercontent.com/35046731/71642684-25818200-2c7d-11ea-94d9-8b325ba2eb86.gif)

**Comment by w8tcha** [comment]
Thanks, issue is already fixed in the master branch, and now in the stable branch. Will be fixed in 2.30.06
