### ISSUE TITLE
Move My Activity into it's own page similar to My Topics with tabs

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#517]
Gradually, the Activity Stream is becoming more and more great. The next progression I feel is moving it out of My Account and into it's own section like My Topics and organizing the type of activities via Tabs.  Each tab can have a badge count for unread activity items. 

A lot vertical space is used up by the activity type (e.g. "Was Quoted"). And there are only five shown. If the user replies five times, they have to go to page 2 to find what their activity notification is regarding. Actually as a user, I am not sure why I would want to see an item showing that I replied to a post. It feels redundant. 
![image](https://user-images.githubusercontent.com/5612416/71644570-21129480-2c90-11ea-8192-d86f6e1f3b4e.png)

A My Activity page laid out something similar to My Topics with tabs, and showing a badge count for each activity type I think would be very beneficial to users.
![image](https://user-images.githubusercontent.com/5612416/71644588-78b10000-2c90-11ea-8e30-ac57e1dd2726.png)

I'm thinking tabs similar to how condensed the recent topics would be really great to have for each tab under my activity.
![image](https://user-images.githubusercontent.com/5612416/71644633-42c04b80-2c91-11ea-9eeb-526f7bd337aa.png)

**Comment by w8tcha** [comment]
> Actually as a user, I am not sure why I would want to see an item showing that I replied to a post. It feels redundant.

I guess its a misunderstanding of the card! It shows the users activity and not notifications. but it also includes activities by other users. Github does the same.

I think tabs would be an overkill for this. a filter seems to the better ui options

<img width="637" alt="filter" src="https://user-images.githubusercontent.com/722575/71718461-8cd53880-2e1b-11ea-87a5-9c0083ca1655.PNG">

**Comment by Zero2Cool** [comment]
Yes, I misunderstood, sorry. 

So, I'll change my request to ... can we leave posts user replied to under My Account and replace My Activity with My Notifications that includes Private Messages, Thanks, Been Quoted and Mentions?

**Comment by w8tcha** [comment]
I understand but makes it kinda confusing when giving thanks and received thanks would be in to different pages. Why not just make a different view for mobile. and also allow the sorting by unread!

**Comment by Zero2Cool** [comment]
Because even on my large screen monitor, I only see 5 and have to use pagination to see more.  Sorting would be a big benefit. Maybe throw them into a table via tablesorter and leverage the tablesorter functionality? I dunno. I promise, I am not trying to be difficult, I just feel this is has a lot of promise and feels just so close.

**Comment by w8tcha** [comment]
no problem i understand you. I made some changes. You can now select how many items are displayed. filter for unread is also possible. And also there is less content on smaller devices

**Comment by Zero2Cool** [comment]
Cool. It looks like the build failed though. I'll pull it later and check it out.

**Comment by Zero2Cool** [comment]
> no problem i understand you. I made some changes. You can now select how many items are displayed. filter for unread is also possible. And also there is less content on smaller devices

Merged the changes and got a few comments. This is what I see when clicking My Activity.
![image](https://user-images.githubusercontent.com/5612416/71862254-dbeec800-30be-11ea-89e0-15f19e4806a2.png)

1. "Your Account" is the first thing in view, and takes up most of the area.
2. "Your Activity" shows when others thank or mention or quote your post. That doesn't really fit into the "Your Activity" realm.  Could probably split them into different areas.  Or maybe rename it "Activity Stream"?

**My Activity** 
Given (Gave) Thanks to a Post
Created a new Topic
Replied to a Post

**My Notifications**
Was Mentioned
Received a Thanks to a Post
Was Quoted

**Comment by w8tcha** [comment]
Okay how about. Put the notifications on a new page and leave the your activities on the current page. Would that be okay?

**Comment by Zero2Cool** [comment]
> Okay how about. Put the notifications on a new page and leave the your activities on the current page. Would that be okay?

I think that'd make sense. What are your thoughts on it?

**Comment by Zero2Cool** [comment]
Additionally, maybe include "Marked for Answer" as well. I think some folks would like to be notified their post was the solution.

**Comment by w8tcha** [comment]
My activity now shows only users actions. and a new page my notifications shows the unread quotes, mentions and replies

**Comment by w8tcha** [comment]
![notify](https://user-images.githubusercontent.com/722575/72681291-61607800-3ac2-11ea-8fa9-31a6856f1a9e.png)

i think i found a better solution to show the unread notifications

**Comment by Zero2Cool** [comment]
How do you mark All as Read? A button/link on the footer of the drop down?

**Comment by w8tcha** [comment]
Yes i guess one button  to dismiss them all would be enough. Also i will add a user setting where the user can disable notifications completely

**Comment by Zero2Cool** [comment]
What if a user accidentally clicks mark all as read, can they go back and view notifications that were read?

**Comment by w8tcha** [comment]
Yes then you go to click on the bell and go to the notifications page

**Comment by w8tcha** [comment]
the changes have been comitted
