### ISSUE TITLE
Auto-Save not cleared after post is submitted

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#518]
**Describe the bug**
Read the title

**To Reproduce**
1. Create a new topic
2. Type up a post and wait for the auto-save to kick in at least once
3. Submit post
4. Reply to another thraed
5. Create new topic

**Expected behavior**
Once the auto-saved content has been submitted, it should be cleared. 

**Screenshots**

**System (please complete the following information):**
 - YAF Version:  YAF.NET 2.31 BETA 201912290340 
 - .NET Version: .NET Framework Version: 4.7.2
 - SQL Server: SQL Server 2017
 
**Affected browser**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge

**Additional context**
I'm Batman!

**Comment by w8tcha** [comment]
hello batman 😀

**Comment by w8tcha** [comment]
Issue is fixed in both master and stable. and will be included in 2.30.06
