### ISSUE TITLE
Source Code Formatting

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#519]
I've noticed a few times the code doesn't look like it's being formatted before being saved and committed. Little things like this below.  Maybe implement [editorconfig ](https://editorconfig.org/)with ReSharper to force formatting on Save to have a consistent code base?  Very minor, but it has caused some issues when merging YAF master into my changes so thought I'd bring it up.

![image](https://user-images.githubusercontent.com/5612416/71743502-5652ea00-2e2a-11ea-9a5c-c76ead4da0fe.png)

**Comment by w8tcha** [comment]
I think you need to import the yaf patterns. and also StyleCop for Resharper is required..


[YAFCodeStyle.zip](https://github.com/YAFNET/YAFNET/files/4020771/YAFCodeStyle.zip)

**Comment by Zero2Cool** [comment]
Nice, I will have to check that out, but how is me having that going to make the source code I pull off Github format consistently?

**Comment by w8tcha** [comment]
Sorry I really don't know how the editorconfig works and if it's work with resharper. But the indent in the Screenshot is the code style for yaf

**Comment by Zero2Cool** [comment]
Ohhhh. So the space I have circled here is intentional?
![image](https://user-images.githubusercontent.com/5612416/71759267-2af2ee00-2e70-11ea-9ae2-ed15a49cc55f.png)

**Comment by w8tcha** [comment]
Yes correct. With my current setup vs does this automatically
