### ISSUE TITLE
YAF v2.3.0.05 - Moderate menu option visible in Guest mode

### ISSUE THREAD

**Issue by JamalAPI** [YAFNET/YAFNET#520]
In **Guest** mode, the Moderate menu option is visible. Shouldn't this option be visible only to administrators and moderators? 

**Screenshots**
![YAF_Moderate](https://user-images.githubusercontent.com/35046731/71767938-a2ac3180-2edf-11ea-97ed-97020d07b298.jpg)

YAF: v2.3.0.05

**Comment by w8tcha** [comment]
The moderate button/page is visible if the current user is a moderator. Which means that you set the moderator access mask to guests in on of your forums. Or you enabled the moderate checkbox for the guest access mask

**Comment by JamalAPI** [comment]
It was one the forums that caused the issue. Closing now.
