### ISSUE TITLE
Access Masks - better layout.

### ISSUE THREAD

**Issue by JamalAPI** [YAFNET/YAFNET#521]
I would to like to suggest that **Access Masks** section when creating a **forum be moved below the Category textbox** and to show **ALL** access masks for the Admin, Guest and Registered Member initially set the default as:
![2020-01-04_13-55-05](https://user-images.githubusercontent.com/35046731/71770385-e449d600-2ef9-11ea-93ea-1dc989c9de29.jpg)

Right now the Access Masks is bottom of forum creation page and only the Initial Access is listed as Admin Only. Then after forum is created, I have to go back and set the Access Masks. It kind of a cumbersome process.

**Comment by w8tcha** [comment]
Agree. this will require to change some of the logic behind, but i will change that. Will be included in 2.31
