### ISSUE TITLE
Suggestion: Display Post layout

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#524]
For years I've been trying to figure out a good layout for Display Post. I've been looking at other forums, and YAF and been trying to find something that would work. 

A few weeks ago I started throwing together a JS Fiddle of it. Here's where I'm at so far.

http://jsfiddle.net/Zero2Cool/t2hz16qg/154
![image](https://user-images.githubusercontent.com/5612416/72259913-33b59380-35d7-11ea-9e3e-c524577305a9.png)

I originally wanted the userbox left, message area right, but after you changed it to vertical, I really took to liking that better. It gives the user a more consistent experience from Desktop and Mobile.  

I moved things around to make userbox solely user related and message area solely message related. It also uses the full width when on small devices too which I think is good.

Some functionality tweaks I would suggest to this that I have yet to implement would be.
1. Display 3 usernames for the thanks an then put them in a list.  
2. On small devices I would suggest putting answer, edit, delete and IP into a list. 
3. On small devices show Thank, Quote and Reply  icons without text.
4. Clicking on the Username displays a Profile Card showing joined date, location, post count, medals, and link to users profile

+Quote means you have not selected this message for multi-quote
-Quote means you've selected this message as a multi-quote

Do you think this would be good for YAF? If not, that's cool, but do you think it would be difficult to modify YAF to use this display post layout concept?

**Comment by w8tcha** [comment]
it looks a bit strange too me, and dont follow the overall ui of the board where the buttons are located in the footer.

i would prefer more the github approach with the menu behind the three dots

![displaypost](https://user-images.githubusercontent.com/722575/72881014-44b18380-3d00-11ea-8d38-9f10b0a3574c.png)

also the right click context menu (desktop only) 

![contextmenu](https://user-images.githubusercontent.com/722575/72881104-67dc3300-3d00-11ea-911c-1a393ae394b9.png)

**Comment by Zero2Cool** [comment]
The changes made are an improvement.  👍

Although, I don't recall buttons in the footer elsewhere in YAF other than Display Post.  That said, I do not think footer should be used for Display Post because when you have post on top of post, it's not pleasant to the eye because of all the wasted space. See below. 
![image](https://user-images.githubusercontent.com/5612416/72896500-854fd380-3ce5-11ea-9475-dc98aef4262d.png)

If you're absolutely must use footer in Display Post, I would offer up a suggestion to add "py-0" after "card-footer". That padding is not necessary (i.e. one of several reasons I found using Card is not optimal). Here's what it looks like with the py-0 added.
![image](https://user-images.githubusercontent.com/5612416/72897126-cdbbc100-3ce6-11ea-8c79-6a3a5f392aad.png)

When you are on small devices, the margins are using up space horizontally as well. If you look at my example, the Display Post maximizes the use of area more effectively.  Please note, this might be a CSS styling thing somewhere else and is not likely directly related to a Card being used for Display Post.  In other words, not a major issue in my mind.
![image](https://user-images.githubusercontent.com/5612416/72897176-f5128e00-3ce6-11ea-9db0-61ee036de43e.png)

Overall, I think this is a step in the right direction but much more tweaks are needed. (just my opinion of course)

**Comment by w8tcha** [comment]
> If you're absolutely must use footer in Display Post, I would offer up a suggestion to add "py-0" after "card-footer". That padding is not necessary (i.e. one of several reasons I found using Card is not optimal). Here's what it looks like with the py-0 added.

makes sense. will add this

> Overall, I think this is a step in the right direction but much more tweaks are needed. (just my opinion of course)

im open for suggestions. i added the suggestions from above expect the buttons.

**Comment by Zero2Cool** [comment]
Suggestions from what I see thus far. 


I think the avatar not having such a fat padding would be an improvement.

Move Rank below the Username

Reputation thing could be moved to the right instead of below the username.  Which reminds me to mention items that can be hidden should probably not leave a "white" space if the admin elects to hide them.

**Comment by JP58** [comment]
In my forum, rank is unimportant information - but country flags next to the avatar/username are much more important...  As they were in the older "userbox"... ;-) 

Maybe controlled in settings? 

Of course some members think that # of posts is important too, but that's a "hovercard thingy"... ;-)

**Comment by Zero2Cool** [comment]
I've always hated Post counts. Two decades of forum administration watching posters belittle someone for having X posts while they have Y posts was obnoxious, lol. Especially on a paintball website (most users were teenagers so that was probably what soured me the fastest). 

I would like the Display Post to be more configurable. I've found even maintaining my own branch is a bit of a challenge. I like my code formatted to adhere to best practice standards (which can VARY from developer to developer, there is no WRONG formatting -- assuming it's consistent of course) and then having to apply the same change over and over and over again.  I update a lot, so that is my fault. 😋😛

I was thinking maybe since I desire the Forum List, Topics and Display Post controls/pages somewhat radically different than YAF, I should just create something like "kjdDispalyPost" and then reference that control instead of Display Post.  But then I miss out on the cool stuff Ingo adds. 

I also like having things compartmentalized (e.g. the info bar for editing a post, or the thanks bar for those who have thanked the user for the message/post). 

I dunno though. I only have ONE layout to make me happy. Ingo is trying to make a plethora of people happy. I wouldn't want his job!! (he doesn't get paid NEARLY enough for his time and efforts)

**Comment by JP58** [comment]
What I would like would to have default empty element configurable CSS classes added to each forum element - to be used if you wish to and if you don't it's ignored - kind of like class="row mycustomrow" for the row element and such... If not used, no impact to original BS but gives a possibility to add styling to the standard BS anywhere - maybe...  Maybe I' out in the blue here, it's just a thought.

Since the available element classes are written in the code, maybe it could be an idea to add a "custom class" in the code class string for each element and have all the custom class tags as empty CSS classes as a starter kit in a file in the Content/Themes... 

I may be way out here, I was just dreaming....  :-D

**Comment by w8tcha** [comment]
> I think the avatar not having such a fat padding would be an improvement.

Done

> Move Rank below the Username

Done

> Reputation thing could be moved to the right instead of below the username. Which reminds me to mention items that can be hidden should probably not leave a "white" space if the admin elects to hide them.

Which item did you mean? if the reputation bar is disabled it doesnt leave any whitespace

**Comment by w8tcha** [comment]
> Maybe all the "old userbox" items can be controlled in settings?

No, only you can disable the reputation bar. That user box concept was really stupid. Especially when something changed. thats why i removed it completely.

> What I would love would be to have default empty element configurable CSS classes added to each written forum element - to be used if you wish to and if you don't it's ignored - kind of like class="row mycustomrow" for the row element and such... If not used, no impact to original BS but gives a possibility to add styling to the standard BS anywhere - maybe... Maybe I' out in the blue here, it's just a thought.

At the moment each page has its own css class name applied so technically you can already do that

**Comment by Zero2Cool** [comment]
> Which item did you mean? if the reputation bar is disabled it doesnt leave any whitespace

Merged the latest changes as of this post into my branch, gotta work through some errors and then I'll test. Then provide visuals.

**Comment by Zero2Cool** [comment]
Okay, error fixed. (had to do a update to get the Activity field added, no biggie).

This is a **_custom theme_**, let me get that out there.

1. Rank seems to have some left padding that makes it uneven with the username.
2. Maybe drop Topic Starter below Rank? I dunno, just an idea.
3. The relative time and post number vertical spacing is uneven. I think a little top padding to vertically align it might give it a better visual appearance.

![image](https://user-images.githubusercontent.com/5612416/73371811-e1819d00-427b-11ea-9fa3-06b1f76402f9.png)


I got something goofy with my theme that is having this happen. 
![image](https://user-images.githubusercontent.com/5612416/73372046-3a513580-427c-11ea-80b1-6bf8dca7c669.png)

**Comment by w8tcha** [comment]
> I got something goofy with my theme that is having this happen when I click the ... option in the display post header. 

Did you applied a custom css to the btn or btn-link class?

**Comment by Zero2Cool** [comment]
> > I got something goofy with my theme that is having this happen when I click the ... option in the display post header.
> 
> Did you applied a custom css to the btn or btn-link class?

Not sure, but when I changed to a standard theme, it's normal, so that's something I can fix easily.

**Comment by w8tcha** [comment]
> Rank seems to have some left padding that makes it uneven with the username.

the badge starts with the username

<img width="768" alt="test" src="https://user-images.githubusercontent.com/722575/73600670-f5ffb700-4553-11ea-821a-3705ff28f9a4.png">

i dont see any padding

**Comment by w8tcha** [comment]
> Maybe drop Topic Starter below Rank? I dunno, just an idea.

3 rows looks kinda strange

> The relative time and post number vertical spacing is uneven. I think a little top padding to vertically align it might give it a better visual appearance. 

Thats because the dotted line. will be fixed

**Comment by Zero2Cool** [comment]
This is actually part of the stock theme that I used as my base.

https://bootswatch.com/lumen/

![image](https://user-images.githubusercontent.com/5612416/73601680-4e6e8e80-452b-11ea-8941-3f36c96c89de.png)

**Comment by w8tcha** [comment]
very strange. i removed the btn classes. it should now look correct

**Comment by Zero2Cool** [comment]
> very strange. i removed the btn classes. it should now look correct

In my demo site, looks much gooder. 
![image](https://user-images.githubusercontent.com/5612416/73609563-865dec00-4594-11ea-8833-7c3870482658.png)

**Comment by Zero2Cool** [comment]
> > Rank seems to have some left padding that makes it uneven with the username.
> 
> the badge starts with the username
> 
> <img alt="test" width="768" src="https://user-images.githubusercontent.com/722575/73600670-f5ffb700-4553-11ea-821a-3705ff28f9a4.png">
> 
> i dont see any padding

Something was looking odd about it, but I realized that's why I put mine in a table and centered it so it had a little better look to it.  But, you are right, no padding, it's just the stock bootstrap themeing that makes it look silly.

**Comment by Zero2Cool** [comment]
No more changes to the Display Post? This is the final version?

**Comment by w8tcha** [comment]
There wasnt anymore feedback, sorry thats why i closed it

**Comment by Zero2Cool** [comment]
> There wasnt anymore feedback, sorry thats why i closed it

Do you not find the other concepts worth implementing? If not, then absolutely this can be closed.  The context menu is neat, some users really like it. I find it trouble some due to my habit of highlighting a word/phrase and right clicking "search google" lol. I'll adapt.

**Comment by w8tcha** [comment]
You mean with the thanks list? It's hard to implement with the current Ajax solution without post back

**Comment by Zero2Cool** [comment]
> You mean with the thanks list? It's hard to implement with the current Ajax solution without post back

Okay, fair enough. No need to keep it open. The new Display Post is an improvement.

**Comment by Zero2Cool** [comment]
> > There wasnt anymore feedback, sorry thats why i closed it
> 
> Do you not find the other concepts worth implementing? If not, then absolutely this can be closed. The context menu is neat, some users really like it. I find it trouble some due to my habit of highlighting a word/phrase and right clicking "search google" lol. I'll adapt.

Is it possible to disable the right click menu? I'm having trouble finding it in settings.

**Comment by w8tcha** [comment]
No, there isn't a setting to disable it. Is this needed?

**Comment by Zero2Cool** [comment]
> No, there isn't a setting to disable it. Is this needed?

Maybe not disabled via setting but atleast how it can be disabled. When it was just affecting me I let it go, but others are finding it hard to highlight parts of a post to copy/paste. I think it's neat feature but it kind of blocks a common (for some) user experience.

**Comment by w8tcha** [comment]
<img width="194" alt="selected" src="https://user-images.githubusercontent.com/722575/79116193-159f3100-7d88-11ea-8ddf-69e712f5be42.PNG">

you can still copy a text in a post and the bubble pops up for quoting

**Comment by Zero2Cool** [comment]
> <img alt="selected" width="194" src="https://user-images.githubusercontent.com/722575/79116193-159f3100-7d88-11ea-8ddf-69e712f5be42.PNG">
> 
> you can still copy a text in a post and the bubble pops up for quoting

Absolutely, however, when you right click to search by the highlighted portion, the cool context menu pops up. 
![image](https://user-images.githubusercontent.com/5612416/79117010-89711780-7d4f-11ea-8d29-670806d6ff6d.png)

The common user experience when doing this is something similar to this. And this is what folks are missing and I'm not sure how to incorporate it. Wait, maybe ... could a "search by [insert highlighted text] in {default search engine}" be added to the context menu??
![image](https://user-images.githubusercontent.com/5612416/79117030-9988f700-7d4f-11ea-8097-9918a79c99c6.png)

**Comment by w8tcha** [comment]
OOh i'm seeeing this option today for the first time. Is that actually something people use?

**Comment by Zero2Cool** [comment]
> OOh i'm seeeing this option today for the first time. Is that actually something people use?

I kinda live by it, lol.  I assumed this would only affect me, but even in our slowest part of the year, I've received feedback about it causing some others a bit of trouble.  
![image](https://user-images.githubusercontent.com/5612416/79122517-72392680-7d5d-11ea-8cb3-637fbb4137d4.png)

**Comment by w8tcha** [comment]
okay i understand. so i will remove the select quoting bubble, and add a 2 options to the context menu , quote selected text and search google...

Also this will be enabled and works on mobile too!

**Comment by Zero2Cool** [comment]
> okay i understand. so i will remove the select quoting bubble, and add a 2 options to the context menu , quote selected text and search google...
> 
> Also this will be enabled and works on mobile too!

Awesome! This is why you are my favorite YAF Developer!! ;-) ;-)

**Comment by w8tcha** [comment]
> > okay i understand. so i will remove the select quoting bubble, and add a 2 options to the context menu , quote selected text and search google...
> 
> > 
> 
> > Also this will be enabled and works on mobile too!
> 
> 
> 
> Awesome! This is why you are my favorite YAF Developer!! ;-) ;-) 

Hmh i'm the only developer for yaf. So it's an easy choice 😂🤗

**Comment by AlbertoP57** [comment]
Old topic but still current: **YAF on small devices**.

This morning I compared the posts layout (smartphone) in two different forums:
1) tapatalk
2) YAF

Well. My opinion is tapatalk layout is way better then YAF when used in a smartphone. The reasons in two screenshots:

tapatalk:

![image](https://user-images.githubusercontent.com/18015672/79461467-7fbd0d80-7ff6-11ea-9e8e-7f9f27504a36.png)

YAF

![image](https://user-images.githubusercontent.com/18015672/79461502-89df0c00-7ff6-11ea-9d11-888a6dfba0be.png)

Both screenshots are taken with the same smartphone (Chrome on Android 10). A real smartphone not a PC's emulation.

Dark background is not the problem. The main problem (IMHO) is that the first one has a cleaner and pleasant layout.

Anyway you can judge by yourself.

By the way, have a look for the message's menu:

![image](https://user-images.githubusercontent.com/18015672/79463102-af6d1500-7ff8-11ea-89e4-fe31dcce3ced.png)

Isnt cool?

> 
> Hmh i'm the only developer for yaf. So it's an easy choice 😂🤗

have you ever wondered why? 😂😂😂

We are not anymore in '90 when "message boards" were the only way to communicate. Now people prefer facebook to forums.

**Comment by w8tcha** [comment]
![D6A5FD1C-B842-4D68-9D15-3FC4BF9B5699](https://user-images.githubusercontent.com/722575/79478810-25c74280-800c-11ea-9784-cf7dc200f4b1.png)

Well atleast the post menu and footer buttons are already added in 2.31.3. 

So adding small image avatar and a quote with less spacing could be easily added.

The online icon can be disabled! Ifyou don't find it usefull

**Comment by Zero2Cool** [comment]
> Well. My opinion is tapatalk layout is way better then YAF when used in a smartphone. The reasons in two screenshots:
Trying to compare TapaTalk to YAF is a big unrealistic. TapaTalk is backed by a company. YAF is backed by one dude.  As long as we continue to provide constructive feedback for YAF, then YAF will continue to improve. That's the great thing about an open source project! The community can have a helping hand! So, let's keep the suggestions coming and YAF will continue to be improved!

> We are not anymore in '90 when "message boards" were the only way to communicate. Now people prefer facebook to forums.

People who want rich meaningful interaction continue to use Message Boards. Those who want to be keyboard warriors and attempt to be "viral" use Twitter and Facebook. Choose your community accordingly.

**Comment by AlbertoP57** [comment]
> Trying to compare TapaTalk to YAF is a big unrealistic. TapaTalk is backed by a company. YAF is backed by one dude. 

Of course. My message was not meant to be irrespectful to the job done. But we need to be realistic. Is YAF a toy or a tool? I contributed to YAF (very little things) when it was a tool. If tapatalk is better... well ... we just have to copy from them (or from other forums).

> As long as we continue to provide constructive feedback for YAF, then YAF will continue to improve. That's the great thing about an open source project! The community can have a helping hand! So, let's keep the suggestions coming and YAF will continue to be improved!
> 

Some open source project are better than commercial project. Yaf would need more people working and more people making decisions.

> People who want rich meaningful interaction continue to use Message Boards. Those who want to be keyboard warriors and attempt to be "viral" use Twitter and Facebook. Choose your community accordingly.

I was born with message boards ... I have already chosen 😂😂😂

**Comment by AlbertoP57** [comment]
> ![D6A5FD1C-B842-4D68-9D15-3FC4BF9B5699](https://user-images.githubusercontent.com/722575/79478810-25c74280-800c-11ea-9784-cf7dc200f4b1.png)
> 
Picture from smartphone or tablet?

**Comment by Zero2Cool** [comment]
> Of course. My message was not meant to be irrespectful to the job done. But we need to be realistic. Is YAF a toy or a tool? I contributed to YAF (very little things) when it was a tool. If tapatalk is better... well ... we just have to copy from them (or from other forums).


I see no harm in replicating success where others have found it. I mimicked my custom bootstrap layout after XenForo.  They have a nice smooth fluid layout for topics and messages.

**Comment by w8tcha** [comment]
> Picture from smartphone or tablet?

Smartphone

**Comment by Zero2Cool** [comment]
> OOh i'm seeeing this option today for the first time. Is that actually something people use?

Is there an option to completely disable the YAF context menu? Something that lets users use the OS/browser context menu instead?
