### ISSUE TITLE
MyTopics "Unread topics" tab does not give time ago selection option

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#525]
All tabs in the "My Topics" give a time ago selection possibility except one. 

1. Click on your user profile
2. Select 'My Topics'
3. Go to Unread Topics tab

Here I presume that I can select the time period as I can in the other tabs on the page. 
But no... 

 - YAF Version:  2.31 BETA 202001150940
 - .NET Version 4.7.2
 - SQL Server 2019
 - Win Server 2016 Standard 

![image](https://user-images.githubusercontent.com/5246746/72747833-014afe00-3bb6-11ea-948b-ff506a637169.png)

**Comment by w8tcha** [comment]
> Here I presume that I can select the time period as I can in the other tabs on the page.

Why ? is there really a need to filter unread topics by date? I guess it would be better to hide the dropdown

**Comment by JP58** [comment]
I thought of/imagined a scenario when a new forum member sees this feature and presses it... 
And gets a list of about 37 500 topics (in my forum)....  ;-)

**Comment by w8tcha** [comment]
> I thought of/imagined a scenario when a new forum member sees this feature and presses it...
And gets a list of about 37 500 topics (in my forum).... ;-)

But in this case the tab active tabs and unread tabs would be the same. Unread Tabs tabs for new users is irrelevant i think.
