### ISSUE TITLE
Post date not quite ok in hover "tooltips".  

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#526]
For topics lists - when you hover the post title, posted by or the "information" icon - you mostly get "Invalid date".  However, it is not consistent - I get "1 year ago", "2 years ago", 6 months ago on some topics/posts...  Seems like some kind of JS date format setting issue.  

I of course expect to see the correct date or correct time ago, depending of forum settings.  :-) 

![image](https://user-images.githubusercontent.com/5246746/72749937-b59b5300-3bbb-11ea-9253-09202afa4844.png)

![image](https://user-images.githubusercontent.com/5246746/72749826-5e957e00-3bbb-11ea-811b-ab99935af899.png)

![image](https://user-images.githubusercontent.com/5246746/72749883-88e73b80-3bbb-11ea-98a2-08aa1c51674a.png)

Does look ok on a post in a topic though. 
![image](https://user-images.githubusercontent.com/5246746/72750722-e2506a00-3bbd-11ea-9670-7cbbc17bfc3b.png)

 - YAF Version:  2.31 BETA 202001150940
 - .NET Version 4.7.2
 - SQL Server 2019
 - Win Server 2016 Standard

**Comment by JP58** [comment]
I can add that I use CDN for JS in the forum config.

**Comment by w8tcha** [comment]
fixed with latest commit
