### ISSUE TITLE
YAF.NET v2.3.0.06 ASP.pages_topics_ascx' does not contain a definition for 'LastPostImageTT' 

### ISSUE THREAD

**Issue by JamalAPI** [YAFNET/YAFNET#528]
Click a topic, you get:

Compilation Error
Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately.

Compiler Error Message: CS1061: 'ASP.pages_topics_ascx' does not contain a definition for 'LastPostImageTT' and no extension method 'LastPostImageTT' accepting a first argument of type 'ASP.pages_topics_ascx' could be found (are you missing a using directive or an assembly reference?)

````
Line 21:                 </div>
Line 22:                 <div class="card-body" id="body" runat="server">
Line 23:                     <YAF:ForumList AltLastPost="<%# this.LastPostImageTT %>" runat="server" ID="ForumList" />
Line 24:                 </div>
Line 25:             </div>
````

**Comment by w8tcha** [comment]
Fixed in 2.30.07
