### ISSUE TITLE
Suggestion - Make Search indexing/re-indexing into a background job

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#529]
**Is your feature request related to a problem? Please describe.**
I wondered why the new Lucene Search feature never gave me any results... 
Then I understood I had to do an initial "re-index" via the Search admin in host settings to get some indexing of old posts done... I had expected to be able to search the forum directly after upgrading...  ;-) 

This did not go well at first when doing it, had to increase the http executionTimeout setting into ridiculous values (6000) before I finally got my test forum indexed so you could search it... There were 500 000+ posts to be indexed initially and that takes some time. You really don't want to set the executionTimeout to such big values since it affects all web queries (including malicious ones).          

**Describe the solution you'd like**
I suggest it should be a background task that runs by itself once/day or so with a long timeout setting. 

The first indexing is the one that takes a very long time, and I think the forum admins who upgrade to 2.3 from older versions and adopt the new Lucene search may be as bewildered as I was when not finding any search results due to the fact that you have to do the initial one manually. After the first successful initial indexing, the re-indexing runs swiftly within "normal" timeout settings.    

**Describe alternatives you've considered**
Lucene is much better than the older SQL Server options, so I would say that there is no way back.
If YAF would ever go multi-platform .Net Core in the future, Lucene is the obvious way to go today. :-)    

**Other thoughts**
I have a software (Gallery Server Pro) where the search indexing is run as a background task, scheduled or submitted as a background job on demand and that works just great.

**Comment by w8tcha** [comment]
Actually there is a search index task. Which runs one time every day, in the night between 1-2 am

**Comment by JP58** [comment]
Ok, have seen it now...  :-) 
However, it seems like 550 000 post was too much for it to do an initial index creation... 

I suspect an unwanted timeout in the service, since I have never had any search results in 2.3x using Lucene until I did it manually via the re-index button interactively and adding & adjusting the executionTimeout value to a high value in web.config .  

Suddenly I finally got some content (about 300MB) in the App_Data/search_index folder, as expected...  :-)

**Comment by w8tcha** [comment]
> I think the background indexing task needs some "loving care" so it also can manage initial indexing for "larger" forums - even if it takes much longer time than expected. :-)

Yes but i im still looking for a solution to index the entire board in parts instead of the whole board at one time

**Comment by w8tcha** [comment]
Okay i made some changes.

When upgrading it initializes the search index task.

Going to Host > Search > Re-index will also initialize the search index task (no more need to set a huge timeout setting).

The task also can handle huge dbs in the background.

I can close here. Issue will be resolved in 2.31.0
