### ISSUE TITLE
Auto-lock inactive accounts (with setting)

### ISSUE THREAD

**Issue by yaf-squirrel** [YAFNET/YAFNET#53]
In reference to this comment - https://github.com/YAFNET/YAFNET/issues/16#issuecomment-24345974 - this would be a nice feature -- helps lock down old accounts automatically just in case an attacker gets past the user's password - when they see they're locked, they'll email or contact somehow...

Additional would be setting in admin for auto-lock inactivity period, and ability to give reason for lock to user (or maybe a notification email sent when locked so user can restore account) - like hotmail does (did)

(Not sure where this went, but was intentioned for 2.1 milestone or beyond)

**Comment by w8tcha** [comment]
I propose the solution instead of doing it automatically. Adding a new  option to the Admin > Users page where you can lock all users that are not active for x Years. And set them to approve = false. This would disable the user without loosing the content

**Comment by w8tcha** [comment]
added in 2.31.0
