### ISSUE TITLE
Failed to load jquery.ForumExtensions.js

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#530]
Easy to reproduce. Download the source code (commit d20ba542f4d837a2785c2e6fad2e44a139e7142a). Open it in Visual Studio 2019. Set your db.config, rename recommended web.config and debug application.  I verified the file exists. It just is not being loaded.

![image](https://user-images.githubusercontent.com/5612416/73610697-f625a400-459f-11ea-9aa2-687d3b87a6ff.png)

**Comment by w8tcha** [comment]
When you click on the link (jquery.ForumExtensions.js) in the console what is the url?

I can't reproduce it

**Comment by Zero2Cool** [comment]
I think it's a web.config issue. I renamed it the recommended web config, but had to use my old one to get the right membership.  The error was happening when the create a post page. Working through it to see if I can narrow down what I messed up.

**Comment by Zero2Cool** [comment]
Correcting the web.config removed that ForumExtensions error. Only thing left is the bottom part of the screenshot I posted above. 

![image](https://user-images.githubusercontent.com/5612416/73612579-7d7c1300-45b2-11ea-92e7-8ab64321d0d5.png)


Probably another web.config issue.
