### ISSUE TITLE
Latest source doesn't compile

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#531]
I think there might be a mapping for DLL's issue that's causing this.

All I did was download the source from GitHub, opened it up and tried to build and got this.  I tried this because when I did a pull request of latest YAF into mine, I got errors. And it's the same errors as below. 

Did I do something wrong?

![image](https://user-images.githubusercontent.com/5612416/75115773-7d0def80-5627-11ea-8ee0-195feb516cd7.png)

**Comment by w8tcha** [comment]
It should compile in Release mode.

**Comment by Zero2Cool** [comment]
> It should compile in Release mode.

What can be done so it compiles in Debug mode?

**Comment by w8tcha** [comment]
it should work now

**Comment by w8tcha** [comment]
Does it work now for you? I think you need to click on solution and then rebuild all

**Comment by Zero2Cool** [comment]
Just tried and no. Rebuilt all projects. Probably something I have to figure out on my end. No biggie.

![image](https://user-images.githubusercontent.com/5612416/75282589-f0099880-57d6-11ea-9403-c812e705c0f5.png)

**Comment by w8tcha** [comment]
You need to update the web.config. Change yaftaskmodule to taskmodule

**Comment by Zero2Cool** [comment]
> You need to update the web.config. Change yaftaskmodule to taskmodule

Tried that, didn't work.  Copied the recommended web.config and brought my membership portion over and now it works.
