### ISSUE TITLE
Unknown server tag 'YAF:RoleRankStyles'.

### ISSUE THREAD

**Issue by mcshaz** [YAFNET/YAFNET#539]
when clicking on the 'roles' menu tab from the administrator page, running the latest version (2.31.1), I get the error

```
Unknown server tag 'YAF:RoleRankStyles'
Line 182: <YAF:RoleRankStyles ID="RoleRankStylesGroups"  RawStyles="<%# ((YAF.Types.Models.Group)Container.DataItem).Style %>" runat="server" />
```

**Comment by w8tcha** [comment]
Thanks for the report, issue has been already fixed. and will be resolved with version 2.31.02

**Comment by mcshaz** [comment]
Thank you for what amounts to a massive and consistent effort actively maintaining this excellent project for17 years - I don't think I have ever seen that from a single developer open source .net project before!

Do you have a rough estimate of when the new version might be released? I know this is a slightly cheeky question for a free and open source project. However I am quickly putting together a discussion forum for Intensive Care clinicians (of which I am one) to discuss preparedness and initial response to the COVID-19 epidemic, and as the current release is not functional as a private forum (due to this issue), I will look at alternatives if 2.31.02 is likely to be more than a couple of days. Thank you again.

**Comment by w8tcha** [comment]
The release is scheduled for Sunday. but i uploaded it as pre-release.

https://github.com/YAFNET/YAFNET/releases/tag/v2.3.1.2-beta-1

**Comment by mcshaz** [comment]
thank you - you are a star!
