### ISSUE TITLE
Creating Poll throws Null error

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#541]
I'm able to create poll, but when a user creates one that is not Admin, this happens.

I tried testing this on the YAF Support site, but it appears Polls are not permitted.

![image](https://user-images.githubusercontent.com/5612416/75990541-abf35380-5eba-11ea-9a1f-bf4fd3032d40.png)

 Powered by YAF.NET 2.31

**Comment by w8tcha** [comment]
will be fixed in 2.31.02
