### ISSUE TITLE
Suggestion - Please get a plain reply button on posts... 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#543]
**Is your feature request related to a problem? Please describe.**
Since we only have "Quote" and "Add to quote" as direct reply options to a message, a myriad of unnecessary quotes (often including also images) are used in replies - at least in my YAF forum. This is quite annoying since not all members delete the quoted message. Noone uses the "Post Reply" or "Quick Reply" at the page bottom since they are mostly replying to a message further up the page... 

**Describe the solution you'd like**
Add a simple "Reply" option that uses the page bottom "Post Reply" logic. 

If I remember correctly, it used to be there in the 1.9.x-2.0.x versions before the "Add to quote" button was added... In my opinion, that "Add to quote" is a totally unnecessary feature - at least in my YAF forum where multiple full post quotes are not used at all. Does anyone actually use that feature? 

**Describe alternatives you've considered**
I haven't considered any alternatives, except that only having a reply button and if you want to quote you mark the text you want to quote would be good enough.   

**Additional context**
![image](https://user-images.githubusercontent.com/5246746/76116133-bceeb280-5fe9-11ea-913d-a9ad327e1ca4.png)

**Comment by w8tcha** [comment]
>  Does anyone actually use that feature?

I use this feature every day in the support forum. Dont forget there exist different use cases!

> Please get a plain reply button on posts..

The button already exist on desktop browser. Just right click inside a post. the context menu contains a reply button!

> I haven't considered any alternatives, except that only having a reply button and if you want to quote you mark the text you want to quote would be good enough.

Thats also possible via the selected quoting button. just select a text and the selected quote button will appear

<img width="129" alt="quoting" src="https://user-images.githubusercontent.com/722575/76155687-bb0f1700-60ef-11ea-80d2-28399757c84f.PNG">

**Comment by JP58** [comment]
Ok, you mean this
![image](https://user-images.githubusercontent.com/5246746/76451025-15012c80-63cf-11ea-8c84-82dbdc6db4ab.png)

But that's not the normal way for general forum users to reply, esp on mobile devices... 
Users press what they see when they read a post. It's great though that the logic is there - just please add it to the post footer too by default so also the average forum user has a chance to select reply or quote instinctively.  ;-)

At least that's what I think... :-)

**Comment by Zero2Cool** [comment]
On my board, I disallow the repeated quote within a quote nonsense. The multi-quote is used quite a bit though to respond to several posts without creating multiple replies.

If each Display Post has Reply on it, I would assume that means quote and reply because you've selected that specific post to reply to.   I can see some confusion though. Are you adding a reply to the Topic? Are you adding a reply to a response within the Topic? Are you quoting someone and responding directly to them? There are several avenues that could be assumed.

**Comment by w8tcha** [comment]
The only option i would see is rename Quote to Reply (with Quote) and add Reply to the post or Reply (without Quote)
