### ISSUE TITLE
Change icon proposal

### ISSUE THREAD

**Issue by AlbertoP57** [YAFNET/YAFNET#544]
I would like to use the icon **fa-thumbtack** instead of **fa-sticky-note**. I could made the modifications but to avoid waste of time its better to discuss before to change the code.

How it looks now:
![image](https://user-images.githubusercontent.com/18015672/76207736-a0779380-61fe-11ea-83a0-3ba7af467a59.png)

My proposal 1:
![image](https://user-images.githubusercontent.com/18015672/76207780-b6855400-61fe-11ea-97f1-08f01da89dea.png)

Or (better) my proposal 2:
![image](https://user-images.githubusercontent.com/18015672/76207830-cd2bab00-61fe-11ea-8f8d-8b133d481184.png)

Or (even better for me almost sacrilege ...) my proposal 3:
![image](https://user-images.githubusercontent.com/18015672/76207935-006e3a00-61ff-11ea-9349-4c414ca78e1e.png)

In favor of discussion we can also check how important and modern sites such as steamcommunity deal with the issue:

![img1](https://user-images.githubusercontent.com/18015672/76208123-580ca580-61ff-11ea-858b-c9939d43952a.png)

**Comment by w8tcha** [comment]
icon change makes sense. but i propose a cleaner approach

![sticky](https://user-images.githubusercontent.com/722575/76291174-e428d680-62ac-11ea-83eb-3c38e4021467.png)
