### ISSUE TITLE
Suggestion - Prevent reply to member A by member B and vice versa. 

### ISSUE THREAD

**Issue by JP58** [YAFNET/YAFNET#546]
**Is your feature request related to a problem? Please describe.**
At least in my forum there are users that seem to like to drive eachother nuts... And they often come in pairs...  ;-) 

**Describe the solution you'd like**
If possible - some kind filter or such that prevents member A from replying to a post from member B. And of course then also member B from replying to member A.  Preferably a time-limited filter like suspension and such. Of course PM's too in the same filter.  Maybe it could be even be a user setting that would be a better user decision sometimes than "Hide posts from this member" in some cases. Would really be an addition as a choice for ignoring a particular member as some other forum software has, including all communication both ways but still seeing other posts from the opponent member. But I would certainly have it as a moderator option as the first choice. 

**Describe alternatives you've considered**
The moderate single user feature in the new version (have not implemented the 2.31 version yet in the "live" forum) could be enough, but that of course affects all new posts from a member and not the "member<->member grudges". Will also mean more manual moderator work to maintain.  It's quite a handful to have a forum full of grumpy old men, to be honest... 

**Additional context**
Today the moderators solve it by suspending members, but since the member in question may have fully valid contributions elsewhere in the forum that tool is too blunt for moderators.  The idea came from one of the moderators in my forum... 
![image](https://user-images.githubusercontent.com/5246746/76456245-00289700-63d7-11ea-8cff-bc5656b9047f.png)

**Comment by w8tcha** [comment]
I can't see how this would work? Who would decide who can reply which user?

Isn't the moderate user feature exactly what would solve the problem? Since the only way would be that a moderator look at the actual post.

**Comment by Zero2Cool** [comment]
> I can't see how this would work? Who would decide who can reply which user?

I personally cannot see much use in this, however, to implement it I think using the ignore feature would be a starting point. If User A is ignoring User B, they cannot reply to their posts and vice versa.

**Comment by w8tcha** [comment]
The only option i would see is rename Quote to **Reply (with Quote)**  and add **Reply** to the post or **Reply (without Quote)**
