### ISSUE TITLE
Main forum page access stats

### ISSUE THREAD

**Issue by AlbertoP57** [YAFNET/YAFNET#551]
**Describe the bug**
Wrong forum stats in main page when you set "access mask" for that forum

**To Reproduce**
1. Go to 'admin, settings, forum, edit...' and set a forum this way:
![image](https://user-images.githubusercontent.com/18015672/78752143-d631a880-7973-11ea-8444-a74614a2d20c.png)

I guess it means I want a user can read messages but not posts new. It works that way (cannot post) but in the main page I get:
![image](https://user-images.githubusercontent.com/18015672/78752396-535d1d80-7974-11ea-889f-eebd8032c21c.png)

0 topics and 0 posts? Why?

Further, if I come back to normal "member access" it still shows 0 to stats. 

**System (please complete the following information):**
 - YAF Version: YAF.NET 2.32 ALPHA 202002261318

**Comment by w8tcha** [comment]
The issue that caused this is fixed. However to restore the count you need to post a new message in this forum
