### ISSUE TITLE
Missing editor

### ISSUE THREAD

**Issue by AlbertoP57** [YAFNET/YAFNET#552]
**Describe the bug**
After the last sync there is no editor in posts anymore.

**To Reproduce**
![image](https://user-images.githubusercontent.com/18015672/78793832-3f84dc00-79b3-11ea-9621-2fef6adec4db.png)

this is the console error messages:
![image](https://user-images.githubusercontent.com/18015672/78794028-7d820000-79b3-11ea-9341-302c2b493761.png)

Any ideas?

TY

**System (please complete the following information):**
 - YAF Version: YAF.NET 2.32 ALPHA 202004081217

**Comment by w8tcha** [comment]
Did you clear the Brower cache?

**Comment by AlbertoP57** [comment]
Ctrl+R Usually I do it ... not today...
What an i$$$t!

Thank you
