### ISSUE TITLE
CKEditor doesn't work properly on the newest version

### ISSUE THREAD

**Issue by voquanghoa** [YAFNET/YAFNET#555]
**Describe the bug**
- New Topic: CKEditor doesn't work properly on the newest version

**To Reproduce**
- Clone the source code to local 
- Open the solution with Visual Studio 2019
- Fresh new install the forum: 
+ Some minor changes in config files (to make the forum works)
+ New database (and let the installer initialize it)
- Finish the installation and create a Topic in the Test Forum
- See the CKEditor doesn't display properly

![image](https://user-images.githubusercontent.com/10450325/79129388-5706ff00-7dcf-11ea-82ad-6ee27a817591.png)

**Some attempts:**

- I saw the web trying to download JQuery 3.5.0 from MS CDN but it doesn't exist 
![image](https://user-images.githubusercontent.com/10450325/79129679-dac0eb80-7dcf-11ea-803a-93ae62ac6d77.png)

Then I downgraded JQuery to the version 3.4.1 

- Download the newest version of CKEditor from [https://ckeditor.com/](https://ckeditor.com/) and replace the existing one (yafsrc\YetAnotherForum.NET\Scripts\ckeditor)

**System (please complete the following information):**
 - YAF Version: YAF.NET 2.32 BETA 202004130655 
 - .NET Version 4.7.2 (the default one)
 - SQL Server 15
 
**Affected browser**

✔️ Chrome
✔️  IE
* [ ] Firefox
* [ ] Safari
* [ ] Edge

I attached the patch file in the attachment. (Now I know GitHub doesn't allow me to upload a patch file, I named it .txt instead)

Thanks for investigation.
[changes.txt](https://github.com/YAFNET/YAFNET/files/4469989/changes.txt)

**Updates**

I found this similar issue here https://github.com/YAFNET/YAFNET/issues/552 and my answer is yes, I clean cache but it doesn't help
![image](https://user-images.githubusercontent.com/10450325/79131358-b31f5280-7dd2-11ea-82c2-80ceb8d26dc3.png)

**Comment by w8tcha** [comment]
You can ignore the jquery issue. it automatically fallback to the local jquery file if the cdn is not available!

**Comment by w8tcha** [comment]
Did you get the same eror on the editor demo page?

**Comment by voquanghoa** [comment]
> You can ignore the jquery issue. it automatically fallback to the local jquery file if the cdn is not available!

Thanks for letting me know about it. I really appreciate it. But I just tried to fix the CKEditor issue. 

Do you able to reproduce the issue?

The demo page: https://ckeditor.com/ckeditor-4/demo/, it works properly.

**Comment by voquanghoa** [comment]
My friend started using the framework to build a forum and he got this issue on his computer.

I tried by my-self on my PC and yes, even we worked separately (different PC, I don't know his steps) but the issue is the same.

**Comment by w8tcha** [comment]
> Do you able to reproduce the issue?

No. By the way if you want to use the forum then you should use the stable branch not the master branch. The master branch is beta

**Comment by w8tcha** [comment]
Is the language set in the forum ? or the default language is set?

**Comment by voquanghoa** [comment]
> > Do you able to reproduce the issue?
> 
> No. By the way if you want to use the forum then you should use the stable branch not the master branch. The master branch is beta

This reply is useful. I switched to the branch stable and ... it works!!

![image](https://user-images.githubusercontent.com/10450325/79136651-8d4a7b80-7ddb-11ea-808a-5fda05b0612e.png)

I couldn't access the Install page because ... hmm

![image](https://user-images.githubusercontent.com/10450325/79136589-760b8e00-7ddb-11ea-9aa4-505821801721.png)

It can't be accessed from my side

![image](https://user-images.githubusercontent.com/10450325/79136744-b8cd6600-7ddb-11ea-88c1-ba07ffad6266.png)

I hope you can fix it soon.

Thanks.
