### ISSUE TITLE
"Similar Topics" deleted still visible

### ISSUE THREAD

**Issue by vubiz-am** [YAFNET/YAFNET#556]
**Describe the bug**
I deleted a couple of posts and while they disappeared from the main list they still appear in the "similar posts" area. 

I cleared the cache but that didn't work so I also tried restarted the app but the topic that was deleted still shows under "Similar Topics" and when you try to click the link to the deleted topic you get error

**To Reproduce**
1. Make posts
2. Check "Similar Topics", post should be here
3. Delete these posts
4. Check again "Similar Topics", posts still visible

**Expected behavior**
"Similar Topics", has to be cleared from deleted posts

**Screenshots**

**System (please complete the following information):**
 - YAF Version: [e.g. YAF v2.31.2]
 - .NET Version [e.g. 4.7.2]
 - SQL Server [e.g. SQL Server 2012]
 
**Affected browser**
All

**Additional context**
----

**Comment by w8tcha** [comment]
Thanks. Issue will be fixed in 2.31.3. However you need to re-index the search

**Comment by vubiz-am** [comment]
Thanks!
