### ISSUE TITLE
Suggestion: privacy

### ISSUE THREAD

**Issue by AlbertoP57** [YAFNET/YAFNET#557]
**Is your feature request related to a problem? Please describe.**
When YAF Forum was born there was no need for privacy.
Nowadays it has become important. Each company must have its own privacy policy.

**Describe the solution you'd like**
Make small adjustments to the current privacy management.

A) The link description is correct ("Privacy policy") but the effective link is "Rules" (as the destination page is): 

![image](https://user-images.githubusercontent.com/18015672/79337691-41f0b400-7f26-11ea-96f3-ebefb76befbd.png)

It would be fair if the landing page was called "privacy" (instead of "rules").

B) Instead of the current description contained in the [language.xml] file, it would be advisable to use an external ad-hoc file. You know, in Europe there are very strict rules; each company must publish its own regulation.
I do not think it would be appropriate to modify the language file but to create a kind of "template" that can be modified by the forum administrator. Possibly, if the template does not exist, the text contained in the language file (as it is now) should be displayed.

I could write my personal change but I think it would be appropriate to equip the YAF Forum with a global tool.

Alberto

**Comment by w8tcha** [comment]
> It would be fair if the landing page was called "privacy" (instead of "rules").

The Page Title is "Forum Roules and Policies" so the page name should be RulesAndPrivacy

> Instead of the current description contained in the [language.xml] file, it would be advisable to use an external ad-hoc file. You know, in Europe there are very strict rules; each company must publish its own regulation.

But this would cause problems you would need a template file for each language. People customize their language files for years
