### ISSUE TITLE
Support Unicode for Admin Features

### ISSUE THREAD

**Issue by voquanghoa** [YAFNET/YAFNET#559]
Hello,

I have installed the forum on my server and I found that some Admin features like Categories And Forums, if I enter a Unicode text and hit Save, the text will error and display the question mark ??? instead of the origin one

If I enter the Unicode text directly in the database, it will display properly

See my screenshots:

What I entered

![image](https://user-images.githubusercontent.com/10450325/79442758-2a3b2d80-8003-11ea-8efd-3485409c57da.png)

I received

![image](https://user-images.githubusercontent.com/10450325/79442944-63739d80-8003-11ea-86ec-55e228b86b3c.png)

The issue does not occur with normal user's feature because when I enter Unicode in My Profile settings or Create a new Post, I can enter Unicode text and it works, no error.

Could you help me to check on this?

Thanks.

Other information

**System (please complete the following information):**
 - YAF Version: YAF.NET 2.31.2
 - .NET Version 4.0
 - SQL Server: Sql 2019 (version 15)

**Affected browser**
* [*] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge

**Culture:** Vietnamese: Tiếng Việt (Việt Nam)

**Comment by w8tcha** [comment]
Thanks for the Report. Issue will be fixed in 2.31.03
