### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by AlbertoP57** [YAFNET/YAFNET#560]
**Describe the bug**

After the latest sync:
1) home page is mis-aligned (but I guess its easy to solve)
2) error when access to a category:
![image](https://user-images.githubusercontent.com/18015672/79742168-b6e73380-8302-11ea-9b36-3fbdaa917ec7.png)

**System (please complete the following information):**
![image](https://user-images.githubusercontent.com/18015672/79741939-6079f500-8302-11ea-8da0-d26e32e8125b.png)

**Comment by w8tcha** [comment]
Look like you forgot to run the upgrade wizard

**Comment by Zero2Cool** [comment]
> Look like you forgot to run the upgrade wizard

I ran the update wizard and I still got the error.  To get my testing to begin, I just renamed `ParentForumdId` to `ForumId` :D

**Comment by w8tcha** [comment]
In that case restart the app or clear the application cache

**Comment by Zero2Cool** [comment]
> In that case restart the app or clear the application cache

I'm not sure that would have made a difference. I downloaded the source and had it running from my desktop. 🤷‍♂️🤷🏻‍♂️

**Comment by AlbertoP57** [comment]
> Look like you forgot to run the upgrade wizard

As Zero2Cool did I ran it too. Versions (before and after) are anyway the same (75 if I dont remeber bad). Maybe there is something in the install procedure.

> In that case restart the app or clear the application cache

VS2019 in desktop?

**Comment by w8tcha** [comment]
> I'm not sure that would have made a difference.

Restarting the iis application or clear the application cache would clear the cache, because otherwise the date will not be reloaded

**Comment by Zero2Cool** [comment]
> > I'm not sure that would have made a difference.
> 
> Restarting the iis application or clear the application cache would clear the cache, because otherwise the date will not be reloaded

Yeah, that wouldn't have made a difference.  (I just had restarted my computer before coding so restarting IIS wouldn't be the issue).   Well, let me ask this. What would clearing the application cache, or restarting IIS accomplish?

**Comment by w8tcha** [comment]
> What would clearing the application cache, or restarting IIS accomplish?

The user data is stored in the cache, clearing the cache reloads the data

**Comment by AlbertoP57** [comment]
> I ran the update wizard and I still got the error. To get my testing to begin, I just renamed `ParentForumdId` to `ForumId` :D

To get rid I modified the code (inside UserPageBase.cs -> PageValueAsInt):
`if (this.Page?[field] != null)
{
    return this.Page[field].ToType<int>();
}
return 0;
`
with
`object ret;
if (this.Page.TryGetValue(field, out ret))
    return ret.ToType<int>();
else
    return 0;
`

Now it works. But why the key is missing? The upgrade shows me the version 75.

**Comment by Zero2Cool** [comment]
> Now it works. But why the key is missing? The upgrade shows me the version 75.

Try restarting IIS and the other steps @w8tcha suggested. I don't see how it'll help personally, but he's much more knowledgeable about this application than I could ever imagine being!

**Comment by AlbertoP57** [comment]
You had the error and resolved restarting IIS?
I am not on the production server. I am working on desktop pc with vs 2019. I restarted the PC, I cleared the only cache available to VS:
C:\Users\XXX\AppData\Local\Microsoft\VisualStudio\16.0_a0cd3bc7\ComponentModelCache

But no way. I guess the reason is in the db I am working with (an old, converted, db).

**Comment by Zero2Cool** [comment]
Is that parameter supposed to be pulled in from the database or is it stored in the UI or ... where does it get persisted from?  If it's in the database, we can easily see if the update wizard failed to procure the field.

**Comment by w8tcha** [comment]
I updated the appversion to 77 (76 is the current release 2.31.3) but be aware the appversion will be only increased for releases, not for every commit. If there is a commit where a db script is changed you guys need to run the upgrade wizard manually.

And yes restart iis would also clear the cache

**Comment by Zero2Cool** [comment]
> I updated the appversion to 77 (76 is the current release 2.31.3) but be aware the appversion will be only increased for releases, not for every commit. If there is a commit where a db script is changed you guys need to run the upgrade wizard manually.
> 
> And yes restart iis would also clear the cache

I ran the update wizard manually. Did I need to change the number in the query string?

**Comment by w8tcha** [comment]
> > I updated the appversion to 77 (76 is the current release 2.31.3) but be aware the appversion will be only increased for releases, not for every commit. If there is a commit where a db script is changed you guys need to run the upgrade wizard manually.
> 
> > 
> 
> > And yes restart iis would also clear the cache
> 
> 
> 
> I ran the update wizard manually. Did I need to change the number in the query string?

No thats not necessary

**Comment by w8tcha** [comment]
Can we close this issue?

**Comment by AlbertoP57** [comment]
Today I haven't had time too. Tomorrow I will try with an old database.

**Comment by w8tcha** [comment]
Sorry looks like i copied the code to the wrong sp. Issue is fixed now. Running the Upgrade wizard is required.
