### ISSUE TITLE
two columns?

### ISSUE THREAD

**Issue by AlbertoP57** [YAFNET/YAFNET#561]
After wasting time because I was thinking about a mistake, I saw that it was wanted. There is a commit with title:
**Refactoring and UI changes forum layout has now 2 columns**

So, suddenly, we now have that horrible main page.

No proposal, no discussion, nothing at all? Just did it?

You often say that the forum is **_yours_**. 
My precious! (Gollum). In a post you said you are the only forum developer ...

**Comment by Zero2Cool** [comment]
You can change the layout so it doesn't have two columns. It's done via bootstrap so it's quite simple.  I don't think Ingo has time to submit a proposal for every idea he has. Keep in mind, this is done in the beta branch. So he works his tail off, comes up with ideas, implements them and sees how they go. He relies on community feedback for approval or disapproval.  

Also, it's open source, make the changes. I have made a plethora that I have to replicate each time I merge current YAF into my stuff. :-)

**Comment by w8tcha** [comment]
> No proposal, no discussion, nothing at all? Just did it?

Well there is a discussion now! This software is beta. i try out stuff and see if it works. If you dont like the two column layout we could make a setting for it.

i tested this  because i stole this form the famous invision board. which is still the no1 forum software.

**Comment by Zero2Cool** [comment]
> i tested this because i stole this form the famous invision board. which is still the no1 forum software.

If you want to mimic a board, try XenFor https://xenforo.com/community/

**Comment by AlbertoP57** [comment]
Well. I am getting low popularity. There are 3 users here and I am 1v2. 
Please accept my apologies ... I'd like to explain better: 

The main disadvantage of "old" forums was the "fixed" layout (900px, 1000px, etc).

Finally we have the power of bootstrap that recognize for us the width of the page and waste 4/12 of the screen width with unnecessary infos?

Some forums use the right sidebar to advertise inside. But this is an open source project! No advertising ;)

> You can change the layout so it doesn't have two columns. It's done via bootstrap so it's quite simple.

I know bootstrap ;) But I don't want to keep too many changes.

> If you dont like the two column layout we could make a setting for it.

This could be an idea.

**Comment by w8tcha** [comment]
> Finally we have the power of bootstrap that recognize for us the width of the page and waste 4/12 of the screen width with unnecessary infos?

Atleast for me the active discussion is the most important info. And the first place I look at. And I prefer replacing empty space with content instead of scrolling

**Comment by Zero2Cool** [comment]
> Well. I am getting low popularity. There are 3 users here and I am 1v2.
> Please accept my apologies ... I'd like to explain better:
Please do not view it like this.  There is no versus here. Everyone contributing to this has the same end goal, making YAF better.  

I'm not warm to the multiple columns concept. I've always been a very symmetrical designer. Some have said it's OCD, lol.   But, with wide-screen monitors so readily available and in use, I understand the desire to put more content on the initial top level view.   In all actuality, I would rather the landing page be completely different.  (e.g. landing page show latest 20 posts that user has access to view).
