### ISSUE TITLE
ThemeButton.cs error

### ISSUE THREAD

**Issue by AlbertoP57** [YAFNET/YAFNET#563]
**Describe the bug**
Using the last code I get this error:

![image](https://user-images.githubusercontent.com/18015672/81702451-97f44100-946b-11ea-9d61-d1ffbbcd1502.png)

for each link I follow from the main page. 

To continue I modified the code:
![image](https://user-images.githubusercontent.com/18015672/81703083-69c33100-946c-11ea-9d6d-b9c0a09d942f.png)

But I don't know if it makes sense...

**Comment by w8tcha** [comment]
should be fixed now

**Comment by AlbertoP57** [comment]
even worse (:

now I cannot neither build the app (first error is  in Services\SendNotification.cs missing namespace Identity)

![image](https://user-images.githubusercontent.com/18015672/81714978-f6bfb780-9477-11ea-83e5-b0344da65e2e.png)

**Comment by w8tcha** [comment]
Just wait a few days until I finish making the changes. Or use the stable branch for now

**Comment by w8tcha** [comment]
issue is fixed now
