### ISSUE TITLE
error in HelpLabel.cs

### ISSUE THREAD

**Issue by AlbertoP57** [YAFNET/YAFNET#566]
Admin mode
Host -> Host Settings

it raises an error in HelpLabel.cs

when:
this.LocalizedPage = "ADMIN_HOSTSETTINGS"
this.LocalizedTag = "USRSTATS_CACHE_TIMEOUT"

To be able to do something I added this but I guess it's not the solution ... 

![image](https://user-images.githubusercontent.com/18015672/82216301-1132de80-9919-11ea-83d6-9551756ea474.png)

**Comment by w8tcha** [comment]
I cant reproduce the issue. Since the exception should be handled. what exception are you getting?

**Comment by AlbertoP57** [comment]
True,

![image](https://user-images.githubusercontent.com/18015672/82224524-36791a00-9924-11ea-9551-0496057997e7.png)

maybe it is a VS2019 issue. I unchecked the checkbox and all goes on. The 15 days ago version had not that problem. That's why I have point it.

**Comment by w8tcha** [comment]
i think its because the checkbox is checked. in your visual studio (as seen in the picture) otherwise the issue would be handled by the try catch block

**Comment by AlbertoP57** [comment]
Maybe. I like to be notified of null reference. I remember I set it time ago. Honestly I havent noticed it was a global option. Sorry for this issue.
