### ISSUE TITLE
cannot register new user anymore

### ISSUE THREAD

**Issue by AlbertoP57** [YAFNET/YAFNET#567]
Using a clean database. I cannot create a new account. When I ask to register he continues to loop:

http://localhost:50165/RulesAndPrivacy

**Comment by w8tcha** [comment]
does it work when you add the causesvalidation="False attribute to the Accept button on the rulesandprivacy page?

**Comment by AlbertoP57** [comment]
yes 
![image](https://user-images.githubusercontent.com/18015672/82228238-2e6fa900-9929-11ea-8d93-5a4aaaeab8e9.png)
it goes on.

P.S. (1): Maybe not related but I had to add the key:

`<add key="ValidationSettings:UnobtrusiveValidationMode" value="None" />`

in appSettings. 

P.S. (2): Time ago I modified the login form and you accepted it. It was this one:
![image](https://user-images.githubusercontent.com/18015672/82229491-ccb03e80-992a-11ea-837d-53b10945fccf.png)

Now you turn back to the old one. 
![image](https://user-images.githubusercontent.com/18015672/82229562-e81b4980-992a-11ea-93b5-6d59ac62335f.png)

**Comment by w8tcha** [comment]
What you mean with g on? Does this fix the issue or not?

Why you need to add that setting?

**Comment by w8tcha** [comment]
> P.S. (2): Time ago I modified the login form and you accepted it. It was this one:

That page is a completely rewrite. Sorry I didn't Lok at te old page wihbthe login form

**Comment by AlbertoP57** [comment]
> What you mean with g on? Does this fix the issue or not?

👍  Yes. With CausesValidation = "false" it works. I can join now. 
When clicking the red button (" I do not agree to these Rules and Policies") would it be better it was redirected to the home page?

> 
> Why you need to add that setting?

Because of this error:
![image](https://user-images.githubusercontent.com/18015672/82295673-64a43b80-99b0-11ea-90d4-d1295d27fdd4.png)

I have googled the error and that was just the first working suggestion.

**Comment by w8tcha** [comment]
> When clicking the red button (" I do not agree to these Rules and Policies") would it be better it was redirected to the home page?

this should work if the causesvalidation is added

**Comment by w8tcha** [comment]
> I have googled the error and that was just the first working suggestion.

I guess the better solution would be to move the jquery scriptreference to application_Start

**Comment by w8tcha** [comment]
I moved the scriptdefinition to Application_Start. this should resolve the issue

**Comment by AlbertoP57** [comment]
👍 

all its working now.
TY
