### ISSUE TITLE
jquery.ForumExtensions Error

### ISSUE THREAD

**Issue by john2014** [YAFNET/YAFNET#571]
YAF Version: 2.31.6
Browser: Any

From the homepage, menu was not working correctly (sub menu option did not open). Do I looked at browser console and saw the error message:

TypeError: (intermediate value)(...) is not a function
jquery.ForumExtensions.min.js:327:117021
    <anonymous> jQuery

You already have the link to my site. If you view console, after loading default2.aspx or default.aspx, you will see the console error message.

**Comment by w8tcha** [comment]
Issue will be fixed in 2.31.07
