### ISSUE TITLE
Error posting 2nd ad

### ISSUE THREAD

**Issue by john2014** [YAFNET/YAFNET#572]
YAF: 2.31.6

If you goto Host Settings > Advert Settings, enter any html code 

Example: &lt;test&gt; and click Save

System gives error message:

A potentially dangerous Request.Form value was detected from the client (ctl00$cph$forum$ctl03$IPLocatorUrlPath="...city/?key=<your_api_key>&ip={0...").

**Comment by w8tcha** [comment]
Make Sure page validation is disabled in the web.config or the default.aspx

The default.aspx should have `ValidateRequest="false"` attribute set

**Comment by john2014** [comment]
I do have validaterequest=false in default.aspx. It is still giving this error message.

Could you kindly test this in in your machine as follows: Add validaterequest=false in default.aspx. But do not add validaterequest in web.config (since we need to validate request for rest of the site)

**Comment by w8tcha** [comment]
I have validateRequest set to true in the web.config. And to false on the page with the forum control. And it works. The aspx page override a the web.config.

Can you post your web.config?

**Comment by john2014** [comment]
Here is the web.config: 

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="rewriter" type="YAF.UrlRewriter.Configuration.RewriterConfigurationSectionHandler, YAF.UrlRewriter" requirePermission="false" />
  </configSections>
  <connectionStrings configSource="db.config" />
  <appSettings configSource="app.config" />
  <rewriter configSource="URLRewriter.config" />
  <system.net>
    <mailSettings>
      <smtp configSource="mail.config" />
    </mailSettings>
  </system.net>

  <system.web>
    <httpRuntime />
    
    <customErrors defaultRedirect="~/global/Error.aspx" mode="RemoteOnly">
   </customErrors>

    <globalization culture="en-US" uiCulture="en" requestEncoding="UTF-8" responseEncoding="UTF-8" fileEncoding="UTF-8" />

    <authentication mode="Forms">
      <forms name=".YAFNET_Authentication" protection="All" timeout="43200" cookieless="UseCookies" />
    </authentication>

    <compilation debug="false" targetFramework="4.7.2">
      
      <assemblies>
        <add assembly="netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" />
      </assemblies>
    </compilation>

    <httpHandlers>
      <add verb="GET" path="Resource.ashx" type="YAF.Core.Handlers.ResourceHandler, YAF.Core" />
    </httpHandlers>
    <httpModules>
      <add name="TaskModule" type="YAF.Core.TaskModule, YAF.Core" />
      <add name="UrlRewriter" type="YAF.UrlRewriter.RewriterHttpModule,YAF.UrlRewriter" />
    </httpModules>

    <pages clientIDMode="AutoID">
      <controls>
        <add tagPrefix="asp" namespace="System.Web.UI" assembly="System.Web.Extensions" />
        <add tagPrefix="asp" namespace="System.Web.UI.WebControls" assembly="System.Web.Extensions" />
        <add tagPrefix="asp" namespace="System.Web.UI.HtmlControls" assembly="System.Web"/>
        
        <add tagPrefix="YAF" namespace="YAF" />
        <add tagPrefix="YAF" namespace="YAF.Configuration" />
        <add tagPrefix="YAF" namespace="YAF.Web.Controls" assembly="YAF.Web" />
      </controls>
      <namespaces>
        <add namespace="YAF.Core" />
        <add namespace="YAF.Utils" />
        <add namespace="YAF.Types.Interfaces" />
        <add namespace="YAF.Types" />
        <add namespace="YAF.Web.Controls" />
      </namespaces>
    </pages>

    <membership defaultProvider="YafMembershipProvider" hashAlgorithmType="SHA1">
      <providers>
        <clear />
        
        <add name="YafMembershipProvider" applicationName="YetAnotherForum" connectionStringName="yafnet" requiresUniqueEmail="true" useSalt="true" type="YAF.Providers.Membership.YafMembershipProvider"/>
        
        <add name="AspNetSqlMembershipProvider" applicationName="YetAnotherForum" connectionStringName="yafnet" enablePasswordReset="false" enablePasswordRetrieval="true" maxInvalidPasswordAttempts="5" minRequiredNonalphanumericCharacters="0" minRequiredPasswordLength="5" passwordAttemptWindow="15" passwordFormat="Encrypted" requiresQuestionAndAnswer="false" requiresUniqueEmail="true" type="System.Web.Security.SqlMembershipProvider" />
      </providers>
    </membership>

    <roleManager enabled="true" defaultProvider="YafRoleProvider">
      <providers>
        <clear/>
        
        <add name="YafRoleProvider" applicationName="YetAnotherForum" connectionStringName="yafnet" type="YAF.Providers.Roles.YafRoleProvider"/>
        
        <add name="AspNetSqlRoleProvider" applicationName="YetAnotherForum" connectionStringName="yafnet" type="System.Web.Security.SqlRoleProvider"/>
      </providers>
    </roleManager>

    <profile enabled="true" defaultProvider="AspNetSqlProfileProvider" inherits="YAF.Utils.YafUserProfile">
      <providers>
        <clear />
        <add name="AspNetSqlProfileProvider" applicationName="YetAnotherForum" connectionStringName="yafnet" type="System.Web.Profile.SqlProfileProvider"  />
      </providers>
    </profile>
    <machineKey validationKey="3C29AB6D26BF5B247CF4603839B32545DC5FB15CF0D02CF39E6FAEABF407FE3A99AABC221A24D696E32A1C776FAF2544FCCD533B5867A31FA86B4F4E386727E6" decryptionKey="D286FE1059ED951D0F02689C9864DBBBD2EF4F9C51243BD809326B4163A78EBC" validation="SHA1" decryption="AES"/>
    <webServices>
      <protocols>
        <add name="HttpGet" />
        <add name="HttpPost" />
      </protocols>
    </webServices>
  </system.web>

  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="bin;bin\languages" />
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
        <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="12.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Primitives" publicKeyToken="ADB9793829DDAE60" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-3.1.4.0" newVersion="3.1.4.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="B03F5F7F11D50A3A" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.0.6.0" newVersion="4.0.6.0"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>

  <system.webServer>
    <validation validateIntegratedModeConfiguration="false" />
    <modules>
      <remove name="TaskModule" />
      <remove name="UrlRewriter" />
      <add name="TaskModule" type="YAF.Core.TaskModule, YAF.Core" preCondition="managedHandler" />
      <add name="UrlRewriter" type="YAF.UrlRewriter.RewriterHttpModule,YAF.UrlRewriter" preCondition="managedHandler" />
    </modules>
    <handlers>
      <add name="YafHandler" preCondition="integratedMode" verb="GET" path="Resource.ashx" type="YAF.Core.Handlers.ResourceHandler, YAF.Core" />
      <add name="YafSitemapHandler" path="Sitemap.xml" verb="*" type="YAF.Core.Handlers.SiteMapHandler, YAF.Core" preCondition="integratedMode" />
      <add name="FileUploader" path="FileUploader.ashx" verb="*" type="YAF.Core.Handlers.FileUploader, YAF.Core" preCondition="integratedMode" />
    </handlers>
  </system.webServer>
</configuration>

**Comment by w8tcha** [comment]
<httpRuntime requestValidationMode="2.0" />

What happens if you set the requestvalidationmode?

**Comment by john2014** [comment]
I added pages validatereuest=false in web.config and still got the same server error message

Requestvalidationmode wont be applicable here?

**Comment by w8tcha** [comment]
Sorry the code was removed, now you should see the line

**Comment by john2014** [comment]
Are you also able to add any html tag in the 2nd post ads?

**Comment by john2014** [comment]
> 
> 
> Sorry the code was removed, now you should see the line

Which line should I see? and in which file (web.config)?

**Comment by w8tcha** [comment]
replace line 

` <httpRuntime />`

With 

`<httpRuntime requestValidationMode="2.0" />`

**Comment by john2014** [comment]
Now the Host settings page is empty.

Browser console error:

```
Loading failed for the <script> with source “../Scripts/jquery-3.4.1.js”. default2.aspx:61:1
Loading failed for the <script> with source “../Scripts/jquery.ForumAdminExtensions.js?v=1”. default2.aspx:62:1
ReferenceError: jQuery is not defined
default2.aspx:2197:1
Empty string passed to getElementById(). 1250 autofill.js:252:20
```

​

Here is screenshot: 

![Screenshot_2020-06-17 Green Card Forum - Administration - Host Settings](https://user-images.githubusercontent.com/5694946/84968551-99003a00-b0cb-11ea-8548-ba08eba576aa.png)

**Comment by w8tcha** [comment]
At the moment I have no more ideas how to relive this.

It works without problems on all my sites live and demo.

I tr3to reproduce the issue on the weekend

**Comment by john2014** [comment]
Never mind, I was able to resolve it successfully. Per your suggestion, I added the requestvalidationmode in web.config and that solved this issue.
