### ISSUE TITLE
Register with FB/Twtr/Google gives error

### ISSUE THREAD

**Issue by john2014** [YAFNET/YAFNET#574]
In the register page, when I click on Register with Fb/Twtr/Google, I get the error:

Object reference not set to an instance of an object.

Screenshot

![Screenshot_2020-06-19 Object reference not set to an instance of an object ](https://user-images.githubusercontent.com/5694946/85172623-51da8c00-b226-11ea-8acc-3565cc2627f6.png)

**Comment by w8tcha** [comment]
Odd this feature should be disabled. Maybe I need to remove it completely in yaf 2.31.7

**Comment by john2014** [comment]
Is sign on with google, twittter, etc no longer supported?

The app.config file and YAF wiki still lists those options as available.

https://github.com/YAFNET/YAFNET/wiki/Google-Integration

Also If social media sign on is not supported, how do we disable it? Remove keys from app.config or through forum settings (where to find them) or both?

**Comment by w8tcha** [comment]
You only need to go to the host settings and disable single sign on under login settings.

At the moment it is broken. And as on the wiki pages described you need yaf 3.00

**Comment by john2014** [comment]
Ok, I noticed in that wiki page, you have now changed/updated single sign on from YAF 2.0 to YAF 3.0
