### ISSUE TITLE
Error Message: Jquery.popover is not a function

### ISSUE THREAD

**Issue by john2014** [YAFNET/YAFNET#576]
On the YAF forum landing page when I view the browser console on my site (default.aspx), in addition to issue #571, I also see another error message:

TypeError: jQuery(...).popover is not a function

The error occurs in this line in default.aspx:

`jQuery('.forum-icon-legend-popvover').popover({html:true,content:"\r\n\r\n<ul class='list-group list-group-flush'>\r\n    <li class='list-group-item d-flex align-items-center'>\r\n        <span class='fa-stack'>        \r\n        <i class='fas fa-comments fa-2x text-success'></i>&nbsp;\r\n        </span>\r\n        <span>\r\n            New Posts\r\n        </span>\r\n    </li>\r\n    <li class='list-group-item d-flex align-items-center'>\r\n        <span class='fa-stack'>        \r\n        <i class='fas fa-comments fa-2x text-secondary'></i>&nbsp;\r\n        </span>            \r\n        <span>\r\n            No New Posts\r\n        </span>\r\n    </li>\r\n    <li class='list-group-item d-flex align-items-center'>\r\n        <span class='fa-stack small'>\r\n            <i class='fas fa-comments fa-stack-2x text-secondary'></i>\r\n            <i class='fas fa-lock fa-stack-1x text-warning' style='position:absolute; bottom:0 !important;text-align:right;line-height: 1em;'></i>\r\n        </span>&nbsp;\r\n        <span class='align-bottom'>\r\n            Forum Locked\r\n        </span>\r\n    </li>\r\n</ul>",trigger:"focus hover"});`

and this line:

`
jQuery('.topic-link-popover').popover({title:'Last Post&nbsp;by ...',html:true,trigger:'focus hover',template:'<div class="popover" role="tooltip"><h3 class="popover-header"></h3><div class="arrow"></div><div class="popover-body"></div></div>'});jQuery('.topic-link-popover').on('inserted.bs.popover',function(){jQuery('.popover-timeago').each(function(){jQuery(this).html(function(index,value){return moment(value).fromNow();});jQuery(this).removeClass('popover-timeago');});})`

**Comment by w8tcha** [comment]
its caused be the same issue as #570. will be fixed in 2.31.7
