### ISSUE TITLE
Unable to view user profile - From active discussion

### ISSUE THREAD

**Issue by john2014** [YAFNET/YAFNET#577]
1. Goto forum landing page.
2. Scroll down to active discussion.
3. Click on any username

Expected: User profileto open
Actual: The page simply reloads.

Another bug is that username link should not be a post. It should be directly linked to their profile (so that we can right click and open link in new window). Opening in new window is useful when we want to ban users posting spam.

**Comment by w8tcha** [comment]
Duplicate issue.  Same as #576

You could resolve this by downloading the stable branch and update the Jquery.forumextensions.min in your forum
