### ISSUE TITLE
Ban Users - From Active Discussions

### ISSUE THREAD

**Issue by john2014** [YAFNET/YAFNET#578]
The best way to check if users has posted spam is to scroll down to active discussion. 

If they have posted spam and we want to ban them, currently we have to do lots of click to goto Admin User section. In older version of forum, Admin Users was one click away.

Suggestion: In active discussion, when an admin clicks on user name, show a popup with a new link called Admin User. We can click this link (in new window; if there are lots of spams) and ban users quickly.

**Comment by w8tcha** [comment]
> If they have posted spam and we want to ban them, currently we have to do lots of click to goto Admin User section. In older version of forum, Admin Users was one click away.

The logic is still the same only the menu button edit user has been moved. when you view a post right click (or click on the 3 dots on the right) and click **edit user**

**Comment by john2014** [comment]
Is there an option to admin users that from "Active Discussion"; instead of opening every post, scrolling down and find users and then right click and edit user.

In the older version 2.0 there used to be a way to Admin User from Active Discussion.

**Comment by w8tcha** [comment]
Well there was never such option.

> Is there an option to admin users that from "Active Discussion"; instead of opening every post, scrolling down and find users and then right click and edit user.

Well in that case you can check if the content is actually spam.

Otherwise you could also enable bot checking, in that case the users would be automatically banned on register or before they post. In that case you have to do nothing
