### ISSUE TITLE
Banned users appearing in active users lists

### ISSUE THREAD

**Issue by john2014** [YAFNET/YAFNET#579]
If we ban a user from forum (for posting too many spam posts), they are still appearing in active users list. In addition, when we click on that users, it redirects to error message (since we have banned and deleted user).

Please remove all banned/deleted users from active users list. 

Also please remove them from "Last post today by <spammer>" list located below active discussion as well as "The newest member is <spammer>"

**Comment by w8tcha** [comment]
the stats are cached. As workaround wait 15 minutes or clear the cache in the host settings.
