### ISSUE TITLE
Sitemap.xml been overwriten

### ISSUE THREAD

**Issue by john2014** [YAFNET/YAFNET#580]
I have set my custom sitemap.xml file on the server. But it seems YAF is overwriting that file with its own data. How do I stop YAF from creating custom sitemap.xml file in root folder?

Here is the format of YAF generated sitemap.xml. This file is been served even though I have my custom sitemap.xml (it seems url rewriting is redirecting request to this file and generating its own file).

`<urlset>
<url>
<loc>
https://www.example.com/forum/sitemap.xml?g=topics&f=1
</loc>
<changefreq>always</changefreq>
<lastmod>2014-03-18T02:54:16.72</lastmod>
<priority>0.8</priority>
</url>
<url>
<loc>
https://www.example.com/forum/sitemap.xml?g=topics&f=2
</loc>
<changefreq>always</changefreq>
<lastmod>2019-08-23T06:58:34.58</lastmod>
<priority>0.8</priority>
</url>
</urlset>`

**Comment by w8tcha** [comment]
This can be easily resolved by removing the sit map handler from the web.config. Just search for the sit map handler line in the web.config and remove it

**Comment by john2014** [comment]
Thank you. That solved the issue.

BTW, google search console says there are many errors in that sitemap.xml file generated by YAF. So I looked closely and the error is in lastmod tag. 

Current: <lastmod>2020-03-18T12:58:30.223</lastmod>
Expected: <lastmod>2020-03-18T12:58:30</lastmod>

The bug is that is is adding milliseconds at end (30.223 should be 30)

**Comment by w8tcha** [comment]
It should be 2020-08-24T09:18:38-04:00 According to the [w3c time](https://www.w3.org/TR/NOTE-datetime) . Issue is fixed in 2.31.7
