### ISSUE TITLE
Farsi Library Upgrade

### ISSUE THREAD

**Issue by john2014** [YAFNET/YAFNET#581]
Visual Studio tells me that there is an update for Farsi Library. Is this library used by YAF?

Current installed version: 2.5.1.5
Updated version: 2.7.0 (published on Feb 2017).

Could you update this library to latest version?

**Comment by w8tcha** [comment]
which project in your source points to the old version ? If I look at the source all projects reference to latest version. Also the install packages include the latest version.

Looks like your source is not updated

**Comment by john2014** [comment]
I removed the entire /Bin and /Forum directory and copied it from source code. I am not sure which sourcecode is pointing to older version (and also where it is finding the old version).

**Comment by w8tcha** [comment]
>  I am not sure which sourcecode is pointing to older version (and also where it is finding the old version).

then why to you think that yaf uses an old version? Sorry but i dont unterstand the problem

**Comment by john2014** [comment]
In visual studio, under nuget manager, it says there is an update for Farsi library. In addition, nuget manager gives following info:

Current installed version: 2.5.1.5
Updated version: 2.7.0 (published on Feb 2017).

**Comment by w8tcha** [comment]
If you click on it to upgrade it would show you which project of yaf is outdated.

But again it looks like your source is not up to date. I downloaded the Source Package again and there is no reference of the old version

**Comment by john2014** [comment]
Only yaf project is using this library. If I click to upgrade, it would overwrite the dll files in /Bin folder. I am not sure if that could cause some errors?

**Comment by w8tcha** [comment]
> Only yaf project is using this library.

This means that the packages.config (in the YetAnotherForum.NET folder) is outdated

**Comment by john2014** [comment]
ok, since you confirmed its upgraded on your end and there are no issues with manually updating, I will close this.
