### ISSUE TITLE
Profile maked as noindex

### ISSUE THREAD

**Issue by john2014** [YAFNET/YAFNET#582]
All the user profiles (/forum/default.aspx?g=profile&u=XX) have a noindex,nofollow in meta tags. How can we disable those?

**Comment by w8tcha** [comment]
This can only be disabled from the source, And it should not be disabled.

**Comment by john2014** [comment]
I would like to disable that due to social network type site. Could you tell me which file and which folder this code is present in? Thank you.

**Comment by w8tcha** [comment]
Change line from...

` else if (this.ForumPageType != ForumPages.forum && this.ForumPageType != ForumPages.topics)`

to

`else if (this.ForumPageType != ForumPages.forum && this.ForumPageType != ForumPages.topics && this.ForumPageType != ForumPages.Profile)`

in the file Modules\CanonicalMetaTagModule.cs in the YAF Project
