### ISSUE TITLE
Not able to attach files / Copy paste images

### ISSUE THREAD

**Issue by ggupta8181** [YAFNET/YAFNET#583]
Hi Team

On our forum page while creating / editing any topic we are not able to attach any files . It shows the buttons to attach the file. Drag drop the file and upload the file . We are able to select the file but when we click on start upload nothing happens. 

Same thing happens when we select some text along with document ( Lets say from any PDF / Word doc ) then only text gets paste and images are not showing up directly in the editor. 

Please suggest at the earliest.

**Comment by w8tcha** [comment]
>  We are able to select the file but when we click on start upload nothing happens.

With the information you provided it's impossible to help you! 

After you click start upload are there any errors in the Browser console?

Which yaf version did you use?

**Comment by ggupta8181** [comment]
Hi,

Find attached the YAF version details and the details of issue video recorded for your reference to check and assist further. Hope this helps.

[issue video.zip](https://github.com/YAFNET/YAFNET/files/4982523/issue.video.zip)
![WhatsApp Image 2020-07-27 at 6 41 09 PM](https://user-images.githubusercontent.com/68842278/88553433-e795e200-d042-11ea-8b37-444b71da4b33.jpeg)

**Comment by w8tcha** [comment]
Does the issue also occurs in the latest version?

Are you using the recommended.web.config?

Are there any JS issues in the browser console?

**Comment by w8tcha** [comment]
By the way the second issue 

> Same thing happens when we select some text along with document ( Lets say from any PDF / Word doc ) then only text gets paste and images are not showing up directly in the editor.

This is not an issue. It's a feature request. This needs to be posted in a separate topic

**Comment by ggupta8181** [comment]
What about 1st issue ? Not able to attach ?

Regards,

Gaurav Gupta
+91-9971128133
_________________

On 28-Jul-2020 6:56 AM, Ingo <notifications@github.com> wrote:

By the way the second issue

Same thing happens when we select some text along with document ( Lets say from any PDF / Word doc ) then only text gets paste and images are not showing up directly in the editor.

This is not an issue. It's a feature request. This needs to be posted in a separate topic

-

**Comment by ggupta8181** [comment]
For the second issue also how do a user know that it's a feature request as not bug because these days in almost all editors this copy paste of images is supported...for e.g in GitHub also this happens.

Please do the needful at your end .

Regards,

Gaurav Gupta
+91-9971128133
_________________

On 28-Jul-2020 6:56 AM, Ingo <notifications@github.com> wrote:

By the way the second issue

Same thing happens when we select some text along with document ( Lets say from any PDF / Word doc ) then only text gets paste and images are not showing up directly in the editor.

This is not an issue. It's a feature request. This needs to be posted in a separate topic

-

**Comment by w8tcha** [comment]
> What about 1st issue ? Not able to attach ? 

You have not answered my questions above

Does the issue also occurs in the latest version?

Are you using the recommended.web.config?

Are there any JS issues in the browser console?

**Comment by ggupta8181** [comment]
File attachment issue resolved after upgrading .
