### ISSUE TITLE
Login Issue 

### ISSUE THREAD

**Issue by ggupta8181** [YAFNET/YAFNET#584]
After I am logged out and when try to login again Java Void error comes at bottom left corner. 

Then when I go back a step in forum then I am able to see the login pop up and able to login

PFA the version details and Issue video with Snapshot
![WhatsApp Image 2020-07-27 at 6 41 09 PM](https://user-images.githubusercontent.com/68842278/88554042-9fc38a80-d043-11ea-861f-cc49224022a1.jpeg)
[Login issue.zip](https://github.com/YAFNET/YAFNET/files/4982551/Login.issue.zip)

**Comment by w8tcha** [comment]
Does the issue also occurs in the latest version?

Are there any JS issues in the browser console?

**Comment by ggupta8181** [comment]
The version details I have shared in my last post, dont know whether it is latest or not.

What is the recommended config ?

Regards,

Gaurav Gupta
+91-9971128133
_________________

On 27-Jul-2020 10:35 PM, Ingo <notifications@github.com> wrote:

Does the issue also occurs in the latest version?

Are there any JS issues in the browser console?

**Comment by w8tcha** [comment]
If you want to know if your using the latest version got to Admin > Upgrade > Version Check in your forum installation.

You can also check the downloads page to see what's the latest version...

https://yetanotherforum.net/download

**Comment by ggupta8181** [comment]
This issue also seems to be resolved after upgrading to latest version.
