### ISSUE TITLE
Not able to copy paste image directly from Word/ other documents

### ISSUE THREAD

**Issue by ggupta8181** [YAFNET/YAFNET#585]
Hi Team,

when we select some text along with document ( Lets say from any PDF / Word doc ) then only text gets paste and images are not showing up directly in the editor.

PFA the issue video for reference. We are using the latest upgraded version of YAF.

I have been told in the Bug ID 583 that it is a feature request so posting here.
[issue video.zip](https://github.com/YAFNET/YAFNET/files/4986522/issue.video.zip)

Hoping for a quick resolution

**Comment by ggupta8181** [comment]
This seems to be working fine too after upgrading to latest version so closing

**Comment by ggupta8181** [comment]
When we select one particular image from document and copy and then paste in editor then it works now, but if we copy the whole document with images it is only pasting Text .

**Comment by w8tcha** [comment]
I did some investigation. Looks like this is a technical limitation. it is not possible to paste both text + image. You can ether paste text or an image. But not both

**Comment by ggupta8181** [comment]
May be you are right...but I have seen that in some software for e.g in OS ticket editor  it at least works and shows both text and images  if I am copying some text and images lets say that are  already embedded lets say in some  email body content so I think this can be solved too. 

 Suppose  if I don't want to attach a document for some reason and I just want to add content and images in the topic from any already existing Doc or PDF  then I will have to manually copy paste each image which is a tedious process and not at all user friendly but a cumbersome task.

Hope you agree with what I am saying so request you to please check the possibilities.

**Comment by w8tcha** [comment]
I understand the problem. But the Browser API does not allow this. There is no way to paste both form the Javascript Clipboard API-
