### ISSUE TITLE
Blueimp gallery doesn't close and open properly

### ISSUE THREAD

**Issue by justiceorjustus** [YAFNET/YAFNET#590]
**Describe the bug**
Opening blueimp gallery for the first time and then closing causes the scrollbar to disappear and not allow scrolling. On the second opening of blueimp gallery, the gallery opens and then closes right away, but the scrollbar returns.

**To Reproduce**
1. Post an image that will show a thumbnail for blueimp gallery
2. Open the thumbnail in blueimp gallery
3. Close
4. Try to scroll
5. Clink thumbnail and gallery again

**Expected behavior**
Gallery opens and closes properly

**Screenshots**
Video: https://lawndork.tinytake.com/tt/NDU5NzIzMl8xNDU2OTU5NA

**System (please complete the following information):**
 - YAF Version: [e.g. YAF v3]
 
**Affected browser**

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Edge

**Additional context**

**Comment by justiceorjustus** [comment]
FYI, I was able to fix this by updating to BlueImp 3.3.0. I don't know the YAF code base enough to know if I updated this correctly... but it seems to work.

**Comment by w8tcha** [comment]
Please make sure you running the latest source code! This issue is already fixed

https://github.com/YAFNET/YAFNET/commit/f329881c2057bf00d83bf9312c2c923060b6f383

**Comment by justiceorjustus** [comment]
I think after doing my forum launch on Monday, I may do a pull request and try to replicate most of my changes... do you have any suggestion on how I should handle that? I don't use github enough to know what to do.

My main confusion is how to handle the .ascx files in my main "LD" project separately from my YAFNET source code changes in my YAFNET build.

**Comment by w8tcha** [comment]
> I think after doing my forum launch on Monday, I may do a pull request and try to replicate most of my changes... do you have any suggestion on how I should handle that? I don't use github enough to know what to do.
> 

Well the correct why would be to fork the project and then you can always sync the project with one git command merge. And most cases it would keep your modifications intact.

> My main confusion is how to handle the .ascx files in my main "LD" project separately from my YAFNET source code changes in my YAFNET build.
> 

It depends what changed you make. If there are only visual changes, than do it with css instead.

> 
> And also that the files in my YAFNET build will be in the /forum directory and won't match with your folder structure.

But you don't have to change the source code for that! Just you need to change the app settings and correctly. I tested with your website without any problems.
