### ISSUE TITLE
Ability to show certain profile properties next to username on new topics and replies

### ISSUE THREAD

**Issue by justiceorjustus** [YAFNET/YAFNET#591]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The ability to show certain profile properties and custom profile definitions next to the username on a post.
![image](https://user-images.githubusercontent.com/27013322/92160147-983e9080-edfc-11ea-9815-64a830401bf2.png)

If not null, the ability to turn on certain profile properties (like location) and custom profile definitions next to the username or next to the user's post.

**Describe alternatives you've considered**

**Additional context**
This would be useful for me, because answering certain most related to lawn care are different depending on region and grow zone. It would be nice for the user to be able to see that when answering.

**Comment by w8tcha** [comment]
added in YAF 3.00 alpha 2
