### ISSUE TITLE
Delete does not delete message

### ISSUE THREAD

**Issue by justiceorjustus** [YAFNET/YAFNET#592]
**Describe the bug**
Delete doesn't work for then the user is trying to delete their own message

**To Reproduce**
1. Delete topic or reply
2. Enter reason
3. It returns to the topic without deleting it

**Expected behavior**
The topic or reply should be deleted

**Screenshots**
[https://lawndork.tinytake.com/tt/NDYwMjk5NV8xNDU4ODY4MQ](https://lawndork.tinytake.com/tt/NDYwMjk5NV8xNDU4ODY4MQ)

**System (please complete the following information):**
 - YAF Version: [e.g. YAF v3]

**Comment by w8tcha** [comment]
I cant reproduce the issue with build YAF.NET 3.0.0 ALPHA 202009060052 . The issue report is  missing the version info

**Comment by w8tcha** [comment]
Argh sorry i tried deleting the topic. message deleting doent work
