### ISSUE TITLE
Upgrade failure

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#595]
Trying to upgrade from 2.31 to 3.0 alpha.
I don't have a yaf_aspnetusers.
I do have aspnet_Users and yaf_user.

🤷‍♂️

**To Reproduce**
![image](https://user-images.githubusercontent.com/5612416/92417251-d9011700-f126-11ea-9c25-77fed3c0be5a.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/5612416/92416640-131ce980-f124-11ea-94f9-fdcaa92255e1.png)

**System (please complete the following information):**
 - YAF Version: [e.g. YAF.NET 2.31]
 - .NET Version [e.g. 4.7.2]
 - SQL Server [e.g. SQL Server 2016]

**Comment by w8tcha** [comment]
Thats odd. Which provider are you using? Chan you check the atable aspnet_Users and if the column IsApproved has a not null attribute?!

**Comment by Zero2Cool** [comment]
Whatever provider is default. I didn't change anything, only pointed it to my database. No, the column does not exist.

**Comment by w8tcha** [comment]
Does the table contains the users or is the table empty? If it's empty the users should be in table yaf_prov_membership

**Comment by Zero2Cool** [comment]
I don't have access to the database I ran the upgrade on, however, in my live version, the Table [aspnet_Uesrs] has all of the users in it. And table [yaf_prov_Membership] has zero records.

**Comment by w8tcha** [comment]
it was the wrong table to check. can you make a screenshot of the columns of the table aspnet_Membership?

**Comment by Zero2Cool** [comment]
> it was the wrong table to check. can you make a screenshot of the columns of the table aspnet_Membership?

![image](https://user-images.githubusercontent.com/5612416/92594653-b414bd00-f268-11ea-88c8-295965015019.png)
