### ISSUE TITLE
Sharing cookies doesn't work. HttpContext.User

### ISSUE THREAD

**Issue by webmedia1012** [YAFNET/YAFNET#596]
**Describe the bug**
HttpContext.User cannot see the cookies created on a different Project

**To Reproduce**
1. Create a new project like Web and provide Identity Management like a login and user account creation

**Expected behavior**
1. What should happen is that when you're already logged in on the project created above, you shouldn't login anymore to the Forum

**Actual Results**
1. Still asks you to login to the forum.

Please provide documentation on how to achieve this. 

Thank you very much!
Regards,
PD

**Comment by w8tcha** [comment]
At the moment yaf uses the classic asp.net membership providers. So your website would need to use the same membership model.

You can look at the yaf sample application, how the integration would work.

**Comment by Pistle** [comment]
The User property provides programmatic access to the properties and methods of the IPrincipal interface. Because ASP.NET pages contain a default reference to the System. Web namespace (which contains the HttpContext class), you can reference the members of HttpContext on an .

**Comment by webmedia1012** [comment]
> At the moment yaf uses the classic asp.net membership providers. So your website would need to use the same membership model.
> 
> You can look at the yaf sample application, how the integration would work.

Thanks for the reply sir, just a clarification when you say use same membership model, did mean use the model thats on the YAF project? 

Thanks again.

**Comment by w8tcha** [comment]
> > At the moment yaf uses the classic asp.net membership providers. So your website would need to use the same membership model.
> 
> > 
> 
> > You can look at the yaf sample application, how the integration would work.
> 
> 
> 
> Thanks for the reply sir, just a clarification when you say use same membership model, did mean use the model thats on the YAF project? 
> 
> 
> 
> Thanks again.

Yes

**Comment by webmedia1012** [comment]
thank you! what I did to make it work was created a saml parser then just did a saml authentication
