### ISSUE TITLE
Bug on replying to a post/ adding a new topic

### ISSUE THREAD

**Issue by nickornotto** [YAFNET/YAFNET#597]
The error happens on `/PostMessage?t=..&f=..` on trying to execute the following scalar:

"INSERT INTO \"yaf_EventLog\" (\"EventTime\",\"UserID\",\"Source\",\"Description\") VALUES (@EventTime,@UserID,@Source,@Description); SELECT SCOPE_IDENTITY()"

YAF.NET v2.3.1.09
.NET 4.8
Windows 10
SQL Server 2016 LocalDB
Chrome

1. Click reply to a topic.
2. Add the message and click Post.
3. An error will display:

```
Exception Details: System.Data.SqlClient.SqlException: String or binary data would be truncated.
The statement has been terminated.

Line 56:         public object ExecuteScalar() 
Line 57:         { 
Line 58:             return dbCmd.ExecuteScalar(); 
Line 59:         } 
Line 60:
```

The exception it is trying to log:

> {Exception at URL (URL:'/Default.aspx?g=PostMessage&t=2&f=1')
> System.Data.SqlClient.SqlException (0x80131904): Must declare the scalar variable "@0".
> Must declare the scalar variable "@0".
>    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
>    at System.Data.SqlClient.SqlDataReader.get_MetaData()
>    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
>    at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
>    at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
>    at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
>    at ServiceStack.OrmLite.OrmLiteCommand.ExecuteReader() in C:\...\forums\ServiceStack\ServiceStack.OrmLite\OrmLiteCommand.cs:line 48
>    at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.ExecReader(IDbCommand dbCmd, String sql) in C:\...\forums\ServiceStack\ServiceStack.OrmLite\OrmLiteReadCommandExtensions.cs:line 42
>    at ServiceStack.OrmLite.OrmLiteResultsFilterExtensions.ConvertToList[T](IDbCommand dbCmd, String sql) in C:\...\forums\ServiceStack\ServiceStack.OrmLite\OrmLiteResultsFilterExtensions.cs:line 98
>    at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.Select[T](IDbCommand dbCmd, String sql, Object anonType) in C:\...\forums\ServiceStack\ServiceStack.OrmLite\OrmLiteReadCommandExtensions.cs:line 485
>    at ServiceStack.OrmLite.OrmLiteReadApi.<>c__DisplayClass1_0`1.<Select>b__0(IDbCommand dbCmd) in C:\...\forums\ServiceStack\ServiceStack.OrmLite\OrmLiteReadApi.cs:line 27
>    at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter) in C:\...\forums\ServiceStack\ServiceStack.OrmLite\OrmLiteExecFilter.cs:line 70
>    at ServiceStack.OrmLite.OrmLiteReadExpressionsApi.Exec[T](IDbConnection dbConn, Func`2 filter) in C:\...\forums\ServiceStack\ServiceStack.OrmLite\OrmLiteReadExpressionsApi.cs:line 16
>    at ServiceStack.OrmLite.OrmLiteReadApi.Select[T](IDbConnection dbConn, String sql) in C:\...\forums\ServiceStack\ServiceStack.OrmLite\OrmLiteReadApi.cs:line 27
>    at YAF.Core.Model.UserRepositoryExtensions.<>c__DisplayClass16_0.<WatchMailList>b__5(IDbCommand db) in C:\...\forums\YAF.Core\Model\UserRepositoryExtensions.cs:line 701
>    at YAF.Core.Data.DbAccessBase.Execute[T](Func`2 execFunc, IDbCommand cmd, IDbTransaction dbTransaction) in C:\...\forums\YAF.Core\Data\DbAccessBase.cs:line 131
>    at YAF.Core.Model.UserRepositoryExtensions.WatchMailList(IRepository`1 repository, Int32 topicId, Int32 userId) in C:\...\forums\YAF.Core\Model\UserRepositoryExtensions.cs:line 700
>    at YAF.Core.Services.SendNotification.ToWatchingUsers(Int32 newMessageId) in C:\...\forums\YAF.Core\Services\SendNotification.cs:line 378
>    at YAF.Pages.PostMessage.PostReply_Click(Object sender, EventArgs e) in C:\...\forums\YetAnotherForum.NET\Pages\PostMessage.ascx.cs:line 786
>    at YAF.Web.Controls.ThemeButton.OnClick(EventArgs e) in C:\...\forums\YAF.Web\Controls\ThemeButton.cs:line 752
>    at YAF.Web.Controls.ThemeButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument) in C:\...\forums\YAF.Web\Controls\ThemeButton.cs:line 474
>    at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
>    at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
>    at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
> ClientConnectionId:d97534fa-623f-4902-8377-8d371efcba89
> Error Number:137,State:2,Class:15}

**Comment by w8tcha** [comment]
Which version are you using? The issue has been already fixed. Please upgrade to the latest version 2.31.9

**Comment by nickornotto** [comment]
As above - YAF.NET v2.3.1.09 - which I saw on the YAF website this morning.

Thanks for updating the version on the site so quickly. I'll take a look

**Comment by w8tcha** [comment]
If you downloaded the source then it was not the 2.31.9 release it was the 3.00 alpha. Sorry for the confusion. That's why I updated the release to version 2.31.10

**Comment by nickornotto** [comment]
And how to upgrade? Just copy the files I guess? Or which files have changed? I think it would be simpler to know which files have changed if just a few.

**Comment by Zero2Cool** [comment]
> And how to upgrade? Just copy the files I guess? Or which files have changed? I think it would be simpler to know which files have changed if just a few.

Regarding how to upgrade, go to the Releases area, download the YAF-v2.3.1.10-Upgrade.zip and proceed. 

https://github.com/YAFNET/YAFNET/releases

**Comment by w8tcha** [comment]
> And how to upgrade? Just copy the files I guess? Or which files have changed? I think it would be simpler to know which files have changed if just a few.

It depends. Was the installation of 2.31.9 a new installation or an upgrade?  If if was an upgrade then you have to replace all files and follow the upgrade guide. If it was a new installation you can't install 2.31.10 you have to stay on the alpha channel and update to the latest commit

**Comment by nickornotto** [comment]
It was a new installation

**Comment by nickornotto** [comment]
I don't get what you mean - what is alpha channel? How do I update the previous version if it was a new install?

**Comment by w8tcha** [comment]
Unfortunately when you downloaded the package the zip was containing the  wrong version. On github there are 2 branches the stable branch (which contains version 2.31.10) and the master branch (3.00 alpha). 

You downloaded and installed yaf 3.00, at the bottom of the page (Footer) you can see what version you are using. From this version its not possible to downgrade to an older version. You can only keep updating the version to a newer version of the alpha branch, by downloading the branch and updating the files. 

https://github.com/YAFNET/YAFNET/archive/master.zip

Or you create a fork on github then you can always directly see what files have changed

**Comment by nickornotto** [comment]
Well, I just used the source code version available on the downloads page.

In terms of the upgrade I just started from scratch.

However now when posting a new topic/ replying there is no warning about a new message - normally a badge would show next to the forum and underneath in the summary and the forum icon would go green. This doesn't happen anymore in version 2.3.1.10.

**Comment by w8tcha** [comment]
> However now when posting a new topic/ replying there is no warning about a new message - normally a badge would show next to the forum and underneath in the summary and the forum icon would go green. This doesn't happen anymore in version 2.3.1.10.

Thats the correct behavior if you read the message or your last visit is newer then the message the icon doesnt show up. Otherwiese you need to turn on  **Read Tracking via Database** in the Host settings under Features
