### ISSUE TITLE
500 - Internal server error. when I try to install the v2.2.4.19

### ISSUE THREAD

**Issue by osirisAman** [YAFNET/YAFNET#599]
Goodmorning, 

Since I wasn't able to write in the forum because after inserting the capthca the page keep loading and I can't finish the registration and so post on the forum. Anyway my problem is that my client prefers a lot the older version of the YAF, not the new one with the built in bootstrap since it's harder for him to edit it. At this point I downloaded from here the v2.2.4.19 and I tried to install it in my web server but when I run the folder from the broweser I get the 500 - Internal server error. Note that I configured the web.config with the MachineKey, following the same process I did when I succesfully installed the latest version but with the 2.2.4.19 nothing. 

Thank you.

**Comment by w8tcha** [comment]
Is the folder configured as application in IIS?

**Comment by osirisAman** [comment]
Hello! Yes, I am on godaddy hosting. From the Plesk I created a new Virtual Directory called forum and it created a folder in the root where I put the YAF Files. Now I did again and when I run the setup I get this: 

**Server Error in '/forum' Application.**
Runtime Error
_Description: An exception occurred while processing your request. Additionally, another exception occurred while executing the custom error page for the first exception. The request has been terminated._

**Comment by w8tcha** [comment]
What error are you getting when you turn custom errors off in the web.config?

**Comment by osirisAman** [comment]
I get this: 

Compilation Error
Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately.

Compiler Error Message: CS0246: The type or namespace name 'YAF' could not be found (are you missing a using directive or an assembly reference?)

Source Error:
 
--
Line 97:     </roleManager> Line 98:  Line 99:     <profile enabled="true" defaultProvider="YafProfileProvider" inherits="YAF.Utils.YafUserProfile"> Line 100:      <providers> Line 101:        <clear />

**Comment by osirisAman** [comment]
This is the Compiler:

`C:\Windows\SysWOW64\inetsrv> "C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe" /t:library /utf8output /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel\v4.0_4.0.0.0__b77a5c561934e089\System.ServiceModel.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.ApplicationServices\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.ApplicationServices.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_32\System.EnterpriseServices\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.EnterpriseServices.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Web\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Web.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Activities\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Activities.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll" /R:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscorlib.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Services\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.Services.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ComponentModel.DataAnnotations\v4.0_4.0.0.0__31bf3856ad364e35\System.ComponentModel.DataAnnotations.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Activation\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Activation.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Microsoft.CSharp\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.CSharp.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.WorkflowServices\v4.0_4.0.0.0__31bf3856ad364e35\System.WorkflowServices.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Data.DataSetExtensions\v4.0_4.0.0.0__b77a5c561934e089\System.Data.DataSetExtensions.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.IdentityModel\v4.0_4.0.0.0__b77a5c561934e089\System.IdentityModel.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.WebPages.Deployment\v4.0_2.0.0.0__31bf3856ad364e35\System.Web.WebPages.Deployment.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Extensions\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.Extensions.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Activities\v4.0_4.0.0.0__31bf3856ad364e35\System.Activities.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_32\System.Web\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Web.dll" /R:"C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.DynamicData\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.DynamicData.dll" /out:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\forum\fec41ff7\eef9f227\App_Code.hxsskwzf.dll" /debug- /optimize+ /w:4 /nowarn:1659;1699;1701;612;618 /warnaserror-  "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\forum\fec41ff7\eef9f227\App_Code.hxsskwzf.0.cs" "C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\forum\fec41ff7\eef9f227\App_Code.hxsskwzf.1.cs"


Microsoft (R) Visual C# Compiler version 4.8.3761.0

for C# 5
Copyright (C) Microsoft Corporation. All rights reserved.



This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

g:\pleskvhosts\xxx.net\httpdocs\forum\web.config(99,30): error CS0246: The type or namespace name 'YAF' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by w8tcha** [comment]
The error message is clear, you forgot to copy the bin folder to the server

**Comment by osirisAman** [comment]
Excuse my ignorance. But where is this bin folder? I dont have it in my Zip :O

**Comment by w8tcha** [comment]
Well i dont know what zip file you downloaded, but if you download the source package, then you need to compile yaf first. Or download the install package.

**Comment by osirisAman** [comment]
I did download this one: https://github.com/YAFNET/YAFNET/archive/v2.2.4.19.zip

**Comment by w8tcha** [comment]
You downloaded the Source Package of that old version. In that case you need to compile it with Visual Studio and then Deploy it to the server. 

Or you download the last install version of the old 2.24 branch 

https://github.com/YAFNET/YAFNET/releases/download/v2.2.4.20/YAF-v2.2.4.20-Install.zip

**Comment by osirisAman** [comment]
@w8tcha Thanks, finally I can run the install but after I put the first configuration password again, error..

**Security Exception**
_Description: The application attempted to perform an operation not allowed by the security policy.  To grant this application the required permission please contact your system administrator or change the application's trust level in the configuration file.

Exception Details: System.Security.SecurityException: Request for the permission of type 'System.Web.AspNetHostingPermission, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed._

Source Error:

`

The source code that generated this unhandled exception can only be shown when compiled in debug mode. To enable this, please follow one of the below steps, then request the URL:1. Add a "Debug=true" directive at the top of the file that generated the error. Example:  <%@ Page Language="C#" Debug="true" %>or:2) Add the following section to the configuration file of your application:<configuration>   <system.web>       <compilation debug="true"/>   </system.web></configuration>Note that this second technique will cause all files within a given application to be compiled in debug mode. The first technique will cause only that particular file to be compiled in debug mode.Important: Running applications in debug mode does incur a memory/performance overhead. You should make sure that an application has debugging disabled before deploying into production scenario.
--


`

`

[SecurityException: Request for the permission of type 'System.Web.AspNetHostingPermission, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.]    YAF.Utils.Helpers.ConfigHelper.WriteAppSetting(String keyName, String keyValue) +40    YAF.Install._default.Wizard_NextButtonClick(Object sender, WizardNavigationEventArgs e) +1882    System.Web.UI.WebControls.WizardNavigationEventHandler.Invoke(Object sender, WizardNavigationEventArgs e) +0    System.Web.UI.WebControls.Wizard.OnNextButtonClick(WizardNavigationEventArgs e) +116    System.Web.UI.WebControls.Wizard.OnBubbleEvent(Object source, EventArgs e) +417    System.Web.UI.Control.RaiseBubbleEvent(Object source, EventArgs args) +37    System.Web.UI.WebControls.Button.OnCommand(CommandEventArgs e) +120    System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +272    System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument) +12    System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument) +15    System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData) +35    System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +6796    System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +250    System.Web.UI.Page.ProcessRequest() +76    System.Web.UI.Page.ProcessRequestWithNoAssert(HttpContext context) +24    System.Web.UI.Page.ProcessRequest(HttpContext context) +62    ASP.install_default_aspx.ProcessRequest(HttpContext context) +4    System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +195    System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +50    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +73
--


`

**Comment by w8tcha** [comment]
This would require trust level to full for the asp.net application, but it looks like you are us using a shared hosting provider.

You can set the config password manually in the app.config

**Comment by osirisAman** [comment]
Perfect. Worked also this. Don't hate me but now I Create New DB Connection String and I put my MSSQL database infos. I test the connection and it says all good. I go on next and

 **No Write Access to Database Connection Strings**
Please open the db.config file in the application root directory and add/update the following key in the <connectionStrings> section:

<add name="yafnet" connectionString="Data Source=xxxxxxxxmyhostxxxxxxx;Initial Catalog=yaf;User ID=yaf;Password=Test123" />
Click "Next" when you are ready.

I checked but there are 3 strings there mmh

**Comment by osirisAman** [comment]
@w8tcha OKAY! hahaha worked. I installed it. May I send you the link? Because yet problems aren't finished. I can login but when I create a topi or log in in the admin area i get logged off. When I try to register a new user another error: http://www.arduer.net/forum/rules

Note: I am waiting my SSL to be activated. I hope it's not this the problem.

**Comment by w8tcha** [comment]
No sorry but it cannot work without trust level set to full. This is now required for almost every asp.net application.

**Comment by osirisAman** [comment]
If I set to my Plesk this: **CAS trust level** to Full?

**Comment by w8tcha** [comment]
Yes if you can set it, then it needs to be set to full

**Comment by osirisAman** [comment]
Done, Now everything on the server gives me Service Unavailable - HTTP Error 503. The service is unavailable. 

is it normal?

**Comment by w8tcha** [comment]
It could be a temporary problem with the registration. Atleast others have no problems registering.
