### ISSUE TITLE
Forums: Mobile: Forum posts cannot be pressed, redirected to User profile instead of posts.

### ISSUE THREAD

**Issue by nickornotto** [YAFNET/YAFNET#600]
The issue is only present in portrait mode. Seems to happen only with narrow mobile screens.

Steps to recreate:
1. Navigate to the Forums on a mobile device.
2. Enter a forum discussion.
3. Press on a post title to be navigated the post discussion

Expected result: Tapping on a post title navigates to the discussion for that post.

Actual Result: Tapping on posts redirects to the users profile instead of the post discussion.

The user popover seems to be obstructing the post title and depending how big it is it either prevents clicking through to the post whatsoever. If the mouse happens to be over the author name then it clicks through to that user profile instead through to the post.

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - YAF Version: 2.3.1.10
 - .NET Version 4.7.2
 
**Affected browser**
* [ ] Chrome
* [ ] Firefox

I could upload screenshots but am unable to attach image to the issue

**Comment by w8tcha** [comment]
I can confirm the issue!

PS: to attach images simply drag & drop them in to the editor. Or click on the line bellow the editor where it says attach files

**Comment by w8tcha** [comment]
FIXED via https://github.com/YAFNET/YAFNET/commit/79df41588812ee5a9407990a03a31cf35d1b91d7
