### ISSUE TITLE
captcha image not show

### ISSUE THREAD

**Issue by lnicolae** [YAFNET/YAFNET#604]
**Describe the bug**
A clear and concise description of what the bug is. Captcha image is mssing on Register a new user

**To Reproduce**
1. Go to 'Regoister'
2. Click on 'try to create a new user'
3. Scroll down to 'down to buttons'
4. See error (missing captcha image)

**Expected behavior**
missing captcha image 

**Screenshots**

**System (please complete the following information):**
 - YAF Version: [e.g. YAF v2.3.1.12] on http and https
 - .NET Version [e.g. 4.xxx] default code version
 - SQL Server [e.g. SQL Server 2017]
 
**Affected browser**

* [x] Chrome
* [x] Firefox
* [ ] Safari
* [ ] Edge

**Additional context**
on browser console line 
/resource.ashx?c=1&t=30.01.2021%2010:24:32  sometime has no error, sometime can't be found!
and the captcha image is not show, only defaul missing image

**THIS IS AVAILABLE ONLY/APEAR FROM LOCAL URL, e.g. 192.168.0.X**

**Comment by w8tcha** [comment]
Are you using the recommend web.config?

It looks like the Resource handle entry is missing

**Comment by lnicolae** [comment]
I just remane recomended web config file. This "BUG" appear only from local URl, 192.168.0.X, on external url that is redirected to local url lmachine, the image apear

**Comment by lnicolae** [comment]
![Cap11](https://user-images.githubusercontent.com/807984/106356306-6a0ba100-6307-11eb-91da-29f60ae24b02.png)
![Cap12](https://user-images.githubusercontent.com/807984/106356308-6aa43780-6307-11eb-86cb-99438032ead9.png)

**Comment by w8tcha** [comment]
That is happening probably because of the url refer check. only the forum base url mask that is saved in the Board Settings can be used. Multiple urls is not supported at the moment.

**Comment by w8tcha** [comment]
Trying to fix the issue. when you open the image url directly in the browser what error message are you getting?

**Comment by lnicolae** [comment]
site working from server that is not on local uri, 
Image not found, in any browser when open from server on local uri

**Comment by w8tcha** [comment]
You need to copy the URL from the page source and copy it in the browser Adress bar. When you access this page you should see a different error message.
