### ISSUE TITLE
When will support .net core / .Net 5.0

### ISSUE THREAD

**Issue by dotnba** [YAFNET/YAFNET#613]
Any support for .NET core in future?

**Comment by w8tcha** [comment]
Yes

https://github.com/YAFNET/YAFNET/issues/398

**Comment by dotnba** [comment]
> Yes
> 
> You can read more about it here..
> #398

The #398 issue was posted three years ago .It is not planed yet? .NET core is a cross-platform.Yaf can run on linux if it was migrated to .net core. Front-end and back-end separation and  supportrd mysql or other db are also needed....

**Comment by dotnba** [comment]
> Yes
> 
> You can read more about it here..
> #398

The #398 issue was posted three years ago .It is not planed yet? .NET core is a cross-platform.Yaf can run on linux if it was migrated to .net core. Front-end and back-end separation and  supportrd mysql or other db are also needed....

**Comment by w8tcha** [comment]
Sorry but then you didnt read it. Or atleast not my comment from January. where i posted that i started working on  a new version Which will run on .net 5/6.

**Comment by dotnba** [comment]
> Sorry but then you didnt read it. Or atleast not my comment from January. where i posted that i started working on a new version Which will run on .net 5/6.
“So i started building a new YAF NET 5 and with razor pages. It will take some time, but the current situation that i have to migrate my websites away from a Windows Server and also away from the MS SQL Server, forcing me to do this.
So yes there will be an .NET (Core) Version. Maybe when .NET 6 is out by the end of the Year there will be a first alpha version.”
 It's so cool ! I am looking forward to it.Thanks a lot !
