### ISSUE TITLE
Login does not persist 

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#635]
On the YetAnotherForum.NET website, each time I close my browser and come back. I have to reset my password. I've cleared my cache on Chrome too.

**Comment by w8tcha** [comment]
I cant reproduce this. Did you enable the checkbox "Remember me"? Its also possible that you need to delete all old cookies for that site

**Comment by Zero2Cool** [comment]
It makes me reset my password each time.

**Comment by w8tcha** [comment]
I dont understand, when you hit the Remember me checkbox you get redirected to the reset password page?

**Comment by w8tcha** [comment]
Which browser is used?

**Comment by Zero2Cool** [comment]
> I dont understand, when you hit the Remember me checkbox you get redirected to the reset password page?

I'm confused. Why would remember me matter? The remember me should keep users logged in if checked. I'm being forced to reset my password. 🤷🏼‍♂️

**Comment by Zero2Cool** [comment]
> Which browser is used?

Windows 10. Chrome.

**Comment by w8tcha** [comment]
> > I dont understand, when you hit the Remember me checkbox you get redirected to the reset password page?
> 
> 
> 
> I'm confused. Why would remember me matter? The remember me should keep users logged in if checked. I'm being forced to reset my password. 🤷🏼‍♂️

Now I understand the problem. The title is so misleading to understand the problem. 

Also posting multiple issues will not help solve the problem.

Can you describe the steps to reproduce the original issue?
