### ISSUE TITLE
can't login after up upgrade

### ISSUE THREAD

**Issue by myCollections** [YAFNET/YAFNET#636]
Hello,

I just upgrade to latest version.
Everything is working fine, but i can't get the pop-up login when i click on connection.

Any clue ?

you can test it here : [http://www.mycollections.fr/forum/](http://www.mycollections.fr/forum/)

Thanks for your help.

**Comment by w8tcha** [comment]
it appears that the wrong js file is loaded **Scripts/jquery.ForumExtensions.js** instead of **Scripts/jquery.ForumExtensions.min.js** 

When you rename the file, then it should work.

Did you use the upgrade package, or did you use the source version and compile yaf yourself?

**Comment by myCollections** [comment]
Thanks for the quick feedbcak.

I update from upgrade package.
I delete script files one more time, verify that Scripts/jquery.ForumExtensions.min.js is here, but i still have the same issue.

**Comment by w8tcha** [comment]
Check your web.config. I guess debug is enabled

`<compilation debug="false" targetFramework="4.7.2" optimizeCompilations="false" />`

debug needs to be set to false

**Comment by myCollections** [comment]
It works :) 👍 
Thanks a lot.
I found some mistake in french translation, how can i help on this ?

**Comment by w8tcha** [comment]
> I found some mistake in french translation, how can i help on this ?

One way would be to send a Pull request with the changes you made. or if you dont know how to do that, then just create a new issue and attach the updated french.xml file.
