### ISSUE TITLE
Sending Private Message Does Not Work

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#645]
**Describe the bug**
Attempted to respond to a Private Message and the page reloaded.

**To Reproduce**
1. Access Private Messages
2. Click "Reply with Quote" or "Reply" (Update: Sending a new Private Message doesn't work)
3. Add your message response below quoted text
4. Click "Post"

**Expected behavior**
Message to be sent and redirected to Private Message index.

**System (please complete the following information):**
YAF Support Website → https://yetanotherforum.net/
 
**Affected browser**
Chrome 94
![image](https://user-images.githubusercontent.com/5612416/138782824-00cf419c-0ea7-47aa-8c1d-c057bff68c3d.png)
 
Console errors.
![image](https://user-images.githubusercontent.com/5612416/138783094-fba63b82-0f50-48e9-a212-17f02090f4f8.png)

**Comment by w8tcha** [comment]
What do you think about the new conversion layout. I just uploaded to the support forum

**Comment by Zero2Cool** [comment]
> What do you think about the new conversion layout. I just uploaded to the support forum

Nice!

Are profile avatars removed now?

**Comment by w8tcha** [comment]
What you mean by profile avatars?

On the profile page there are still avatars.

**Comment by Zero2Cool** [comment]
> What you mean by profile avatars?
> 
> On the profile page there are still avatars.

![image](https://user-images.githubusercontent.com/5612416/139597786-76c1f2f7-b0d7-490a-b34c-9dcccb50cc1c.png)
Yes, they are in profile, but I'm represented by ZC in posts and such and not the avatar I selected.

**Comment by w8tcha** [comment]
Do you mean in posts or in pms?

![image](https://user-images.githubusercontent.com/722575/139605245-e2142235-a197-4e4f-9e37-b2dbc299dbde.jpeg)

Atleast I see your avatar. I check if there is an issue

**Comment by Zero2Cool** [comment]
Strange. I see that now in the Forums. But just Private Messages shows my avatar as "ZC" now. Maybe that's by design?

**Comment by w8tcha** [comment]
Oh it's a bug. Avatar is not loaded for the outbox message. Will be fixed with the next update

**Comment by w8tcha** [comment]
i updated the forum, the avatar should load now

**Comment by Zero2Cool** [comment]
> i updated the forum, the avatar should load now

What did you do? None of my Avatars or Attachments are displaying after upgrading to latest. 

Test Site http://kevinduganjr-002-site1.etempurl.com/

**Comment by w8tcha** [comment]
Can you describe the steps to reproduce the problem?
