### ISSUE TITLE
AppVeyor builds do not have artifacts

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#650]
The appveyor doesn't seem to be persisting builds anymore. Is this by design or am I looking in the wrong place?

https://ci.appveyor.com/project/YAFNET/yafnet/builds/41434345/artifacts
![image](https://user-images.githubusercontent.com/5612416/140650443-d7e2c980-f33c-4864-999a-6b3650d6f141.png)

**Comment by w8tcha** [comment]
Its working again. But the current commit is the release. So you could also just download the release version.
