### ISSUE TITLE
The UTC time represented when the offset is applied must be between year 0 and 10,000

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#656]
Using a database from YAF 2.31 to update to the latest source. The upgrade goes fine, but after clicking "Finish", this error occurs. I know I mentioned it in the Sample Application repo, but wanted to capture it with a little more detail for you. I'm not sure what key `AdminPageAccess1` refers to, but that might help you.

![image](https://user-images.githubusercontent.com/5612416/141360591-188eb3b7-5479-4ccd-9798-7dca4a724e50.png)

**Comment by w8tcha** [comment]
This appears to be a timezone issue datetime.maxvalue produced different results. What timezone are you in?

In my timezone it works

**Comment by Zero2Cool** [comment]
Central Time Zone
Wisconsin USA.

**Comment by w8tcha** [comment]
I was able to reproduce the issue, and also resolve it.

**Comment by Zero2Cool** [comment]
That got me passed the error. My password doesn't work to let me log in, so that's the next hurdle. BTW, I had to add the `System.Threading.Tasks.Extensions` package to YAF.Core project to get it to compile.

**Comment by w8tcha** [comment]
> My password doesn't work to let me log in, so that's the next hurdle

Did you follow the upgrade guide? make sure you update the appsettings with the legacy provider info. Then you can login

**Comment by Zero2Cool** [comment]
> > My password doesn't work to let me log in, so that's the next hurdle
> 
> Did you follow the upgrade guide? make sure you update the appsettings with the legacy provider info. Then you can login

I'm going to be doing the upgrade guide next, good call out!

**Comment by Zero2Cool** [comment]
Is this the right guide? → https://github.com/YAFNET/YAFNET/wiki/Upgrade-to-YAF.NET-v3.0.1-(or-newer)
I thought I saw one that was more detailed but I'll have to look further in a little bit. Got some stuff to take care of.

I tried using the migration tool and it errored out on me saying `Object reference not set to an instance of an object.`

I've added my web.config but please note I added the .md extension so it could be attached.
[Web.config.md](https://github.com/YAFNET/YAFNET/files/7528091/Web.config.md)

**Comment by Zero2Cool** [comment]
I'm not finding the guide that walked through the app.settings changes. Is it not under Wiki anymore?

> > My password doesn't work to let me log in, so that's the next hurdle
> 
> Did you follow the upgrade guide? make sure you update the appsettings with the legacy provider info. Then you can login

Sorry, I'm not seeing the part of the guide that references the appSettings anymore. Is it on GitHub or the YAF Support site?

**Comment by w8tcha** [comment]
I updated the migration tool. it should work probably now.

**Comment by Zero2Cool** [comment]
> I updated the migration tool. it should work probably now.

Still didn't work, same error. Can you link me to the walkthrough for appSettings? I can't find it anymore.

**Comment by w8tcha** [comment]
For me it works with the web.config you attached. did you test a different web.config?

The walk through doesn't exist anymore. I would have to rewrite it. But this will take time, i hope i can do that next week.

**Comment by w8tcha** [comment]
I was able to restore the guide. I put the changes in an extra page...

https://github.com/YAFNET/YAFNET/wiki/Web.Config-changes-from-2.30.16-to-3.0.1

**Comment by Zero2Cool** [comment]
> I was able to restore the guide. I put the changes in an extra page...
> 
> https://github.com/YAFNET/YAFNET/wiki/Web.Config-changes-from-2.30.16-to-3.0.1

Thanks. 

I used the migration tool and did it manually and it's always an issue.  I'm getting these reference errors so when I have time I'll have to figure out why. They make no sense since JSON is on 13 in the projects and Cookies is correct. 

`Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0` 
`Could not load file or assembly 'Microsoft.Owin.Security.Cookies, Version=4.1.1.0`

**Comment by w8tcha** [comment]
I check tommorow again with your database. But the last time i tried the password was working with the 

`<add key="YAF.LegacyMembershipPasswordFormat" value="Hashed" />`

set in the appsettings

**Comment by Zero2Cool** [comment]
> I check tommorow again with your database. But the last time i tried the password was working with the
> 
> `<add key="YAF.LegacyMembershipPasswordFormat" value="Hashed" />`
> 
> set in the appsettings

That's what I have, but still wasn't working. I went to reset my password and it was forcing me to meet this criteria.

Passwords must have at least one non letter or digit character. 
Passwords must have at least one digit ('0'-'9'). 
Passwords must have at least one uppercase ('A'-'Z').

**Comment by w8tcha** [comment]
Okay i was able to reproduce the problem and also Resolve it. Turns out some of the user passwords have the format hashed and some are encrypted.

But the correct format can be detected automatically so the **LegacyMembershipPasswordFormat** setting is no longer needed.

I have no clue why the Membership Provider you are using storing the passwords encrypted instead of hashed. Which is by the way a terrible idea. If you have access to the db you can de-crypt all passwords easily. Which is not possible when there are stored hashed. In YAF 3 all passwords are stored as hash

**Comment by Zero2Cool** [comment]
> Okay i was able to reproduce the problem and also Resolve it. Turns out some of the user passwords have the format hashed and some are encrypted.
> 
> But the correct format can be detected automatically so the **LegacyMembershipPasswordFormat** setting is no longer needed.
> 
> I have no clue why the Membership Provider you are using storing the passwords encrypted instead of hashed. Which is by the way a terrible idea. If you have access to the db you can de-crypt all passwords easily. Which is not possible when there are stored hashed. In YAF 3 all passwords are stored as hash

I'm not sure why that'd be handled like that. However, my website started out as php, then DotNetNuke w/YAF before finally being ASP.NET Web Forms with YAF. Maybe that has something to do with it and then people haven't updated their passwords since moving to the Web Forms with YAF?

**Comment by Zero2Cool** [comment]
BTW, using the update you committed regarding passwords and I was able to log into my old database without needing to change/reset password. So, your fix worked.
