### ISSUE TITLE
CTRL + Enter to Submit Post

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#658]
I noticed when making a post, we cannot hold CTRL and ENTER to submit the post. Was this removed or maybe a bug? I used the YAF Support Forum for testing.

**Comment by w8tcha** [comment]
Was that a feature before? It does not exist in the ckeditor, but I can add it in the next update

**Comment by Zero2Cool** [comment]
> Was that a feature before? It does not exist in the ckeditor, but I can add it in the next update

Yep. Best feature ever. It's common key combination for submitting posts in other platforms and sending email.
