### ISSUE TITLE
Value cannot be null. Parameter name: httpContext

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#659]
**Describe the bug**
Download the latest source code from master branch, rename the web.config, create a sql server database (e.g. SQL Server 2019) and run the code.

Here are the errors in the order in which I received them after clicking "Continue" in Visual Studio 2019 Professional.
![image](https://user-images.githubusercontent.com/5612416/141787427-84d30eda-ef88-4557-b019-1c4e878d8fe6.png)
![image](https://user-images.githubusercontent.com/5612416/141787461-09e1111e-195c-4384-8555-d508af31c8ca.png)
![image](https://user-images.githubusercontent.com/5612416/141787494-d9f7aef7-6f0d-4673-86b7-5346861a3f31.png)
![image](https://user-images.githubusercontent.com/5612416/141787528-bce0645f-d221-4d65-b1e7-8592b68ac145.png)

**Comment by w8tcha** [comment]
I cant reproduce it, but i submitted a possible fix. Can you confirm it?

**Comment by Zero2Cool** [comment]
I downloaded the source from master, created a SQL Server 2019 database and ran the solution. 

![image](https://user-images.githubusercontent.com/5612416/142768465-0eda7098-bad3-461b-83d4-b132f7e3d0be.png)

**Comment by w8tcha** [comment]
Sorry the recommended.web.config was not updated.

**Comment by Zero2Cool** [comment]
> Sorry the recommended.web.config was not updated.

Repeated same steps from initial issue entry and voila, fresh install works. Thank you.
