### ISSUE TITLE
Could not load file or assembly 'Microsoft.Extensions.Primitives, Version=3.1.0.0

### ISSUE THREAD

**Issue by dieptang** [YAFNET/YAFNET#661]
**Describe the bug**
My forum cannot post new article anymore, I don;t know why when I create new post, click post it's showing error:

` Could not load file or assembly 'Microsoft.Extensions.Primitives, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Primitives, Version=3.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

**To Reproduce**
Very simple, when creating new post, it's showing error page.

**Screenshots**
![image](https://user-images.githubusercontent.com/7411097/142619185-89b2ff28-d2ca-458d-b4b0-0197c0d07656.png)

**WebConfig**
`<runtime>
      <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <probing privatePath="bin;bin\languages" />
        <dependentAssembly>
          <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
          <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="12.0.0.0" />
        </dependentAssembly>
      </assemblyBinding>
     <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Primitives" publicKeyToken="ADB9793829DDAE60" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-3.1.7.0" newVersion="3.1.7.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="B03F5F7F11D50A3A" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.0.6.0" newVersion="4.0.6.0"/>
      </dependentAssembly>
    </runtime>`

**System (please complete the following information):**
 - YAF Version: [e.g. YAF v2.3.1.11]
 - .NET Version [e.g. 4.5]
 - SQL Server [e.g. SQL Server 2016]
 

**Additional context**
I checked the dll inside bin folder, Microsoft.Extensions.Primitives version 3.1.7. Andalso the web.config also having correct setting, but I don't know where is the Microsoft.Extensions.Primitives 3.1.0 on the error.
I tried downgrade dll from Microsoft.Extensions.Primitives 3.1.7 to version 3.1.0 but it's showed Could not load file or assembly 'Microsoft.Extensions.Primitives, Version=3.1.7.0

Please help me find out the solution. Thanks

**Comment by w8tcha** [comment]
Did you follow the upgrade Guide?

https://github.com/YAFNET/YAFNET/wiki/Upgrade-to-YAF.NET-v3.0.1-(or-newer)

` <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="bin;bin\languages" />
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" />
        <bindingRedirect oldVersion="0.0.0.0-13.0.0.0" newVersion="13.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Bcl.AsyncInterfaces" publicKeyToken="cc7b13ffcd2ddd51"/>
        <bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin.Security" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Owin.Security.Cookies" publicKeyToken="31bf3856ad364e35" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Extensions.Primitives" publicKeyToken="ADB9793829DDAE60" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-5.0.0.1" newVersion="5.0.0.1"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="B03F5F7F11D50A3A" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51"/>
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.1" newVersion="4.2.0.1"/>
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Memory" culture="neutral" publicKeyToken="cc7b13ffcd2ddd51" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.1.1" newVersion="4.0.1.1" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>`

**Comment by w8tcha** [comment]
I dont have that old version anymore. You should upgrade first to latest version 3.0.1 or atleast 2.31.16. Otherwise its impossible to help.

**Comment by dieptang** [comment]
> I dont have that old version anymore. You should upgrade first to latest version 3.0.1 or atleast 2.31.16. Otherwise its impossible to help.

Okay, I will update to recent version and update this post soon. Thanks

**Comment by dieptang** [comment]
There are having issue on my Windows Server with .net framework 4.5. It's solved now. Many thanks
