### ISSUE TITLE
Odd behavior with UrlRewriter 

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#662]
I'm using my old UrlRewriter config, but noticed for Topics the T is capitalized and the spaces are not replaced with hyphens. This causes the page to just reload instead of viewing the topics under the forum selected.

The URL in the browser changes to `http://localhost:50544/forum/Topics/4-Green%20Bay%20Packers%20Talk` however, it's just the main forum listing. If I replace `%20` with `-` and hit enter, the page navigates as expected.

Is this a bug or just something I have to figure out with the UrlRewriter?

![image](https://user-images.githubusercontent.com/5612416/143263982-72f033b7-b61b-432b-8cb9-e6834ccffacb.png)

For comparison, this is what I see when I hover over the same forum topic listing on my live site.
![image](https://user-images.githubusercontent.com/5612416/143264635-20071aeb-5742-4c29-bff0-019cb739a8ea.png)

**Comment by w8tcha** [comment]
Another file i forgot to commit. the upgraded urlrewriter.config for the sampleapplication

**Comment by Zero2Cool** [comment]
> Another file i forgot to commit. the upgraded urlrewriter.config for the sampleapplication

Appears to have worked, thank you
