### ISSUE TITLE
Smiley "Categories"

### ISSUE THREAD

**Issue by Jaben** [YAFNET/YAFNET#67]
Provide backend and front-end tabbed control for smiley categories.

**Comment by w8tcha** [comment]
<img width="410" alt="emoji" src="https://user-images.githubusercontent.com/722575/34621491-a5b9e586-f249-11e7-9d79-b558c855c829.PNG">

hello unicode emojis

**Comment by Zero2Cool** [comment]
Are there plans to update the Mobile theme (\themes\yafmobile\mobilepages\) Smiley's as well?

**Comment by w8tcha** [comment]
done

**Comment by Jaben** [comment]
👍

**Comment by Zero2Cool** [comment]
What editor must be chosen to use this? I checked the YAF forums and can't find this feature, and I updated my beta site last night and checked all editors and am not finding it.

**Comment by w8tcha** [comment]
Did you use the stable branch or the beta master branch? The button are available via the standard yaf bbcode editor.

**Comment by Zero2Cool** [comment]
I used the stable branch.

**Comment by Zero2Cool** [comment]
Damn!! lol ... Okay, thank you.  So if I download the latest commit from master branch, I should have this?

**Comment by w8tcha** [comment]
Yes, but be aware a lot oft things are not working in that version.

**Comment by Zero2Cool** [comment]
Understood. Are the things not working listed in the 39 Issues pertaining to this repository?

**Comment by w8tcha** [comment]
No there is no list. And again no its not in the stable branch.
