### ISSUE TITLE
In my profile while selecting my country, state and city, the STATE part doesn't work!

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#673]
**Describe the bug**
In my profile while selecting my country, state and city, the STATE part doesn't work!

**To Reproduce**
1. Go to 'My Settings'
2. Click on 'Edit My Profile..'
3. Scroll down to 'Location'
4. Change 'State' , I first saw no states at all, now I discovered that the state names are colored white on a white background and so, I did not see any of the, ...  the states are there, I just could not see the white names on a white background.....

**Expected behavior**
The colors have to work well. There was no contrast so I could no see them. Please fix the theme template. I have used both dark templates and in both cases I get the same problem.

**System (please complete the following information):**
 - YAF Version: 3.2.1
 - .NET Version 4.8
 - SQL Server 2019
 
**Affected browser**
* [ ] Chrome
* [ x ] Firefox
* [ ] Safari
* [ ] Edge

**Comment by w8tcha** [comment]
Which theme are you using?

**Comment by daprose-dotcom** [comment]
Cyborg and darkly
