### ISSUE TITLE
Please add option to start categories/forums/topics in collapsed mode

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#674]
**Is your feature request related to a problem? Please describe.**
The way it works now, you can read all categories, all forums in each category and on the right side, the latest topics in each forum.

Please add an option in Board Settings to start all categories/forums/topics in collapsed mode or Expanded mode as it is now,
I prefer the collapsed mode, meaning, only categories should be displayed, user must click on the desired category to expand it.

**Describe the solution you'd like**
Please make the display of all categories and forums be collapsed at start up , no forums nor topics to begin with.

**Describe alternatives you've considered**
There is no better alternative as the one I suggest for web sites with a large number of categories and forums. In my case I have a site with 28 categories and over 1740 forums that I need to bring over to YafNet. It makes no sense to display all that on the front page.

**Additional context**
I need this to work like the forums at http://mybbs.org 

Thanks for your help and understanding.

**Comment by daprose-dotcom** [comment]
Excellent, we are getting there!, I had to change the default setting to Collapsed mode in the BoardSettings.cs (Yaf.Configuration) as I did not find the option anywhere in the menus. And it is working fine so far.  Excellent job Ingo!

In the right side of each category there is an arrow to expand or collapse each category. Can you make the Name of Each category a link to do that as well?  

Web pages are MARKUP HYPER LINK pages, People prefer links that they understand without more complications. 
You can have both options, the arrows on the right and the Name of each category itself working as a TOGGLE to EXPAND or COLLAPSE.  This is a very easy thing to do so I hope you approve my request.  Thanks so much for your help and understanding. I think YafNet is ready for the next generation of large scale FORUM MANAGEMENT SYSTEMS.

You are doing a great job.

**Comment by daprose-dotcom** [comment]
Where are you located? I think you sleep while I am awake! Can we chat on the phone/whatsApp?

**Comment by w8tcha** [comment]
Option is under Admin > Board Settings (included with latest commit f92f129cd3258e0b4e9bcfe8867d2d970f749b76) 

> In the right side of each category there is an arrow to expand or collapse each category. Can you make the Name of Each category a link to do that as well?

Also category name is now a link

**Comment by w8tcha** [comment]
> Where are you located? I think you sleep while I am awake! Can we chat on the phone/whatsApp?

Germany, and sorry but to chat support! I already work 12 hours 7 days a week in my main job.
