### ISSUE TITLE
Albums do not work at all

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#676]
**Describe the bug**
I tried to edit/create an album, and instead I was redirected to the board's main page.
No error is given by the application, you are just redirected to the main page.

**To Reproduce**
1. Go to 'My Account'
2. Click on 'Edit Albums'
3. You are being redirected to the main board's page. No to the albums page.

**System (please complete the following information):**
 - YAF Version: v3.2.1
 - .NET Version 4.8
 - SQL Server 2019
 
**Affected browser**
* [ ] Chrome
* [ x ] Firefox
* [ ] Safari
* [ ] Edge

**Comment by w8tcha** [comment]
[FIXED] with c0c576d8e9a273ee56ce9efba1dcb97dc8ccbc72
