### ISSUE TITLE
Stats show erroneous number of Forums and Users

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#679]
**Describe the bug**
The statistics at the footer show a wrong number of forums and users

**To Reproduce**
1. Go to the main board page'
2. Look at the bottom where it says Statistics
3. The number of Forums is wrong! It shows 1 Forum when in reality I have 1587 forums
4. The number of Users is correct as I imported 154 from 8198. However, I can't see any of them except 2 users that I entered manually. 

**Expected behavior**
The number of forums should be taken from a [Count (*) as ForumsCount] FROM the Yaf_Forums table, not from other fields/tables
The number of users displayed is correct, however, I can see any of them in the MEMBERS page, except the 2 users I entered manually.
Again, if it shows the real number, the question is why they do not show up in the members page?
I did check the table YAF_Users  and it is fine, all users are there, but I think you are using two tables, the AspNetUsers and the Yaf_Users, duplicating is not advisable. We have to stick with only one table.

**Screenshots**
![YAF-ERRORS](https://user-images.githubusercontent.com/95335292/158043453-4e1509fb-182d-4b5d-9faa-4aacc226c6f2.png)

**System (please complete the following information):**
 - YAF Version: 3.1.3.BETA
 - .NET Version 4.8
 - SQL Server 2019
 
**Affected browser**
* [ ] Chrome
* [ x ] Firefox
* [ ] Safari
* [ ] Edge

**Comment by w8tcha** [comment]
This statistics are cached, you can clear the cache via the host settings under cache?

Did you create the forums via the admin interface or manually in the db?

**Comment by w8tcha** [comment]
Creating users by manually add them in the user table is a bad idea and will not work! There is a user importing function in the admin interface

**Comment by daprose-dotcom** [comment]
I imported via T-SQL IMPORT SCRIPT the data on both tables successfully, I can see all the categories and forums on the main board page, However, the statistics are wrong. Let me check clearing the cache to see if that works fine. I will let you know.

**Comment by daprose-dotcom** [comment]
Nope!. clearing the cache does not work. Statistics report is still wrong!

**Comment by w8tcha** [comment]
> I imported via T-SQL IMPORT SCRIPT the data on both tables successfully, I can see all the categories and forums on the main board page, However, the statistics are wrong. Let me check clearing the cache to see if that works fine. I will let you know.
> 
> 

Can your post your script for one forum? There must be something wrong with your script.

**Comment by daprose-dotcom** [comment]
How can I send you the database so you can see it? 
I do not want to publish it here!

**Comment by daprose-dotcom** [comment]
I created the scripts on the fly, and after finish it I closed those windows. 
It is very easy. it takes just 2 or 3 lines of code, The main part I used the Import Data feature of the SQL Server management Console. And the cross references I entered via a short SQL- SCRIPT, for example:

INSERT INTO [yafnet].[dbo].[yaf_UserGroup]
SELECT UserID, 3
FROM [yafnet].[dbo].[yaf_Users]

This script imported the UserGroup

**Comment by w8tcha** [comment]
Im back home, i found the problem with the wrong forum count. It only shows the wrong count if there are no topics., Fixed in dce018e4a4a69783fc8ca59dbc79e08cc71aec1c

**Comment by w8tcha** [comment]
> I created the scripts on the fly, and after I finished I closed those windows. It is very easy. it takes just 2 or 3 lines of code, The main part I used the Import Data feature of the SQL Server management Console. And the cross references I entered via a short SQL- SCRIPT, for example:
> 
> INSERT INTO [yafnet].[dbo].[yaf_UserGroup] SELECT UserID, 3 FROM [yafnet].[dbo].[yaf_Users]
> 
> Provided that I had already imported the Yaf_Users table, this script imported the Yaf_UserGroup

Sorry but this will not work you also need to create the user in the membership tables, or use the import feature

**Comment by daprose-dotcom** [comment]
![YAF-IMPORT](https://user-images.githubusercontent.com/95335292/158084237-714edf4a-116c-497c-ad78-462f88113097.png)

YafNet Imported all 7581 members successfully!  Great, we are almost ready to rock-n-roll !!
