### ISSUE TITLE
TapaTalk Support Discussion

### ISSUE THREAD

**Issue by Jaben** [YAFNET/YAFNET#68]
Look into TapaTalk support.

One immediate issue is that TapaTalk seems to be very PHP-y -- the API reflects this with API examples using ".php" extensions:

![tapatalkphpapi](https://f.cloud.github.com/assets/448726/1624955/a9918750-56ca-11e3-8dda-33a2ad0fbfe9.png)

These issues and others would need to be dealt with... frankly, I believe it would take a large rewrite of YAF.NET to make it work properly.

**Comment by Zero2Cool** [comment]
If TapaTalk would take 10-20 hours to implement, what would it the hours to be fore implementing bootstrap?

**Comment by w8tcha** [comment]
You are missing the point, tapatalk will be implemented in the future. A responsive web site with Bootstrap are not solving the same problems as Tapatalk would do.

**Comment by Zero2Cool** [comment]
I thought the point was to be more mobile friendly amongst many devices. That's bootstrap. What problems are there that I'm failing to see?

**Comment by w8tcha** [comment]
Well the most important thing Push Notifications can only be done through native apps not web apps. And also dont forget people prefer native apps over websites on mobile devices.

**Comment by Zero2Cool** [comment]
I had no idea Push Notifications was of any importance whatsoever. Haven't heard anyone asking for it. The number one issue in this regard I hear from users is device compatibility for viewing the forums. That said, you certainly hear a vastly wider audience than my narrow short user base, lol.   Anyhow, if it's that important, that will be great for YAF to have that Tapa Talk stuff going.  Looking forward to that.

**Comment by JP58** [comment]
Hmmm... SignalR, anyone? ;-) 
Server "push" made easy... Could maybe be applicable for the forum software too....
