### ISSUE TITLE
Make PLAY/AUDIO BBCode a native BBCode distributed in YafNet

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#680]
**Is your feature request related to a problem? Please describe.**
Please make the PLAY (radio/audio/voice) BBCode a native BBCode distributed in YafNet

Please check this site: http://mybbs.org/foros/posts/t6-La-Mundialisima---La-mejor-de-todas

**Describe the solution you'd like**
I know you already have YouTube and perhaps VIDEO, but there is no AUDIO/RADIO/VOICE BBcode ready. Please include the following code with YafNet: 

NAME: AUDIO
DESCRIPTION: [AUDIO][localization=AUDIOMOD_DESCRIPTION]Place your radio/voice/audio URL here[/localization][/AUDIO]

Normal Expression: \[audio\](?<inner>.+?)\[/audio\]

Replace Normal Expression with: 
[div]
[audio controls autoplay]
  [source src="${inner}" type="audio/mpeg"]
[/audio]
[/div]

Replace [ and ] with "<" and ">" 

**Describe alternatives you've considered**
Radio/Audio/Voice is strong entertaiment now a days, please check this out at:
http://mybbs.org/foros/posts/t6-La-Mundialisima---La-mejor-de-todas

Please add them all. We live in an era where audio, video, speach and radio are all required.

**Comment by daprose-dotcom** [comment]
[BBCodeExport.zip](https://github.com/YAFNET/YAFNET/files/8239169/BBCodeExport.zip)

**Comment by w8tcha** [comment]
> Please add them all. We live in an era where audio, video, speach and radio are all required.

You can add custom bbcodes via Admin > Settings > BB Code Extensions

**Comment by daprose-dotcom** [comment]
Why not make it easy for other users that are not as technical as you and me. The great majority are lost in space. Please include the BBcode in the main stream of yafNet.

**Comment by daprose-dotcom** [comment]
I tried to login into your YafNet support forum , entered my login ID wich is the same as here, daprose-dotcom , forgot my password, off course, I need to authorize your email server IP to receive the password recup email. What is your SMTP IP to authorize you at my end...

**Comment by daprose-dotcom** [comment]
GOt it, I just authorized the last IP in my log and it did work! I got the email
