### ISSUE TITLE
While editing My Profile, YafNet crashes baddly!

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#681]
**Describe the bug**
Wanted to update my profile, added a URL and some Info, tried to save but it crashes!

**To Reproduce**
1. Go to 'My Account'
2. Click on 'Edit Profile'
3. Add some text in info and a URL'
4. Try to SAVE
5. It crashes!

**Screenshots**

Forum Error

Exception of type 'System.Web.HttpUnhandledException' was thrown.

System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.Globalization.CultureNotFoundException: Culture is not supported.
Parameter name: name
en_us is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at System.Globalization.CultureInfo.CreateSpecificCulture(String name)
   at YAF.Controls.EditUsersProfile.get_CurrentCultureInfo()
   at YAF.Controls.EditUsersProfile.UpdateUserProfile()
   at YAF.Controls.EditUsersProfile.UpdateProfileClick(Object sender, EventArgs e)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**System (please complete the following information):**
 - YAF Version: 3.1.3.BETA
 - .NET Version 4.8
 - SQL Server 2019
 
**Affected browser**
* [ ] Chrome
* [ x ] Firefox
* [ ] Safari
* [ ] Edge

**Additional context**

**Comment by w8tcha** [comment]
Where does this value "en_us" coming from? Have you modified the language files ?

**Comment by daprose-dotcom** [comment]
> Where does this value "en_us" coming from? Have you modified the language files ?

I may have created the culture field in the old database that I imported. I changed all user's culture to NULL

**Comment by w8tcha** [comment]
> > Where does this value "en_us" coming from? Have you modified the language files ?
> 
> I may have created the culture field in the old database that I imported. I changed all user's culture to NULL

Does it work now with user culture null?

**Comment by daprose-dotcom** [comment]
yes, it works! And it does not produce any errors no more while editing my profile. Maybe that was the problem!

**Comment by daprose-dotcom** [comment]
AS you can see. I am an expert in crashing anything I put my hands on!

**Comment by w8tcha** [comment]
> yes, it works! And it does not produce any errors no more while editing my profile. Maybe that was the problem!

Good this should also solved the other issue #682

**Comment by daprose-dotcom** [comment]
Yes, both problems solved, but It does not allow me to post any attachments. I can enter the page but it is all empty, no options, no buttons no nothing

**Comment by w8tcha** [comment]
> Yes, both problems solved, but It does not allow me to post any attachments. I can enter the page but it is all empty, no options, no buttons no nothing

I dont understand the problem? On the Edit Profile page you cant add attachments.,

**Comment by daprose-dotcom** [comment]
Yes, please Go to My Account, you can not add any attachments there! the page is blank.

**Comment by w8tcha** [comment]
The page you referring to only list the existing attachments.

Attachments can only be added via the editor. Simply drag and drop a file in the editor. Or use the paperclip button in the editor toolbar
