### ISSUE TITLE
YafNet changed my language from English to arabic.xml

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#682]
**Describe the bug**
Without me selecting to change language, Yafnet changed my language from English to Arabian, I could not understand anything I read on the screen. This is a horrendous bug!! 

I was testing the SAVE option in each one of my Profile Settings, and suddenly it changed my language!! I had to go to the database and manually change it back to the English language!

**To Reproduce**
1. Go to 'My Account'
2. Click on 'Edit Profile'
3. Scroll down and test each of the options and SAVE, even if you do not make any changes.
4. See the error. Some pages crash and suddenly it changed my language all by itself!

**Expected behavior**

**Screenshots**
I should have taken a picture but I was too busy trying to figure out how to recover. I could not understand anything I saw on the screen. 

**System (please complete the following information):**
 - YAF Version: 3.1.3.BETA
 - .NET Version 4.8]
 - SQL Server 2019
 
**Affected browser**
* [ ] Chrome
* [ x ] Firefox
* [ ] Safari
* [ ] Edge

**Comment by w8tcha** [comment]
What error are you getting?

**Comment by daprose-dotcom** [comment]
I did NOT get any error msg when it suddenly changed my language from English to Arabian

**Comment by daprose-dotcom** [comment]
I did get an error while trying to SAVE MY PROFILE, I posted the error MSG on a separate issue ..
