### ISSUE TITLE
Please move the welcome user message above the main menu

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#685]
**Describe the bug**
Nothing should be displayed over the top of the main menu. In fact, have an option to remove the header image from the top of the main menu so we can have a headless forum like I have at http://daprose.com/forums 

**To Reproduce**
1. Go to 'yafNet' at http://daprose.com/forums 
2. See that I removed everything above the main menu, but I do not want to do this on the source code, I prefer an option in the Board Settings (Display Settings) area, With Banner o no Banner above the main menu.

We should do the same with the Welcome Message, it should be displayed UNDER THE MAIN MENU, nothing above the main menu. Please correct that in future versions. Thanks a lot....

**System (please complete the following information):**
 - YAF Version: 3.1.3.BETA
 - .NET Version 4.8]
 - SQL Server 2019
 
**Affected browser**
* [ x ] Chrome
* [ x ] Firefox
* [ x ] Safari
* [ x ] Edge

**Comment by w8tcha** [comment]
There exist a setting to Hide the Logo.  Its currently in the app settings in the web.config

`<add key="YAF.ShowToolBar" value="false" />`

**Comment by w8tcha** [comment]
> Nothing should be displayed over the top of the main menu.

Thats seems like a personally choice not a bug. I will add a setting to disable that message.

**Comment by daprose-dotcom** [comment]
> <add key="YAF.ShowToolBar" value="false" />

Where in the web.config should I place this?

It would be better as an option in the Host -> Host Settings -> Display options
