### ISSUE TITLE
List all categories and/or subcategories, Forums/Subforums alphabetically

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#686]
Please list all categories and/or subcategories, Forums and /or Subforums alphabetically.

When dealing with names, (like the phone book or yellow pages), list of countries, list of students, etc. lists are always ALPHABETICAL, never ever scrambled.  Use the order categories by number only when the number is greater than 0, otherwise, ORDER BY CATEGORY/FORUM NAMES always! 

**System (please complete the following information):**
 - YAF Version: 3.1.3.BETA
 - .NET Version 4.8
 - SQL Server 2019
 
**Affected browser**
* [ x ] Chrome
* [ x ] Firefox
* [ x ] Safari
* [ x ] Edge

**Comment by daprose-dotcom** [comment]
This should be considered a programming error as all lists in the whole planet, every country you live at, are alphabetical, not by number.

Tasks, instructions, commands, bill payments, they are by number of priority, but not any list of names. Please reconsider

**Comment by w8tcha** [comment]
This is a misunderstanding. The Ording number makes it possible to sort the forums in the way the admin wants to th order to be.

For example..

I would want a order like this..

* feature requests
* Bugs

And not 

* bugs
* Feature requests

With the sort order by id this is possible

**Comment by daprose-dotcom** [comment]
Please let each Forum administrator choose or decide: SORT BY ORDER NUMBER, or SORT ALPHABETICALLY FROM A-Z

The option must be there for Categories, for Forums, and for Topics

**Comment by w8tcha** [comment]
As a compromise would you accept a function in the. Admin interface that changes the sort order automatically to make it order from a-z?

**Comment by daprose-dotcom** [comment]
Yeahhh!!! Thank you Ingo, I know that after reasoning a little bit, the light will come to you as it comes to me. Thanks a lot for not being so hard headed.

**Comment by daprose-dotcom** [comment]
If you present this:

    bugs
    Feature requests

Instead of this

    feature requests
    Bugs

Believe me, you will not kill anybody.

**Comment by daprose-dotcom** [comment]
Please go to http://daprose.com/forums

Click on Regional, and find your country! Germany!
See the list of countries already alphabetized.  That is how people find they country, from A-Z, imagine if the list would be scrambled! It would be crazy!!

Now imagine if I want to add another country to the list, maybe I forgot to list it before, wowowwwww, too much work adding and reorganizing everything by number!

**Comment by w8tcha** [comment]
But you can compare a country  list with the board layout, that to completely different lists

**Comment by daprose-dotcom** [comment]
No my friend, you are thinking a Forum as a "Tech support Forum". 
I am thinking YafNet as a Global tool for all types of forums.

Plus, if you alfabetize and I want to order  a forum to be first in the list, I can always add a character in the beginin, like:

1. My First Category
2. My Second Category
The A category
The B category

So, if you alphabetize the categories from A-Z I still have full control on placing one category before all other categories by adding any character before the name that is lower than "A"
