### ISSUE TITLE
The Statistics should be part of the Footer

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#687]
I see the statistics only on the main page but no statistics when I read topics or see the list of forums. 
The site statistics must be shown in all pages regardless, (except ADMIN pages). Please make it a part of the footer instead!

**System (please complete the following information):**
 - YAF Version: 3.1.3.BETA
 - .NET Version 4.8]
 - SQL Server 2019
 
**Affected browser**

All browsers

**Comment by w8tcha** [comment]
Why is that a must? Seems more like a waste of space.

**Comment by daprose-dotcom** [comment]
Well, the statistics show the latest number of topics, it should include replies and the last/new member aboard. 

That makes it very interesting, but I would like to add to the statistics the time of the latest visitor online, this is very important as well. I say this is very important because if a see a visitor that just entered the site then I can start talking to him on the audio broadcast using the BBcode you just added to yafnet, (remember?), and he/she will hear my voice while visiting the forum,  Comprende?

**Comment by daprose-dotcom** [comment]
So, the Admin Announcement Box should understand BBcodes as well.

**Comment by w8tcha** [comment]
> I see the statistics only on the main page but no statistics when I read topics or see the list of forums.
The site statistics must be shown in all pages regardless, (except ADMIN pages). Please make it a part of the footer instead!

Please understand that this request seems to be specific to your forum. If this is not requested by more users it wont be added.

But here is a way on how to implement it in your source..

1. Disable the Stats in the Host Settings > Display > Show Forum Statistics 
2.  Then in the Project YAF.Web  in the file Controls/Footer.cs

change line from...

```c#
writer.Write(@"<footer class=""footer""><div class=""text-end"">");
```

to...
```c#
var stats = this.Page.LoadControl($"{BoardInfo.ForumServerFileRoot}controls/Statistics.ascx");

writer.Write(stats.RenderToString());

 writer.Write(@"<footer class=""footer""><div class=""text-end"">");
```

**Comment by daprose-dotcom** [comment]
Yes, I did it as suggested and it works better this way, We could also move it to the right column but that column only shows on the main board. So, I preferred it to be a part of the footer, I just need to add some more information to the statistics. I need the last visitor's date and time.

**Comment by w8tcha** [comment]
> I just need to add some more information to the statistics. I need the last visitor's date and time.

You can get the last visitor from the Active Table

Put this in the ActiveRepositoryExtensions.cs file (in the project YAF.Core)

```c#
public static ActiveUser GetLastActiveUser(this IRepository<Active> repository)
        {
            CodeContracts.VerifyNotNull(repository);

            return repository.DbAccess.Execute(
                db =>
                {
                    var expression = OrmLiteConfig.DialectProvider.SqlExpression<Active>();

                    expression.Join<User>((a, u) => u.ID == a.UserID && (u.Flags & 4) != 4).Select(a => Sql.Max(a.LastActive))
                        .Select<Active, User>(
                            (a, b) => new
                            {
                                a.UserID,
                                UserName = b.Name,
                                UserDisplayName = b.DisplayName,
                                b.UserStyle,
                                IsGuest = Sql.Custom<bool>(
                                    $"({OrmLiteConfig.DialectProvider.ConvertFlag($"{expression.Column<User>(x => x.Flags, true)}&4")})"),
                                b.Suspended,
                                a.Browser,
                                a.LastActive
                            });

                    return db.Connection.Single<ActiveUser>(expression);
                });
        }
```

then you can load it on the Controls/Statistics.asxc page

```c#
<li class="list-group-item">
                                <%= this.GetRepository<Active>().GetLastActiveUser().LastActive %>
                            </li>
```

that show the last active user date and time

**Comment by w8tcha** [comment]
> I have recompiled it and I still get an error here:
> 
> <%= this.GetRepository().GetLastActiveUser().LastActive %>

What error are you getting?

**Comment by daprose-dotcom** [comment]
It was a compiler error. It does not recognize the "LastActive" part
