### ISSUE TITLE
Dashboard does not show number of categories, number of forums, nor number of replies

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#688]
**Describe the bug**
The Admin Dashboard does not show number of categories, number of forums, nor number of replies.
Please make sure we show all the counts in the admin dashboard.

Also please change "POSTS" for "TOPICS" Posts is a common gorgon of BLOGS, not used in FORUMS, in Forums we post "TOPICS", Lets use a global terminology please! 

Categories --> Forums --> Topics --> Replies

**To Reproduce**
1. Go to 'Admin'
2. Click on 'Admin Index'
3. See this ...

![daprose-forums-dashboard](https://user-images.githubusercontent.com/95335292/158238518-ecff4f73-eecf-4e63-a731-f5470a6853cc.png)

**System (please complete the following information):**
 - YAF Version: 3.1.3.BETA
 - .NET Version 4.8
 - SQL Server 2019
 
**Affected browser**
All browsers

**Comment by daprose-dotcom** [comment]
My friend. Please do not put this request in the list of "never do these" but in the list of DO THIS IMMEDIATELY. Thank you!

**Comment by w8tcha** [comment]
Well it's not a bug it's an feature request. And not in the list of never to do things.

But you have to understand that this is an open source project. I have a real job, and only 3-5 hours a week where I have time to turn on a computer and work as volunteer on this project. So of course I have to prioritize every issue.

**Comment by daprose-dotcom** [comment]
Dear Ingo, I happily volunteer to help you all the way, once I learn to program in c# off course. I am not a c# programmer but I do understand that language as I was a C programmer in my old days. Really, I am not strong in c# like you obviously are. I do prefer vb.net, asp classic. and also the old "C" language for desktop or server applications. 

My believe is that if we can produce "a more competitive Forum application", you and me will endup working exclusively for  YafNet. 

By a more competitive application I mean we have to "DEFEAT" the big monsters already dominating the market (Facebook and Twitter).  I do not think this is impossible, but it does require to arm ourselves with a more logical, more advanced, and more efficient APP than the one we already have. We are not too far. I think we are getting closer, You are already in the right direction. But not there yet. Let's keep working on it, we can succeed. Yes we can.

Check: http://daprose.com/forums and let me know if you hear the radio automatically,
