### ISSUE TITLE
Add the Board Announcement message to the TOP on the right column

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#689]
Please Add the Board Announcement message box to the TOP on the right column, 
Please do not place it under the main menu as it is now!

Make it look like this please !!

![daprose-forums-main](https://user-images.githubusercontent.com/95335292/158255247-ee61caa7-e941-440f-af00-253beca060ca.png)

**Comment by w8tcha** [comment]
I prefer it under the main menu. Placing it on the right column would place it on the end of the page on small screen devices. Also the 2 Column layout is only used on the Board page.

Feel free to add this yourself in the Board.ascx

```c#
<%@ Register TagPrefix="YAF" TagName="BoardAnnouncement" Src="../controls/BoardAnnouncement.ascx" %>

 <% if (this.PageBoardContext.BoardSettings.TwoColumnBoardLayout){ %>
        
            <YAF:BoardAnnouncement ID="BoardAnnouncement" runat="server" />
    <% } %>
        <YAF:ActiveDiscussion ID="ActiveDiscussions" runat="server" />
```

**Comment by daprose-dotcom** [comment]
It has to look as nice as the one I end you the image. It doesn't matter if on mobile devices it goes to the bottom of the page, but above the "Active Discussions" panel..   I have no idea hot to make it look nice as the image I send you.. It has to match the feel and look of the board!!   I do not know where to insert the code you have just sent me.  Not a remote idea.
