### ISSUE TITLE
Publishing replaces all the config files except the web.config

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#690]
**Describe the bug**
First, I have to congratulate you for providing us a copy of yafNet that publishes the web SQL Server portion on the first shot!! 

No errors whatsoever, and it published all files successfully. Please see the new version o yafnet at
http://daprose.com/forums

Second. The only errors that I've noticed are that all my config files (except web.config) where replaced and I lost all my configurations. That should not happen at all. 

Please make those changes now. Change all config files (app.config, db.config, mail.config, etc) to recommended-app.config, recommended-db.config, recommended-mail.config, and so on) so people do not crash their systems on the first try. Also, include the recommended-web.config file, this is very important.

Besides that, I did not really like having the header image or anything above the main menu but I will check the ADMIN pages to see how to get rid of that. 

You are doing a great job Ingo. Every time I try YafNet is better and better! Congratulations!!
Please send me via email the 3.1.3.BETA zip file to support@daprose.com , the one we have been working on the past days! I do not want version 3.1.2

**Comment by w8tcha** [comment]
> Please send me via email the 3.1.3.BETA zip file

You can always download the latest source code from github

https://github.com/YAFNET/YAFNET/archive/refs/heads/master.zip
