### ISSUE TITLE
Yafnet does not remove the image on the heading

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#691]
**Describe the bug**
When I clear the name of the logo image name in the ADMIN -> SETTINGS -> BOARD SETTINGS page, after I click SAVE the logo name is still there. It should not show any image nor save the old name I just cleared from that box.

**To Reproduce**
1. Go to 'ADMIN -> SETTINGS -> BOARD SETTINGS'
2. Clear the name of the logo file'
3. SAVE the new configuration
4. The logo is still there and the name just cleared is still there!

**Expected behavior**
When I clear the logo name it must not show anything above the main menu.

**Screenshots**
![daprose-forums-logo-error](https://user-images.githubusercontent.com/95335292/158269461-247ffb6e-a868-46df-8f87-516a6b80a8c5.png)

**System (please complete the following information):**
 - YAF Version: 3.1.2
 - .NET Version 4.8
 - SQL Server 2019
 
**Affected browser**
ALL BROWSERS

**Comment by w8tcha** [comment]
The only way to hide the logo is to disable it in the appsettings in the app.config

` <add key="YAF.ShowToolBar" value="false" />`

The option to clear the selection should not be there. This will be fixed in 3.1.3

**Comment by daprose-dotcom** [comment]
I tried <add key="YAF.ShowToolBar" value="false" /> but it also removes the main menu. I do not want that. So, the other option is better, removing or commenting out the welcome control from the Board page.

**Comment by w8tcha** [comment]
Sorry i forgot the appsetting also removes the menu. To remove the logo only remove the banner link in the default.aspx

`<asp:HyperLink runat="server" id="BannerLink"></asp:HyperLink>`

**Comment by daprose-dotcom** [comment]
Ohhh, I have already done that myself, that is why in my source the banner does't show the logo image.
Thanks for the advice anyway!
