### ISSUE TITLE
How to remove Current Time and Your Last Visit?

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#692]
How do I remove the Current time: 5:20:28 PM. and Your last visit: Monday, March 14, 2022 5:02:42 PM.

I do not want anything to show in that line.

**Comment by w8tcha** [comment]
The easiest solution would be to remove the control from the board page

Remove the html from the file ../Pages/Board.ascx

```c#
<div class="row">
    <div class="col">
        <YAF:ForumWelcome runat="server" ID="Welcome" />
    </div>
</div>
```
