### ISSUE TITLE
Please do not load any forum names on the main board page

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#693]
**Is your feature request related to a problem? Please describe.**
Hello Ingo, we need to save all unnecessary hits to the SQL server. We do not need to load the 2000 forums to he main board page.  We may have to divide/duplicate the main board page into 2 or 3 pages.

The first page, (the board page), lists only the categories. 
The second page, (a Forums page), lists only the forums available on the category selected on the first page.
The third page, shows only the topics available on the forum selected on the second page.

If we do these, we will not load any unnecessary data from the SQL server. Memory will be optimized and YafNet itself will run faster, Meaning that we can accommodate and serve more users and have more categories, more forums and more topics.  (Remember to alphabetize everything from A-Z)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by daprose-dotcom** [comment]
For the Board Page, we will only read the categories once, and serve that list to all sessions. 
We will never have to read the sql server again to obtain the list of categories but only once, 
no matter how many visitors we may have.

PROCEDURE:
Create a DICTIONARY, or a VIRTUAL RECORDSET on the GLOBAL.ASAX 
We only need to DECLARE two fields, the CATEGORY_ID and the CATEGORY_NAME. 
Do not try to add any data to the DICTIONARY, or a VIRTUAL RECORDSET on the GLOBAL.ASAX 

This DICTIONARY/RECORDSET will be filled once on the Board.cs.ascx and will serve all sessions without hitting the SQL server again and again on every visitor's visit.

The first visitor will fill UP the data on the DICTIONARY/RECORDSET created in the GLOBAL.ASAX. Wi will save millions of unnecessary hits to the SQL Server

**Comment by w8tcha** [comment]
I do not understand the problem you're trying to solve. To get the categories and forums on the start page is only 1 db call, no matter how many forums and categories there are

**Comment by daprose-dotcom** [comment]
Every time we have a visitor, the SQL Server is hit with a request for all categories and forums.
If you follow my advice, the SQL Server will be hit only one time no matter how may thousands of user/visitors we may have. I will send you the sample code so you will understand better and implement it. This is invisible to the users and admins, but the result is the front page will be a lot faster to show up and the SQL Server is never hit again for each visitor.

**Comment by daprose-dotcom** [comment]
include the following line as the first line on the global.asax

<OBJECT ID="rsCategories" PROGID="ADODB.Recordset" RUNAT="Server" SCOPE="Application"></OBJECT>

Include the following code in the Application_OnStart Area in the global.asax

    Application.Lock

        rsMyCats.Fields.Append "CatID", 3, , adFldIsNullable
        rsMyCats.Fields.Append "CatName", 200, 100 , adFldIsNullable
        rsMyCats.Open

    Application.UnLock

**Comment by w8tcha** [comment]
Sorry but you don't understand the forum. Be aware that the forum list ist different for every user. And it loads other date with one db call. Performance wise it would not make it faster to cache this list

**Comment by daprose-dotcom** [comment]
Please, investigate a little bit!
This procedure is implemented at http://mybbs.org 
Check it out....

To understand the difference.  go to http://gtmetrix.com
and then compare the load speed of YafNet (http://yetanotherforum.net) versus MyBBS (http://mybbs.org)

**Comment by daprose-dotcom** [comment]
See the report, YafNet got a GRADE "C" with only 69% Efficiency
MyBBS got a grade "A" with 100% efficiency

![gtmetrix-compare](https://user-images.githubusercontent.com/95335292/158489209-1f894b94-8ec9-4a10-be27-0feaa38e46b4.png)

**Comment by daprose-dotcom** [comment]
By the Way, GRADE "C" are the worst websites in the world, when it comes to SPEED AND PERFORMANCE

**Comment by w8tcha** [comment]
But the results are caused by the Javascript files. This has nothing to do with the sql. You can see it in the results at the gtmetrix page. Those js files are only once after that the browser caches them.

**Comment by daprose-dotcom** [comment]
You are not being logical. 
For you, it is the same 1 millon hits to the server than only 1 hit, serving the same 1 millon users/
Are you in your good senses?

**Comment by daprose-dotcom** [comment]
Better I am going to grab a beer and fly as high as possible to forget I mentioned to you these concerns that are not your concerns whatsoever. Good night dear Ingo. Need to rest a little bit.

**Comment by w8tcha** [comment]
Why are you so rude? I was responding to the comments you made about the results from the gtmetrix site...

![4FE8C65C-1DF9-47BE-AC1B-BA2C12779F0C](https://user-images.githubusercontent.com/722575/158492978-173a15d0-31f7-4cb2-8fa5-e5d320d1a3c0.png)

You can see in the results why the rating is lower

**Comment by daprose-dotcom** [comment]
Yes, that is another problem we need to discuss, all the unnecessary java scripts and modules, but I am not ready to touch bases on that area because I have not investigated enough ... some other time, my primary concern is the unnecessary load of all the categories and forums over and over again when in fact it is not necessary.

When we create a recordset at the application level, (not at the session level), this will never be recreated nor duplicated for each new visitor we receive, but instead we can access this recordset from every user's session. 
Why does it sound impossible to do this?  I see it as something very useful, very practical, very important. People love fast websites, believe me!! plus I am really concerned because I have another idea in my mind that I have not shared it with you as yet but it is doable. Do you ever sleep?

**Comment by daprose-dotcom** [comment]
Ooohh jejejeje so sorry! I was making a jock , you did not understand it. So sorry if I did not make myself clear. I do not have any intentions to insult you whatsoever. Never take it that way. 
I, (same as you), English is not my native language, I speak 4 languages, English, Italian, Portuguese and Spanish, ( and a little bit of Cirillo (Russian) as my wife was from Russia.)   please forget it. 

> You make assumptions without knowing or understanding the code. I know you don't believe anything I'm writing but you have to understand that certain db calls are necessary in order to make the forum work. Since yaf 3 I reduced the db calls by at least 60%. And everything that can be cached is cached.

Dear Ingo, please cool down. Please do not get emotional on any issues I discus with you. My goal is your very same goals, We are in the same team, I am not against you but with you, in your team. So, you and I want the best output on this project. 

I do understand you very well what you mean, We may have to create a definite fork and have two versions of YafNet, One as you have designed it and programmed it, And the other With a different Name called: 

**YetTheSameForumButFaster**, a Forum that we can put all the ideas that come to mind to make it faster or better or simply for large scale forums with over 30,000 forums or so.  Please remember the old USENET which is still alive but I think it is almost dead, mainly because the ambitions and caprices of a few individuals that have commercialized the ideas and opinions of people all over the world. Now a days, you have to pay big money to have access to the complete USENET stream, so, a few people offer free access to some categories of the USENET stream but those services are almost unreliable. 

So, I had an idea, one that I have no idea if it is possible to accomplish or not, it has to do with forums all over the world but sharing the exact same database.  Internet speed have improved tremendously to the point that I can have a 10 gigabits for only $100 per month. Before, to obtain this speed was practically impossible, but not today. So, sharing a common database to provide users a better service, it does not seem to be a bad idea. As I told you, I have no idea if this is something you and I can do. Or I may have to try it on my own. But heck!   we would not be programmers if we don't like experimenting, improving, innovating, etc.

**Comment by daprose-dotcom** [comment]
So, after everything was said and we are still good friends, almost ready to share the same house and food, let's to this step by step. Remember I am not a c# programmer so you may have to help me, and one we accomplish these goals, you will see the difference:

LETS DO STEP # 1:
include the following line as the first line on the global.asax
[OBJECT ID="rsCategories" PROGID="ADODB.Recordset" RUNAT="Server" SCOPE="Application"></OBJECT]
Change [ and ] for < and > in the precious line

System Should NOT crash with that addition in the GLOBAL.ASAX
I am doing it in my version right now!

**Comment by daprose-dotcom** [comment]
Yes, I did make the change. the RECORDSET was created and YafNet did not crash !!

Now, lets to STEP #2
Include the following code in the Application_OnStart Area in the global.asax

Application.Lock

    rsCategories.Fields.Append "CatID", 3, , adFldIsNullable
    rsCategories.Fields.Append "CatName", 200, 100 , adFldIsNullable
    rsCategories.Open

Application.UnLock

**Comment by daprose-dotcom** [comment]
My GLOBAL.ASAX looks like this:

-------------------
`
<OBJECT ID="rsYafCategories" PROGID="ADODB.Recordset" RUNAT="Server" SCOPE="Application"></OBJECT>
<%@ Application Inherits="YAF.Core.Context.YafHttpApplication" Language="C#" %>

<script runat="server">

    static string _pagePath;

    void Application_OnStart(object sender, EventArgs e)
    {
        // Code that runs on application startup
        Application.Lock();
        //rsYafCategories.Fields.Append("CatID", 3, 0, ADODB.FieldAttributeEnum.adFldIsNullable);
        //rsYafCategories.Fields.Append("CatName", 200, 100 , ADODB.FieldAttributeEnum.adFldIsNullable);
        //rsYafCategories.Open();
        Application.UnLock();

    }

    void Application_BeginRequest(object sender, EventArgs e)
    {
        string path = Request.PhysicalPath;
        if (path == _pagePath)
        {
            //Response.Write("Page viewed");
            //Response.End();
        }
    }

</script>
`
------------------

Can you please make it work! I do not know the c# equivalent for the field.append, I think this is correct but we need a reference for the ADODB library only.
