### ISSUE TITLE
When I reply to one of my own replies Yafnet Crashes

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#696]
**Describe the bug**
When I reply to one of my own replies, Yafnet crashes!!

**To Reproduce**
1. Go to 'any reply' of your own
2. Click on 'Reply'
3. Enter eny text and save it
4. See error, Yafnet crashes but it does add the reply! It is there!

**Expected behavior**

**System (please complete the following information):**
 - YAF Version: 3.1.3.BETA
 - .NET Version 4.8
 - SQL Server 2019
 
**Affected browser**
* [ ] Chrome
* [ x ] Firefox
* [ ] Safari
* [ ] Edge

**Additional context**

**Comment by w8tcha** [comment]
Can you post the error message?

Atleast with an unmodified version i can not reproduce the error

**Comment by daprose-dotcom** [comment]
Here is a copy of the error message

            <h2> <i>Access to the path 'C:\inetpub\wwwroot\aspx-aspnetportal\App_Data\search_index' is denied.</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An unhandled exception occurred during 
the execution of the current web request. Please review the stack trace 
for more information about the error and where it originated in the 
code.

            <br><br>

            <b> Exception Details: </b>System.UnauthorizedAccessException: Access to the path 'C:\inetpub\wwwroot\aspx-aspnetportal\App_Data\search_index' is denied.
<br><br>ASP.NET is not authorized to access the requested resource. 
Consider granting access rights to the resource to the ASP.NET request 
identity. ASP.NET has a base process identity (typically 
{MACHINE}\ASPNET on IIS 5 or Network Service on IIS 6 and IIS 7, and the
 configured application pool identity on IIS 7.5) that is used if the 
application is not impersonating.  If the application is impersonating 
via &lt;identity impersonate="true"/&gt;, the identity will be the 
anonymous user (typically IUSR_MACHINENAME) or the authenticated request
 user.
<br><br>To grant ASP.NET access to a file, right-click the file in File 
Explorer, choose "Properties" and select the Security tab. Click "Add" 
to add the appropriate user or group. Highlight the ASP.NET account, and
 check the boxes for the desired access.<br><br>

            <b>Source Error:</b> <br><br>

            

An unhandled exception was generated during the execution of the current  web request. Information regarding the origin and location of the  exception can be identified using the exception stack trace below.
--


</font>
</body>
</html>

**Comment by daprose-dotcom** [comment]
Ok ok now I know what is going on, in the new website I just created, I did not have the App_Data folder, nor it had all rights, so I fixed that and now it works fine. No more errors.

You should distribute your app with that folder, even if it is empty, and add instructions to make that folder writable.

Case closed for me ! But you will have the same issue with every new installation!!

**Comment by w8tcha** [comment]
When the write permissions are set for the entire folder, then the folder is created automatically. The check for writing permission is now executed automatically on the install wizard
