### ISSUE TITLE
Please add an IsActive field in the Yaf_Category

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#697]
> I can't help you. If you already modified the source code that all boards share the same data. Then simply add the is active column yourself. If you need this.

Sorry Ingo, I have to insist in this request for the following reasons:

1) I have not made any changes in the database structure, nor in the code itself, perhaps you did not know but your setup is already working that way, It does accept a shared database by default, without me making any changes! I just discovered this is possible and it is working great!!  So, this is something you did, not something I did!!  I am only trying to take advantage of something "you did", and as I told you, this is a beautiful feature for which I congratulate you.

2) As I told you before, even if we do not go further, Administrators need that feature to enable/disable categories on a temporary bases.  This is a requirement that doesn't have anything to do with having a shared database or not, but it should work fine in both cases anyway.

Please reconsider!

**Comment by w8tcha** [comment]
Okay i created another milestone release 3.2.0. This is the next release containing new features. And probably the last release for the old obsolete.net framework.

Please understand that feature is really complex and this requires a lot of code changes in various places, and this will take time.

**Comment by daprose-dotcom** [comment]
The main idea is:

1, ALTER the yaf_Category table and add the field name IsActive, Type bit, default value = 1
2. Add a check box or a sliding bar (YES/NO) in the CATEGORY FORM to deactivate or activate each category.
3. Modify the SQL QUERY that pulls the categories and ADD a condition in the SQL STATEMENT "WHERE IsActive = 1"
4. Modify the UPGRADE SQL SCRIPT so all previous installations get updated to the new structure.

WE SHOULD BE DOING THE SAME FOR THE FORUMS not only for the categories as this is a very useful feature to manage and control all categories and forums without having to delete anything.

Thank you for your patience and understanding.

**Comment by daprose-dotcom** [comment]
> And probably the last release for the old obsolete.net framework.

Just a comment: Please remember that all applications in the whole planet were developed for the /net framework. so, it will never be obsolete. 

Microsoft has brought a lot of junky technology to the market that never succeeded. There you have F#, just to mention one. This was supposed to replace c# and guess what, no way!! That will never happen!   By the way, I am still programming in the old "ASP Classic" that started almost 35 years ago,  All new servers and desktop operating systems still offer that language because the millions of applications that still run on that language. This is amazing.  And I am using the QuickBasic Compiler 64 for all my linux machines!  That language is so generous and powerful, thanks God it exists!

The new CORE platform is said that will also sun on LINUX machines, I think for that to happen they should also offer a HTTP Server that understands all the CORE applications, and that m,y friend means the Administrators will need to REMOVE the APACHE servers.  hehehehe no way my friend!!  No one will do that ever. They may have to setup new machines with the CORE server, yes, but the Apache Server so far is wining the market share in the whole planet!!
