### ISSUE TITLE
Main Board Page hits the SQL Server in excess

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#699]
Dear Ingo, I have developed a short application in ASP.NET to do exactly what I have been recommending you to do in YafNet.  The result of implementing my recommendation is impressive as you can see in the image-report from GTMETRIX.COM

Check the results. I am using the same amounts of Nugets and JavaScripts but the difference in performance is tremendous. (Huge!!)

**To Reproduce**
1. Go to 'http://gtmetrix.com'
2. Enter your domain name and compare it with http://AspNetPortal.XYZ
3. See the results
4. We should think about this carefully. The more times my website is visited, the more hits my server evades. 

**Screenshots**
![gtmetrix-aspnetportal](https://user-images.githubusercontent.com/95335292/159103973-46b9a963-0d7c-42a1-b234-e2fcd2dcd7fc.png)

**System (please complete the following information):**
 - YAF Version: 3.1.3.BETA
 - .NET Version 4.8
 - SQL Server 2019
 
**Affected browser**
* [ x ] Chrome
* [ x ] Firefox
* [ x ] Safari
* [ x ] Edge

**Comment by w8tcha** [comment]
The results show a 404 error page. Of course a get good results on that page.

I don't understand why you continue spamming here. And trying to solve a problem that did not exist

**Comment by w8tcha** [comment]
As a solution I propose, that you make the changes to yaf ans make a pull request. And then we can compare the results

**Comment by daprose-dotcom** [comment]
Yes, that is a good idea. I think you have done a great job so far, The improvements that I suggest can only make it even better. But so far, it is already a great application..   the problems that I find have to do with running a large scale setup. I need something that can handle 100ths of categories, over 100,000 forums, millions of topics and replies..  

The way YafNet works now, it loading everything on the main board page. That would make it impossible to be considered for a large scale setup.  Please do not misunderstand me. I think YafNet is one of the best forum applications in the world. But mainly for small setups. It is great!!  

We will keep working together when I do the pull request and make all the necessary changes in future versions. For now, I'll wait for your promised version 3.2.0 ... the current version is not friendly enough to start.  Keep up the good work! You are doing great!!

**Comment by w8tcha** [comment]
> The way YafNet works now, it is loading everything on the main board page. That would make it impossible to be considered for a large scale setup. Please do not misunderstand me. I think YafNet is one of the best forum applications in the world. But mainly for small setups. It is great!!

Well we have large scale forums and they do work great. With 1million+ online users and  3 Million members.

**Comment by daprose-dotcom** [comment]
Yes, I've noticed a more elaborated organization in the user's base. It is great it can candle so many users. Congratulations. I was referring to the Categories, Forums and Topics, We may have to split the main BOARD page into 3 pages, the main page to handle only categories, the second only forums, and the third only topics. The code is already there we just have to split the board page into 3 pages.

The administration page for Categories and Forums also have to be split into 2 pages, one page to create/edit/update only the categories, and the second page to create the forums on a selected category only. Not showing the complete list because it would be too big, Too many forums displayed at one time. It is hard/difficult to work that way.,

**Comment by daprose-dotcom** [comment]
So sorry you got an error while fetching http://aspnetportal.xyz  I was working on that portal and usually, very often, I crash that page. hehehehe   that is the domain i run all my experiments, it is my working area for the moment. No guaranties that it will function correctly 24 hours a day/7days a week.  I am planning to create a full CMS that can import a WordPress site from eiither a MySQL script or a WordPress XML (Export) file. I have over 40 WordPress sites but I am not happy at all with so many crashes, updates, crashes again and so forth ... DO you speak German or English?

**Comment by daprose-dotcom** [comment]
> I don't understand why you continue to refuse that the Page Speed Results on the GTmetrix site have nothing to do with the Sql DB calls.

It is not only about SQL DB Calls, it may be only one call, (by the way, it can be reduced to no calls at all. 0 calls. But the other aspect is about Internet bandwidth. Sending 10 megabytes of data to every client when he/she is interested in only one category that measures only 25 characters, makes a big difference. 

More important when you are sending those 10 mega bytes to every user in the world.

Guess what,  perhaps you are not familiar with latin-america as I am, but there are 20 countries with internet speeds lower than 0.3 mbps and most people in those 20 countries pay for only 1 GB of data per month. So, they can not play with their bandwidth they way you and I play having unlimited bandwidth and a connection speed of 1000 MBPS, compared to only 0.3 MBPS most of them have.

Sorry for insisting on this issue and being a bit more technical but that is the true. So, the question is, why do we have to insistently send bulks of unnecessary data to 1000ths of users, repleting their bandwidth with data they are not interested nor they can afford?  

To you and me this may not be important, to the majority of people in all Latin-america, (over 400 million people), for them is extremely important.

**Comment by w8tcha** [comment]
I dont understand why you continue to make false statements. Yaf dont send 10 mb of data with each request.

I made some real performance tests. The issue with a board containing large amount of Categories and Forums, is that the dom tree becomes to large, and slow. This is again not an sql issue but a rendering issue.

To resolve this the only way is to limit the out put. For example the Amount of Sub forums is by default already limited to 5. And for example Topics and Posts are fetched paged. With and x amount of entries shown on the page.

To finally resolve this solution i will implement paging to the forum lists via infinite scrolling. The will reduce the load time and the page size.

**Comment by daprose-dotcom** [comment]
> I dont understand why you continue to make false statements. Yaf dont send 10 mb of data with each request.
Not your setup but mine. That depends on each setup. In my case, with over 28 categories and 1700 forums and over 30,000 topics, i think we bulk send more than 10 MB on the main page alone. So, am telling a false statement? or you simple do not think but only in your own setup?  The world is not only about you, and your problems. People have their own, believe me. 

I thin you are always a little bit sentimental and take a defensive position without thinking other people may have other problems. I never attempt to insult you but I usually receive uncomfortable comments from your part when at this end I have real and serious problems I need to solve.  So, are you going to stop taking a defensive position all the time and start acting as a problem solver or what?  

QUESTION: The problems I convey to you sound unreasonable or out of this world?

By the way, ... I do not take drugs, not even smoke any marijuana.

**Comment by w8tcha** [comment]
As i wrote above i working on a solution. I created a test setup with 1000 categories each containing 1 million forums, 1000 sub forums.

My only problem is that why would you need a forum with so many forums and categories, i never seen a forum like this. But if that is what is needed then i build the solution.

**Comment by daprose-dotcom** [comment]
If you go to http://daprose.com (please go there) and click on the Forums link, you will notice it will take you to http://MyBBS.org instead, and not to your application YafNET that I installed it at http://daprose.com/forums  

In fact, your application looks a lot better, it is really beautiful, but unfortunately, in my situation, it does not serve the purpose.  I can't use it.

http://daprose.com/forums  is a link only you and I know about it. It is hidden from the rest of all menus in my 50 or more websites.  I am still using MyBBS.ORG instead. in fact, the data I had posted in my YafNet setups, I have 3 setups, are only for experimental purposes, not used in the real world.  And the reason is that YafNet still do not serve my special needs. 

I have been working with you because I like YafNet, not because I use it in the real world. I have them on hidden folders, (NOT ADVERTISED IN ANY OF MY WEBSITES), so I can discuss these issues with you. That;s all.  Trying to let you understand the problems that I face, but you get sentimental and think that YafNet already solves all the problems in the world.  

Well, as you can see, it is not solving my problems, I can't use it in it's present form.

Cheers!!

**Comment by daprose-dotcom** [comment]
No question about it. I agree with you 100%, YafNet is for hobbiests  and businesses with small problems. And yes, I also agree with you and understand that it is your time and you can do whatever you can do with it, for the rest of your like. If you check your forum at YetAnotherFOrum.net, I tried to convey this problem more than 7 year ago. I did post the same request then and never got any answers.  So, if I waited 7 years, why would I be able to wait another 7 years. In the mean time, I have been using other applications. (unfortunately) 

So, the invitation remains, when ever you start taking this not as a hobby but as a real business adventure, let's talk about it. Without any more insults from your part. Please.

**Comment by w8tcha** [comment]
> No question about it. I agree with you 100%, YafNet is for hobbiests  and businesses with small problems. And yes, I also agree with you and understand that it is your time and you can do whatever you can do with it, for the rest of your life. If you check your forum at YetAnotherForum.net, I tried to convey this problem more than 7 year ago. I did post the same request then and I never got any answers.  So, if I waited 7 years, why wouldn't I be able to wait another 7 years??. In the mean time, I have been using other applications. (unfortunately) 
> 
> 
> 
> So, the invitation remains, when ever you start taking this not as a hobby but as a real business adventure, let's talk about it. Without any more insults from your part. Please.

You don't have to wait 7 years. As I wrote above I build the pageing solution, which will be included in the 2.1.3 release. Also the isactive flag is already included but not active
