### ISSUE TITLE
Speed and Performance

### ISSUE THREAD

**Issue by daprose-dotcom** [YAFNET/YAFNET#700]
For some people, speed and/or performance is not important. They probably prefer the nice look of their sites, and that's it, or simply, they may have never really tested the performance and landing page speed of their website, compared to other similar websites somewhere in the world.

Any website taking longer than 3 seconds to display a website page is considered a slow website. And people, really, don't like slow sites. Users usually tend to go to some other faster sites if they can, rather than dealing with slow monsters.

I have run a few speed and performance tests among 3 similar forum services.

1. http://mybbs.org (MyBBS)
2. http://aspnetportal.xyz (AspNetPortal)
3. http://daprose.com/forums  (YafNet)

The results speak for themselves. See the following screen shot ...

![GTMETRIX-ALL-SITES-TEST](https://user-images.githubusercontent.com/95335292/160093312-7f30c85e-3349-44a6-89b6-422358e9ed03.jpg)

We need to improve the speed and performance of YafNet. It already has a beautiful and pleasant design, but speed and performance may be important to others as well. Others perhaps may have some special needs, or there may be people that are interested in speed and performance as everybody should!!

Just a friendly request!!  Please speed up YafNet as much as it may be possible!
The landing page is the most important page in all websites in the world!

**Comment by w8tcha** [comment]
i commited some changes and added paging to the board index page.

At the moment the only perfomance report i use the Lighthouse from google. which is included in the browser and can be access via the Dev Tools (F12) or via the website [web.dev](https://web.dev)
