### ISSUE TITLE
Unable to find an entry point named 'SIa069da76968b7553' in DLL 'SQLite.Interop.dll'

### ISSUE THREAD

**Issue by laomms** [YAFNET/YAFNET#701]
sqlite version. has anyone else encountered a similar problem?  
I have try reinstall the System.Data.SQLite.Core.

**Comment by w8tcha** [comment]
That dll is not automatically copied to the bin folder. If you copy the file from the Folder YAF.Data\YAF.Data.Sqllite\bin\Debug\net4\x64 

to  

YetAnotherForum.NET\Bin

then it should work.
