### ISSUE TITLE
Sequence contains no elements 

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#714]
Latest version from repository and fresh installation using MSSQL throw the following exception when hitting Finish installation Wizard:

```
**Description:** An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code
**Exception Details:** System.InvalidOperationException: Sequence contains no elements
```
```
Line 247:        }
Line 248:            
Line 249:        if (this.Data.Item2.First().Total > this.Data.Item2.Count)
Line 250:        {
Line 251:            this.ShowMore.Visible = true;
```
`Source File: C:\Users\User\Downloads\yafsrc\YetAnotherForum.NET\Controls\CategoryList.ascx.cs    Line: 249`

**Comment by w8tcha** [comment]
Issue is fixed now. But you need to delete the database and re-install or Change the Flags value from 0 to 1 manually in the table yaf_Category for entry

**Comment by SinaBina** [comment]
Thanks
