### ISSUE TITLE
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces'

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#715]
Running YAF for the first time within VS2022 from latest source throw the following error:

```
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.

Exception Details: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
```
Changing DLL version in Web.config to 6.0.0.0 did the trick.

**Comment by w8tcha** [comment]
are you using the recommend.web.config?

**Comment by SinaBina** [comment]
> are you using the recommend.web.config?

Yes. everything untouched.

**Comment by w8tcha** [comment]
okay i see that file was not updated., Should be resolved now

**Comment by SinaBina** [comment]
> okay i see that file was not updated., Should be resolved now

Well done.Thanks
