### ISSUE TITLE
UI Scroll To Last Post

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#725]
You've done a lot of work on this project and seems a lot of things are in different spots. Good work!  One question I have currently is can you point me to the area I can find the auto scroll? Something that has always annoyed me with websites is when the UI moves without my action, haha.  If you don't know it off hand, no worries, I'll dig around.

**Comment by w8tcha** [comment]
https://github.com/YAFNET/YAFNET/blob/f3f5d99ddaa8dade97750cf51f713d522883da81/yafsrc/YetAnotherForum.NET/Pages/Posts.ascx.cs#L708

**Comment by Zero2Cool** [comment]
> https://github.com/YAFNET/YAFNET/blob/f3f5d99ddaa8dade97750cf51f713d522883da81/yafsrc/YetAnotherForum.NET/Pages/Posts.ascx.cs#L708

Thank you. 

A little heads up, if you are not already aware, using the [converted to file scoped namespace] means no one can run the project/solution with anything before Visual Studio 2022.

**Comment by w8tcha** [comment]
> > https://github.com/YAFNET/YAFNET/blob/f3f5d99ddaa8dade97750cf51f713d522883da81/yafsrc/YetAnotherForum.NET/Pages/Posts.ascx.cs#L708
> 
> 
> 
> Thank you. 
> 
> 
> 
> A little heads up, if you are not already aware, using the [converted to file scoped namespace] means no one can run the project/solution with anything before Visual Studio 2022. 

Yes correct, that's why the minimum version is set to vs 17 (2022)

**Comment by KevinDuganJr** [comment]
I was assuming commenting that line out would do the trick, but it still does the scroll to the bottom. What can I do to disable that feature please?

**Comment by w8tcha** [comment]
Simply remove the post anchor in the ..controls/DisplayPost.ascx

```
 <div>
                        <a id="post<%# this.DataSource.MessageID %>"
                           href="<%# this.Get<LinkBuilder>().GetLink(ForumPages.Posts,new { m = this.DataSource.MessageID, name = this.PageBoardContext.PageTopic.TopicName }) %>">
                            #<%# this.CurrentPage * this.PageBoardContext.BoardSettings.PostsPerPage + this.PostCount + 1%>
                        </a>
                    </div>
```

**Comment by KevinDuganJr** [comment]
I commented out the C# code as I think the anchor is used elsewhere. I could be wrong, but thank you, problem solved! 😀
