### ISSUE TITLE
Moving a topic creates two entries.

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#729]
In the latest source and in an upgrade scenario from 1.9.6, moving a topic to another forum creates two entries marked with "Moved" in the original forum.

Regards

**Comment by w8tcha** [comment]
I cannot reproduce the issue. Can you describe the steps to reproduce the issue?

**Comment by SinaBina** [comment]
In a new installation moving a topic works file but when you upgdare from and older version it happens therefore simply try to move a topic.If you still can't reproduce I will make a video.

**Comment by w8tcha** [comment]
I tried to do it with an upgrade scenario. But i still can't reproduce it. Feel free to make a video,

**Comment by SinaBina** [comment]
[Bug.zip](https://github.com/YAFNET/YAFNET/files/8692596/Bug.zip)

**Comment by w8tcha** [comment]
Can you check the yaf_Topic table if there are actually to new topics created with that name, that have the TopicMovedID set?

**Comment by w8tcha** [comment]
I was finally able to reproduce the issue, fixed.
