### ISSUE TITLE
Avatars and Attachments Not Displaying

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAFNET#737]
After upgrading from 2.31 to 3.1.4, avatars and attachments are not being displayed. 

**To Reproduce**
1. Go to 'http://kevinduganjr-002-site1.etempurl.com/
2. Click on a topic
3. Scroll down to to see avatar and attachments missing

**Expected behavior**
The expected behavior is avatars display and attachments display.

**Screenshots**
Avatars
![image](https://user-images.githubusercontent.com/5612416/168075550-ce239410-f63b-4935-8a15-2c077b3ae9be.png)
![image](https://user-images.githubusercontent.com/5612416/168075633-8160f882-f9ab-410f-b007-567be3df60aa.png)

Attachments show like this for a second.
![image](https://user-images.githubusercontent.com/5612416/168075443-3b0a9965-1559-434a-bd71-0bfbdb8d01a6.png)
And then that little rectangle disappears.
![image](https://user-images.githubusercontent.com/5612416/168075502-e50ea4f5-89b7-4816-9b76-c75fe21fc7d3.png)

**System (please complete the following information):**
 - YAF Version: 3.1.4
 - .NET Version:  4.8 or later
 - SQL Server SQL Server 2017
 
This might be related, not sure, but previous editor we could copy/paste an image and it would be uploaded as an attachment and inserted into the message. After upgrading, that is something I am unable to do.

**Comment by Zero2Cool** [comment]
> If i open the avatar url directly it leads directly to the board main page. Which indicates its an url rewriting issue or the resource handler is missing in the web.config.

I'll check that. I used the Url rewriter from the Sample Application in hopes of a clean upgrade.

**Comment by w8tcha** [comment]
i updated the source of the sample application

**Comment by Zero2Cool** [comment]
> i updated the source of the sample application

Looks like the avatars are not displaying an error, but now they are displaying letters instead of the actual avatar. Attachments are still not displaying -- still looking into that.

**Comment by w8tcha** [comment]
The text avatars are the default avatars. If the user has no avatar or the avatar can't be loaded. Check the yaf_user table for the avaterimage column if an avatar exist.

**Comment by Zero2Cool** [comment]
> The text avatars are the default avatars. If the user has no avatar or the avatar can't be loaded. Check the yaf_user table for the avaterimage column if an avatar exist.

You fixed mine on the YAF boards before. Do you recall what you did? Because I know my account has an avatar and it's not being displayed.

I have this under Avatar column for my account.
![image](https://user-images.githubusercontent.com/5612416/168089921-d2ccc0d7-7e8b-4984-a3ff-f6c6a8e48dcc.png)

**Comment by Zero2Cool** [comment]
> Regarding the Attachments, are there any entries in the event log?

I'll have to check, but right now when I check EventLog this is happening.
![image](https://user-images.githubusercontent.com/5612416/168090541-ff426780-a153-4f7f-9309-dcacbf93ff0b.png)

**Comment by Zero2Cool** [comment]
I was using a remote avatar and looks like that is not available anymore. This is version 2.31 screenshot.
![image](https://user-images.githubusercontent.com/5612416/168094927-a390cfc2-3399-4f37-9570-6d5d4c5d40be.png)

And version 3.1.4
![image](https://user-images.githubusercontent.com/5612416/168094972-caa5b8ee-8ee7-4192-b6ac-9988d19b9e26.png)

**Comment by w8tcha** [comment]
its possible that your errors are not logged in the event log? Have you disabled under Host > Logs > **Allow log Application Info**?

**Comment by Zero2Cool** [comment]
> its possible that your errors are not logged in the event log? Have you disabled under Host > Logs > **Allow log Application Info**?

It's logging some errors. I will check though. I also get an error when trying to do a Search. I think it's related to my URL Rewriter problem though.
![image](https://user-images.githubusercontent.com/5612416/168100165-e54b5496-1672-406b-a505-01b2b0a93f86.png)

I'll enable some of these.
![image](https://user-images.githubusercontent.com/5612416/168100266-e3982b9c-d96c-41dc-bc1c-cb09e5c61bca.png)

**Comment by Zero2Cool** [comment]
Enabled those log entries and I think this should help.
![image](https://user-images.githubusercontent.com/5612416/168100879-b5ef7607-7b87-4e2e-8571-bb949256c0ce.png)

**Comment by w8tcha** [comment]
> It's logging some errors. I will check though. I also get an error when trying to do a Search. I think it's related to my URL Rewriter problem though.

Thats an issue of the sample application. Again not an issue of yaf.

If you remove the code from the RouteConfig.cs...
```cs
routes.MapRoute(
                name: "Default",
                url: "{controller}/{action}/{id}",
                defaults: new { action = "Index", id = UrlParameter.Optional });
```

Then it should work. Remember this is a sample application.

**Comment by w8tcha** [comment]
> I was using a remote avatar and looks like that is not available anymore.

Correct. Unfortinatiolyx remote urls are a security issue, also it leeds to  endless event log entries if the urls are dead. The only way is to disable this.

**Comment by Zero2Cool** [comment]
> > I was using a remote avatar and looks like that is not available anymore.
> 
> Correct. Unfortinatiolyx remote urls are a security issue, also it leeds to endless event log entries if the urls are dead. The only way is to disable this.

Agreed on security issue. I just didn't think of it until I poked around more. :) Makes sense. Clean easy fix.

**Comment by Zero2Cool** [comment]
> > I was using a remote avatar and looks like that is not available anymore.
> 
> Correct. Unfortinatiolyx remote urls are a security issue, also it leeds to endless event log entries if the urls are dead. The only way is to disable this.

Agreed on security issue. I just didn't think of it until I poked around more. :) Makes sense. Clean easy fix.

**Comment by w8tcha** [comment]
Does the folder uploads exist in the folder Packershome?

**Comment by Zero2Cool** [comment]
> Yes you're right, Issue is fixed now

I've been trying to test it, but there were some updates and now I got could not load assemblies so gotta update sample application and YAF. :)

**Comment by Zero2Cool** [comment]
Okay, this is a little different. When you click on the attached image, it displays, but without clicking, no display.

Example URL: http://packerpeople.com/forum/Posts/t32100-4th-Round--132nd-Overall--WR-Romeo-Doubs

![image](https://user-images.githubusercontent.com/5612416/168152027-abd89157-040a-4115-9623-d8bf2fe25c69.png)

Clicking on the "Click here" dialog... first click it opens and closes, second click it stays open.
![image](https://user-images.githubusercontent.com/5612416/168152157-74aafeab-9e73-477d-b7b7-584b70630ca9.png)

**Comment by w8tcha** [comment]
I didnt update the preview images only the links itself. Not the image attachments should display correctly
