### ISSUE TITLE
Upload and attachement issues

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#738]
In the latest source and in an upgrade scenario from 1.9.6,
1-User's attachments is not shown in his profile and it empty.
2-Attaching a new file (Uploading) to a topic through editor fails. Nothing happen after showing the "Please wait until all Upload(s) are completed and the Dialog closes itself! " message.
![Screenshot 2022-05-14 at 15-14-23 Attachments · My Board](https://user-images.githubusercontent.com/5496007/168422426-154dd551-2428-4898-9048-ec05c8dc2ce7.png)

**Comment by w8tcha** [comment]
1. Looks like the migrating proccess for such old db is different. the migrating of attachments on a upgrade is fixed now
2. After the dialog is closed the attachment is added to the editor message. If not then there is likely an Javascript error. Can you check the browser console after the upload for js errors?

**Comment by SinaBina** [comment]
1.The migration doesn't seem to work. Still no attachment is shown in user panel. Should I upgrade the database again?
2.The only errors i get:

```
GEThttp://localhost:50165/content/jquery.fileupload.comb.css
[HTTP/1.1 404 Not Found 2ms]

When rendering the <html> element, the used values of CSS properties “writing-mode”, “direction”, and “text-orientation” on the <html> element are taken from the computed values of the <body> element, not from the <html> element’s own values. Consider setting these properties on the :root CSS pseudo-class. For more information see “The Principal Writing Mode” in https://www.w3.org/TR/css-writing-modes-3/#principal-flow [PostMessage](http://localhost:50165/PostMessage?t=5023&f=57)

When rendering the <html> element, the used values of CSS properties “writing-mode”, “direction”, and “text-orientation” on the <html> element are taken from the computed values of the <body> element, not from the <html> element’s own values. Consider setting these properties on the :root CSS pseudo-class. For more information see “The Principal Writing Mode” in https://www.w3.org/TR/css-writing-modes-3/#principal-flow [ckeditor.js:108:423](http://localhost:50165/Scripts/ckeditor/ckeditor.js)
```

**Comment by w8tcha** [comment]
1. Yes sorry, but you have to upgrade the db from 1.96 to 3 again.

**Comment by SinaBina** [comment]
No need to say sorry.You are doing amazing job.Thank you.
I am happy I can help.

**Comment by SinaBina** [comment]
I tested the older

> 1. Yes sorry, but you have to upgrade the db from 1.96 to 3 again.

No need to say sorry.You are doing amazing job.Thank you.
I am happy I can help.

**Comment by w8tcha** [comment]
i forgot to commit all updated files. uploads should work now

**Comment by SinaBina** [comment]
Sehr gut, Danke.
