### ISSUE TITLE
Unhandled exception in user suspension

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#739]
In the latest source and in an upgrade scenario from 1.9.6, An unhandled exception is thrown when admin tries to suspend users although the operation itself works fine.
It seems that the error is caused by server mis-configurations but the exception should be handled.

```
An attempt was made to access a socket in a way forbidden by its access permissions 74.125.140.108:587 
Exception Details: System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 74.125.140.108:587
Source File: C:\Users\User\Desktop\yafsrc\YAF.Core\Services\MailService.cs    Line: 84
```

[An attempt was made to access a socket in a way forbidden by its access permissions 74.125.140.108 587.htm.zip](https://github.com/YAFNET/YAFNET/files/8697766/An.attempt.was.made.to.access.a.socket.in.a.way.forbidden.by.its.access.permissions.74.125.140.108.587.htm.zip)

**Comment by w8tcha** [comment]
Seems like an issue with the mail server or wrong mail settings, and no yaf issue. 

If I try to Google the error the following stackoverflow.com solutions I found...

https://stackoverflow.com/questions/20779336/an-attempt-was-made-to-access-a-socket-in-a-way-forbidden-by-its-access-permiss#20891269

**Comment by SinaBina** [comment]
I see w8tcha.
The problem is from my side but should the exception been handled or there is no need?

**Comment by w8tcha** [comment]
Yes correct, i add error handling to all mail sending

**Comment by SinaBina** [comment]
Thanks
