### ISSUE TITLE
"Users browsing this topic" shows wrong information

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#741]
In the latest source and in an upgrade scenario from 1.9.6 and in the "Users browsing this topic" section instead of username , User-agent is shown.This works fine in a new installation.

![Screenshot 20](https://user-images.githubusercontent.com/5496007/168577554-d997e8f7-f8c3-4b21-88e4-4c24e0f21d12.png)

**Comment by w8tcha** [comment]
The icon would indicate that the user is a search engine crawler. Can you check the table yaf_Active what shows the Column for Flags?

**Comment by SinaBina** [comment]
> The icon would indicate that the user is a search engine crawler. Can you check the table yaf_Active what shows the Column for Flags?

![Untitled](https://user-images.githubusercontent.com/5496007/168977068-5d7767d1-8a8b-448c-8e92-838f2e0cd322.png)

**Comment by w8tcha** [comment]
That screenshot doesnt show that the user is browsing a topic. But in that case it would not show the crawler icon. If you delete all entries is then the correct user name displayed?

**Comment by SinaBina** [comment]
> That screenshot doesn't show that the user is browsing a topic. But in that case it would not show the crawler icon. If you delete all entries is then the correct user name displayed?

Yes it works.Maybe deleting all active users during each upgrade will be a good idea.
