### ISSUE TITLE
Issues when creating new forum

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#744]
From the latest source and in a new installation scenario couple of issues have been identified (Attached Video):)
1-Creating a new forum under a new category throw an exception.
2-Newly created topics in the newly created forum do not have "Manage Topic" Button.

[Issues.zip](https://github.com/YAFNET/YAFNET/files/8761956/Issues.zip)

**Comment by w8tcha** [comment]
1.  Thats not an issue, vs studio now normally stops in a try catch handler. You can ignore that message And click on continue
2.   Check the access masks for the newly created Foru, as i can see in the video you set the Administrators Group to Member Access.

**Comment by SinaBina** [comment]
> 1. Thats not an issue, vs studio now normally stops in a try catch handler. You can ignore that message And click on continue
> 
>     2. Check the access masks for the newly created Foru, as i can see in the video you set the Administrators Group to Member Access.

I see.Thanks

**Comment by SinaBina** [comment]
> I changed the try catch handler to an if clause to avoid the error

Well done.
