### ISSUE TITLE
"Object reference not set to an instance of an object" in culture

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#752]
In an upgrade scenario from 1.9.6 when the following conditions are met, the "Object reference not set to an instance of an object" is thrown and operation is terminated.

1-Forum is upgraded from 1.9.6.
2-Users are allowed to select forum language.
3-User's selected language is different form forum's default culture.
4-Under user menu, click "Edit Settings".

[Stack Traces.zip](https://github.com/YAFNET/YAFNET/files/8855084/Stack.Traces.zip)

**Comment by w8tcha** [comment]
Issue should be resolved by upgrading to db version 87. I committed the changes to upgrade to latest version

**Comment by SinaBina** [comment]
It is fixed.
