### ISSUE TITLE
Send User Welcome Notification is not working

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#763]
In the latest source selecting "Send as private message" under Host Setting > Host Setup > Login/Registration Settings  > Send User Welcome Notification does not work and newly registered users do not receive such PM.

**Comment by w8tcha** [comment]
The welcome mail/pm is send after the new account is approved (when the user clicks on the approve link in the email).

The pm is only send if Private Messages is enabled in the host settings (under Host > Host Settings > Features > Private Messages > Allow Private Messages)

**Comment by SinaBina** [comment]
All right but what if the user is approved manually through admin index page?
BTW I don't seem to be able to find an option where users are not required to confirm their emails? is it removed?

**Comment by w8tcha** [comment]
> All right but what if the user is approved manually through admin index page?

Thats fixed now. If you manually approve the user then the welcome pm/email is also send

> BTW I don't seem to be able to find an option where users are not required to confirm their emails? is it removed?

With identity thats no longer possible
