### ISSUE TITLE
Auto scroll to top

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#764]
In the latest source clicking on any "Show Moderators" Button will scroll the forum to the top.

![Screenshot 2022-09-07 at 14-32-04 Test](https://user-images.githubusercontent.com/5496007/188851086-7c11bba8-5cf0-4f80-8c52-7f74ff395e97.png)

**Comment by SinaBina** [comment]
Scrolling is fixed but it seems that forum is loaded on demand which means it is not loaded until you scroll to the bottom.So if you don't scroll to the bottom the "Show Moderators" works, but if you scroll and the rest of forum is loaded then it doesn't work and clicking "Show Moderators" does not show the box.

**Comment by w8tcha** [comment]
> Scrolling is fixed but it seems that forum is loaded on demand which means it is not loaded until you scroll to the bottom.So if you don't scroll to the bottom the "Show Moderators" works, but if you scroll and the rest of forum is loaded then it doesn't work and clicking "Show Moderators" does not show the box.

Issue should be fixed now
