### ISSUE TITLE
Avatar caching issue

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#768]
In the latest source uploading/deleting an Avatar requires a page refresh/reload to see the result. For example you need to hit "Clear Avatar" button two times to get the result.

**Comment by SinaBina** [comment]
The issue still exist if the following condition is met:
1-User upload an image larger than allowed size
2-Pop-up message is shown saying "Image size can't be larger than *x* pixels. The size of your image was 1600x860 pixels. The image was resized to fit."
3-pop-up message is clicked away

It should be refreshed.

**Comment by w8tcha** [comment]
Fixed
