### ISSUE TITLE
Warning/Advisory messages

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#770]
YAF lacks warning/advisory messages during some of its operations for example:

- Pruning Topics/PMs (Admin page) as they are considered a dangerous operations and need to be reconsidered by a pop-up etc. messages
- Deleting all PMs (through "delete all" button) in "My Inbox" also need user confirmation.

I think it is a better practice to add such messages.

**Comment by w8tcha** [comment]
The inbox actually have the confirm Dialogs. But for some reason it didn't work. Issue should be fixed. 

For the admin function i dont really understand why an admin needs confirm dialogs?! For regular users i can understand but for admins, i dont think its necessary

**Comment by SinaBina** [comment]
Yes but admin is Human too and all human are prune to mistake 😄 .

**Comment by w8tcha** [comment]
Turns out all the referenced admin pages have confirm dialogs. And now they work again.
