### ISSUE TITLE
Pruning Topics/PM Maintenance issues

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#771]
In the latest source and in an upgrade scenario following tasks throw exceptions:

1. **Admin > Maintenance > Prune Topics** (without changing parameters) throws:

![Screenshot 2022-09-12 at 12-34-33 Prune Topics · My Test Forum](https://user-images.githubusercontent.com/5496007/189603296-5b848650-cc0a-441b-a663-76527ced0db5.png)

![devenv_gU9EgCGxJX](https://user-images.githubusercontent.com/5496007/189602862-0c149afa-a73e-470d-b350-2e1701fd5c7f.png)

2. **Admin > Maintenance > PM Maintenance** operation is not successful If you try to delete PMs (read or unread) older than "0" days which means today's PMs. The rest works fine.

**Comment by w8tcha** [comment]
1. Logging issue is fixed.
2. Value should only be set to minimum 1, also fixed!
