### ISSUE TITLE
Task Manager Issue

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#775]
In the latest source in both new/upgrade scenario in **Admin > Maintenance > Task Manager > "Stop Task"**
does not stop the task. It looks like Tasks are just restarted and not stopped.

![Screenshot 2022-09-20 at 15-24-54 My Test Forum](https://user-images.githubusercontent.com/5496007/191241243-16253aba-e898-4545-8acd-5b23ff8bf8ec.png)

Suggestion for improvements:
1-Clicking the "Stop Task" button should change the caption to "Start Task" and Vice versa.
2-An advisory pop-up message to let the user know the result.

**Comment by w8tcha** [comment]
The button is completely useless. I removed the button. It makes no sense to stop the tasks

**Comment by SinaBina** [comment]
Now get:
`CS1061: 'ASP.pages_admin_taskmanager_ascx' does not contain a definition for 'TaskRepeaterItemCommand' and no extension method 'TaskRepeaterItemCommand' accepting a first argument of type 'ASP.pages_admin_taskmanager_ascx' could be found (are you missing a using directive or an assembly reference?)`

[Uploading Compilation Error.zip…]()

**Comment by w8tcha** [comment]
fixed

**Comment by SinaBina** [comment]
I don't think it is a good idea to remove the button.I think it was there for a reason.It gives admins a second chance.Imagine an admin mistakenly send massive number of emails to users. There should be a second chance to stop the task.
Just my two cents.

**Comment by w8tcha** [comment]
There is no task for email sending. What you describe is not possbible. All emails are send directly

**Comment by SinaBina** [comment]
> There is no task for email sending. What you describe is not possbible. All emails are send directly

As I remember there is such task in older versions and is controlling the flow of email sending to avoid host blockage due to large number of emails.It was very helpful specially in shared hosting.

![Screenshot 2022-10-08 at 18-04-10  Administration - Task Manger](https://user-images.githubusercontent.com/5496007/194713481-a56ea6b5-8ec9-4ade-8871-8e3b39aa6555.png)

**Comment by w8tcha** [comment]
Yes correct, because old .net versions needed such workarounds to handle threaded tasks. Newer .net version have better solutions build in. So of course that's why the MailSend Task is no longer needed. Also it is executed in seconds so stoping it would be impossible.
