### ISSUE TITLE
CKEditor is not visible

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#776]
In both upgrade and new installation newly registered users do not see the post editor (CKEditor). No error is logged within YAF but the following errors are logged in the browser's inspector panel:

![Screenshot 2022-09-20 at 15-52-42 Post New Topic · My Test Forum](https://user-images.githubusercontent.com/5496007/191246286-7e5e2083-ac4b-461a-b942-adcd9e2ecd9a.png)

`Uncaught TypeError: c is null
    setLang http://localhost:50165/Scripts/ckeditor/ckeditor.js:268
    <anonymous> http://localhost:50165/Scripts/ckeditor/plugins/albumsbrowser/lang/en.js?t=M4I8:1
ckeditor.js:268:294
Uncaught TypeError: editor.lang.albumsbrowser is undefined
    init http://localhost:50165/Scripts/ckeditor/plugins/albumsbrowser/plugin.js?t=M4I8:102
    x http://localhost:50165/Scripts/ckeditor/ckeditor.js:283
    x http://localhost:50165/Scripts/ckeditor/ckeditor.js:261
    y http://localhost:50165/Scripts/ckeditor/ckeditor.js:261
    A http://localhost:50165/Scripts/ckeditor/ckeditor.js:261
    onload http://localhost:50165/Scripts/ckeditor/ckeditor.js:262
    setTimeout handler*load/F/f.$.onload http://localhost:50165/Scripts/ckeditor/ckeditor.js:262
    F http://localhost:50165/Scripts/ckeditor/ckeditor.js:262
    load http://localhost:50165/Scripts/ckeditor/ckeditor.js:263
    x http://localhost:50165/Scripts/ckeditor/ckeditor.js:282
    k http://localhost:50165/Scripts/ckeditor/ckeditor.js:268
    load http://localhost:50165/Scripts/ckeditor/ckeditor.js:266
    x http://localhost:50165/Scripts/ckeditor/ckeditor.js:261
    y http://localhost:50165/Scripts/ckeditor/ckeditor.js:261
    A http://localhost:50165/Scripts/ckeditor/ckeditor.js:261
    onload http://localhost:50165/Scripts/ckeditor/ckeditor.js:262
    setTimeout handler*load/F/f.$.onload http://localhost:50165/Scripts/ckeditor/ckeditor.js:262
    F http://localhost:50165/Scripts/ckeditor/ckeditor.js:262
    load http://localhost:50165/Scripts/ckeditor/ckeditor.js:263
    load http://localhost:50165/Scripts/ckeditor/ckeditor.js:265
    k http://localhost:50165/Scripts/ckeditor/ckeditor.js:267
    load http://localhost:50165/Scripts/ckeditor/ckeditor.js:268
    x http://localhost:50165/Scripts/ckeditor/ckeditor.js:281
    g http://localhost:50165/Scripts/ckeditor/ckeditor.js:280
    getStylesSet http://localhost:50165/Scripts/ckeditor/ckeditor.js:530
    load http://localhost:50165/Scripts/ckeditor/ckeditor.js:266
    x http://localhost:50165/Scripts/ckeditor/ckeditor.js:261
    y http://localhost:50165/Scripts/ckeditor/ckeditor.js:261
    A http://localhost:50165/Scripts/ckeditor/ckeditor.js:261
    onload http://localhost:50165/Scripts/ckeditor/ckeditor.js:262
    setTimeout handler*load/F/f.$.onload http://localhost:50165/Scripts/ckeditor/ckeditor.js:262
    F http://localhost:50165/Scripts/ckeditor/ckeditor.js:262
    load http://localhost:50165/Scripts/ckeditor/ckeditor.js:263
    load http://localhost:50165/Scripts/ckeditor/ckeditor.js:265
    getStylesSet http://localhost:50165/Scripts/ckeditor/ckeditor.js:530
    g http://localhost:50165/Scripts/ckeditor/ckeditor.js:280
    m http://localhost:50165/Scripts/ckeditor/ckeditor.js:280
    d http://localhost:50165/Scripts/ckeditor/ckeditor.js:260
    x http://localhost:50165/Scripts/ckeditor/ckeditor.js:261
    y http://localhost:50165/Scripts/ckeditor/ckeditor.js:261
    A http://localhost:50165/Scripts/ckeditor/ckeditor.js:261
    onload http://localhost:50165/Scripts/ckeditor/ckeditor.js:262
    setTimeout handler*load/F/f.$.onload http://localhost:50165/Scripts/ckeditor/ckeditor.js:262
    F http://localhost:50165/Scripts/ckeditor/ckeditor.js:262
    load http://localhost:50165/Scripts/ckeditor/ckeditor.js:263
    load http://localhost:50165/Scripts/ckeditor/ckeditor.js:260
    m http://localhost:50165/Scripts/ckeditor/ckeditor.js:279
    q http://localhost:50165/Scripts/ckeditor/ckeditor.js:279
    b http://localhost:50165/Scripts/ckeditor/ckeditor.js:567
    loadPart http://localhost:50165/Scripts/ckeditor/ckeditor.js:569
    q http://localhost:50165/Scripts/ckeditor/ckeditor.js:279
    h http://localhost:50165/Scripts/ckeditor/ckeditor.js:278
    m http://localhost:50165/Scripts/ckeditor/ckeditor.js:10
    fire http://localhost:50165/Scripts/ckeditor/ckeditor.js:12
    fire http://localhost:50165/Scripts/ckeditor/ckeditor.js:13
    fireOnce http://localhost:50165/Scripts/ckeditor/ckeditor.js:12
    fireOnce http://localhost:50165/Scripts/ckeditor/ckeditor.js:13
    k http://localhost:50165/Scripts/ckeditor/ckeditor.js:276
    k http://localhost:50165/Scripts/ckeditor/ckeditor.js:276
    callback http://localhost:50165/Scripts/ckeditor/ckeditor.js:263
    x http://localhost:50165/Scripts/ckeditor/ckeditor.js:261
plugin.js:102:21
`

**Comment by w8tcha** [comment]
Found the problem

**Comment by SinaBina** [comment]
Tested in the following conditions.
-Any browsers (Edge,Firefox,Opera)
-New installation or Upgrade scenario
-Different User and Board language
-Same User and Board Language
-"Allow User Change Language?" Enabled or Disabled
