### ISSUE TITLE
Banned Name

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#780]
How does "Banned Name" section works?
Admin > Spam Protection > Banned Name
I add for example "David, Mike, etc." or use regex like "^https?://" but new users are still able to register with such names.

Any idea?

**Comment by w8tcha** [comment]
Check the wiki page on the topic spam bots

https://github.com/YAFNET/YAFNET/wiki/Protect-YAF.NET-against-Spam-BOTS

**Comment by SinaBina** [comment]
I am afraid it does not answer my question.I mean I want to disallow users from using specific names e.g. David.Does adding the name to "Banned Name" section should disallow users from choosing one? if yes then it doesn't work.

![Screenshot 2022-09-21 at 16-03-07 Banned Names · My Test Forum](https://user-images.githubusercontent.com/5496007/191493678-678789b0-d0a8-40d4-9e5f-b99feca065f8.png)

**Comment by w8tcha** [comment]
Yes it does, if you want to block certain names then you need to set the bot check to reject user. Via Host > Host Settings >[Bot Spam Settings (User Checking) > Handling of Bots during Registration > Block User

**Comment by SinaBina** [comment]
Thanks
