### ISSUE TITLE
Reseting users password

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#785]
There was a very useful feature in older version of YAF where admins were able to Reset and Email users' password. I can not find it in the new version. Any help?

**Comment by w8tcha** [comment]
that feature was removed, but if the feature is usefull i can add it back in

**Comment by SinaBina** [comment]
Sure It is really appreciated.It is useful specially when users are not able to reset their passwords for reasons like mail server issues, forgetting email or username etc.

**Comment by w8tcha** [comment]
But you do understand that a reset button does the same function as the forgot password button on the login page?! It only sends an reset password email to the user.

**Comment by SinaBina** [comment]
Indeed. just empowering the admins.

**Comment by KevinDuganJr** [comment]
Is this feature difficult to reimplement?

**Comment by w8tcha** [comment]
No, it only takes a few minutes. 

But as a workaround you can also go to the forgot password page, enter the name or email Adress and send a user the Reset password mail. It's the same process.

**Comment by KevinDuganJr** [comment]
No,, unfortunately, that won't work the same. Often times I need to reset the password cuz their email is invalid. It's been a challenge to keep folks using email they keep active. 🤦

**Comment by w8tcha** [comment]
Sorry but the admin interface would do the same thing. The Request token from the email is needed to change the password. This is a security feature of asp.net identity.

**Comment by KevinDuganJr** [comment]
Ooh, I must not have updated since you changed the membership. I'm still on 2.31 and have this option.  So yeah, just forcing an email sent wouldn't be any better than them doing it themselves. Being able to change the user password was nice. Pretty sure you can still manually change the password with identity membership. I did it at my last job. 

![image](https://user-images.githubusercontent.com/5612416/199966594-39de04cf-e009-492a-979c-534682f1305a.png)

**Comment by w8tcha** [comment]
to understand you want to change the password manually, but how would you send the user the new password if you dont know the new email address?

**Comment by KevinDuganJr** [comment]
> to understand you want to change the password manually, but how would you send the user the new password if you dont know the new email address?

They'd find me on Facebook, Twitter or simply create another account. If they did the latter, I would just delete that account, update their email and then in the Fan Shout part say "User X, check your email for temp password".

**Comment by w8tcha** [comment]
That seems to be am easy way to hack in to somebodies account. Or how would you verify the authenticity of the user.

**Comment by KevinDuganJr** [comment]
> That seems to be am easy way to hack in to somebodies account. Or how would you verify the authenticity of the user.

It's a very small community and I know how to check IP's.

**Comment by w8tcha** [comment]
I checked the msdn documentation but there seem to be no option to reset the password without token.

**Comment by w8tcha** [comment]
> > That seems to be am easy way to hack in to somebodies account. Or how would you verify the authenticity of the user.
> 
> 
> 
> It's a very small community and I know how to check IP's. 

Okay I understand but then simply change the email address of the account and the forget password function can be used

**Comment by KevinDuganJr** [comment]
> Okay I understand but then simply change the email address of the account and the forget password function can be used

Yep. I've kind of talked myself out of this being critical, haha. I'll have to find my old work project and see WTF I did because I know I had to do it for a lot of Customers. It was annoying.

**Comment by w8tcha** [comment]
Well I think there is a good reason to increase security and don't allow admins to randomly change user passwords.

I remember now that why I removed the change password tab in yaf 3. Because the forgot password page serves the same purpose.

Technically it would be possible to generate the token without sending the email and then directly changing the password.

But from my point of view directly changing the email address seems to be the better solution, and also would require less steps.

**Comment by KevinDuganJr** [comment]
> Well I think there is a good reason to increase security and don't allow admins to randomly change user passwords.
> 
> I remember now that why I removed the change password tab in yaf 3. Because the forgot password page serves the same purpose.
> 
> Technically it would be possible to generate the token without sending the email and then directly changing the password.
> 
> But from my point of view directly changing the email address seems to be the better solution, and also would require less steps.

Yep, I am with you.  One issue I encountered was people not changing the temporary password. There are ways around that too though.  Bottom line, I think what you did is the right thing and I'm good with it. I panicked when I saw it wasn't there but talking through this, bah, they all know how to find me and they'll just need to give me a valid email. 

BTW, I was curious and finally found how I was manually setting passwords.
![image](https://user-images.githubusercontent.com/5612416/199977816-2c59dab0-9541-4143-8b37-dd75fd1e8df9.png)

**Comment by KevinDuganJr** [comment]
> that feature was removed, but if the feature is usefull i can add it back in

It was super useful. 

I just found out we can't update users email addresses either.  My board has folks over 15 years and it's an issue I'm seeing more and more. The issue of "no access to that email anymore, what do I do?" and I'm basically unable to help them.

**Comment by w8tcha** [comment]
done
