### ISSUE TITLE
"Delete All More Than Days Old" not working

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#787]
Latest Source
Admin > Admin Index > "Delete All More Than Days Old" button is not working.No more error,exception etc.

**Comment by w8tcha** [comment]
Can you describe the steps to reproduce the problem? not working is not an error description. 

Deleted users are logged in the event log, if logging of deleted users is enabled in the event log

**Comment by SinaBina** [comment]
To reproduce the issue: 
1-Admin > Users & Roles > Users > Tools > Lock Inactive Accounts (5 years)
2-Admin > Admin Index >  Unverified Users > "Delete All More Than Days Old" (1 day)  or "Approve All"
Result: No user is removed or approved.the page just refreshes .No more error,exception etc.

Notes: both buttons works fine if users are registered through registration form and has not verified their emails.You can either approve them all or delete those who has not verified their email older than n days. It just doesn't work under the above circumstance.

**Comment by w8tcha** [comment]
Ok i understand issue is fixed now. those locked or deleted users should no longer be shown as Unverified Users after you click on lock inactive users.
