### ISSUE TITLE
Autoscroll depth 

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#792]
Can the depth of the autoscroll be adjusted? It scrolls way too far down. It should probably stop at the top of the latest post. Instead it scrolls to the bottom of it and then you have to scroll up which kinda defeats the purpose of the autoscroll.

**Comment by w8tcha** [comment]
At least on my local test forum and on the support forum i cannot reproduce this. It scroll to the anchor on top of the post

**Comment by KevinDuganJr** [comment]
Hmm. I'm using the standalone YAF with Sample Application raw code. Using last commit for both and haven't edited it.

Galaxy S10. Chrome browser if that matters. 


This is where it's scrolling for me. Does the Javascript code reference the site css elements as a starting point? 
![Screenshot_20221030-065237_Chrome](https://user-images.githubusercontent.com/5612416/198877007-2b457fe0-b772-4829-97b6-683ab768d8ed.png)

**Comment by KevinDuganJr** [comment]
Hmm. I'm using the standalone YAF with Sample Application raw code. Using last commit for both and haven't edited it.

Galaxy S10. Chrome browser if that matters.

This is where it's scrolling for me. Does the Javascript code reference the site css elements as a starting point?

![Screenshot_20221030-065617_Chrome](https://user-images.githubusercontent.com/5612416/198877166-dae0eb43-1d4a-4f70-a005-1ac2bd402c8b.png)

**Comment by w8tcha** [comment]
If i look at the sceenshot then it appears that the scroll is exactly where message anchor is. but there is the menu from your site which overlaps it. but this is not part of yaf.

**Comment by KevinDuganJr** [comment]
> If i look at the sceenshot then it appears that the scroll is exactly where message anchor is. but there is the menu from your site which overlaps it. but this is not part of yaf.

Oops. You're right. It's more of a SampleApplication issue, my bad. The autoscroll probably works perfect without that extra menu that's added in SampleApplication. Can we hadd padding to the anchor point to account for the height of the navbar?

**Comment by w8tcha** [comment]
But the fixed header is not part of the sample application. This cant be fixed from yaf because its only relevant for your site.

Can you try the following solutions by adding this to your site css..

```css
html {
  scroll-padding-top: 70px; /* height of sticky header */
}
```

**Comment by KevinDuganJr** [comment]
> But the fixed header is not part of the sample application. This cant be fixed from yaf because its only relevant for your site.
> 
> Can you try the following solutions by adding this to your site css..
> 
> ```css
> html {
>   scroll-padding-top: 70px; /* height of sticky header */
> }
> ```

From the SampleApplication repository, this is where the navbar is set to fixed. So, it'll be any site that uses the SampleApplication. 

Thanks you, that does help and I can toy with that to how I need!!! 😁
![image](https://user-images.githubusercontent.com/5612416/198881487-f757b9bd-46e9-47fd-ae4a-112758ab0a70.png)

**Comment by w8tcha** [comment]
Yes you're right. I added the css to the sample application
