### ISSUE TITLE
CKEditor context menu

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#793]
Anyway to use a different editor or disable the context menu? This really makes crafting a message impossible when you need to select certain words and such. 

![Screenshot_20221101-075856_Chrome](https://user-images.githubusercontent.com/5612416/199238311-a088c28b-eb89-4256-ae30-69057355a91b.png)

**Comment by w8tcha** [comment]
Would it be okay if the host setting enable/disable the custom context menu also applies to the editor?

**Comment by w8tcha** [comment]
done

**Comment by KevinDuganJr** [comment]
Pulled the trigger and updated today. Thank you so much for option to disable that context menu!!
