### ISSUE TITLE
Mail Clipped

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#801]
I'm still going through the settings and configurations, but I'm not finding where we can alter the email template. Can it be altered? I'm now getting this (see below) on emails received from YAF. 

![image](https://user-images.githubusercontent.com/5612416/200672872-e15cd2ff-81b6-459f-b833-122b284a0e7a.png)

**Comment by w8tcha** [comment]
I re-openend the issue. I forgot to address the issue. A the moment the entire site css is loaded, which makes the html to big and it gets clipped by google. 

This needs to be fixed by creating a small css file for the email

**Comment by KevinDuganJr** [comment]
I noticed that. My fix was to remove the {css} so the file wouldn't be injected. I figured that was intentional for a reason I don't understand.

**Comment by w8tcha** [comment]
Well the css is needed to apply the bootstrap theme styling is applied to the mail. But of course not the entire theme css is needed.

**Comment by KevinDuganJr** [comment]
Understandable. Makes sense. 

I have creating new CSS on my to do list lol
