### ISSUE TITLE
Message looks different after submitted

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#803]
When writing a post, we see clean single line space, but when the post gets displayed, it has massive gaps between the line.  Is this a YAF thing or CKEditor thing? It seems to be adding a < p > instead of < br >.

Here's what I see when typing message.
![image](https://user-images.githubusercontent.com/5612416/200853735-973d7aff-0984-4e3a-bf66-44579c1af764.png)

Here's what that same exact message looks like once displayed.
![image](https://user-images.githubusercontent.com/5612416/200853790-d98b156b-8637-4c07-819f-d2921ad9b2be.png)

See those p tags? I don't think those should be there. They  aren't even wrapped around anything. The li tags are sufficient.
![image](https://user-images.githubusercontent.com/5612416/200856234-6b74c564-a756-436f-8ade-d20e29148a62.png)

Looks like this is kind of a known bug.
https://dev.ckeditor.com/ticket/6849

Update: It seems the p tags are added whenever you hit Enter.  When you hold shift and hit enter, then it spaces properly.

Update2: Well, it's stored in the database normal, so maybe it's just a issue with how messages are displayed? 

`````New or Improved Features
[list][*]Tags are a thing now
[*]Report Private Message
[*]Speed Improvements
[*]No more Glyphicon, using Font-Awesome
[*]Attachments display in search results
[/list]

**Comment by KevinDuganJr** [comment]
The messages still look different.

Message before submitted.
![image](https://user-images.githubusercontent.com/5612416/202000280-4332ab65-c2af-4a44-9022-8c57c70a93cd.png)

Message after submitted.
![image](https://user-images.githubusercontent.com/5612416/202000236-e5878774-fa00-4d65-9810-cf4e1f85ef72.png)

**Comment by w8tcha** [comment]
8 cannot see any difference.can you highlight what 8s the difference for you?

**Comment by KevinDuganJr** [comment]
`````This could be the fastest game in NFL history.
Both teams are going to want to run the ball.
Packers -3 over/under 41.5
Sammy Watkins and Allan Lazard have huge games as Aaron will take some shots.

Jones and Dillon combine for 175± yds.
Defense hold Henry to less than 125yds.

Take the Packers, give the points, take the over!!

Packers 31
Titans    17

BOOK IT!!

**Comment by w8tcha** [comment]
I commited a fix to resolve the line issue. Can you verify it?

**Comment by KevinDuganJr** [comment]
I think it should be good now. thank you

![image](https://user-images.githubusercontent.com/5612416/202455588-e6224082-3ac8-4bbb-b863-864a181326d6.png)
