### ISSUE TITLE
Deleting aspnet Membership Table

### ISSUE THREAD

**Issue by SinaBina** [YAFNET/YAFNET#804]
Is it safe to delete the following tables before upgrading the forum to the latest version? They are all empty and it seems that in the newer versions they are not needed anymore!

![Untitled](https://user-images.githubusercontent.com/5496007/200885235-c9708b44-75cd-41bc-bc39-3d7eecb2b920.png)

**Comment by w8tcha** [comment]
Yes if that tables are empty then the yaf\_provider is used and stored in the yaf\_Membership tables. So its save to delete those empty Tables
