### ISSUE TITLE
How to enable spellcheck for CKEditor4

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#807]
I noticed with the change of editors that the browser spell check no longer works. How can that be enabled? I couldn't find it in settings.

**Comment by KevinDuganJr** [comment]
Using the latest source, the spell check still does not work.

**Comment by w8tcha** [comment]
Need more info. Is this browser specific? I tested with chrome and edge. Maybe your browser does not support native spell check

**Comment by KevinDuganJr** [comment]
I typed a word that isn't a word, and no little squiggly line under it. I was using Chrome, and Edge. I'll investigate further tomorrow and report back. I spent most of the day trying to get the Build Package bat to work. Burned me haha.

**Comment by KevinDuganJr** [comment]
I tried it again, now it works. 🤷‍♂️
