### ISSUE TITLE
AutoUpdater and Stored Procedures

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#811]
Will the updater always remove the yaf stored procedures when we do updates? Just curious because I use several to auto generate posts from RSS feeds.  It's not a big deal, I can just save them off into one file and run it after an update, but thought I'd ask first. :) 

![image](https://user-images.githubusercontent.com/5612416/201104693-75546f56-f5e9-46cc-9c7e-76d109029478.png)

**Comment by KevinDuganJr** [comment]
> No, there are only remove when you upgrade to 3.x. But it makes absolutely no sense to use them, simply use the orm api

I agree, but I'm not sure how to change it to use the API instead. Maybe something I do later after I figure out a theme.

**Comment by w8tcha** [comment]
well yaf\_forum\_updatestats is now 

```c#
BoardContext.Current.GetRepository<Forum>().UpdateStats(forumId)
```

yaf\_message\_approve

```c#
BoardContext.Current.GetRepository<Message>().Approve
```

yaf\_message\_save is splitted in

```c#
BoardContext.Current.GetRepository<Message>().SaveNew
```

and 

```c#
BoardContext.Current.GetRepository<Message>().Update
```

yaf\_topic\_latest

```c#
BoardContext.Current.GetRepository<Topic>().Latest
```

yaf\_topic\_save

```c#
BoardContext.Current.GetRepository<Topic>().SaveNew
```

yaf\_user\_upgrade

```c#
BoardContext.Current.GetRepository<User>().Promote
```

**Comment by KevinDuganJr** [comment]
Thanks! 

I'm just not sure how to use those. It looks like I would have to create the object (Topic, Message, etc.), populate it entirely and then pass it through. I won't have all that without a lot of re-working.

**Comment by w8tcha** [comment]
No you don't need to create those objects. Normally vs intelligence would automatically suggest it, but in case not just reference YAF.Types.Models

**Comment by KevinDuganJr** [comment]
I will have to look into that. Should be pretty straight forward.
