### ISSUE TITLE
BuildPackage MSB3073 Error

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#812]
I've been messing around with this all morning, not sure what the issue is, but BuildPackage.bat is not working. Any ideas what I'm doing wrong?  I've tried downloading the Source from 318 and get the same issue as I do with the latest commit to master. 🤷‍♂️

![image](https://user-images.githubusercontent.com/5612416/201173964-325bde70-bff6-444c-ac9f-0debbcddedc9.png)

**Comment by w8tcha** [comment]
Do you have the net6 for yaf source 3.18 installed?

**Comment by KevinDuganJr** [comment]
> Do you have the net6 for yaf source 3.18 installed?

I will check. I had to rollback my Visual Studio 2022 because it woudln't compile YAF so maybe my NET6 got hosed.

**Comment by KevinDuganJr** [comment]
> Do you have the net6 for yaf source 3.18 installed?

Looks like it is installed.

![image](https://user-images.githubusercontent.com/5612416/201184527-982c33d3-97cd-43e7-af10-ca5ab212aaf2.png)

**Comment by KevinDuganJr** [comment]
Looks like I needed this. Now it works. :)

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.100-windows-x64-installer

**Comment by w8tcha** [comment]
Correct for the current beta 3.19 net7 is needed and for the release 3.1.8 net 6

**Comment by KevinDuganJr** [comment]
> Correct for the current beta 3.19 net7 is needed and for the release 3.1.8 net 6

I didn't see that notified anywhere, which is why it took so long to figure it out. And the bat doesn't export errors.

**Comment by w8tcha** [comment]
Sorry I was not aware that it's needed. For yaf to compile in vs you only need. .net framework 4.8.

The build packages is only there to create the release packages for github. I don't understand why you would use this. The publish feature in vs is much faster ans easier to use to deploy the application directly to the server.

**Comment by KevinDuganJr** [comment]
Well, if it's not stated the latest NET version is used, why would someone just download it? 🤷‍♂️

You said to use something other than BAT files. What ya mean?? If there's better than the BAT, sign me up. I waste so many hours because of that.

**Comment by w8tcha** [comment]
> Well, if it's not stated the latest NET version is used, why would someone just download it? 🤷‍♂️

I don't understand the question. In the  documentation under install requirements it is described that.net framework 4.8 is needed.

Also for building the source.

But I will add a description that.net 7 is needed for the buildpackages

**Comment by w8tcha** [comment]
> 
> You said to use something other than BAT files. What ya mean?? If there's better than the BAT, sign me up. I waste so many hours because of that.

https://learn.microsoft.com/en-us/visualstudio/deployment/deploying-applications-services-and-components-resources?view=vs-2022

**Comment by KevinDuganJr** [comment]
I saw the target framework was 4.8 framework, which is why I didn't think I needed NET 7 for BuildPackages. Not a big deal.

**Comment by KevinDuganJr** [comment]
> > You said to use something other than BAT files. What ya mean?? If there's better than the BAT, sign me up. I waste so many hours because of that.
> 
> https://learn.microsoft.com/en-us/visualstudio/deployment/deploying-applications-services-and-components-resources?view=vs-2022

Ahh, yeah, I know about that. I just figured the BuildPackages bat was best option.
