### ISSUE TITLE
Activity Feed notification

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#817]
The little bell icon dealio doesn't change when you have an activity feed notification. Simple to test this. Sign in with two different users in different browsers, thank the other other users post, refresh page. You'll see the icon hasn't changed state, but if you expand the dropdown, you'll see an unread activity feed notification.

![image](https://user-images.githubusercontent.com/5612416/201737869-f0065b0f-b1f4-4899-ac4e-ce53a0db3b1f.png)

**Comment by w8tcha** [comment]
I cannot reproduce this. Which theme do you use? Can you reproduce this with the yaf theme?

**Comment by KevinDuganJr** [comment]
Hmm. I'll have to check other themes. I'm using Slate as my base and then changed some colors.

**Comment by w8tcha** [comment]
![notify](https://user-images.githubusercontent.com/722575/201939946-e0b01ea5-4b2e-4051-beba-1c430069c09e.png)

it should look like this. Similar to github

**Comment by KevinDuganJr** [comment]
> ![notify](https://user-images.githubusercontent.com/722575/201939946-e0b01ea5-4b2e-4051-beba-1c430069c09e.png)
> 
> it should look like this. Similar to github

I'm not sure why it's not showing up. The only thing I changed to the header was adding 'py-0' so the navbar would take up less vertical space. I removed that and tested and still no luck. Obviously, I didn't think that would fix it, but figured it was worth a shot.

**Comment by w8tcha** [comment]
Can you reproduce it on the support forum? You should have a notification

**Comment by KevinDuganJr** [comment]
Appears to work on Support forum. I'm on YAF 3.1.9 BETA if that matters.
![image](https://user-images.githubusercontent.com/5612416/202013313-bd3609d8-3a55-4dc5-ba7b-e2a724c56e26.png)
