### ISSUE TITLE
Strange CKEditor behavior with lists and the source option

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#819]
I'm having issues with displaying lists. So, I tried to use Source and when I went back to Normal view, the contents in my lists are gone.

Source
![image](https://user-images.githubusercontent.com/5612416/201936134-37fbc8d4-ba8b-4cf0-8ee7-a1e17fe26f34.png)

Normal
![image](https://user-images.githubusercontent.com/5612416/201936171-1c3ec78b-54f9-4694-a82c-671bd745d3f3.png)

Source again
![image](https://user-images.githubusercontent.com/5612416/201936374-f5c9b90f-d70a-4126-a393-28dab80dc304.png)

And when I posted with the Source view, the post itself looks like this.
![image](https://user-images.githubusercontent.com/5612416/201936792-3acbe71f-3be0-414c-a310-e53d536e93f7.png)

**Comment by w8tcha** [comment]
Looking at the first Screenshot I can see you defined a list but not a list item. Of course this can not work.

List should look like 

[list]
[*]list item 1
[*]list item 2
[/list]

**Comment by KevinDuganJr** [comment]
Maybe this isn't really an issue, I don't know. But using the Normal view on the editor, I was able to get the format how I was hoping for. And when editing it, it still shows up. It's probably just an issue with me using old BBCodes.

![image](https://user-images.githubusercontent.com/5612416/201938062-46da0e71-3ced-4280-ba01-1f780e570cd9.png)

**Comment by KevinDuganJr** [comment]
> Looking at the first Screenshot I can see you defined a list but not a list item. Of course this can not work.
> 
> List should look like..
> 
> ```
> [list]
> [*]list item 1
> [*]list item 2
> [/list]
> ```

I tried that as well and it just displayed displayed the text verbatim. I must have messed something up. Very strange. I'll kill this and chalk it up as "user being dumb". User being me.
