### ISSUE TITLE
Text for Reply with Quote missing

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#822]
I'm not sure this qualifies as a bug as it's not really broken. I noticed the text for replying with quote is missing.

`````this.Quote.Text = this.GetText("BUTTON_QUOTE_TT");`````

To get the text to show, I just added that above line here in DisplayPost.ascx.cs

![image](https://user-images.githubusercontent.com/5612416/203159337-72506602-fdf4-47ab-ac02-7b33c7c52cbc.png)

**Comment by w8tcha** [comment]
It's not a bug it's a feature. Text is only shown on desktop but not on small screen devices. To save space

**Comment by KevinDuganJr** [comment]
> It's not a bug it's a feature.
> 
> By default allbuttons in the footer don't have text. But maybe Its better to revert to to the original idea of display text only on big screens

It wasn't showing on desktop. That's why I dug around to figure it out.
