### ISSUE TITLE
install/default.aspx Forum Error with Exception

### ISSUE THREAD

**Issue by WhiteJue** [YAFNET/YAFNET#861]
installing v3.1.12(downloaded from releases page) with SqlServer on Windows Server 2012 R2
Here's the error message:

> System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.NullReferenceException
>    at YAF.Core.Services.Localization.Localization.LoadTranslation()
>    at YAF.Core.Services.Localization.Localization.GetLocalizedTextInternal(String page, String tag)
>    at YAF.Core.Services.Localization.Localization.GetText(String page, String tag)
>    at ASP.install_default_aspx.__DataBind__control5(Object sender, EventArgs e)
>    at System.Web.UI.Control.OnDataBinding(EventArgs e)
>    at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding)
>    at System.Web.UI.Control.DataBindChildren()
>    at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding)
>    at System.Web.UI.Control.DataBindChildren()
>    at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding)
>    at System.Web.UI.Control.DataBindChildren()
>    at System.Web.UI.Control.DataBind(Boolean raiseOnDataBinding)
>    at YAF.Install._default.Page_Load(Object sender, EventArgs e)
>    at System.Web.UI.Control.OnLoad(EventArgs e)
>    at System.Web.UI.Control.LoadRecursive()
>    at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
>    at System.Web.UI.Page.HandleError(Exception e)
>    at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
>    at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
>    at System.Web.UI.Page.ProcessRequest()
>    at System.Web.UI.Page.ProcessRequest(HttpContext context)
>    at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
>    at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
>    at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

* YAF.NET Support Forums: https://yetanotherforum.net/forum/

**Comment by w8tcha** [comment]
Issue will be fixed in YAF 3.1.13
