### ISSUE TITLE
French translation mistakes : Date are not displayed correctly

### ISSUE THREAD

**Issue by Christophe1476** [YAFNET/YAFNET#870]
**Describe the bug**
There is some mistakes in "French.json" about date formatting. "D" value is translated with "ré" (the french music note). "FORMAT_DATE_LONG" and "FORMAT_DATE_SHORT" are concerned. 

**To Reproduce**
1. French language must be enabled during setup
2. All dates are displayed with "ré" value.

**System**
 - YAF Version: 3.1.12
 - .NET Version : 4.8
 - SQL Server 2017
 
**Affected browser**
This is a server side issue.

Here is a fix of the json file : [french.json.zip](https://github.com/YAFNET/YAFNET/files/10956374/french.json.zip)

**Comment by w8tcha** [comment]
Thanks for the report. This issue was also in some other languages. Caused by the auto translation.
