### ISSUE TITLE
Deploy Package(s)

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#902]
I downloaded the latest commit from master/main and ran it against my beta database. It worked without issue, but I can't seem to find the bat files to create the deploy packages outside of using the Visual Studio Publish option. I thought everything might be included under the wwwroot directory, but that is missing assemblies that I know will be needed.

TL;DR: How do we get just the deploy files from a build/commit? 😀 I know this isn't production ready, but I have a test site.

**Comment by w8tcha** [comment]
Whats the reason to use the packages? The best solution to directly deploy to an iis is if you create an Publishing profile inside visual studio .

More Info here...
https://learn.microsoft.com/en-us/aspnet/core/tutorials/publish-to-iis?view=aspnetcore-7.0&tabs=visual-studio

then you can directly use the command line to deploy the files to your site

`dotnet publish/p:Configuration=Release ../YAF.NET-Sqlite.sln /p:PublishProfile=<MsDeployPackageProfileName>`

i added back the buildpackages and the updated gruntfile to create the packages

**Comment by KevinDuganJr** [comment]
I'm just not a fan of the Visual Studio Publish option. I was looking for something that was similar to what YAF provided previously, that is all. Change is inevitable, change is good, but I was just trying to make sure I wasn't missing something and wanted to see if I could seamlessly add the latest YAF build/commit to my "Sample Application" and when I saw all the files in the /publish directory, I thought I'd ask about the build packages.   Because the build packagers were concise and clear.

**Comment by w8tcha** [comment]
Understandable. I also never used the publish option inside vs. 

However in net core things work differently. So I have to figure out the best solution.

**Comment by w8tcha** [comment]
I think this can be closed. The build packages are now created via nodejs/grunt 

You can now with one line of code build the packages,  or via the task runner in vs.

to create the mssql package only run

`grunt deploy-SqlServer `
