### ISSUE TITLE
Indent in Test Forum is not displayed for Post or Preview

### ISSUE THREAD

**Issue by Aellaithy** [YAFNET/YAFNET#908]
**Describe the bug**
When using the Indent button in Post Reply, the indents are displayed in the text box correctly, but when previewing or after posting the reply the indents are not displayed as the tag [indend] is used.

**To Reproduce**
1. Go to 'https://testforum.yetanotherforum.net/'
2. Open any topic.
3. Click the 'Post Reply' button or the 'Reply' button on any of the posted messages.
4. Fill in the reply making sure to include indents using the 'Insert Indent' button.
5. Click the 'Preview' button (Check screenshots)
6. Click the 'Post' button. (Check screenshots)

**Expected behavior**
The Message/Reply is posted successfully with the indents being displayed correctly.

**Actual behavior**
The Message/Reply is posted successfully, but in place of the indents the tag [indend] is displayed instead.
If the tag is changed to [indent] then the indent is displayed correctly.

**Screenshots**
'Post' button --> Message/Reply
![image](https://github.com/YAFNET/YAFNET/assets/44909560/8a82ff52-2b35-4062-b02a-de724bad45d7)

'Preview' button --> Preview
![image](https://github.com/YAFNET/YAFNET/assets/44909560/e8bf7ddc-65c1-46f7-a87c-8f4b5e7c31a7)

 
**Affected browser**

* [ x ] Chrome
* [ x ] Firefox
* [ x ] Safari
* [ x ] Edge

**Comment by w8tcha** [comment]
Fixed in latest commit, will be fixed in YAF 3.1.14
