### ISSUE TITLE
YAF Text Editor

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#941]
I know it's the right decision to go to just one editor, but I just dislike this CKEditor experience. 

Most common issues.
- Copy text from another website, paste into editor and SOMETIMES it breaks things and by break things I mean it throws the entire formatting out of whack and you can't even see any posts in the thread. Manual database editing is required to fix the issue.
- Editing in Source view and click back to normal view, it'll go just all white (see below) and then we can't do anything. Entire post is lost. this basically happens if you screw up a bbcode tag so it's safe to say "user error" on this, haha. 
- If you highlight text and click a custom tag, it just overwrites that highlighted text and puts the BBCode tags down.  Previous editor would wrap the tags around the text.
- I don't even post on my site anymore because the mobile experience is challenging

I hate coming off as an ungrateful user here (I'm very sorry) and I have tried numerous times to repeat my troubles so they can be fixed. 

This is all being compared to the YAFEditor which I cannot recall having these issues with. Can we go back to YAF Text Editor? 

Also, my version is YAF.NET 3.1.9 BETA 202211100820 

Here's an example of a post going all white and being completely lost.
![image](https://github.com/YAFNET/YAFNET/assets/5612416/911b0031-3f56-48da-adb6-9db57a45ba2e)

And I tried catching the browser errors because maybe that can be useful.
![image](https://github.com/YAFNET/YAFNET/assets/5612416/4369b05f-473a-4345-acce-dea8f51c0b96)

**Comment by w8tcha** [comment]
I can understand you, i have similar experiences.

The goal by switching to the ckeditor was to provide a better experience and show the formatted bbcode as html in the editor. but that seems to be causing more problems than it solves.

Its seems now with the ckeditor is EOL (no more updates). its time to go back and use the yaf editor. With the same ui as the forum, and better integration.

Which will be included in 3.1.15

**Comment by KevinDuganJr** [comment]
> I can understand you, i have similar experiences.
> 
> The goal by switching to the ckeditor was to provide a better experience and show the formatted bbcode as html in the editor. but that seems to be causing more problems than it solves.
> 
> Its seems now with the ckeditor is EOL (no more updates). its time to go back and use the yaf editor. With the same ui as the forum, and better integration.
> 
> Which will be included in 3.1.15

Bummer you are also having similar experiences, but that is good about YAF Editor coming back. I will have to figure out how to upgrade my site for sure! 😁

**Comment by w8tcha** [comment]
New Improved editor is back, with some improvements

- New Undo Manager to undo/ redo text via button or Strg+Y/Z
- Auto completing of bbcode tags 
- Character counter
- Auto Suggest of Mentions, start typing '@ + Username'

**Comment by KevinDuganJr** [comment]
The CTRL + Enter to submit seems to be missing. 😬 😉
