### ISSUE TITLE
Migrate/install on nginx on linux

### ISSUE THREAD

**Issue by gromavic** [YAFNET/YAFNET#951]
Hello!

Could you share documentation about installing/migating YAF forum from Windiws (IIS) to Linux (nginx)?

**Comment by w8tcha** [comment]
You can find an install guide on how to install am asp.net core application on the ms documentation site....

https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-7.0&tabs=linux-ubuntu

**Comment by gromavic** [comment]
Which dll should I use in linux service?

**Comment by w8tcha** [comment]
All dlls which are created during publish are needed.

**Comment by gromavic** [comment]
I cant test app cause I don't know whci dll to use
Test the app:

From the command line, run the app: dotnet <app_assembly>.dll.

**Comment by w8tcha** [comment]
Ah sorry now I understand. The the dll is YAF.dll

**Comment by gromavic** [comment]
I can't publish app due to next behaviour. Could you share advice about this issue? 

~/YAFNET-3.1.14/yafsrc$ **dotnet publish YAF.NET-SqlServer.sln --framework net48 -o Release**
MSBuild version 17.4.8+6918b863a for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  ServiceStack -> /home/user/YAFNET-3.1.14/yafsrc/ServiceStack/ServiceStack/bin/Debug/net48/ServiceStack.dll
  YAF.Lucene.Net -> /home/user/YAFNET-3.1.14/yafsrc/Lucene.Net/Lucene.Net/bin/Debug/net472/YAF.Lucene.Net.dll
  ServiceStack.OrmLite -> /home/user/YAFNET-3.1.14/yafsrc/ServiceStack/ServiceStack.OrmLite/bin/Debug/net48/ServiceStack.OrmLite.dll
  ServiceStack.OrmLite.SqlServer -> /home/user/YAFNET-3.1.14/yafsrc/ServiceStack/ServiceStack.OrmLite.SqlServer/bin/Debug/net48/ServiceStack.OrmLite.SqlServer.dll
  ServiceStack -> /home/user/YAFNET-3.1.14/yafsrc/Release/
CSC : error CS7027: Error signing output with public key from file '..\YetAnotherForum.NET.snk' -- File not found. [/home/user/YAFNET-3.1.14/yafsrc/YAF.Types/YAF.Types.csproj::TargetFramework=net48]
  YAF.Lucene.Net.Analysis.Common -> /home/user/YAFNET-3.1.14/yafsrc/Lucene.Net/Lucene.Net.Analysis.Common/bin/Debug/net472/YAF.Lucene.Net.Analysis.Common.dll
  YAF.Lucene.Net.Queries -> /home/user/YAFNET-3.1.14/yafsrc/Lucene.Net/Lucene.Net.Queries/bin/Debug/net472/YAF.Lucene.Net.Queries.dll
  ServiceStack.OrmLite -> /home/user/YAFNET-3.1.14/yafsrc/Release/
  ServiceStack.OrmLite.SqlServer -> /home/user/YAFNET-3.1.14/yafsrc/Release/
  YAF.Lucene.Net.Highlighter -> /home/user/YAFNET-3.1.14/yafsrc/Lucene.Net/Lucene.Net.Highlighter/bin/Debug/net472/YAF.Lucene.Net.Highlighter.dll
  YAF.Lucene.Net.QueryParser -> /home/user/YAFNET-3.1.14/yafsrc/Lucene.Net/Lucene.Net.QueryParser/bin/Debug/net472/YAF.Lucene.Net.QueryParser.dll

**Comment by w8tcha** [comment]
This cannot work. You downloaded the wrong version. Version 3.1.14 will not run on linux. You need to clone, or download the master branch with the current 4.0 BETA.

**Comment by gromavic** [comment]
Could you be so kind and share some instructions? After running YAF service on Ubuntu and configuring reverce proxy nginx to application port I can't get in browser page with installation or something from YAF forum? 
Am I right that install page should be displayed no matter configured db or not in config files? I suppose install proccess allow to provide server name/base/user/password and other  db configurations?

**Comment by w8tcha** [comment]
> Could you be so kind and share some instructions?

Unfortunately no, i never used linux before. I don't know if i i have time to test this in the future.

> Am I right that install page should be displayed no matter configured db or not in config files? I suppose install process allow to provide server name/base/user/password and other db configurations?

Correct, but you can define the connection string in the appsettings.json

`"ConnectionStrings": {
    "DefaultConnection": "data source=(local);initial catalog=yafnet;Integrated Security=True;TrustServerCertificate=True;"
  },`

**Comment by gromavic** [comment]
I can't understand how to deploy this app on Ubuntu. I published application, but where Install  folder folder, how to collect full architecture of site? No any instructions for Linux OS.

**Comment by w8tcha** [comment]
But all the is described in the guide i posted above, did you read it?

>> Run [dotnet publish](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish) from the development environment to package an app into a directory (for example, bin/Release/net7/publish

the publish folder contains all files you need to run the app

>> Copy the ASP.NET Core app to the server using a tool that integrates into the organization's workflow (for example, SCP, SFTP). It's common to locate web apps under the var directory (for example, var/www/yafnet).

>> Test the app:

From the command line, run the app: dotnet YAF.dll.
In a browser, navigate to http://<serveraddress>:<port> to verify the app works on Linux locally.
