### ISSUE TITLE
GetAttachment 404 console error

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#956]
Using the latest source code, when trying to make a reply to a post the console has numerous errors.

https://github.com/YAFNET/YAFNET/commit/6293e03d33cdb158d80ccc1409e3133c230d1a4a

I was still able to copy/paste from the clipboard and the image still displayed.

![image](https://github.com/YAFNET/YAFNET/assets/5612416/e211c70c-9453-4b00-83e2-386fb7f13b55)

**Comment by w8tcha** [comment]
Where does the error occur? did you copy the uploads to the correct folder? in YAF 4 there are in a different folder.

**Comment by KevinDuganJr** [comment]
This is a new topic post with no attachments.

![image](https://github.com/YAFNET/YAFNET/assets/5612416/7cb9a58d-089f-48e6-81f8-40e804d12d41)

**Comment by w8tcha** [comment]
found the issue, fixed!
