### ISSUE TITLE
Event Log → YAF.NET Upgraded to Version 3.1.15 BETA 202308240630 

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#958]
Upgraded my SampleApplication last night with the latest NETFX commit. Everything seemed fine locally. When I deployed it to my server, I am noticing a lot of entries into the eventlog  stating the sit was upgraded. 
 
My question would be, why is this happening?

![image](https://github.com/YAFNET/YAFNET/assets/5612416/026e52b0-ee0a-4c80-8aff-6b04aa36db5b)

**Comment by KevinDuganJr** [comment]
A note, I had to comment out a few things to get YAF stand alone to function.

This kept blowing up because of a "NULL"
![image](https://github.com/YAFNET/YAFNET/assets/5612416/5ed7bbeb-8478-413a-a1b3-cd04c4a238ad)

And these columns would be dropped, then I would get an error saying the column couldn't be found. 
![image](https://github.com/YAFNET/YAFNET/assets/5612416/9d972c5b-dc1b-47de-88f3-68c2d57de262)

**Comment by KevinDuganJr** [comment]
Actually, it is happening when I run the source code for SampleApplication while pointing to SQL Server. 

![image](https://github.com/YAFNET/YAFNET/assets/5612416/b641205c-ec0c-4859-ae10-ded553a6f525)

**Comment by w8tcha** [comment]
Don't comment out any code,.  post it as issue instead. Otherwise its impossible to reproduce. I fixed the issue with the dropped columns.

**Comment by w8tcha** [comment]
> This kept blowing up because of a "NULL"

because you comment out the code the log entry is generated with every page visit! post the stack trace of the null exception please.

**Comment by KevinDuganJr** [comment]
> > This kept blowing up because of a "NULL"
> 
> because you comment out the code the log entry is generated with every page visit! post the stack trace of the null exception please.

lol, okay.  I'm restoring the database to start fresh.

**Comment by KevinDuganJr** [comment]
Here's what I got.
![image](https://github.com/YAFNET/YAFNET/assets/5612416/9018b495-d8ba-4375-ac09-d7a8cd7c28b4)
![image](https://github.com/YAFNET/YAFNET/assets/5612416/27f34ad4-d73a-4f77-bf6b-5746c8365eea)

**Comment by w8tcha** [comment]
ok i commited a possible fx

**Comment by KevinDuganJr** [comment]
> ok i commited a possible fx

Okay, nothing commented out. The source code builds and runs.  

I am still getting a new event log entry each time the application is restarted though.  The first entry is when I ran the code in Visual Studio, then I went and restarted the application. 

![image](https://github.com/YAFNET/YAFNET/assets/5612416/c0206ee2-f5d9-4f96-a1c9-538ff07357b5)

**Comment by w8tcha** [comment]
Hmh, this is odd. if the upgrade process runs on every app restart then the version is not saved to the database.

Can you check the yaf_registry 

```
SELECT  [Value]
  FROM [dbo].[yaf_Registry]
  where name = 'version'
```

**Comment by KevinDuganJr** [comment]
> SELECT  [Value]
>   FROM [dbo].[yaf_Registry]
>   where name = 'version'

Restored my database and downloaded latest commit. 
![image](https://github.com/YAFNET/YAFNET/assets/5612416/1f2a448c-2c13-42c5-86a8-12d2d8c7722c)

**Comment by w8tcha** [comment]
There should be only be one entry. Delete the row with the 87.

**Comment by KevinDuganJr** [comment]
> There should be only be one entry. Delete the row with the 87.

I've actually had this issue before. And I think it'll just create another one because the BoardID is NULL.

![image](https://github.com/YAFNET/YAFNET/assets/5612416/62d0e0d2-28e9-4859-a0e9-402109231ad2)

**Comment by w8tcha** [comment]
Correct the boardid should must be null

**Comment by KevinDuganJr** [comment]
> Correct the boardid should must be null

Oh, I didn't realize that. Okay, so I'm restarting the application now to see if the entries in the event log and I'm not seeing the extra entries. I've rebuilt the source code twice, restarted the application twice. Normally, I'd have four entries but as you can see. Just the one. 

Thank you! I think this one can be closed as just an error in my original database, not a code problem.
![image](https://github.com/YAFNET/YAFNET/assets/5612416/c4b8ff30-6bac-4cfc-892b-6964023aad01)

**Comment by KevinDuganJr** [comment]
> Correct the boardid should must be null

Should BoardId be NULL for all of them? 

I ask because I just updated some settings in Host Settings and a good portion of the registries have been duplicated but with BoardId as NULL. I went from 295 entries to 444.
