### ISSUE TITLE
Remember Me option not keeping users logged in

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#967]
Since I upgraded to the latest version. Everyone has to keep logging in the next day. It's happening on mobile devices and PC's.  I have the Remember Me checked so not sure why this happening. Any thoughts or areas I should check?

**Comment by w8tcha** [comment]
At the moment i have no clue. Nothing has changed in yaf. 

Maybe something has changed in the updated owin libraries. 

At least when i log in i can see that the cookie expire date has set to 14 days (which is the default value). But i dont know yet if i need to login tomorrow again.

I increased the expire date to 30 days. But i dont think this will solve the problem.

**Comment by KevinDuganJr** [comment]
I believe this happened because I rebuilt my SampleApplication and over rode my web.config and did not have the Machine Key set. I set it yesterday and this morning I was still logged in. I'm gonna mark this as closed.
