### ISSUE TITLE
Add CSS Class to Inputs

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#968]
I know I'm tossing a lot at you, my apologies. I'm just excited. Anyhow, I noticed there's a strong contrast between themes. Example, here's 'cosmo' and all of the input fields (select, dropdown, editor, text, etc) have a white background with black font.  Maybe adding something like bg-{dark/light} and text-{dark/light} will help keep the contrast down? 

I know you cannot theme YAF in a manner that makes every theme flawless. The web/admin has to do that part, but I think giving some base css classes to alter would be a great option. At least, that's how I'm thinking, but what are your thoughts?

![image](https://github.com/YAFNET/YAFNET/assets/5612416/689b0d8d-b140-42ce-b77f-0083c62cb01f)

**Comment by w8tcha** [comment]
That's why there is a setting now to switch between dark/light theme. Then you get the experience you want.

**Comment by KevinDuganJr** [comment]
> That's why there is a setting now to switch between dark/light theme. Then you get the experience you want.

Yes, but there isn't a class associated to the editor so it's unaffected by that toggle of dark/light. Unless I missed it.

**Comment by w8tcha** [comment]
There is no need for that. If you switch to comso dark all inputs are Black

**Comment by KevinDuganJr** [comment]
> There is no need for that. If you switch to comso dark all inputs are Black

Sweet! I must have used one that is not working in my example images above. I just checked a different them and it toggles as expected.
