### ISSUE TITLE
Notification Bell - Circle 

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#969]
Currently the notification icon "bell" uses "text-primary", but that can be difficult to notice across other themes. What do you think about using "text-warning" because that will also pop out to the user?

My theme is kind of horse poopoo right now, but this gives you an idea.

text-primary
![image](https://github.com/YAFNET/YAFNET/assets/5612416/b690dbbd-0596-421f-b7ff-0d2d5913ed79)

text-warning
![image](https://github.com/YAFNET/YAFNET/assets/5612416/c028f330-4a6c-4cc7-93f9-51c6cec634de)

**Comment by w8tcha** [comment]
I think the text-danger fits better, it also matches the other notifications in the user menu
