### ISSUE TITLE
View Private Messages as Chat

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAFNET#971]
I think the Private Messages could be treated similar as a forum Topic. The topic could be viewable by the participants similar to when users view a forum topic. Rather than Private Messages being similar to emails, it would be more similar to chat. Meaning, you can read the flow of the discussion by opening up the "chat" thread. 

What do you think about this idea?

**Comment by w8tcha** [comment]
Actually thats already the case. But currently it was not working. I committed a fix. But it doesn't work always. The entire system is so flawed.

In YAF 4 pms are completely removed. And replaced with a direct real time chat.

![chat](https://github.com/YAFNET/YAFNET/assets/722575/fcfea4f7-ff2f-49dd-9d5b-b86889312f9d)

**Comment by w8tcha** [comment]
Yes it's using signalr, and of course it's stored in the db.

**Comment by KevinDuganJr** [comment]
> Yes it's using signalr, and of course it's stored in the db.

The Chat isn't stored in the database so of course I would have to ask to clarify. Thank you.

**Comment by w8tcha** [comment]
I assume you mean the demo chat inside the sample application. 

It only shows how you can integrate yaf, and not directly use it.

Mazbe it's better to remove it. If it causes confusion.

**Comment by KevinDuganJr** [comment]
> I assume you mean the demo chat inside the sample application.
> 
> It only shows how you can integrate yaf, and not directly use it.
> 
> Mazbe it's better to remove it. If it causes confusion.

Correct, I was referring to YAF Sample Application. 

If you feel the YAF Sample Application is causing confusion, by all means, remove it.
