### ISSUE TITLE
Modals do not work on main/latest

### ISSUE THREAD

**Issue by rameyroad** [YAFNET/YAFNET#987]
**Describe the bug**
Bootstrap modals are not working on the install pages or for the login box.

**To Reproduce**
1. Cone the repo from either the main netfx or branch.
2. Build & Run
3. On a clean DB install, observe that the modal popup does not display on the installation page.
4. On an existing DB, click the "Login" link on any page.

**Expected behavior**
Modal popups should display and user should be able to login.

**Actual behavior**
Modals do not display, and login is not possible.

**Screenshots**
From the console window, I observe that bootstrap is not loading:
<img width="297" alt="image" src="https://github.com/YAFNET/YAFNET/assets/13038953/b1f41c1f-5d38-4ac1-89b1-d6fcfbb1ffcc">

**System (please complete the following information):**
 - YAF Version: latest from main or netfx branch. Also verified on the 3.1.13.0 tag
 - .NET Version 4.8.1 & .NET Core 7.0
 
**Affected browser**
* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [X] Edge

**Additional context**
None

**Comment by w8tcha** [comment]
In the screenshot I can see an 404 error. Looks like the Java scripts files are Not loaded. Possible the files do not exist on the test server?!

**Comment by rameyroad** [comment]
Of course open to me having it wrong, but I’m running from the repo on my
dev machine. The lib folder is there with bootstrap in it, but not sure the
bundle is built or loaded.

**Comment by w8tcha** [comment]
No problem, you downloaded the yaf 4.0 beta from the master branch. At this point there is no documentation on how to build the sources. only the notice that you need to have node and npm installed.

From the Yetanotherforum.net folder you need to run in the prompt..

`npm install`

And then

`grunt`

To compile the js and css sources.

**Comment by rameyroad** [comment]
Thank you. I started from scratch, and performed the following steps:

   1. Updated my database connection string.
   2. cd to Yetanotherforum.net  folder
   3. npm install
   4. grunt
   5. dotnet build .\YAF-SqlServer.csproj
   6. dotnet run --project .\YAF-SqlServer.csproj

The site loaded without the errors and the Login popup works as expected:

[image: image.png]
